version: "2"
linters:
  default: none
  enable:
    - errcheck
    - errname
    - errorlint
    - gocritic
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - modernize
    - prealloc
    - revive
    - staticcheck
    - testifylint
    - thelper
    - unconvert
    - wastedassign
    - whitespace
  settings:
    modernize:
      disable:
        # Replace []byte(fmt.Sprintf) with fmt.Appendf.
        - fmtappendf
        # Remove redundant re-declaration of loop variables.
        - forvar
        # Replace explicit loops over maps with calls to maps package.
        - mapsloop
        # Replace if/else statements with calls to min or max.
        - minmax
        # Suggest replacing omitempty with omitzero for struct fields.
        - omitzero
        # Remove obsolete //+build comments.
        - plusbuild
        # Replace 3-clause for loops with for-range over integers.
        - rangeint
        # Replace reflect.TypeOf(x) with TypeFor[T]().
        - reflecttypefor
        # Replace loops with slices.Contains or slices.ContainsFunc.
        - slicescontains
        # Replace sort.Slice with slices.Sort for basic types.
        - slicessort
        # Use iterators instead of Len/At-style APIs.
        - stditerators
        # Replace strings.Index etc. with strings.Cut.
        - stringscut
        # Replace HasPrefix/TrimPrefix with CutPrefix.
        - stringscutprefix
        # Replace ranging over Split/Fields with SplitSeq/FieldsSeq.
        - stringsseq
        # Replace += with strings.Builder.
        - stringsbuilder
        # Replace context.WithCancel with t.Context in tests.
        - testingcontext
        # Replace unsafe pointer arithmetic with function calls.
        - unsafefuncs
    misspell:
      locale: US
    revive:
      rules:
        - name: if-return
          disabled: true
    staticcheck:
      checks:
        - -ST1016 # Disable a rule for linting the generated converters in SDK.
    testifylint:
      disable:
        - require-error # Do not force using require instead of assert checks.
        - empty # Do not force using Empty assertion instead of Equal assertion with empty string.
  exclusions:
    presets:
      - legacy
      - std-error-handling
    # Scripts are not part of the production code and may be excluded.
    paths:
      - scripts$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
