// Code generated by object assertions generator (v0.1.0); DO NOT EDIT.

package objectassert

import (
	"fmt"
	"testing"
	"time"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/helpers"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

type CatalogIntegrationAssert struct {
	*assert.SnowflakeObjectAssert[sdk.CatalogIntegration, sdk.AccountObjectIdentifier]
}

func CatalogIntegration(t *testing.T, id sdk.AccountObjectIdentifier) *CatalogIntegrationAssert {
	t.Helper()
	return &CatalogIntegrationAssert{
		assert.NewSnowflakeObjectAssertWithTestClientObjectProvider(sdk.ObjectType("CatalogIntegration"), id, func(testClient *helpers.TestClient) assert.ObjectProvider[sdk.CatalogIntegration, sdk.AccountObjectIdentifier] {
			return testClient.CatalogIntegration.Show
		}),
	}
}

func CatalogIntegrationFromObject(t *testing.T, catalogIntegration *sdk.CatalogIntegration) *CatalogIntegrationAssert {
	t.Helper()
	return &CatalogIntegrationAssert{
		assert.NewSnowflakeObjectAssertWithObject(sdk.ObjectTypeCatalogIntegration, catalogIntegration.ID(), catalogIntegration),
	}
}

func (c *CatalogIntegrationAssert) HasName(expected string) *CatalogIntegrationAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.CatalogIntegration) error {
		t.Helper()
		if o.Name != expected {
			return fmt.Errorf("expected name: %v; got: %v", expected, o.Name)
		}
		return nil
	})
	return c
}

func (c *CatalogIntegrationAssert) HasEnabled(expected bool) *CatalogIntegrationAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.CatalogIntegration) error {
		t.Helper()
		if o.Enabled != expected {
			return fmt.Errorf("expected enabled: %v; got: %v", expected, o.Enabled)
		}
		return nil
	})
	return c
}

func (c *CatalogIntegrationAssert) HasType(expected string) *CatalogIntegrationAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.CatalogIntegration) error {
		t.Helper()
		if o.Type != expected {
			return fmt.Errorf("expected type: %v; got: %v", expected, o.Type)
		}
		return nil
	})
	return c
}

func (c *CatalogIntegrationAssert) HasCategory(expected string) *CatalogIntegrationAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.CatalogIntegration) error {
		t.Helper()
		if o.Category != expected {
			return fmt.Errorf("expected category: %v; got: %v", expected, o.Category)
		}
		return nil
	})
	return c
}

func (c *CatalogIntegrationAssert) HasComment(expected string) *CatalogIntegrationAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.CatalogIntegration) error {
		t.Helper()
		if o.Comment != expected {
			return fmt.Errorf("expected comment: %v; got: %v", expected, o.Comment)
		}
		return nil
	})
	return c
}

func (c *CatalogIntegrationAssert) HasCreatedOn(expected time.Time) *CatalogIntegrationAssert {
	c.AddAssertion(func(t *testing.T, o *sdk.CatalogIntegration) error {
		t.Helper()
		if o.CreatedOn != expected {
			return fmt.Errorf("expected created on: %v; got: %v", expected, o.CreatedOn)
		}
		return nil
	})
	return c
}
