// Code generated by object assertions generator (v0.1.0); DO NOT EDIT.

package objectassert

import (
	"fmt"
	"testing"
	"time"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/helpers"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

type HybridTableAssert struct {
	*assert.SnowflakeObjectAssert[sdk.HybridTable, sdk.SchemaObjectIdentifier]
}

func HybridTable(t *testing.T, id sdk.SchemaObjectIdentifier) *HybridTableAssert {
	t.Helper()
	return &HybridTableAssert{
		assert.NewSnowflakeObjectAssertWithTestClientObjectProvider(sdk.ObjectType("HybridTable"), id, func(testClient *helpers.TestClient) assert.ObjectProvider[sdk.HybridTable, sdk.SchemaObjectIdentifier] {
			return testClient.HybridTable.Show
		}),
	}
}

func HybridTableFromObject(t *testing.T, hybridTable *sdk.HybridTable) *HybridTableAssert {
	t.Helper()
	return &HybridTableAssert{
		assert.NewSnowflakeObjectAssertWithObject(sdk.ObjectTypeHybridTable, hybridTable.ID(), hybridTable),
	}
}

func (h *HybridTableAssert) HasCreatedOn(expected time.Time) *HybridTableAssert {
	h.AddAssertion(func(t *testing.T, o *sdk.HybridTable) error {
		t.Helper()
		if o.CreatedOn != expected {
			return fmt.Errorf("expected created on: %v; got: %v", expected, o.CreatedOn)
		}
		return nil
	})
	return h
}

func (h *HybridTableAssert) HasName(expected string) *HybridTableAssert {
	h.AddAssertion(func(t *testing.T, o *sdk.HybridTable) error {
		t.Helper()
		if o.Name != expected {
			return fmt.Errorf("expected name: %v; got: %v", expected, o.Name)
		}
		return nil
	})
	return h
}

func (h *HybridTableAssert) HasDatabaseName(expected string) *HybridTableAssert {
	h.AddAssertion(func(t *testing.T, o *sdk.HybridTable) error {
		t.Helper()
		if o.DatabaseName != expected {
			return fmt.Errorf("expected database name: %v; got: %v", expected, o.DatabaseName)
		}
		return nil
	})
	return h
}

func (h *HybridTableAssert) HasSchemaName(expected string) *HybridTableAssert {
	h.AddAssertion(func(t *testing.T, o *sdk.HybridTable) error {
		t.Helper()
		if o.SchemaName != expected {
			return fmt.Errorf("expected schema name: %v; got: %v", expected, o.SchemaName)
		}
		return nil
	})
	return h
}

func (h *HybridTableAssert) HasOwner(expected string) *HybridTableAssert {
	h.AddAssertion(func(t *testing.T, o *sdk.HybridTable) error {
		t.Helper()
		if o.Owner != expected {
			return fmt.Errorf("expected owner: %v; got: %v", expected, o.Owner)
		}
		return nil
	})
	return h
}

func (h *HybridTableAssert) HasRows(expected int) *HybridTableAssert {
	h.AddAssertion(func(t *testing.T, o *sdk.HybridTable) error {
		t.Helper()
		if o.Rows == nil {
			return fmt.Errorf("expected rows to have value; got: nil")
		}
		if *o.Rows != expected {
			return fmt.Errorf("expected rows: %v; got: %v", expected, *o.Rows)
		}
		return nil
	})
	return h
}

func (h *HybridTableAssert) HasBytes(expected int) *HybridTableAssert {
	h.AddAssertion(func(t *testing.T, o *sdk.HybridTable) error {
		t.Helper()
		if o.Bytes == nil {
			return fmt.Errorf("expected bytes to have value; got: nil")
		}
		if *o.Bytes != expected {
			return fmt.Errorf("expected bytes: %v; got: %v", expected, *o.Bytes)
		}
		return nil
	})
	return h
}

func (h *HybridTableAssert) HasComment(expected string) *HybridTableAssert {
	h.AddAssertion(func(t *testing.T, o *sdk.HybridTable) error {
		t.Helper()
		if o.Comment != expected {
			return fmt.Errorf("expected comment: %v; got: %v", expected, o.Comment)
		}
		return nil
	})
	return h
}

func (h *HybridTableAssert) HasOwnerRoleType(expected string) *HybridTableAssert {
	h.AddAssertion(func(t *testing.T, o *sdk.HybridTable) error {
		t.Helper()
		if o.OwnerRoleType != expected {
			return fmt.Errorf("expected owner role type: %v; got: %v", expected, o.OwnerRoleType)
		}
		return nil
	})
	return h
}
