// Code generated by object assertions generator (v0.1.0); DO NOT EDIT.

package objectassert

import (
	"fmt"
	"slices"
	"testing"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/internal/collections"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

type OAuthRestAuthenticationAssert struct {
	*assert.SnowflakeObjectAssert[sdk.OAuthRestAuthentication, sdk.AccountObjectIdentifier]
}

// OAuthRestAuthentication removed manually

func OAuthRestAuthenticationFromObject(t *testing.T, oAuthRestAuthentication *sdk.OAuthRestAuthentication) *OAuthRestAuthenticationAssert {
	t.Helper()
	return &OAuthRestAuthenticationAssert{
		assert.NewSnowflakeObjectAssertWithObject("OAuthRestAuthentication", sdk.NewAccountObjectIdentifier(""), oAuthRestAuthentication),
	}
}

// Manually removed assertions for private fields

func (o *OAuthRestAuthenticationAssert) HasOauthTokenUri(expected string) *OAuthRestAuthenticationAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OAuthRestAuthentication) error {
		t.Helper()
		if o.OauthTokenUri == nil {
			return fmt.Errorf("expected oauth token uri to have value; got: nil")
		}
		if *o.OauthTokenUri != expected {
			return fmt.Errorf("expected oauth token uri: %v; got: %v", expected, *o.OauthTokenUri)
		}
		return nil
	})
	return o
}

func (o *OAuthRestAuthenticationAssert) HasOauthClientId(expected string) *OAuthRestAuthenticationAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OAuthRestAuthentication) error {
		t.Helper()
		if o.OauthClientId != expected {
			return fmt.Errorf("expected oauth client id: %v; got: %v", expected, o.OauthClientId)
		}
		return nil
	})
	return o
}

func (o *OAuthRestAuthenticationAssert) HasOauthClientSecret(expected string) *OAuthRestAuthenticationAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OAuthRestAuthentication) error {
		t.Helper()
		if o.OauthClientSecret != expected {
			return fmt.Errorf("expected oauth client secret: %v; got: %v", expected, o.OauthClientSecret)
		}
		return nil
	})
	return o
}

func (o *OAuthRestAuthenticationAssert) HasOauthAllowedScopes(expected ...sdk.StringListItemWrapper) *OAuthRestAuthenticationAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OAuthRestAuthentication) error {
		t.Helper()
		mapped := collections.Map(o.OauthAllowedScopes, func(item sdk.StringListItemWrapper) any { return item })
		mappedExpected := collections.Map(expected, func(item sdk.StringListItemWrapper) any { return item })
		if !slices.Equal(mapped, mappedExpected) {
			return fmt.Errorf("expected oauth allowed scopes: %v; got: %v", expected, o.OauthAllowedScopes)
		}
		return nil
	})
	return o
}
