// Code generated by object assertions generator (v0.1.0); DO NOT EDIT.

package objectassert

import (
	"fmt"
	"testing"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

type OpenCatalogRestConfigAssert struct {
	*assert.SnowflakeObjectAssert[sdk.OpenCatalogRestConfig, sdk.AccountObjectIdentifier]
}

// OpenCatalogRestConfig removed manually

func OpenCatalogRestConfigFromObject(t *testing.T, openCatalogRestConfig *sdk.OpenCatalogRestConfig) *OpenCatalogRestConfigAssert {
	t.Helper()
	return &OpenCatalogRestConfigAssert{
		assert.NewSnowflakeObjectAssertWithObject("OpenCatalogRestConfig", sdk.NewAccountObjectIdentifier(""), openCatalogRestConfig),
	}
}

func (o *OpenCatalogRestConfigAssert) HasCatalogUri(expected string) *OpenCatalogRestConfigAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenCatalogRestConfig) error {
		t.Helper()
		if o.CatalogUri != expected {
			return fmt.Errorf("expected catalog uri: %v; got: %v", expected, o.CatalogUri)
		}
		return nil
	})
	return o
}

func (o *OpenCatalogRestConfigAssert) HasCatalogApiType(expected sdk.CatalogIntegrationCatalogApiType) *OpenCatalogRestConfigAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenCatalogRestConfig) error {
		t.Helper()
		if o.CatalogApiType == nil {
			return fmt.Errorf("expected catalog api type to have value; got: nil")
		}
		if *o.CatalogApiType != expected {
			return fmt.Errorf("expected catalog api type: %v; got: %v", expected, *o.CatalogApiType)
		}
		return nil
	})
	return o
}

func (o *OpenCatalogRestConfigAssert) HasCatalogName(expected string) *OpenCatalogRestConfigAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenCatalogRestConfig) error {
		t.Helper()
		if o.CatalogName != expected {
			return fmt.Errorf("expected catalog name: %v; got: %v", expected, o.CatalogName)
		}
		return nil
	})
	return o
}

func (o *OpenCatalogRestConfigAssert) HasAccessDelegationMode(expected sdk.CatalogIntegrationAccessDelegationMode) *OpenCatalogRestConfigAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenCatalogRestConfig) error {
		t.Helper()
		if o.AccessDelegationMode == nil {
			return fmt.Errorf("expected access delegation mode to have value; got: nil")
		}
		if *o.AccessDelegationMode != expected {
			return fmt.Errorf("expected access delegation mode: %v; got: %v", expected, *o.AccessDelegationMode)
		}
		return nil
	})
	return o
}
