// Code generated by object assertions generator (v0.1.0); DO NOT EDIT.

package objectassert

import (
	"fmt"
	"testing"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

type PolicyReferenceAssert struct {
	*assert.SnowflakeObjectAssert[sdk.PolicyReference, sdk.SchemaObjectIdentifier]
}

func PolicyReferenceFromObject(t *testing.T, policyReference *sdk.PolicyReference) *PolicyReferenceAssert {
	t.Helper()
	return &PolicyReferenceAssert{
		assert.NewSnowflakeObjectAssertWithObject(sdk.ObjectType("PolicyReference"), policyReference.ID(), policyReference),
	}
}

func (p *PolicyReferenceAssert) HasPolicyDb(expected string) *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.PolicyDb == nil {
			return fmt.Errorf("expected policy db to have value; got: nil")
		}
		if *o.PolicyDb != expected {
			return fmt.Errorf("expected policy db: %v; got: %v", expected, *o.PolicyDb)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasNoPolicyDb() *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.PolicyDb != nil {
			return fmt.Errorf("expected policy db to be nil; got: %v", *o.PolicyDb)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasPolicySchema(expected string) *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.PolicySchema == nil {
			return fmt.Errorf("expected policy schema to have value; got: nil")
		}
		if *o.PolicySchema != expected {
			return fmt.Errorf("expected policy schema: %v; got: %v", expected, *o.PolicySchema)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasNoPolicySchema() *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.PolicySchema != nil {
			return fmt.Errorf("expected policy schema to be nil; got: %v", *o.PolicySchema)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasPolicyName(expected string) *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.PolicyName != expected {
			return fmt.Errorf("expected policy name: %v; got: %v", expected, o.PolicyName)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasPolicyNameNotEmpty() *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.PolicyName == "" {
			return fmt.Errorf("expected policy name to be non-empty")
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasPolicyKind(expected sdk.PolicyKind) *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.PolicyKind != expected {
			return fmt.Errorf("expected policy kind: %v; got: %v", expected, o.PolicyKind)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasRefDatabaseName(expected string) *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.RefDatabaseName == nil {
			return fmt.Errorf("expected ref database name to have value; got: nil")
		}
		if *o.RefDatabaseName != expected {
			return fmt.Errorf("expected ref database name: %v; got: %v", expected, *o.RefDatabaseName)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasNoRefDatabaseName() *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.RefDatabaseName != nil {
			return fmt.Errorf("expected ref database name to be nil; got: %v", *o.RefDatabaseName)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasRefSchemaName(expected string) *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.RefSchemaName == nil {
			return fmt.Errorf("expected ref schema name to have value; got: nil")
		}
		if *o.RefSchemaName != expected {
			return fmt.Errorf("expected ref schema name: %v; got: %v", expected, *o.RefSchemaName)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasNoRefSchemaName() *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.RefSchemaName != nil {
			return fmt.Errorf("expected ref schema name to be nil; got: %v", *o.RefSchemaName)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasRefEntityName(expected string) *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.RefEntityName != expected {
			return fmt.Errorf("expected ref entity name: %v; got: %v", expected, o.RefEntityName)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasRefEntityNameNotEmpty() *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.RefEntityName == "" {
			return fmt.Errorf("expected ref entity name to be non-empty")
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasRefEntityDomain(expected string) *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.RefEntityDomain != expected {
			return fmt.Errorf("expected ref entity domain: %v; got: %v", expected, o.RefEntityDomain)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasRefEntityDomainNotEmpty() *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.RefEntityDomain == "" {
			return fmt.Errorf("expected ref entity domain to be non-empty")
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasRefColumnName(expected string) *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.RefColumnName == nil {
			return fmt.Errorf("expected ref column name to have value; got: nil")
		}
		if *o.RefColumnName != expected {
			return fmt.Errorf("expected ref column name: %v; got: %v", expected, *o.RefColumnName)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasNoRefColumnName() *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.RefColumnName != nil {
			return fmt.Errorf("expected ref column name to be nil; got: %v", *o.RefColumnName)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasRefArgColumnNames(expected string) *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.RefArgColumnNames == nil {
			return fmt.Errorf("expected ref arg column names to have value; got: nil")
		}
		if *o.RefArgColumnNames != expected {
			return fmt.Errorf("expected ref arg column names: %v; got: %v", expected, *o.RefArgColumnNames)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasNoRefArgColumnNames() *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.RefArgColumnNames != nil {
			return fmt.Errorf("expected ref arg column names to be nil; got: %v", *o.RefArgColumnNames)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasTagDatabase(expected string) *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.TagDatabase == nil {
			return fmt.Errorf("expected tag database to have value; got: nil")
		}
		if *o.TagDatabase != expected {
			return fmt.Errorf("expected tag database: %v; got: %v", expected, *o.TagDatabase)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasNoTagDatabase() *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.TagDatabase != nil {
			return fmt.Errorf("expected tag database to be nil; got: %v", *o.TagDatabase)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasTagSchema(expected string) *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.TagSchema == nil {
			return fmt.Errorf("expected tag schema to have value; got: nil")
		}
		if *o.TagSchema != expected {
			return fmt.Errorf("expected tag schema: %v; got: %v", expected, *o.TagSchema)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasNoTagSchema() *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.TagSchema != nil {
			return fmt.Errorf("expected tag schema to be nil; got: %v", *o.TagSchema)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasTagName(expected string) *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.TagName == nil {
			return fmt.Errorf("expected tag name to have value; got: nil")
		}
		if *o.TagName != expected {
			return fmt.Errorf("expected tag name: %v; got: %v", expected, *o.TagName)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasNoTagName() *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.TagName != nil {
			return fmt.Errorf("expected tag name to be nil; got: %v", *o.TagName)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasPolicyStatus(expected string) *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.PolicyStatus == nil {
			return fmt.Errorf("expected policy status to have value; got: nil")
		}
		if *o.PolicyStatus != expected {
			return fmt.Errorf("expected policy status: %v; got: %v", expected, *o.PolicyStatus)
		}
		return nil
	})
	return p
}

func (p *PolicyReferenceAssert) HasNoPolicyStatus() *PolicyReferenceAssert {
	p.AddAssertion(func(t *testing.T, o *sdk.PolicyReference) error {
		t.Helper()
		if o.PolicyStatus != nil {
			return fmt.Errorf("expected policy status to be nil; got: %v", *o.PolicyStatus)
		}
		return nil
	})
	return p
}
