// Code generated by object assertions generator (v0.1.0); DO NOT EDIT.

package objectassert

import (
	"fmt"
	"testing"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

type SigV4RestAuthenticationAssert struct {
	*assert.SnowflakeObjectAssert[sdk.SigV4RestAuthentication, sdk.AccountObjectIdentifier]
}

// SigV4RestAuthentication removed manually

func SigV4RestAuthenticationFromObject(t *testing.T, sigV4RestAuthentication *sdk.SigV4RestAuthentication) *SigV4RestAuthenticationAssert {
	t.Helper()
	return &SigV4RestAuthenticationAssert{
		assert.NewSnowflakeObjectAssertWithObject("SigV4RestAuthentication", sdk.NewAccountObjectIdentifier(""), sigV4RestAuthentication),
	}
}

// Manually removed assertions for private fields

func (s *SigV4RestAuthenticationAssert) HasSigv4IamRole(expected string) *SigV4RestAuthenticationAssert {
	s.AddAssertion(func(t *testing.T, o *sdk.SigV4RestAuthentication) error {
		t.Helper()
		if o.Sigv4IamRole != expected {
			return fmt.Errorf("expected sigv4 iam role: %v; got: %v", expected, o.Sigv4IamRole)
		}
		return nil
	})
	return s
}

func (s *SigV4RestAuthenticationAssert) HasSigv4SigningRegion(expected string) *SigV4RestAuthenticationAssert {
	s.AddAssertion(func(t *testing.T, o *sdk.SigV4RestAuthentication) error {
		t.Helper()
		if o.Sigv4SigningRegion == nil {
			return fmt.Errorf("expected sigv4 signing region to have value; got: nil")
		}
		if *o.Sigv4SigningRegion != expected {
			return fmt.Errorf("expected sigv4 signing region: %v; got: %v", expected, *o.Sigv4SigningRegion)
		}
		return nil
	})
	return s
}

func (s *SigV4RestAuthenticationAssert) HasSigv4ExternalId(expected string) *SigV4RestAuthenticationAssert {
	s.AddAssertion(func(t *testing.T, o *sdk.SigV4RestAuthentication) error {
		t.Helper()
		if o.Sigv4ExternalId == nil {
			return fmt.Errorf("expected sigv4 external id to have value; got: nil")
		}
		if *o.Sigv4ExternalId != expected {
			return fmt.Errorf("expected sigv4 external id: %v; got: %v", expected, *o.Sigv4ExternalId)
		}
		return nil
	})
	return s
}
