// Code generated by object assertions generator (v0.1.0); DO NOT EDIT.

package objectassert

import (
	"fmt"
	"testing"
	"time"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/helpers"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

type StorageIntegrationAssert struct {
	*assert.SnowflakeObjectAssert[sdk.StorageIntegration, sdk.AccountObjectIdentifier]
}

func StorageIntegration(t *testing.T, id sdk.AccountObjectIdentifier) *StorageIntegrationAssert {
	t.Helper()
	return &StorageIntegrationAssert{
		assert.NewSnowflakeObjectAssertWithTestClientObjectProvider(sdk.ObjectTypeStorageIntegration, id, func(testClient *helpers.TestClient) assert.ObjectProvider[sdk.StorageIntegration, sdk.AccountObjectIdentifier] {
			return testClient.StorageIntegration.Show
		}),
	}
}

func StorageIntegrationFromObject(t *testing.T, storageIntegration *sdk.StorageIntegration) *StorageIntegrationAssert {
	t.Helper()
	return &StorageIntegrationAssert{
		assert.NewSnowflakeObjectAssertWithObject(sdk.ObjectTypeStorageIntegration, storageIntegration.ID(), storageIntegration),
	}
}

func (s *StorageIntegrationAssert) HasName(expected string) *StorageIntegrationAssert {
	s.AddAssertion(func(t *testing.T, o *sdk.StorageIntegration) error {
		t.Helper()
		if o.Name != expected {
			return fmt.Errorf("expected name: %v; got: %v", expected, o.Name)
		}
		return nil
	})
	return s
}

func (s *StorageIntegrationAssert) HasNameNotEmpty() *StorageIntegrationAssert {
	s.AddAssertion(func(t *testing.T, o *sdk.StorageIntegration) error {
		t.Helper()
		if o.Name == "" {
			return fmt.Errorf("expected name to be non-empty")
		}
		return nil
	})
	return s
}

func (s *StorageIntegrationAssert) HasStorageType(expected string) *StorageIntegrationAssert {
	s.AddAssertion(func(t *testing.T, o *sdk.StorageIntegration) error {
		t.Helper()
		if o.StorageType != expected {
			return fmt.Errorf("expected storage type: %v; got: %v", expected, o.StorageType)
		}
		return nil
	})
	return s
}

func (s *StorageIntegrationAssert) HasStorageTypeNotEmpty() *StorageIntegrationAssert {
	s.AddAssertion(func(t *testing.T, o *sdk.StorageIntegration) error {
		t.Helper()
		if o.StorageType == "" {
			return fmt.Errorf("expected storage type to be non-empty")
		}
		return nil
	})
	return s
}

func (s *StorageIntegrationAssert) HasCategory(expected string) *StorageIntegrationAssert {
	s.AddAssertion(func(t *testing.T, o *sdk.StorageIntegration) error {
		t.Helper()
		if o.Category != expected {
			return fmt.Errorf("expected category: %v; got: %v", expected, o.Category)
		}
		return nil
	})
	return s
}

func (s *StorageIntegrationAssert) HasCategoryNotEmpty() *StorageIntegrationAssert {
	s.AddAssertion(func(t *testing.T, o *sdk.StorageIntegration) error {
		t.Helper()
		if o.Category == "" {
			return fmt.Errorf("expected category to be non-empty")
		}
		return nil
	})
	return s
}

func (s *StorageIntegrationAssert) HasEnabled(expected bool) *StorageIntegrationAssert {
	s.AddAssertion(func(t *testing.T, o *sdk.StorageIntegration) error {
		t.Helper()
		if o.Enabled != expected {
			return fmt.Errorf("expected enabled: %v; got: %v", expected, o.Enabled)
		}
		return nil
	})
	return s
}

func (s *StorageIntegrationAssert) HasComment(expected string) *StorageIntegrationAssert {
	s.AddAssertion(func(t *testing.T, o *sdk.StorageIntegration) error {
		t.Helper()
		if o.Comment != expected {
			return fmt.Errorf("expected comment: %v; got: %v", expected, o.Comment)
		}
		return nil
	})
	return s
}

func (s *StorageIntegrationAssert) HasCommentNotEmpty() *StorageIntegrationAssert {
	s.AddAssertion(func(t *testing.T, o *sdk.StorageIntegration) error {
		t.Helper()
		if o.Comment == "" {
			return fmt.Errorf("expected comment to be non-empty")
		}
		return nil
	})
	return s
}

func (s *StorageIntegrationAssert) HasCreatedOn(expected time.Time) *StorageIntegrationAssert {
	s.AddAssertion(func(t *testing.T, o *sdk.StorageIntegration) error {
		t.Helper()
		if o.CreatedOn != expected {
			return fmt.Errorf("expected created on: %v; got: %v", expected, o.CreatedOn)
		}
		return nil
	})
	return s
}

func (s *StorageIntegrationAssert) HasCreatedOnNotEmpty() *StorageIntegrationAssert {
	s.AddAssertion(func(t *testing.T, o *sdk.StorageIntegration) error {
		t.Helper()
		if o.CreatedOn.IsZero() {
			return fmt.Errorf("expected created on to be set; got zero value")
		}
		return nil
	})
	return s
}
