provider:
  name: snowflakepluginframeworkfunctionaltests
resources:
  warehouse:
    create:
      path: /api/v2/warehouses
      method: POST
    read:
      path: /api/v2/warehouses/{name}
      method: GET
    update:
      path: /api/v2/warehouses/{name}
      method: PUT
    delete:
      path: /api/v2/warehouses/{name}
      method: DELETE
    schema:
      attributes:
        aliases:
          name: id
