package resources

import (
	"context"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/internal/provider"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/generator/defs"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/generator/parameterdefs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

var accountParametersSchema = make(map[string]*schema.Schema)

func init() {
	for _, p := range defs.ParameterDefsForLevel(parameterdefs.ParameterLevelAccount) {
		accountParametersSchema[p.FieldName()] = parameterSchema(p)
	}
}

func handleAccountParametersCreate(d *schema.ResourceData, parameters *sdk.AccountParametersRequest) diag.Diagnostics {
	return JoinDiags(
		handleParameterCreate(d, defs.AbortDetachedQuery.FieldName(), &parameters.AbortDetachedQuery),
		handleParameterCreateWithMapping(d, defs.ActivePythonProfiler.FieldName(), &parameters.ActivePythonProfiler, sdk.ToActivePythonProfiler),
		handleParameterCreate(d, defs.AllowBindValuesAccess.FieldName(), &parameters.AllowBindValuesAccess),
		handleParameterCreate(d, defs.AllowClientMfaCaching.FieldName(), &parameters.AllowClientMfaCaching),
		handleParameterCreate(d, defs.AllowIdToken.FieldName(), &parameters.AllowIdToken),
		handleParameterCreate(d, defs.AllowedSpcsWorkloadTypes.FieldName(), &parameters.AllowedSpcsWorkloadTypes),
		handleParameterCreate(d, defs.Autocommit.FieldName(), &parameters.Autocommit),
		handleParameterCreate(d, defs.BaseLocationPrefix.FieldName(), &parameters.BaseLocationPrefix),
		handleParameterCreateWithMapping(d, defs.BinaryInputFormat.FieldName(), &parameters.BinaryInputFormat, sdk.ToBinaryInputFormat),
		handleParameterCreateWithMapping(d, defs.BinaryOutputFormat.FieldName(), &parameters.BinaryOutputFormat, sdk.ToBinaryOutputFormat),
		handleParameterCreateWithMapping(d, defs.Catalog.FieldName(), &parameters.Catalog, stringToAccountObjectIdentifier),
		handleParameterCreate(d, defs.CatalogSync.FieldName(), &parameters.CatalogSync),
		handleParameterCreate(d, defs.ClientEnableLogInfoStatementParameters.FieldName(), &parameters.ClientEnableLogInfoStatementParameters),
		handleParameterCreate(d, defs.ClientEncryptionKeySize.FieldName(), &parameters.ClientEncryptionKeySize),
		handleParameterCreate(d, defs.ClientMemoryLimit.FieldName(), &parameters.ClientMemoryLimit),
		handleParameterCreate(d, defs.ClientMetadataRequestUseConnectionCtx.FieldName(), &parameters.ClientMetadataRequestUseConnectionCtx),
		handleParameterCreate(d, defs.ClientMetadataUseSessionDatabase.FieldName(), &parameters.ClientMetadataUseSessionDatabase),
		handleParameterCreate(d, defs.ClientPrefetchThreads.FieldName(), &parameters.ClientPrefetchThreads),
		handleParameterCreate(d, defs.ClientResultChunkSize.FieldName(), &parameters.ClientResultChunkSize),
		handleParameterCreate(d, defs.ClientResultColumnCaseInsensitive.FieldName(), &parameters.ClientResultColumnCaseInsensitive),
		handleParameterCreate(d, defs.ClientSessionKeepAlive.FieldName(), &parameters.ClientSessionKeepAlive),
		handleParameterCreate(d, defs.ClientSessionKeepAliveHeartbeatFrequency.FieldName(), &parameters.ClientSessionKeepAliveHeartbeatFrequency),
		handleParameterCreateWithMapping(d, defs.ClientTimestampTypeMapping.FieldName(), &parameters.ClientTimestampTypeMapping, sdk.ToClientTimestampTypeMapping),
		handleParameterCreate(d, defs.CortexCodeCliDailyEstCreditLimitPerUser.FieldName(), &parameters.CortexCodeCliDailyEstCreditLimitPerUser),
		handleParameterCreate(d, defs.CortexCodeDesktopDailyEstCreditLimitPerUser.FieldName(), &parameters.CortexCodeDesktopDailyEstCreditLimitPerUser),
		handleParameterCreate(d, defs.CortexCodeSnowsightDailyEstCreditLimitPerUser.FieldName(), &parameters.CortexCodeSnowsightDailyEstCreditLimitPerUser),
		handleParameterCreate(d, defs.CortexEnabledCrossRegion.FieldName(), &parameters.CortexEnabledCrossRegion),
		// SET stays enabled on create. Only UNSET is skipped, because it reapplies the Snowflake default ALL, which SET no longer accepts (SNOW-3953840).
		handleParameterCreate(d, defs.CortexModelsAllowlist.FieldName(), &parameters.CortexModelsAllowlist),
		handleParameterCreate(d, defs.CsvTimestampFormat.FieldName(), &parameters.CsvTimestampFormat),
		handleParameterCreate(d, defs.DataMetricSchedule.FieldName(), &parameters.DataMetricSchedule),
		handleParameterCreate(d, defs.DataRetentionTimeInDays.FieldName(), &parameters.DataRetentionTimeInDays),
		handleParameterCreate(d, defs.DateInputFormat.FieldName(), &parameters.DateInputFormat),
		handleParameterCreate(d, defs.DateOutputFormat.FieldName(), &parameters.DateOutputFormat),
		handleParameterCreate(d, defs.DefaultDbtVersion.FieldName(), &parameters.DefaultDbtVersion),
		handleParameterCreateWithMapping(d, defs.DefaultDdlCollation.FieldName(), &parameters.DefaultDdlCollation, func(value string) (sdk.StringAllowEmpty, error) { return sdk.StringAllowEmpty{Value: value}, nil }),
		handleParameterCreate(d, defs.DefaultNotebookComputePoolCpu.FieldName(), &parameters.DefaultNotebookComputePoolCpu),
		handleParameterCreate(d, defs.DefaultNotebookComputePoolGpu.FieldName(), &parameters.DefaultNotebookComputePoolGpu),
		handleParameterCreateWithMapping(d, defs.DefaultNullOrdering.FieldName(), &parameters.DefaultNullOrdering, sdk.ToDefaultNullOrdering),
		handleParameterCreate(d, defs.DefaultStreamlitComputePool.FieldName(), &parameters.DefaultStreamlitComputePool),
		handleParameterCreateWithMapping(d, defs.DefaultStreamlitNotebookWarehouse.FieldName(), &parameters.DefaultStreamlitNotebookWarehouse, stringToAccountObjectIdentifier),
		handleParameterCreate(d, defs.DisableUiDownloadButton.FieldName(), &parameters.DisableUiDownloadButton),
		handleParameterCreate(d, defs.DisableUserPrivilegeGrants.FieldName(), &parameters.DisableUserPrivilegeGrants),
		handleParameterCreate(d, defs.DisallowedSpcsWorkloadTypes.FieldName(), &parameters.DisallowedSpcsWorkloadTypes),
		handleParameterCreate(d, defs.EnableAutomaticSensitiveDataClassificationLog.FieldName(), &parameters.EnableAutomaticSensitiveDataClassificationLog),
		handleParameterCreate(d, defs.EnableBudgetEventLogging.FieldName(), &parameters.EnableBudgetEventLogging),
		handleParameterCreate(d, defs.EnableCortexAnalyst.FieldName(), &parameters.EnableCortexAnalyst),
		handleParameterCreate(d, defs.EnableDataCompaction.FieldName(), &parameters.EnableDataCompaction),
		handleParameterCreate(d, defs.EnableEgressCostOptimizer.FieldName(), &parameters.EnableEgressCostOptimizer),
		handleParameterCreate(d, defs.EnableGetDdlUseDataTypeAlias.FieldName(), &parameters.EnableGetDdlUseDataTypeAlias),
		handleParameterCreate(d, defs.EnableIcebergMergeOnRead.FieldName(), &parameters.EnableIcebergMergeOnRead),
		handleParameterCreate(d, defs.EnableIdentifierFirstLogin.FieldName(), &parameters.EnableIdentifierFirstLogin),
		handleParameterCreate(d, defs.EnableInternalStagesPrivatelink.FieldName(), &parameters.EnableInternalStagesPrivatelink),
		handleParameterCreate(d, defs.EnableNotebookCreationInPersonalDb.FieldName(), &parameters.EnableNotebookCreationInPersonalDb),
		handleParameterCreate(d, defs.EnablePerAccountAppServicePrivatelinkUrl.FieldName(), &parameters.EnablePerAccountAppServicePrivatelinkUrl),
		handleParameterCreate(d, defs.EnableSpcsBlockStorageSnowflakeFullEncryptionEnforcement.FieldName(), &parameters.EnableSpcsBlockStorageSnowflakeFullEncryptionEnforcement),
		handleParameterCreate(d, defs.EnableTagPropagationEventLogging.FieldName(), &parameters.EnableTagPropagationEventLogging),
		handleParameterCreate(d, defs.EnableTriSecretAndRekeyOptOutForImageRepository.FieldName(), &parameters.EnableTriSecretAndRekeyOptOutForImageRepository),
		handleParameterCreate(d, defs.EnableTriSecretAndRekeyOptOutForSpcsBlockStorage.FieldName(), &parameters.EnableTriSecretAndRekeyOptOutForSpcsBlockStorage),
		handleParameterCreate(d, defs.EnableUnhandledExceptionsReporting.FieldName(), &parameters.EnableUnhandledExceptionsReporting),
		handleParameterCreate(d, defs.EnableUnloadPhysicalTypeOptimization.FieldName(), &parameters.EnableUnloadPhysicalTypeOptimization),
		handleParameterCreate(d, defs.EnableUnredactedQuerySyntaxError.FieldName(), &parameters.EnableUnredactedQuerySyntaxError),
		handleParameterCreate(d, defs.EnableUnredactedSecureObjectError.FieldName(), &parameters.EnableUnredactedSecureObjectError),
		handleParameterCreate(d, defs.EnforceNetworkRulesForInternalStages.FieldName(), &parameters.EnforceNetworkRulesForInternalStages),
		handleParameterCreate(d, defs.ErrorOnNondeterministicMerge.FieldName(), &parameters.ErrorOnNondeterministicMerge),
		handleParameterCreate(d, defs.ErrorOnNondeterministicUpdate.FieldName(), &parameters.ErrorOnNondeterministicUpdate),
		handleParameterCreateWithMapping(d, defs.EventTable.FieldName(), &parameters.EventTable, sdk.ParseSchemaObjectIdentifier),
		handleParameterCreate(d, defs.ExternalOauthAddPrivilegedRolesToBlockedList.FieldName(), &parameters.ExternalOauthAddPrivilegedRolesToBlockedList),
		handleParameterCreateWithMapping(d, defs.ExternalVolume.FieldName(), &parameters.ExternalVolume, stringToAccountObjectIdentifier),
		handleParameterCreateWithMapping(d, defs.GeographyOutputFormat.FieldName(), &parameters.GeographyOutputFormat, sdk.ToGeographyOutputFormat),
		handleParameterCreateWithMapping(d, defs.GeometryOutputFormat.FieldName(), &parameters.GeometryOutputFormat, sdk.ToGeometryOutputFormat),
		handleParameterCreate(d, defs.HybridTableLockTimeout.FieldName(), &parameters.HybridTableLockTimeout),
		handleParameterCreate(d, defs.IcebergVersionDefault.FieldName(), &parameters.IcebergVersionDefault),
		handleParameterCreateWithMapping(d, defs.InitialReplicationSizeLimitInTb.FieldName(), &parameters.InitialReplicationSizeLimitInTb, sdk.ToFloat64),
		handleParameterCreate(d, defs.JdbcTreatDecimalAsInt.FieldName(), &parameters.JdbcTreatDecimalAsInt),
		handleParameterCreate(d, defs.JdbcTreatTimestampNtzAsUtc.FieldName(), &parameters.JdbcTreatTimestampNtzAsUtc),
		handleParameterCreate(d, defs.JdbcUseSessionTimezone.FieldName(), &parameters.JdbcUseSessionTimezone),
		handleParameterCreate(d, defs.JsTreatIntegerAsBigint.FieldName(), &parameters.JsTreatIntegerAsBigint),
		handleParameterCreate(d, defs.JsonIndent.FieldName(), &parameters.JsonIndent),
		handleParameterCreate(d, defs.ListingAutoFulfillmentReplicationRefreshSchedule.FieldName(), &parameters.ListingAutoFulfillmentReplicationRefreshSchedule),
		handleParameterCreate(d, defs.LockTimeout.FieldName(), &parameters.LockTimeout),
		handleParameterCreateWithMapping(d, defs.LogEventLevel.FieldName(), &parameters.LogEventLevel, sdk.ToLogLevel),
		handleParameterCreateWithMapping(d, defs.LogLevel.FieldName(), &parameters.LogLevel, sdk.ToLogLevel),
		handleParameterCreate(d, defs.MaxConcurrencyLevel.FieldName(), &parameters.MaxConcurrencyLevel),
		handleParameterCreate(d, defs.MaxDataExtensionTimeInDays.FieldName(), &parameters.MaxDataExtensionTimeInDays),
		handleParameterCreateWithMapping(d, defs.MetricLevel.FieldName(), &parameters.MetricLevel, sdk.ToMetricLevel),
		handleParameterCreate(d, defs.MinDataRetentionTimeInDays.FieldName(), &parameters.MinDataRetentionTimeInDays),
		handleParameterCreate(d, defs.MultiStatementCount.FieldName(), &parameters.MultiStatementCount),
		handleParameterCreateWithMapping(d, defs.NetworkPolicy.FieldName(), &parameters.NetworkPolicy, stringToAccountObjectIdentifier),
		handleParameterCreate(d, defs.NoorderSequenceAsDefault.FieldName(), &parameters.NoorderSequenceAsDefault),
		handleParameterCreate(d, defs.OauthAddPrivilegedRolesToBlockedList.FieldName(), &parameters.OauthAddPrivilegedRolesToBlockedList),
		handleParameterCreate(d, defs.OdbcTreatDecimalAsInt.FieldName(), &parameters.OdbcTreatDecimalAsInt),
		handleParameterCreate(d, defs.PeriodicDataRekeying.FieldName(), &parameters.PeriodicDataRekeying),
		handleParameterCreate(d, defs.PipeExecutionPaused.FieldName(), &parameters.PipeExecutionPaused),
		handleParameterCreate(d, defs.PreventUnloadToInlineUrl.FieldName(), &parameters.PreventUnloadToInlineUrl),
		handleParameterCreate(d, defs.PreventUnloadToInternalStages.FieldName(), &parameters.PreventUnloadToInternalStages),
		handleParameterCreate(d, defs.PythonProfilerModules.FieldName(), &parameters.PythonProfilerModules),
		handleParameterCreateWithMapping(d, defs.PythonProfilerTargetStage.FieldName(), &parameters.PythonProfilerTargetStage, sdk.ParseSchemaObjectIdentifier),
		handleParameterCreate(d, defs.QueryTag.FieldName(), &parameters.QueryTag),
		handleParameterCreate(d, defs.QuotedIdentifiersIgnoreCase.FieldName(), &parameters.QuotedIdentifiersIgnoreCase),
		handleParameterCreate(d, defs.ReadConsistencyMode.FieldName(), &parameters.ReadConsistencyMode),
		handleParameterCreate(d, defs.ReplaceInvalidCharacters.FieldName(), &parameters.ReplaceInvalidCharacters),
		handleParameterCreate(d, defs.RequireStorageIntegrationForStageCreation.FieldName(), &parameters.RequireStorageIntegrationForStageCreation),
		handleParameterCreate(d, defs.RequireStorageIntegrationForStageOperation.FieldName(), &parameters.RequireStorageIntegrationForStageOperation),
		handleParameterCreate(d, defs.RowTimestampDefault.FieldName(), &parameters.RowTimestampDefault),
		handleParameterCreate(d, defs.RowsPerResultset.FieldName(), &parameters.RowsPerResultset),
		handleParameterCreate(d, defs.S3StageVpceDnsName.FieldName(), &parameters.S3StageVpceDnsName),
		handleParameterCreate(d, defs.SearchPath.FieldName(), &parameters.SearchPath),
		handleParameterCreateWithMapping(d, defs.ServerlessTaskMaxStatementSize.FieldName(), &parameters.ServerlessTaskMaxStatementSize, sdk.ToWarehouseSize),
		handleParameterCreateWithMapping(d, defs.ServerlessTaskMinStatementSize.FieldName(), &parameters.ServerlessTaskMinStatementSize, sdk.ToWarehouseSize),
		handleParameterCreate(d, defs.SimulatedDataSharingConsumer.FieldName(), &parameters.SimulatedDataSharingConsumer),
		handleParameterCreate(d, defs.SqlTraceQueryText.FieldName(), &parameters.SqlTraceQueryText),
		handleParameterCreate(d, defs.SsoLoginPage.FieldName(), &parameters.SsoLoginPage),
		handleParameterCreate(d, defs.StatementQueuedTimeoutInSeconds.FieldName(), &parameters.StatementQueuedTimeoutInSeconds),
		handleParameterCreate(d, defs.StatementTimeoutInSeconds.FieldName(), &parameters.StatementTimeoutInSeconds),
		handleParameterCreateWithMapping(d, defs.StorageSerializationPolicy.FieldName(), &parameters.StorageSerializationPolicy, sdk.ToStorageSerializationPolicy),
		handleParameterCreate(d, defs.StrictJsonOutput.FieldName(), &parameters.StrictJsonOutput),
		handleParameterCreate(d, defs.SuspendTaskAfterNumFailures.FieldName(), &parameters.SuspendTaskAfterNumFailures),
		handleParameterCreate(d, defs.TaskAutoRetryAttempts.FieldName(), &parameters.TaskAutoRetryAttempts),
		handleParameterCreate(d, defs.TimeInputFormat.FieldName(), &parameters.TimeInputFormat),
		handleParameterCreate(d, defs.TimeOutputFormat.FieldName(), &parameters.TimeOutputFormat),
		handleParameterCreate(d, defs.TimestampDayIsAlways24h.FieldName(), &parameters.TimestampDayIsAlways24H),
		handleParameterCreate(d, defs.TimestampInputFormat.FieldName(), &parameters.TimestampInputFormat),
		handleParameterCreate(d, defs.TimestampLtzOutputFormat.FieldName(), &parameters.TimestampLtzOutputFormat),
		handleParameterCreate(d, defs.TimestampNtzOutputFormat.FieldName(), &parameters.TimestampNtzOutputFormat),
		handleParameterCreate(d, defs.TimestampOutputFormat.FieldName(), &parameters.TimestampOutputFormat),
		handleParameterCreateWithMapping(d, defs.TimestampTypeMapping.FieldName(), &parameters.TimestampTypeMapping, sdk.ToTimestampTypeMapping),
		handleParameterCreate(d, defs.TimestampTzOutputFormat.FieldName(), &parameters.TimestampTzOutputFormat),
		handleParameterCreate(d, defs.Timezone.FieldName(), &parameters.Timezone),
		handleParameterCreateWithMapping(d, defs.TraceLevel.FieldName(), &parameters.TraceLevel, sdk.ToTraceLevel),
		handleParameterCreate(d, defs.TransactionAbortOnError.FieldName(), &parameters.TransactionAbortOnError),
		handleParameterCreateWithMapping(d, defs.TransactionDefaultIsolationLevel.FieldName(), &parameters.TransactionDefaultIsolationLevel, sdk.ToTransactionDefaultIsolationLevel),
		handleParameterCreate(d, defs.TwoDigitCenturyStart.FieldName(), &parameters.TwoDigitCenturyStart),
		handleParameterCreateWithMapping(d, defs.UnsupportedDdlAction.FieldName(), &parameters.UnsupportedDdlAction, sdk.ToUnsupportedDDLAction),
		handleParameterCreate(d, defs.UseCachedResult.FieldName(), &parameters.UseCachedResult),
		handleParameterCreate(d, defs.UseWorkspacesForSql.FieldName(), &parameters.UseWorkspacesForSql),
		handleParameterCreateWithMapping(d, defs.UserTaskManagedInitialWarehouseSize.FieldName(), &parameters.UserTaskManagedInitialWarehouseSize, sdk.ToWarehouseSize),
		handleParameterCreate(d, defs.UserTaskMinimumTriggerIntervalInSeconds.FieldName(), &parameters.UserTaskMinimumTriggerIntervalInSeconds),
		handleParameterCreate(d, defs.UserTaskTimeoutMs.FieldName(), &parameters.UserTaskTimeoutMs),
		handleParameterCreate(d, defs.WeekOfYearPolicy.FieldName(), &parameters.WeekOfYearPolicy),
		handleParameterCreate(d, defs.WeekStart.FieldName(), &parameters.WeekStart),
	)
}

func handleAccountParametersUpdate(d *schema.ResourceData, set *sdk.AccountParametersRequest, unset *sdk.AccountParametersUnsetRequest) diag.Diagnostics {
	// UNSET reapplies the Snowflake default ALL, which is no longer accepted (SNOW-3953840).
	var skipCortexModelsAllowlistUnset *bool
	return JoinDiags(
		handleParameterUpdate(d, defs.AbortDetachedQuery.FieldName(), &set.AbortDetachedQuery, &unset.AbortDetachedQuery),
		handleParameterUpdateWithMapping(d, defs.ActivePythonProfiler.FieldName(), &set.ActivePythonProfiler, &unset.ActivePythonProfiler, sdk.ToActivePythonProfiler),
		handleParameterUpdate(d, defs.AllowBindValuesAccess.FieldName(), &set.AllowBindValuesAccess, &unset.AllowBindValuesAccess),
		handleParameterUpdate(d, defs.AllowClientMfaCaching.FieldName(), &set.AllowClientMfaCaching, &unset.AllowClientMfaCaching),
		handleParameterUpdate(d, defs.AllowIdToken.FieldName(), &set.AllowIdToken, &unset.AllowIdToken),
		handleParameterUpdate(d, defs.AllowedSpcsWorkloadTypes.FieldName(), &set.AllowedSpcsWorkloadTypes, &unset.AllowedSpcsWorkloadTypes),
		handleParameterUpdate(d, defs.Autocommit.FieldName(), &set.Autocommit, &unset.Autocommit),
		handleParameterUpdate(d, defs.BaseLocationPrefix.FieldName(), &set.BaseLocationPrefix, &unset.BaseLocationPrefix),
		handleParameterUpdateWithMapping(d, defs.BinaryInputFormat.FieldName(), &set.BinaryInputFormat, &unset.BinaryInputFormat, sdk.ToBinaryInputFormat),
		handleParameterUpdateWithMapping(d, defs.BinaryOutputFormat.FieldName(), &set.BinaryOutputFormat, &unset.BinaryOutputFormat, sdk.ToBinaryOutputFormat),
		handleParameterUpdateWithMapping(d, defs.Catalog.FieldName(), &set.Catalog, &unset.Catalog, stringToAccountObjectIdentifier),
		handleParameterUpdate(d, defs.CatalogSync.FieldName(), &set.CatalogSync, &unset.CatalogSync),
		handleParameterUpdate(d, defs.ClientEnableLogInfoStatementParameters.FieldName(), &set.ClientEnableLogInfoStatementParameters, &unset.ClientEnableLogInfoStatementParameters),
		handleParameterUpdate(d, defs.ClientEncryptionKeySize.FieldName(), &set.ClientEncryptionKeySize, &unset.ClientEncryptionKeySize),
		handleParameterUpdate(d, defs.ClientMemoryLimit.FieldName(), &set.ClientMemoryLimit, &unset.ClientMemoryLimit),
		handleParameterUpdate(d, defs.ClientMetadataRequestUseConnectionCtx.FieldName(), &set.ClientMetadataRequestUseConnectionCtx, &unset.ClientMetadataRequestUseConnectionCtx),
		handleParameterUpdate(d, defs.ClientMetadataUseSessionDatabase.FieldName(), &set.ClientMetadataUseSessionDatabase, &unset.ClientMetadataUseSessionDatabase),
		handleParameterUpdate(d, defs.ClientPrefetchThreads.FieldName(), &set.ClientPrefetchThreads, &unset.ClientPrefetchThreads),
		handleParameterUpdate(d, defs.ClientResultChunkSize.FieldName(), &set.ClientResultChunkSize, &unset.ClientResultChunkSize),
		handleParameterUpdate(d, defs.ClientResultColumnCaseInsensitive.FieldName(), &set.ClientResultColumnCaseInsensitive, &unset.ClientResultColumnCaseInsensitive),
		handleParameterUpdate(d, defs.ClientSessionKeepAlive.FieldName(), &set.ClientSessionKeepAlive, &unset.ClientSessionKeepAlive),
		handleParameterUpdate(d, defs.ClientSessionKeepAliveHeartbeatFrequency.FieldName(), &set.ClientSessionKeepAliveHeartbeatFrequency, &unset.ClientSessionKeepAliveHeartbeatFrequency),
		handleParameterUpdateWithMapping(d, defs.ClientTimestampTypeMapping.FieldName(), &set.ClientTimestampTypeMapping, &unset.ClientTimestampTypeMapping, sdk.ToClientTimestampTypeMapping),
		handleParameterUpdate(d, defs.CortexCodeCliDailyEstCreditLimitPerUser.FieldName(), &set.CortexCodeCliDailyEstCreditLimitPerUser, &unset.CortexCodeCliDailyEstCreditLimitPerUser),
		handleParameterUpdate(d, defs.CortexCodeDesktopDailyEstCreditLimitPerUser.FieldName(), &set.CortexCodeDesktopDailyEstCreditLimitPerUser, &unset.CortexCodeDesktopDailyEstCreditLimitPerUser),
		handleParameterUpdate(d, defs.CortexCodeSnowsightDailyEstCreditLimitPerUser.FieldName(), &set.CortexCodeSnowsightDailyEstCreditLimitPerUser, &unset.CortexCodeSnowsightDailyEstCreditLimitPerUser),
		handleParameterUpdate(d, defs.CortexEnabledCrossRegion.FieldName(), &set.CortexEnabledCrossRegion, &unset.CortexEnabledCrossRegion),
		handleParameterUpdate(d, defs.CortexModelsAllowlist.FieldName(), &set.CortexModelsAllowlist, &skipCortexModelsAllowlistUnset),
		handleParameterUpdate(d, defs.CsvTimestampFormat.FieldName(), &set.CsvTimestampFormat, &unset.CsvTimestampFormat),
		handleParameterUpdate(d, defs.DataMetricSchedule.FieldName(), &set.DataMetricSchedule, &unset.DataMetricSchedule),
		handleParameterUpdate(d, defs.DataRetentionTimeInDays.FieldName(), &set.DataRetentionTimeInDays, &unset.DataRetentionTimeInDays),
		handleParameterUpdate(d, defs.DateInputFormat.FieldName(), &set.DateInputFormat, &unset.DateInputFormat),
		handleParameterUpdate(d, defs.DateOutputFormat.FieldName(), &set.DateOutputFormat, &unset.DateOutputFormat),
		handleParameterUpdate(d, defs.DefaultDbtVersion.FieldName(), &set.DefaultDbtVersion, &unset.DefaultDbtVersion),
		handleParameterUpdateWithMapping(d, defs.DefaultDdlCollation.FieldName(), &set.DefaultDdlCollation, &unset.DefaultDdlCollation, func(value string) (sdk.StringAllowEmpty, error) { return sdk.StringAllowEmpty{Value: value}, nil }),
		handleParameterUpdate(d, defs.DefaultNotebookComputePoolCpu.FieldName(), &set.DefaultNotebookComputePoolCpu, &unset.DefaultNotebookComputePoolCpu),
		handleParameterUpdate(d, defs.DefaultNotebookComputePoolGpu.FieldName(), &set.DefaultNotebookComputePoolGpu, &unset.DefaultNotebookComputePoolGpu),
		handleParameterUpdateWithMapping(d, defs.DefaultNullOrdering.FieldName(), &set.DefaultNullOrdering, &unset.DefaultNullOrdering, sdk.ToDefaultNullOrdering),
		handleParameterUpdate(d, defs.DefaultStreamlitComputePool.FieldName(), &set.DefaultStreamlitComputePool, &unset.DefaultStreamlitComputePool),
		handleParameterUpdateWithMapping(d, defs.DefaultStreamlitNotebookWarehouse.FieldName(), &set.DefaultStreamlitNotebookWarehouse, &unset.DefaultStreamlitNotebookWarehouse, stringToAccountObjectIdentifier),
		handleParameterUpdate(d, defs.DisableUiDownloadButton.FieldName(), &set.DisableUiDownloadButton, &unset.DisableUiDownloadButton),
		handleParameterUpdate(d, defs.DisableUserPrivilegeGrants.FieldName(), &set.DisableUserPrivilegeGrants, &unset.DisableUserPrivilegeGrants),
		handleParameterUpdate(d, defs.DisallowedSpcsWorkloadTypes.FieldName(), &set.DisallowedSpcsWorkloadTypes, &unset.DisallowedSpcsWorkloadTypes),
		handleParameterUpdate(d, defs.EnableAutomaticSensitiveDataClassificationLog.FieldName(), &set.EnableAutomaticSensitiveDataClassificationLog, &unset.EnableAutomaticSensitiveDataClassificationLog),
		handleParameterUpdate(d, defs.EnableBudgetEventLogging.FieldName(), &set.EnableBudgetEventLogging, &unset.EnableBudgetEventLogging),
		handleParameterUpdate(d, defs.EnableCortexAnalyst.FieldName(), &set.EnableCortexAnalyst, &unset.EnableCortexAnalyst),
		handleParameterUpdate(d, defs.EnableDataCompaction.FieldName(), &set.EnableDataCompaction, &unset.EnableDataCompaction),
		handleParameterUpdate(d, defs.EnableEgressCostOptimizer.FieldName(), &set.EnableEgressCostOptimizer, &unset.EnableEgressCostOptimizer),
		handleParameterUpdate(d, defs.EnableGetDdlUseDataTypeAlias.FieldName(), &set.EnableGetDdlUseDataTypeAlias, &unset.EnableGetDdlUseDataTypeAlias),
		handleParameterUpdate(d, defs.EnableIcebergMergeOnRead.FieldName(), &set.EnableIcebergMergeOnRead, &unset.EnableIcebergMergeOnRead),
		handleParameterUpdate(d, defs.EnableIdentifierFirstLogin.FieldName(), &set.EnableIdentifierFirstLogin, &unset.EnableIdentifierFirstLogin),
		handleParameterUpdate(d, defs.EnableInternalStagesPrivatelink.FieldName(), &set.EnableInternalStagesPrivatelink, &unset.EnableInternalStagesPrivatelink),
		handleParameterUpdate(d, defs.EnableNotebookCreationInPersonalDb.FieldName(), &set.EnableNotebookCreationInPersonalDb, &unset.EnableNotebookCreationInPersonalDb),
		handleParameterUpdate(d, defs.EnablePerAccountAppServicePrivatelinkUrl.FieldName(), &set.EnablePerAccountAppServicePrivatelinkUrl, &unset.EnablePerAccountAppServicePrivatelinkUrl),
		handleParameterUpdate(d, defs.EnableSpcsBlockStorageSnowflakeFullEncryptionEnforcement.FieldName(), &set.EnableSpcsBlockStorageSnowflakeFullEncryptionEnforcement, &unset.EnableSpcsBlockStorageSnowflakeFullEncryptionEnforcement),
		handleParameterUpdate(d, defs.EnableTagPropagationEventLogging.FieldName(), &set.EnableTagPropagationEventLogging, &unset.EnableTagPropagationEventLogging),
		handleParameterUpdate(d, defs.EnableTriSecretAndRekeyOptOutForImageRepository.FieldName(), &set.EnableTriSecretAndRekeyOptOutForImageRepository, &unset.EnableTriSecretAndRekeyOptOutForImageRepository),
		handleParameterUpdate(d, defs.EnableTriSecretAndRekeyOptOutForSpcsBlockStorage.FieldName(), &set.EnableTriSecretAndRekeyOptOutForSpcsBlockStorage, &unset.EnableTriSecretAndRekeyOptOutForSpcsBlockStorage),
		handleParameterUpdate(d, defs.EnableUnhandledExceptionsReporting.FieldName(), &set.EnableUnhandledExceptionsReporting, &unset.EnableUnhandledExceptionsReporting),
		handleParameterUpdate(d, defs.EnableUnloadPhysicalTypeOptimization.FieldName(), &set.EnableUnloadPhysicalTypeOptimization, &unset.EnableUnloadPhysicalTypeOptimization),
		handleParameterUpdate(d, defs.EnableUnredactedQuerySyntaxError.FieldName(), &set.EnableUnredactedQuerySyntaxError, &unset.EnableUnredactedQuerySyntaxError),
		handleParameterUpdate(d, defs.EnableUnredactedSecureObjectError.FieldName(), &set.EnableUnredactedSecureObjectError, &unset.EnableUnredactedSecureObjectError),
		handleParameterUpdate(d, defs.EnforceNetworkRulesForInternalStages.FieldName(), &set.EnforceNetworkRulesForInternalStages, &unset.EnforceNetworkRulesForInternalStages),
		handleParameterUpdate(d, defs.ErrorOnNondeterministicMerge.FieldName(), &set.ErrorOnNondeterministicMerge, &unset.ErrorOnNondeterministicMerge),
		handleParameterUpdate(d, defs.ErrorOnNondeterministicUpdate.FieldName(), &set.ErrorOnNondeterministicUpdate, &unset.ErrorOnNondeterministicUpdate),
		handleParameterUpdateWithMapping(d, defs.EventTable.FieldName(), &set.EventTable, &unset.EventTable, sdk.ParseSchemaObjectIdentifier),
		handleParameterUpdate(d, defs.ExternalOauthAddPrivilegedRolesToBlockedList.FieldName(), &set.ExternalOauthAddPrivilegedRolesToBlockedList, &unset.ExternalOauthAddPrivilegedRolesToBlockedList),
		handleParameterUpdateWithMapping(d, defs.ExternalVolume.FieldName(), &set.ExternalVolume, &unset.ExternalVolume, stringToAccountObjectIdentifier),
		handleParameterUpdateWithMapping(d, defs.GeographyOutputFormat.FieldName(), &set.GeographyOutputFormat, &unset.GeographyOutputFormat, sdk.ToGeographyOutputFormat),
		handleParameterUpdateWithMapping(d, defs.GeometryOutputFormat.FieldName(), &set.GeometryOutputFormat, &unset.GeometryOutputFormat, sdk.ToGeometryOutputFormat),
		handleParameterUpdate(d, defs.HybridTableLockTimeout.FieldName(), &set.HybridTableLockTimeout, &unset.HybridTableLockTimeout),
		handleParameterUpdate(d, defs.IcebergVersionDefault.FieldName(), &set.IcebergVersionDefault, &unset.IcebergVersionDefault),
		handleParameterUpdateWithMapping(d, defs.InitialReplicationSizeLimitInTb.FieldName(), &set.InitialReplicationSizeLimitInTb, &unset.InitialReplicationSizeLimitInTb, sdk.ToFloat64),
		handleParameterUpdate(d, defs.JdbcTreatDecimalAsInt.FieldName(), &set.JdbcTreatDecimalAsInt, &unset.JdbcTreatDecimalAsInt),
		handleParameterUpdate(d, defs.JdbcTreatTimestampNtzAsUtc.FieldName(), &set.JdbcTreatTimestampNtzAsUtc, &unset.JdbcTreatTimestampNtzAsUtc),
		handleParameterUpdate(d, defs.JdbcUseSessionTimezone.FieldName(), &set.JdbcUseSessionTimezone, &unset.JdbcUseSessionTimezone),
		handleParameterUpdate(d, defs.JsTreatIntegerAsBigint.FieldName(), &set.JsTreatIntegerAsBigint, &unset.JsTreatIntegerAsBigint),
		handleParameterUpdate(d, defs.JsonIndent.FieldName(), &set.JsonIndent, &unset.JsonIndent),
		handleParameterUpdate(d, defs.ListingAutoFulfillmentReplicationRefreshSchedule.FieldName(), &set.ListingAutoFulfillmentReplicationRefreshSchedule, &unset.ListingAutoFulfillmentReplicationRefreshSchedule),
		handleParameterUpdate(d, defs.LockTimeout.FieldName(), &set.LockTimeout, &unset.LockTimeout),
		handleParameterUpdateWithMapping(d, defs.LogEventLevel.FieldName(), &set.LogEventLevel, &unset.LogEventLevel, sdk.ToLogLevel),
		handleParameterUpdateWithMapping(d, defs.LogLevel.FieldName(), &set.LogLevel, &unset.LogLevel, sdk.ToLogLevel),
		handleParameterUpdate(d, defs.MaxConcurrencyLevel.FieldName(), &set.MaxConcurrencyLevel, &unset.MaxConcurrencyLevel),
		handleParameterUpdate(d, defs.MaxDataExtensionTimeInDays.FieldName(), &set.MaxDataExtensionTimeInDays, &unset.MaxDataExtensionTimeInDays),
		handleParameterUpdateWithMapping(d, defs.MetricLevel.FieldName(), &set.MetricLevel, &unset.MetricLevel, sdk.ToMetricLevel),
		handleParameterUpdate(d, defs.MinDataRetentionTimeInDays.FieldName(), &set.MinDataRetentionTimeInDays, &unset.MinDataRetentionTimeInDays),
		handleParameterUpdate(d, defs.MultiStatementCount.FieldName(), &set.MultiStatementCount, &unset.MultiStatementCount),
		handleParameterUpdateWithMapping(d, defs.NetworkPolicy.FieldName(), &set.NetworkPolicy, &unset.NetworkPolicy, stringToAccountObjectIdentifier),
		handleParameterUpdate(d, defs.NoorderSequenceAsDefault.FieldName(), &set.NoorderSequenceAsDefault, &unset.NoorderSequenceAsDefault),
		handleParameterUpdate(d, defs.OauthAddPrivilegedRolesToBlockedList.FieldName(), &set.OauthAddPrivilegedRolesToBlockedList, &unset.OauthAddPrivilegedRolesToBlockedList),
		handleParameterUpdate(d, defs.OdbcTreatDecimalAsInt.FieldName(), &set.OdbcTreatDecimalAsInt, &unset.OdbcTreatDecimalAsInt),
		handleParameterUpdate(d, defs.PeriodicDataRekeying.FieldName(), &set.PeriodicDataRekeying, &unset.PeriodicDataRekeying),
		handleParameterUpdate(d, defs.PipeExecutionPaused.FieldName(), &set.PipeExecutionPaused, &unset.PipeExecutionPaused),
		handleParameterUpdate(d, defs.PreventUnloadToInlineUrl.FieldName(), &set.PreventUnloadToInlineUrl, &unset.PreventUnloadToInlineUrl),
		handleParameterUpdate(d, defs.PreventUnloadToInternalStages.FieldName(), &set.PreventUnloadToInternalStages, &unset.PreventUnloadToInternalStages),
		handleParameterUpdate(d, defs.PythonProfilerModules.FieldName(), &set.PythonProfilerModules, &unset.PythonProfilerModules),
		handleParameterUpdateWithMapping(d, defs.PythonProfilerTargetStage.FieldName(), &set.PythonProfilerTargetStage, &unset.PythonProfilerTargetStage, sdk.ParseSchemaObjectIdentifier),
		handleParameterUpdate(d, defs.QueryTag.FieldName(), &set.QueryTag, &unset.QueryTag),
		handleParameterUpdate(d, defs.QuotedIdentifiersIgnoreCase.FieldName(), &set.QuotedIdentifiersIgnoreCase, &unset.QuotedIdentifiersIgnoreCase),
		handleParameterUpdate(d, defs.ReadConsistencyMode.FieldName(), &set.ReadConsistencyMode, &unset.ReadConsistencyMode),
		handleParameterUpdate(d, defs.ReplaceInvalidCharacters.FieldName(), &set.ReplaceInvalidCharacters, &unset.ReplaceInvalidCharacters),
		handleParameterUpdate(d, defs.RequireStorageIntegrationForStageCreation.FieldName(), &set.RequireStorageIntegrationForStageCreation, &unset.RequireStorageIntegrationForStageCreation),
		handleParameterUpdate(d, defs.RequireStorageIntegrationForStageOperation.FieldName(), &set.RequireStorageIntegrationForStageOperation, &unset.RequireStorageIntegrationForStageOperation),
		handleParameterUpdate(d, defs.RowTimestampDefault.FieldName(), &set.RowTimestampDefault, &unset.RowTimestampDefault),
		handleParameterUpdate(d, defs.RowsPerResultset.FieldName(), &set.RowsPerResultset, &unset.RowsPerResultset),
		handleParameterUpdate(d, defs.S3StageVpceDnsName.FieldName(), &set.S3StageVpceDnsName, &unset.S3StageVpceDnsName),
		handleParameterUpdate(d, defs.SearchPath.FieldName(), &set.SearchPath, &unset.SearchPath),
		handleParameterUpdateWithMapping(d, defs.ServerlessTaskMaxStatementSize.FieldName(), &set.ServerlessTaskMaxStatementSize, &unset.ServerlessTaskMaxStatementSize, sdk.ToWarehouseSize),
		handleParameterUpdateWithMapping(d, defs.ServerlessTaskMinStatementSize.FieldName(), &set.ServerlessTaskMinStatementSize, &unset.ServerlessTaskMinStatementSize, sdk.ToWarehouseSize),
		handleParameterUpdate(d, defs.SimulatedDataSharingConsumer.FieldName(), &set.SimulatedDataSharingConsumer, &unset.SimulatedDataSharingConsumer),
		handleParameterUpdate(d, defs.SqlTraceQueryText.FieldName(), &set.SqlTraceQueryText, &unset.SqlTraceQueryText),
		handleParameterUpdate(d, defs.SsoLoginPage.FieldName(), &set.SsoLoginPage, &unset.SsoLoginPage),
		handleParameterUpdate(d, defs.StatementQueuedTimeoutInSeconds.FieldName(), &set.StatementQueuedTimeoutInSeconds, &unset.StatementQueuedTimeoutInSeconds),
		handleParameterUpdate(d, defs.StatementTimeoutInSeconds.FieldName(), &set.StatementTimeoutInSeconds, &unset.StatementTimeoutInSeconds),
		handleParameterUpdateWithMapping(d, defs.StorageSerializationPolicy.FieldName(), &set.StorageSerializationPolicy, &unset.StorageSerializationPolicy, sdk.ToStorageSerializationPolicy),
		handleParameterUpdate(d, defs.StrictJsonOutput.FieldName(), &set.StrictJsonOutput, &unset.StrictJsonOutput),
		handleParameterUpdate(d, defs.SuspendTaskAfterNumFailures.FieldName(), &set.SuspendTaskAfterNumFailures, &unset.SuspendTaskAfterNumFailures),
		handleParameterUpdate(d, defs.TaskAutoRetryAttempts.FieldName(), &set.TaskAutoRetryAttempts, &unset.TaskAutoRetryAttempts),
		handleParameterUpdate(d, defs.TimeInputFormat.FieldName(), &set.TimeInputFormat, &unset.TimeInputFormat),
		handleParameterUpdate(d, defs.TimeOutputFormat.FieldName(), &set.TimeOutputFormat, &unset.TimeOutputFormat),
		handleParameterUpdate(d, defs.TimestampDayIsAlways24h.FieldName(), &set.TimestampDayIsAlways24H, &unset.TimestampDayIsAlways24H),
		handleParameterUpdate(d, defs.TimestampInputFormat.FieldName(), &set.TimestampInputFormat, &unset.TimestampInputFormat),
		handleParameterUpdate(d, defs.TimestampLtzOutputFormat.FieldName(), &set.TimestampLtzOutputFormat, &unset.TimestampLtzOutputFormat),
		handleParameterUpdate(d, defs.TimestampNtzOutputFormat.FieldName(), &set.TimestampNtzOutputFormat, &unset.TimestampNtzOutputFormat),
		handleParameterUpdate(d, defs.TimestampOutputFormat.FieldName(), &set.TimestampOutputFormat, &unset.TimestampOutputFormat),
		handleParameterUpdateWithMapping(d, defs.TimestampTypeMapping.FieldName(), &set.TimestampTypeMapping, &unset.TimestampTypeMapping, sdk.ToTimestampTypeMapping),
		handleParameterUpdate(d, defs.TimestampTzOutputFormat.FieldName(), &set.TimestampTzOutputFormat, &unset.TimestampTzOutputFormat),
		handleParameterUpdate(d, defs.Timezone.FieldName(), &set.Timezone, &unset.Timezone),
		handleParameterUpdateWithMapping(d, defs.TraceLevel.FieldName(), &set.TraceLevel, &unset.TraceLevel, sdk.ToTraceLevel),
		handleParameterUpdate(d, defs.TransactionAbortOnError.FieldName(), &set.TransactionAbortOnError, &unset.TransactionAbortOnError),
		handleParameterUpdateWithMapping(d, defs.TransactionDefaultIsolationLevel.FieldName(), &set.TransactionDefaultIsolationLevel, &unset.TransactionDefaultIsolationLevel, sdk.ToTransactionDefaultIsolationLevel),
		handleParameterUpdate(d, defs.TwoDigitCenturyStart.FieldName(), &set.TwoDigitCenturyStart, &unset.TwoDigitCenturyStart),
		handleParameterUpdateWithMapping(d, defs.UnsupportedDdlAction.FieldName(), &set.UnsupportedDdlAction, &unset.UnsupportedDdlAction, sdk.ToUnsupportedDDLAction),
		handleParameterUpdate(d, defs.UseCachedResult.FieldName(), &set.UseCachedResult, &unset.UseCachedResult),
		handleParameterUpdate(d, defs.UseWorkspacesForSql.FieldName(), &set.UseWorkspacesForSql, &unset.UseWorkspacesForSql),
		handleParameterUpdateWithMapping(d, defs.UserTaskManagedInitialWarehouseSize.FieldName(), &set.UserTaskManagedInitialWarehouseSize, &unset.UserTaskManagedInitialWarehouseSize, sdk.ToWarehouseSize),
		handleParameterUpdate(d, defs.UserTaskMinimumTriggerIntervalInSeconds.FieldName(), &set.UserTaskMinimumTriggerIntervalInSeconds, &unset.UserTaskMinimumTriggerIntervalInSeconds),
		handleParameterUpdate(d, defs.UserTaskTimeoutMs.FieldName(), &set.UserTaskTimeoutMs, &unset.UserTaskTimeoutMs),
		handleParameterUpdate(d, defs.WeekOfYearPolicy.FieldName(), &set.WeekOfYearPolicy, &unset.WeekOfYearPolicy),
		handleParameterUpdate(d, defs.WeekStart.FieldName(), &set.WeekStart, &unset.WeekStart),
	)
}

func handleAccountParameterRead(d *schema.ResourceData, parameters *sdk.AccountParametersDetails) diag.Diagnostics {
	return JoinDiags(
		setResourceData(d, defs.AbortDetachedQuery.FieldName(), parameters.AbortDetachedQuery.Value),
		setResourceData(d, defs.ActivePythonProfiler.FieldName(), parameters.ActivePythonProfiler.Value),
		setResourceData(d, defs.AllowBindValuesAccess.FieldName(), parameters.AllowBindValuesAccess.Value),
		setResourceData(d, defs.AllowClientMfaCaching.FieldName(), parameters.AllowClientMfaCaching.Value),
		setResourceData(d, defs.AllowIdToken.FieldName(), parameters.AllowIdToken.Value),
		setResourceData(d, defs.AllowedSpcsWorkloadTypes.FieldName(), parameters.AllowedSpcsWorkloadTypes.Value),
		setResourceData(d, defs.Autocommit.FieldName(), parameters.Autocommit.Value),
		setResourceData(d, defs.BaseLocationPrefix.FieldName(), parameters.BaseLocationPrefix.Value),
		setResourceData(d, defs.BinaryInputFormat.FieldName(), parameters.BinaryInputFormat.Value),
		setResourceData(d, defs.BinaryOutputFormat.FieldName(), parameters.BinaryOutputFormat.Value),
		setResourceData(d, defs.Catalog.FieldName(), parameters.Catalog.Value.FullyQualifiedName()),
		setResourceData(d, defs.CatalogSync.FieldName(), parameters.CatalogSync.Value),
		setResourceData(d, defs.ClientEnableLogInfoStatementParameters.FieldName(), parameters.ClientEnableLogInfoStatementParameters.Value),
		setResourceData(d, defs.ClientEncryptionKeySize.FieldName(), parameters.ClientEncryptionKeySize.Value),
		setResourceData(d, defs.ClientMemoryLimit.FieldName(), parameters.ClientMemoryLimit.Value),
		setResourceData(d, defs.ClientMetadataRequestUseConnectionCtx.FieldName(), parameters.ClientMetadataRequestUseConnectionCtx.Value),
		setResourceData(d, defs.ClientMetadataUseSessionDatabase.FieldName(), parameters.ClientMetadataUseSessionDatabase.Value),
		setResourceData(d, defs.ClientPrefetchThreads.FieldName(), parameters.ClientPrefetchThreads.Value),
		setResourceData(d, defs.ClientResultChunkSize.FieldName(), parameters.ClientResultChunkSize.Value),
		setResourceData(d, defs.ClientResultColumnCaseInsensitive.FieldName(), parameters.ClientResultColumnCaseInsensitive.Value),
		setResourceData(d, defs.ClientSessionKeepAlive.FieldName(), parameters.ClientSessionKeepAlive.Value),
		setResourceData(d, defs.ClientSessionKeepAliveHeartbeatFrequency.FieldName(), parameters.ClientSessionKeepAliveHeartbeatFrequency.Value),
		setResourceData(d, defs.ClientTimestampTypeMapping.FieldName(), parameters.ClientTimestampTypeMapping.Value),
		setResourceData(d, defs.CortexCodeCliDailyEstCreditLimitPerUser.FieldName(), parameters.CortexCodeCliDailyEstCreditLimitPerUser.Value),
		setResourceData(d, defs.CortexCodeDesktopDailyEstCreditLimitPerUser.FieldName(), parameters.CortexCodeDesktopDailyEstCreditLimitPerUser.Value),
		setResourceData(d, defs.CortexCodeSnowsightDailyEstCreditLimitPerUser.FieldName(), parameters.CortexCodeSnowsightDailyEstCreditLimitPerUser.Value),
		setResourceData(d, defs.CortexEnabledCrossRegion.FieldName(), parameters.CortexEnabledCrossRegion.Value),
		setResourceData(d, defs.CortexModelsAllowlist.FieldName(), parameters.CortexModelsAllowlist.Value),
		setResourceData(d, defs.CsvTimestampFormat.FieldName(), parameters.CsvTimestampFormat.Value),
		setResourceData(d, defs.DataMetricSchedule.FieldName(), parameters.DataMetricSchedule.Value),
		setResourceData(d, defs.DataRetentionTimeInDays.FieldName(), parameters.DataRetentionTimeInDays.Value),
		setResourceData(d, defs.DateInputFormat.FieldName(), parameters.DateInputFormat.Value),
		setResourceData(d, defs.DateOutputFormat.FieldName(), parameters.DateOutputFormat.Value),
		setResourceData(d, defs.DefaultDbtVersion.FieldName(), parameters.DefaultDbtVersion.Value),
		setResourceData(d, defs.DefaultDdlCollation.FieldName(), parameters.DefaultDdlCollation.Value),
		setResourceData(d, defs.DefaultNotebookComputePoolCpu.FieldName(), parameters.DefaultNotebookComputePoolCpu.Value),
		setResourceData(d, defs.DefaultNotebookComputePoolGpu.FieldName(), parameters.DefaultNotebookComputePoolGpu.Value),
		setResourceData(d, defs.DefaultNullOrdering.FieldName(), parameters.DefaultNullOrdering.Value),
		setResourceData(d, defs.DefaultStreamlitComputePool.FieldName(), parameters.DefaultStreamlitComputePool.Value),
		setResourceData(d, defs.DefaultStreamlitNotebookWarehouse.FieldName(), parameters.DefaultStreamlitNotebookWarehouse.Value.FullyQualifiedName()),
		setResourceData(d, defs.DisableUiDownloadButton.FieldName(), parameters.DisableUiDownloadButton.Value),
		setResourceData(d, defs.DisableUserPrivilegeGrants.FieldName(), parameters.DisableUserPrivilegeGrants.Value),
		setResourceData(d, defs.DisallowedSpcsWorkloadTypes.FieldName(), parameters.DisallowedSpcsWorkloadTypes.Value),
		setResourceData(d, defs.EnableAutomaticSensitiveDataClassificationLog.FieldName(), parameters.EnableAutomaticSensitiveDataClassificationLog.Value),
		setResourceData(d, defs.EnableBudgetEventLogging.FieldName(), parameters.EnableBudgetEventLogging.Value),
		setResourceData(d, defs.EnableCortexAnalyst.FieldName(), parameters.EnableCortexAnalyst.Value),
		setResourceData(d, defs.EnableDataCompaction.FieldName(), parameters.EnableDataCompaction.Value),
		setResourceData(d, defs.EnableEgressCostOptimizer.FieldName(), parameters.EnableEgressCostOptimizer.Value),
		setResourceData(d, defs.EnableGetDdlUseDataTypeAlias.FieldName(), parameters.EnableGetDdlUseDataTypeAlias.Value),
		setResourceData(d, defs.EnableIcebergMergeOnRead.FieldName(), parameters.EnableIcebergMergeOnRead.Value),
		setResourceData(d, defs.EnableIdentifierFirstLogin.FieldName(), parameters.EnableIdentifierFirstLogin.Value),
		setResourceData(d, defs.EnableInternalStagesPrivatelink.FieldName(), parameters.EnableInternalStagesPrivatelink.Value),
		setResourceData(d, defs.EnableNotebookCreationInPersonalDb.FieldName(), parameters.EnableNotebookCreationInPersonalDb.Value),
		setResourceData(d, defs.EnablePerAccountAppServicePrivatelinkUrl.FieldName(), parameters.EnablePerAccountAppServicePrivatelinkUrl.Value),
		setResourceData(d, defs.EnableSpcsBlockStorageSnowflakeFullEncryptionEnforcement.FieldName(), parameters.EnableSpcsBlockStorageSnowflakeFullEncryptionEnforcement.Value),
		setResourceData(d, defs.EnableTagPropagationEventLogging.FieldName(), parameters.EnableTagPropagationEventLogging.Value),
		setResourceData(d, defs.EnableTriSecretAndRekeyOptOutForImageRepository.FieldName(), parameters.EnableTriSecretAndRekeyOptOutForImageRepository.Value),
		setResourceData(d, defs.EnableTriSecretAndRekeyOptOutForSpcsBlockStorage.FieldName(), parameters.EnableTriSecretAndRekeyOptOutForSpcsBlockStorage.Value),
		setResourceData(d, defs.EnableUnhandledExceptionsReporting.FieldName(), parameters.EnableUnhandledExceptionsReporting.Value),
		setResourceData(d, defs.EnableUnloadPhysicalTypeOptimization.FieldName(), parameters.EnableUnloadPhysicalTypeOptimization.Value),
		setResourceData(d, defs.EnableUnredactedQuerySyntaxError.FieldName(), parameters.EnableUnredactedQuerySyntaxError.Value),
		setResourceData(d, defs.EnableUnredactedSecureObjectError.FieldName(), parameters.EnableUnredactedSecureObjectError.Value),
		setResourceData(d, defs.EnforceNetworkRulesForInternalStages.FieldName(), parameters.EnforceNetworkRulesForInternalStages.Value),
		setResourceData(d, defs.ErrorOnNondeterministicMerge.FieldName(), parameters.ErrorOnNondeterministicMerge.Value),
		setResourceData(d, defs.ErrorOnNondeterministicUpdate.FieldName(), parameters.ErrorOnNondeterministicUpdate.Value),
		setResourceData(d, defs.EventTable.FieldName(), parameters.EventTable.Value.FullyQualifiedName()),
		setResourceData(d, defs.ExternalOauthAddPrivilegedRolesToBlockedList.FieldName(), parameters.ExternalOauthAddPrivilegedRolesToBlockedList.Value),
		setResourceData(d, defs.ExternalVolume.FieldName(), parameters.ExternalVolume.Value.FullyQualifiedName()),
		setResourceData(d, defs.GeographyOutputFormat.FieldName(), parameters.GeographyOutputFormat.Value),
		setResourceData(d, defs.GeometryOutputFormat.FieldName(), parameters.GeometryOutputFormat.Value),
		setResourceData(d, defs.HybridTableLockTimeout.FieldName(), parameters.HybridTableLockTimeout.Value),
		setResourceData(d, defs.IcebergVersionDefault.FieldName(), parameters.IcebergVersionDefault.Value),
		setResourceData(d, defs.InitialReplicationSizeLimitInTb.FieldName(), formatFloatParameter(parameters.InitialReplicationSizeLimitInTb.Value)),
		setResourceData(d, defs.JdbcTreatDecimalAsInt.FieldName(), parameters.JdbcTreatDecimalAsInt.Value),
		setResourceData(d, defs.JdbcTreatTimestampNtzAsUtc.FieldName(), parameters.JdbcTreatTimestampNtzAsUtc.Value),
		setResourceData(d, defs.JdbcUseSessionTimezone.FieldName(), parameters.JdbcUseSessionTimezone.Value),
		setResourceData(d, defs.JsTreatIntegerAsBigint.FieldName(), parameters.JsTreatIntegerAsBigint.Value),
		setResourceData(d, defs.JsonIndent.FieldName(), parameters.JsonIndent.Value),
		setResourceData(d, defs.ListingAutoFulfillmentReplicationRefreshSchedule.FieldName(), parameters.ListingAutoFulfillmentReplicationRefreshSchedule.Value),
		setResourceData(d, defs.LockTimeout.FieldName(), parameters.LockTimeout.Value),
		setResourceData(d, defs.LogEventLevel.FieldName(), parameters.LogEventLevel.Value),
		setResourceData(d, defs.LogLevel.FieldName(), parameters.LogLevel.Value),
		setResourceData(d, defs.MaxConcurrencyLevel.FieldName(), parameters.MaxConcurrencyLevel.Value),
		setResourceData(d, defs.MaxDataExtensionTimeInDays.FieldName(), parameters.MaxDataExtensionTimeInDays.Value),
		setResourceData(d, defs.MetricLevel.FieldName(), parameters.MetricLevel.Value),
		setResourceData(d, defs.MinDataRetentionTimeInDays.FieldName(), parameters.MinDataRetentionTimeInDays.Value),
		setResourceData(d, defs.MultiStatementCount.FieldName(), parameters.MultiStatementCount.Value),
		setResourceData(d, defs.NetworkPolicy.FieldName(), parameters.NetworkPolicy.Value.FullyQualifiedName()),
		setResourceData(d, defs.NoorderSequenceAsDefault.FieldName(), parameters.NoorderSequenceAsDefault.Value),
		setResourceData(d, defs.OauthAddPrivilegedRolesToBlockedList.FieldName(), parameters.OauthAddPrivilegedRolesToBlockedList.Value),
		setResourceData(d, defs.OdbcTreatDecimalAsInt.FieldName(), parameters.OdbcTreatDecimalAsInt.Value),
		setResourceData(d, defs.PeriodicDataRekeying.FieldName(), parameters.PeriodicDataRekeying.Value),
		setResourceData(d, defs.PipeExecutionPaused.FieldName(), parameters.PipeExecutionPaused.Value),
		setResourceData(d, defs.PreventUnloadToInlineUrl.FieldName(), parameters.PreventUnloadToInlineUrl.Value),
		setResourceData(d, defs.PreventUnloadToInternalStages.FieldName(), parameters.PreventUnloadToInternalStages.Value),
		setResourceData(d, defs.PythonProfilerModules.FieldName(), parameters.PythonProfilerModules.Value),
		setResourceData(d, defs.PythonProfilerTargetStage.FieldName(), parameters.PythonProfilerTargetStage.Value.FullyQualifiedName()),
		setResourceData(d, defs.QueryTag.FieldName(), parameters.QueryTag.Value),
		setResourceData(d, defs.QuotedIdentifiersIgnoreCase.FieldName(), parameters.QuotedIdentifiersIgnoreCase.Value),
		setResourceData(d, defs.ReadConsistencyMode.FieldName(), parameters.ReadConsistencyMode.Value),
		setResourceData(d, defs.ReplaceInvalidCharacters.FieldName(), parameters.ReplaceInvalidCharacters.Value),
		setResourceData(d, defs.RequireStorageIntegrationForStageCreation.FieldName(), parameters.RequireStorageIntegrationForStageCreation.Value),
		setResourceData(d, defs.RequireStorageIntegrationForStageOperation.FieldName(), parameters.RequireStorageIntegrationForStageOperation.Value),
		setResourceData(d, defs.RowTimestampDefault.FieldName(), parameters.RowTimestampDefault.Value),
		setResourceData(d, defs.RowsPerResultset.FieldName(), parameters.RowsPerResultset.Value),
		setResourceData(d, defs.S3StageVpceDnsName.FieldName(), parameters.S3StageVpceDnsName.Value),
		setResourceData(d, defs.SearchPath.FieldName(), parameters.SearchPath.Value),
		setResourceData(d, defs.ServerlessTaskMaxStatementSize.FieldName(), parameters.ServerlessTaskMaxStatementSize.Value),
		setResourceData(d, defs.ServerlessTaskMinStatementSize.FieldName(), parameters.ServerlessTaskMinStatementSize.Value),
		setResourceData(d, defs.SimulatedDataSharingConsumer.FieldName(), parameters.SimulatedDataSharingConsumer.Value),
		setResourceData(d, defs.SqlTraceQueryText.FieldName(), parameters.SqlTraceQueryText.Value),
		setResourceData(d, defs.SsoLoginPage.FieldName(), parameters.SsoLoginPage.Value),
		setResourceData(d, defs.StatementQueuedTimeoutInSeconds.FieldName(), parameters.StatementQueuedTimeoutInSeconds.Value),
		setResourceData(d, defs.StatementTimeoutInSeconds.FieldName(), parameters.StatementTimeoutInSeconds.Value),
		setResourceData(d, defs.StorageSerializationPolicy.FieldName(), parameters.StorageSerializationPolicy.Value),
		setResourceData(d, defs.StrictJsonOutput.FieldName(), parameters.StrictJsonOutput.Value),
		setResourceData(d, defs.SuspendTaskAfterNumFailures.FieldName(), parameters.SuspendTaskAfterNumFailures.Value),
		setResourceData(d, defs.TaskAutoRetryAttempts.FieldName(), parameters.TaskAutoRetryAttempts.Value),
		setResourceData(d, defs.TimeInputFormat.FieldName(), parameters.TimeInputFormat.Value),
		setResourceData(d, defs.TimeOutputFormat.FieldName(), parameters.TimeOutputFormat.Value),
		setResourceData(d, defs.TimestampDayIsAlways24h.FieldName(), parameters.TimestampDayIsAlways24H.Value),
		setResourceData(d, defs.TimestampInputFormat.FieldName(), parameters.TimestampInputFormat.Value),
		setResourceData(d, defs.TimestampLtzOutputFormat.FieldName(), parameters.TimestampLtzOutputFormat.Value),
		setResourceData(d, defs.TimestampNtzOutputFormat.FieldName(), parameters.TimestampNtzOutputFormat.Value),
		setResourceData(d, defs.TimestampOutputFormat.FieldName(), parameters.TimestampOutputFormat.Value),
		setResourceData(d, defs.TimestampTypeMapping.FieldName(), parameters.TimestampTypeMapping.Value),
		setResourceData(d, defs.TimestampTzOutputFormat.FieldName(), parameters.TimestampTzOutputFormat.Value),
		setResourceData(d, defs.Timezone.FieldName(), parameters.Timezone.Value),
		setResourceData(d, defs.TraceLevel.FieldName(), parameters.TraceLevel.Value),
		setResourceData(d, defs.TransactionAbortOnError.FieldName(), parameters.TransactionAbortOnError.Value),
		setResourceData(d, defs.TransactionDefaultIsolationLevel.FieldName(), parameters.TransactionDefaultIsolationLevel.Value),
		setResourceData(d, defs.TwoDigitCenturyStart.FieldName(), parameters.TwoDigitCenturyStart.Value),
		setResourceData(d, defs.UnsupportedDdlAction.FieldName(), parameters.UnsupportedDdlAction.Value),
		setResourceData(d, defs.UseCachedResult.FieldName(), parameters.UseCachedResult.Value),
		setResourceData(d, defs.UseWorkspacesForSql.FieldName(), parameters.UseWorkspacesForSql.Value),
		setResourceData(d, defs.UserTaskManagedInitialWarehouseSize.FieldName(), parameters.UserTaskManagedInitialWarehouseSize.Value),
		setResourceData(d, defs.UserTaskMinimumTriggerIntervalInSeconds.FieldName(), parameters.UserTaskMinimumTriggerIntervalInSeconds.Value),
		setResourceData(d, defs.UserTaskTimeoutMs.FieldName(), parameters.UserTaskTimeoutMs.Value),
		setResourceData(d, defs.WeekOfYearPolicy.FieldName(), parameters.WeekOfYearPolicy.Value),
		setResourceData(d, defs.WeekStart.FieldName(), parameters.WeekStart.Value),
	)
}

var accountParametersCustomDiff = ParametersCustomDiffFromTypedParameters(
	accountParametersProvider,
	accountParameterDiffFunctions,
)

func accountParametersProvider(ctx context.Context, _ ResourceIdProvider, meta any) (*sdk.AccountParametersDetails, error) {
	return meta.(*provider.Context).Client.Accounts.ShowParametersDetails(ctx)
}

func accountParameterDiffFunctions(parameters *sdk.AccountParametersDetails) []schema.CustomizeDiffFunc {
	return []schema.CustomizeDiffFunc{
		BoolTypedParameterValueComputedIf(defs.AbortDetachedQuery.FieldName(), parameters.AbortDetachedQuery, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.ActivePythonProfiler.FieldName(), parameters.ActivePythonProfiler, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.AllowBindValuesAccess.FieldName(), parameters.AllowBindValuesAccess, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.AllowClientMfaCaching.FieldName(), parameters.AllowClientMfaCaching, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.AllowIdToken.FieldName(), parameters.AllowIdToken, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.AllowedSpcsWorkloadTypes.FieldName(), parameters.AllowedSpcsWorkloadTypes, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.Autocommit.FieldName(), parameters.Autocommit, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.BaseLocationPrefix.FieldName(), parameters.BaseLocationPrefix, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.BinaryInputFormat.FieldName(), parameters.BinaryInputFormat, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.BinaryOutputFormat.FieldName(), parameters.BinaryOutputFormat, sdk.ParameterTypeAccount),
		IdentifierTypedParameterValueComputedIf(defs.Catalog.FieldName(), parameters.Catalog, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.CatalogSync.FieldName(), parameters.CatalogSync, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.ClientEnableLogInfoStatementParameters.FieldName(), parameters.ClientEnableLogInfoStatementParameters, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.ClientEncryptionKeySize.FieldName(), parameters.ClientEncryptionKeySize, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.ClientMemoryLimit.FieldName(), parameters.ClientMemoryLimit, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.ClientMetadataRequestUseConnectionCtx.FieldName(), parameters.ClientMetadataRequestUseConnectionCtx, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.ClientMetadataUseSessionDatabase.FieldName(), parameters.ClientMetadataUseSessionDatabase, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.ClientPrefetchThreads.FieldName(), parameters.ClientPrefetchThreads, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.ClientResultChunkSize.FieldName(), parameters.ClientResultChunkSize, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.ClientResultColumnCaseInsensitive.FieldName(), parameters.ClientResultColumnCaseInsensitive, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.ClientSessionKeepAlive.FieldName(), parameters.ClientSessionKeepAlive, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.ClientSessionKeepAliveHeartbeatFrequency.FieldName(), parameters.ClientSessionKeepAliveHeartbeatFrequency, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.ClientTimestampTypeMapping.FieldName(), parameters.ClientTimestampTypeMapping, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.CortexCodeCliDailyEstCreditLimitPerUser.FieldName(), parameters.CortexCodeCliDailyEstCreditLimitPerUser, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.CortexCodeDesktopDailyEstCreditLimitPerUser.FieldName(), parameters.CortexCodeDesktopDailyEstCreditLimitPerUser, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.CortexCodeSnowsightDailyEstCreditLimitPerUser.FieldName(), parameters.CortexCodeSnowsightDailyEstCreditLimitPerUser, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.CortexEnabledCrossRegion.FieldName(), parameters.CortexEnabledCrossRegion, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.CortexModelsAllowlist.FieldName(), parameters.CortexModelsAllowlist, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.CsvTimestampFormat.FieldName(), parameters.CsvTimestampFormat, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.DataMetricSchedule.FieldName(), parameters.DataMetricSchedule, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.DataRetentionTimeInDays.FieldName(), parameters.DataRetentionTimeInDays, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.DateInputFormat.FieldName(), parameters.DateInputFormat, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.DateOutputFormat.FieldName(), parameters.DateOutputFormat, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.DefaultDbtVersion.FieldName(), parameters.DefaultDbtVersion, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.DefaultDdlCollation.FieldName(), parameters.DefaultDdlCollation, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.DefaultNotebookComputePoolCpu.FieldName(), parameters.DefaultNotebookComputePoolCpu, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.DefaultNotebookComputePoolGpu.FieldName(), parameters.DefaultNotebookComputePoolGpu, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.DefaultNullOrdering.FieldName(), parameters.DefaultNullOrdering, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.DefaultStreamlitComputePool.FieldName(), parameters.DefaultStreamlitComputePool, sdk.ParameterTypeAccount),
		IdentifierTypedParameterValueComputedIf(defs.DefaultStreamlitNotebookWarehouse.FieldName(), parameters.DefaultStreamlitNotebookWarehouse, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.DisableUiDownloadButton.FieldName(), parameters.DisableUiDownloadButton, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.DisableUserPrivilegeGrants.FieldName(), parameters.DisableUserPrivilegeGrants, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.DisallowedSpcsWorkloadTypes.FieldName(), parameters.DisallowedSpcsWorkloadTypes, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableAutomaticSensitiveDataClassificationLog.FieldName(), parameters.EnableAutomaticSensitiveDataClassificationLog, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableBudgetEventLogging.FieldName(), parameters.EnableBudgetEventLogging, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableCortexAnalyst.FieldName(), parameters.EnableCortexAnalyst, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableDataCompaction.FieldName(), parameters.EnableDataCompaction, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableEgressCostOptimizer.FieldName(), parameters.EnableEgressCostOptimizer, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableGetDdlUseDataTypeAlias.FieldName(), parameters.EnableGetDdlUseDataTypeAlias, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableIcebergMergeOnRead.FieldName(), parameters.EnableIcebergMergeOnRead, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableIdentifierFirstLogin.FieldName(), parameters.EnableIdentifierFirstLogin, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableInternalStagesPrivatelink.FieldName(), parameters.EnableInternalStagesPrivatelink, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableNotebookCreationInPersonalDb.FieldName(), parameters.EnableNotebookCreationInPersonalDb, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnablePerAccountAppServicePrivatelinkUrl.FieldName(), parameters.EnablePerAccountAppServicePrivatelinkUrl, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableSpcsBlockStorageSnowflakeFullEncryptionEnforcement.FieldName(), parameters.EnableSpcsBlockStorageSnowflakeFullEncryptionEnforcement, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableTagPropagationEventLogging.FieldName(), parameters.EnableTagPropagationEventLogging, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableTriSecretAndRekeyOptOutForImageRepository.FieldName(), parameters.EnableTriSecretAndRekeyOptOutForImageRepository, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableTriSecretAndRekeyOptOutForSpcsBlockStorage.FieldName(), parameters.EnableTriSecretAndRekeyOptOutForSpcsBlockStorage, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableUnhandledExceptionsReporting.FieldName(), parameters.EnableUnhandledExceptionsReporting, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableUnloadPhysicalTypeOptimization.FieldName(), parameters.EnableUnloadPhysicalTypeOptimization, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableUnredactedQuerySyntaxError.FieldName(), parameters.EnableUnredactedQuerySyntaxError, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnableUnredactedSecureObjectError.FieldName(), parameters.EnableUnredactedSecureObjectError, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.EnforceNetworkRulesForInternalStages.FieldName(), parameters.EnforceNetworkRulesForInternalStages, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.ErrorOnNondeterministicMerge.FieldName(), parameters.ErrorOnNondeterministicMerge, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.ErrorOnNondeterministicUpdate.FieldName(), parameters.ErrorOnNondeterministicUpdate, sdk.ParameterTypeAccount),
		IdentifierTypedParameterValueComputedIf(defs.EventTable.FieldName(), parameters.EventTable, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.ExternalOauthAddPrivilegedRolesToBlockedList.FieldName(), parameters.ExternalOauthAddPrivilegedRolesToBlockedList, sdk.ParameterTypeAccount),
		IdentifierTypedParameterValueComputedIf(defs.ExternalVolume.FieldName(), parameters.ExternalVolume, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.GeographyOutputFormat.FieldName(), parameters.GeographyOutputFormat, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.GeometryOutputFormat.FieldName(), parameters.GeometryOutputFormat, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.HybridTableLockTimeout.FieldName(), parameters.HybridTableLockTimeout, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.IcebergVersionDefault.FieldName(), parameters.IcebergVersionDefault, sdk.ParameterTypeAccount),
		FloatTypedParameterValueComputedIf(defs.InitialReplicationSizeLimitInTb.FieldName(), parameters.InitialReplicationSizeLimitInTb, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.JdbcTreatDecimalAsInt.FieldName(), parameters.JdbcTreatDecimalAsInt, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.JdbcTreatTimestampNtzAsUtc.FieldName(), parameters.JdbcTreatTimestampNtzAsUtc, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.JdbcUseSessionTimezone.FieldName(), parameters.JdbcUseSessionTimezone, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.JsTreatIntegerAsBigint.FieldName(), parameters.JsTreatIntegerAsBigint, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.JsonIndent.FieldName(), parameters.JsonIndent, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.ListingAutoFulfillmentReplicationRefreshSchedule.FieldName(), parameters.ListingAutoFulfillmentReplicationRefreshSchedule, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.LockTimeout.FieldName(), parameters.LockTimeout, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.LogEventLevel.FieldName(), parameters.LogEventLevel, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.LogLevel.FieldName(), parameters.LogLevel, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.MaxConcurrencyLevel.FieldName(), parameters.MaxConcurrencyLevel, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.MaxDataExtensionTimeInDays.FieldName(), parameters.MaxDataExtensionTimeInDays, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.MetricLevel.FieldName(), parameters.MetricLevel, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.MinDataRetentionTimeInDays.FieldName(), parameters.MinDataRetentionTimeInDays, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.MultiStatementCount.FieldName(), parameters.MultiStatementCount, sdk.ParameterTypeAccount),
		IdentifierTypedParameterValueComputedIf(defs.NetworkPolicy.FieldName(), parameters.NetworkPolicy, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.NoorderSequenceAsDefault.FieldName(), parameters.NoorderSequenceAsDefault, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.OauthAddPrivilegedRolesToBlockedList.FieldName(), parameters.OauthAddPrivilegedRolesToBlockedList, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.OdbcTreatDecimalAsInt.FieldName(), parameters.OdbcTreatDecimalAsInt, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.PeriodicDataRekeying.FieldName(), parameters.PeriodicDataRekeying, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.PipeExecutionPaused.FieldName(), parameters.PipeExecutionPaused, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.PreventUnloadToInlineUrl.FieldName(), parameters.PreventUnloadToInlineUrl, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.PreventUnloadToInternalStages.FieldName(), parameters.PreventUnloadToInternalStages, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.PythonProfilerModules.FieldName(), parameters.PythonProfilerModules, sdk.ParameterTypeAccount),
		IdentifierTypedParameterValueComputedIf(defs.PythonProfilerTargetStage.FieldName(), parameters.PythonProfilerTargetStage, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.QueryTag.FieldName(), parameters.QueryTag, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.QuotedIdentifiersIgnoreCase.FieldName(), parameters.QuotedIdentifiersIgnoreCase, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.ReadConsistencyMode.FieldName(), parameters.ReadConsistencyMode, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.ReplaceInvalidCharacters.FieldName(), parameters.ReplaceInvalidCharacters, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.RequireStorageIntegrationForStageCreation.FieldName(), parameters.RequireStorageIntegrationForStageCreation, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.RequireStorageIntegrationForStageOperation.FieldName(), parameters.RequireStorageIntegrationForStageOperation, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.RowTimestampDefault.FieldName(), parameters.RowTimestampDefault, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.RowsPerResultset.FieldName(), parameters.RowsPerResultset, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.S3StageVpceDnsName.FieldName(), parameters.S3StageVpceDnsName, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.SearchPath.FieldName(), parameters.SearchPath, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.ServerlessTaskMaxStatementSize.FieldName(), parameters.ServerlessTaskMaxStatementSize, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.ServerlessTaskMinStatementSize.FieldName(), parameters.ServerlessTaskMinStatementSize, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.SimulatedDataSharingConsumer.FieldName(), parameters.SimulatedDataSharingConsumer, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.SqlTraceQueryText.FieldName(), parameters.SqlTraceQueryText, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.SsoLoginPage.FieldName(), parameters.SsoLoginPage, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.StatementQueuedTimeoutInSeconds.FieldName(), parameters.StatementQueuedTimeoutInSeconds, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.StatementTimeoutInSeconds.FieldName(), parameters.StatementTimeoutInSeconds, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.StorageSerializationPolicy.FieldName(), parameters.StorageSerializationPolicy, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.StrictJsonOutput.FieldName(), parameters.StrictJsonOutput, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.SuspendTaskAfterNumFailures.FieldName(), parameters.SuspendTaskAfterNumFailures, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.TaskAutoRetryAttempts.FieldName(), parameters.TaskAutoRetryAttempts, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.TimeInputFormat.FieldName(), parameters.TimeInputFormat, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.TimeOutputFormat.FieldName(), parameters.TimeOutputFormat, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.TimestampDayIsAlways24h.FieldName(), parameters.TimestampDayIsAlways24H, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.TimestampInputFormat.FieldName(), parameters.TimestampInputFormat, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.TimestampLtzOutputFormat.FieldName(), parameters.TimestampLtzOutputFormat, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.TimestampNtzOutputFormat.FieldName(), parameters.TimestampNtzOutputFormat, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.TimestampOutputFormat.FieldName(), parameters.TimestampOutputFormat, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.TimestampTypeMapping.FieldName(), parameters.TimestampTypeMapping, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.TimestampTzOutputFormat.FieldName(), parameters.TimestampTzOutputFormat, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.Timezone.FieldName(), parameters.Timezone, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.TraceLevel.FieldName(), parameters.TraceLevel, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.TransactionAbortOnError.FieldName(), parameters.TransactionAbortOnError, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.TransactionDefaultIsolationLevel.FieldName(), parameters.TransactionDefaultIsolationLevel, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.TwoDigitCenturyStart.FieldName(), parameters.TwoDigitCenturyStart, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.UnsupportedDdlAction.FieldName(), parameters.UnsupportedDdlAction, sdk.ParameterTypeAccount),
		BoolTypedParameterValueComputedIf(defs.UseCachedResult.FieldName(), parameters.UseCachedResult, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.UseWorkspacesForSql.FieldName(), parameters.UseWorkspacesForSql, sdk.ParameterTypeAccount),
		StringTypedParameterValueComputedIf(defs.UserTaskManagedInitialWarehouseSize.FieldName(), parameters.UserTaskManagedInitialWarehouseSize, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.UserTaskMinimumTriggerIntervalInSeconds.FieldName(), parameters.UserTaskMinimumTriggerIntervalInSeconds, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.UserTaskTimeoutMs.FieldName(), parameters.UserTaskTimeoutMs, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.WeekOfYearPolicy.FieldName(), parameters.WeekOfYearPolicy, sdk.ParameterTypeAccount),
		IntTypedParameterValueComputedIf(defs.WeekStart.FieldName(), parameters.WeekStart, sdk.ParameterTypeAccount),
	}
}
