// Code generated by SDK to schema generator (v0.1.0); DO NOT EDIT.

package schemas

import (
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

type apiIntegrationExternalMcpDynamicClientToSchemaMapper struct{}

var _ additionalSchemaMapper[sdk.ApiIntegrationExternalMcpDynamicClient] = apiIntegrationExternalMcpDynamicClientToSchemaMapper{}

// DescribeApiIntegrationExternalMcpDynamicClientSchema represents output of DESCRIBE query for the single ApiIntegrationExternalMcpDynamicClient.
var DescribeApiIntegrationExternalMcpDynamicClientSchema = mergeSchema(map[string]*schema.Schema{
	"enabled": {
		Type:     schema.TypeBool,
		Computed: true,
	},
	// api_provider: manual addition and mapping is needed
	"user_auth_type": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"oauth_resource_url": {
		Type:     schema.TypeString,
		Computed: true,
	},
	// allowed_prefixes: manual addition and mapping is needed
	// blocked_prefixes: manual addition and mapping is needed
	"comment": {
		Type:     schema.TypeString,
		Computed: true,
	},
}, apiIntegrationExternalMcpDynamicClientToSchemaMapper{}.additionalSchema())

var _ = DescribeApiIntegrationExternalMcpDynamicClientSchema

func ApiIntegrationExternalMcpDynamicClientToSchema(apiIntegrationExternalMcpDynamicClient *sdk.ApiIntegrationExternalMcpDynamicClient) map[string]any {
	apiIntegrationExternalMcpDynamicClientSchema := make(map[string]any)
	apiIntegrationExternalMcpDynamicClientSchema["enabled"] = apiIntegrationExternalMcpDynamicClient.Enabled
	// api_provider: manual addition and mapping is needed
	apiIntegrationExternalMcpDynamicClientSchema["user_auth_type"] = apiIntegrationExternalMcpDynamicClient.UserAuthType
	apiIntegrationExternalMcpDynamicClientSchema["oauth_resource_url"] = apiIntegrationExternalMcpDynamicClient.OauthResourceUrl
	// allowed_prefixes: manual addition and mapping is needed
	// blocked_prefixes: manual addition and mapping is needed
	apiIntegrationExternalMcpDynamicClientSchema["comment"] = apiIntegrationExternalMcpDynamicClient.Comment
	apiIntegrationExternalMcpDynamicClientToSchemaMapper{}.additionalToSchema(apiIntegrationExternalMcpDynamicClient, apiIntegrationExternalMcpDynamicClientSchema)
	return apiIntegrationExternalMcpDynamicClientSchema
}

var _ = ApiIntegrationExternalMcpDynamicClientToSchema
