// Code generated by SDK to schema generator (v0.1.0); DO NOT EDIT.

package schemas

import (
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// ShowAuthenticationPolicySchema represents output of SHOW query for the single AuthenticationPolicy.
var ShowAuthenticationPolicySchema = map[string]*schema.Schema{
	"created_on": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"name": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"comment": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"database_name": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"schema_name": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"kind": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"owner": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"owner_role_type": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"options": {
		Type:     schema.TypeString,
		Computed: true,
	},
}

var _ = ShowAuthenticationPolicySchema

func AuthenticationPolicyToSchema(authenticationPolicy *sdk.AuthenticationPolicy) map[string]any {
	authenticationPolicySchema := make(map[string]any)
	if authenticationPolicy.CreatedOn != nil {
		authenticationPolicySchema["created_on"] = authenticationPolicy.CreatedOn.String()
	}
	authenticationPolicySchema["name"] = authenticationPolicy.Name
	authenticationPolicySchema["comment"] = authenticationPolicy.Comment
	if authenticationPolicy.DatabaseName != nil {
		authenticationPolicySchema["database_name"] = authenticationPolicy.DatabaseName
	}
	if authenticationPolicy.SchemaName != nil {
		authenticationPolicySchema["schema_name"] = authenticationPolicy.SchemaName
	}
	authenticationPolicySchema["kind"] = authenticationPolicy.Kind
	if authenticationPolicy.Owner != nil {
		authenticationPolicySchema["owner"] = authenticationPolicy.Owner
	}
	if authenticationPolicy.OwnerRoleType != nil {
		authenticationPolicySchema["owner_role_type"] = authenticationPolicy.OwnerRoleType
	}
	authenticationPolicySchema["options"] = authenticationPolicy.Options
	return authenticationPolicySchema
}

var _ = AuthenticationPolicyToSchema
