// Code generated by SDK to schema generator (v0.1.0); DO NOT EDIT.

package schemas

import (
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

type externalOauthSecurityIntegrationDetailsToSchemaMapper struct{}

var _ additionalSchemaMapper[sdk.ExternalOauthSecurityIntegrationDetails] = externalOauthSecurityIntegrationDetailsToSchemaMapper{}

// DescribeExternalOauthSecurityIntegrationDetailsSchema represents output of DESCRIBE query for the single ExternalOauthSecurityIntegrationDetails.
var DescribeExternalOauthSecurityIntegrationDetailsSchema = mergeSchema(map[string]*schema.Schema{
	// enabled: manual addition and mapping is needed
	// external_oauth_issuer: manual addition and mapping is needed
	// external_oauth_jws_keys_url: manual addition and mapping is needed
	// external_oauth_any_role_mode: manual addition and mapping is needed
	// external_oauth_rsa_public_key: manual addition and mapping is needed
	// external_oauth_rsa_public_key2: manual addition and mapping is needed
	// external_oauth_blocked_roles_list: manual addition and mapping is needed
	// external_oauth_allowed_roles_list: manual addition and mapping is needed
	// external_oauth_audience_list: manual addition and mapping is needed
	// external_oauth_token_user_mapping_claim: manual addition and mapping is needed
	// external_oauth_snowflake_user_mapping_attribute: manual addition and mapping is needed
	// external_oauth_scope_delimiter: manual addition and mapping is needed
	// comment: manual addition and mapping is needed
}, externalOauthSecurityIntegrationDetailsToSchemaMapper{}.additionalSchema())

var _ = DescribeExternalOauthSecurityIntegrationDetailsSchema

func ExternalOauthSecurityIntegrationDetailsToSchema(externalOauthSecurityIntegrationDetails *sdk.ExternalOauthSecurityIntegrationDetails) map[string]any {
	externalOauthSecurityIntegrationDetailsSchema := make(map[string]any)
	// enabled: manual addition and mapping is needed
	// external_oauth_issuer: manual addition and mapping is needed
	// external_oauth_jws_keys_url: manual addition and mapping is needed
	// external_oauth_any_role_mode: manual addition and mapping is needed
	// external_oauth_rsa_public_key: manual addition and mapping is needed
	// external_oauth_rsa_public_key2: manual addition and mapping is needed
	// external_oauth_blocked_roles_list: manual addition and mapping is needed
	// external_oauth_allowed_roles_list: manual addition and mapping is needed
	// external_oauth_audience_list: manual addition and mapping is needed
	// external_oauth_token_user_mapping_claim: manual addition and mapping is needed
	// external_oauth_snowflake_user_mapping_attribute: manual addition and mapping is needed
	// external_oauth_scope_delimiter: manual addition and mapping is needed
	// comment: manual addition and mapping is needed
	externalOauthSecurityIntegrationDetailsToSchemaMapper{}.additionalToSchema(externalOauthSecurityIntegrationDetails, externalOauthSecurityIntegrationDetailsSchema)
	return externalOauthSecurityIntegrationDetailsSchema
}

var _ = ExternalOauthSecurityIntegrationDetailsToSchema
