// Code generated by SDK to schema generator (v0.1.0); DO NOT EDIT.

package schemas

import (
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

type procedureDetailsToSchemaMapper struct{}

var _ additionalSchemaMapper[sdk.ProcedureDetails] = procedureDetailsToSchemaMapper{}

// DescribeProcedureDetailsSchema represents output of DESCRIBE query for the single ProcedureDetails.
var DescribeProcedureDetailsSchema = mergeSchema(map[string]*schema.Schema{
	"signature": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"returns": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"language": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"null_handling": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"body": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"volatility": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"external_access_integrations": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"secrets": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"imports": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"handler": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"runtime_version": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"packages": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"target_path": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"installed_packages": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"execute_as": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"return_not_null": {
		Type:     schema.TypeBool,
		Computed: true,
	},
}, procedureDetailsToSchemaMapper{}.additionalSchema())

var _ = DescribeProcedureDetailsSchema

func ProcedureDetailsToSchema(procedureDetails *sdk.ProcedureDetails) map[string]any {
	procedureDetailsSchema := make(map[string]any)
	procedureDetailsSchema["signature"] = procedureDetails.Signature
	procedureDetailsSchema["returns"] = procedureDetails.Returns
	procedureDetailsSchema["language"] = procedureDetails.Language
	if procedureDetails.NullHandling != nil {
		procedureDetailsSchema["null_handling"] = (*procedureDetails.NullHandling)
	}
	if procedureDetails.Body != nil {
		procedureDetailsSchema["body"] = (*procedureDetails.Body)
	}
	if procedureDetails.Volatility != nil {
		procedureDetailsSchema["volatility"] = (*procedureDetails.Volatility)
	}
	if procedureDetails.ExternalAccessIntegrations != nil {
		procedureDetailsSchema["external_access_integrations"] = (*procedureDetails.ExternalAccessIntegrations)
	}
	if procedureDetails.Secrets != nil {
		procedureDetailsSchema["secrets"] = (*procedureDetails.Secrets)
	}
	if procedureDetails.Imports != nil {
		procedureDetailsSchema["imports"] = (*procedureDetails.Imports)
	}
	if procedureDetails.Handler != nil {
		procedureDetailsSchema["handler"] = (*procedureDetails.Handler)
	}
	if procedureDetails.RuntimeVersion != nil {
		procedureDetailsSchema["runtime_version"] = (*procedureDetails.RuntimeVersion)
	}
	if procedureDetails.Packages != nil {
		procedureDetailsSchema["packages"] = (*procedureDetails.Packages)
	}
	if procedureDetails.TargetPath != nil {
		procedureDetailsSchema["target_path"] = (*procedureDetails.TargetPath)
	}
	if procedureDetails.InstalledPackages != nil {
		procedureDetailsSchema["installed_packages"] = (*procedureDetails.InstalledPackages)
	}
	procedureDetailsSchema["execute_as"] = procedureDetails.ExecuteAs
	procedureDetailsSchema["return_not_null"] = procedureDetails.ReturnNotNull
	procedureDetailsToSchemaMapper{}.additionalToSchema(procedureDetails, procedureDetailsSchema)
	return procedureDetailsSchema
}

var _ = ProcedureDetailsToSchema
