// Code generated by SDK to schema generator (v0.1.0); DO NOT EDIT.

package schemas

import (
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

type stageCommonToSchemaMapper struct{}

var _ additionalSchemaMapper[sdk.StageCommon] = stageCommonToSchemaMapper{}

// DescribeStageCommonSchema represents output of DESCRIBE query for the single StageCommon.
var DescribeStageCommonSchema = mergeSchema(map[string]*schema.Schema{
	// file_format_name: manual addition and mapping is needed
	// file_format_csv: manual addition and mapping is needed
	// file_format_json: manual addition and mapping is needed
	// file_format_avro: manual addition and mapping is needed
	// file_format_orc: manual addition and mapping is needed
	// file_format_parquet: manual addition and mapping is needed
	// file_format_xml: manual addition and mapping is needed
	// directory_table: manual addition and mapping is needed
}, stageCommonToSchemaMapper{}.additionalSchema())

var _ = DescribeStageCommonSchema

func StageCommonToSchema(stageCommon *sdk.StageCommon) map[string]any {
	stageCommonSchema := make(map[string]any)
	// file_format_name: manual addition and mapping is needed
	// file_format_csv: manual addition and mapping is needed
	// file_format_json: manual addition and mapping is needed
	// file_format_avro: manual addition and mapping is needed
	// file_format_orc: manual addition and mapping is needed
	// file_format_parquet: manual addition and mapping is needed
	// file_format_xml: manual addition and mapping is needed
	// directory_table: manual addition and mapping is needed
	stageCommonToSchemaMapper{}.additionalToSchema(stageCommon, stageCommonSchema)
	return stageCommonSchema
}

var _ = StageCommonToSchema
