// Code generated by SDK to schema generator (v0.1.0); DO NOT EDIT.

package schemas

import (
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

type userDetailsToSchemaMapper struct{}

var _ additionalSchemaMapper[sdk.UserDetails] = userDetailsToSchemaMapper{}

// DescribeUserDetailsSchema represents output of DESCRIBE query for the single UserDetails.
var DescribeUserDetailsSchema = mergeSchema(map[string]*schema.Schema{}, userDetailsToSchemaMapper{}.additionalSchema())

var _ = DescribeUserDetailsSchema

func UserDetailsToSchema(userDetails *sdk.UserDetails) map[string]any {
	userDetailsSchema := make(map[string]any)
	userDetailsToSchemaMapper{}.additionalToSchema(userDetails, userDetailsSchema)
	return userDetailsSchema
}

var _ = UserDetailsToSchema
