// Code generated by resource show output assertions generator (v0.1.0); DO NOT EDIT.

package resourceshowoutputassert

import (
	"testing"
	"time"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

type AccountShowOutputAssert struct {
	*assert.ResourceAssert
}

func AccountShowOutput(t *testing.T, name string) *AccountShowOutputAssert {
	t.Helper()

	accountAssert := AccountShowOutputAssert{
		ResourceAssert: assert.NewResourceShowOutputAssert(name),
	}
	return &accountAssert
}

func ImportedAccountShowOutput(t *testing.T, id string) *AccountShowOutputAssert {
	t.Helper()

	accountAssert := AccountShowOutputAssert{
		ResourceAssert: assert.NewImportedResourceShowOutputAssert(id),
	}
	return &accountAssert
}

func AccountsDatasourceShowOutput(t *testing.T, name string) *AccountShowOutputAssert {
	t.Helper()

	return AccountsDatasourceShowOutputOnIdx(t, name, 0)
}

func AccountsDatasourceShowOutputOnIdx(t *testing.T, name string, idx int) *AccountShowOutputAssert {
	t.Helper()

	accountAssert := AccountShowOutputAssert{
		ResourceAssert: assert.NewDatasourceShowOutputAssert(name, "accounts", idx),
	}
	return &accountAssert
}

////////////////////////////
// Attribute value checks //
////////////////////////////

func (a *AccountShowOutputAssert) HasOrganizationName(expected string) *AccountShowOutputAssert {
	a.StringValueSet("organization_name", expected)
	return a
}

func (a *AccountShowOutputAssert) HasAccountName(expected string) *AccountShowOutputAssert {
	a.StringValueSet("account_name", expected)
	return a
}

func (a *AccountShowOutputAssert) HasSnowflakeRegion(expected string) *AccountShowOutputAssert {
	a.StringValueSet("snowflake_region", expected)
	return a
}

func (a *AccountShowOutputAssert) HasRegionGroup(expected string) *AccountShowOutputAssert {
	a.StringValueSet("region_group", expected)
	return a
}

func (a *AccountShowOutputAssert) HasEdition(expected sdk.AccountEdition) *AccountShowOutputAssert {
	a.StringValueSet("edition", string(expected))
	return a
}

func (a *AccountShowOutputAssert) HasAccountURL(expected string) *AccountShowOutputAssert {
	a.StringValueSet("account_url", expected)
	return a
}

func (a *AccountShowOutputAssert) HasCreatedOn(expected time.Time) *AccountShowOutputAssert {
	a.StringValueSet("created_on", expected.String())
	return a
}

func (a *AccountShowOutputAssert) HasComment(expected string) *AccountShowOutputAssert {
	a.StringValueSet("comment", expected)
	return a
}

func (a *AccountShowOutputAssert) HasAccountLocator(expected string) *AccountShowOutputAssert {
	a.StringValueSet("account_locator", expected)
	return a
}

func (a *AccountShowOutputAssert) HasAccountLocatorUrl(expected string) *AccountShowOutputAssert {
	a.StringValueSet("account_locator_url", expected)
	return a
}

func (a *AccountShowOutputAssert) HasManagedAccounts(expected int) *AccountShowOutputAssert {
	a.IntValueSet("managed_accounts", expected)
	return a
}

func (a *AccountShowOutputAssert) HasConsumptionBillingEntityName(expected string) *AccountShowOutputAssert {
	a.StringValueSet("consumption_billing_entity_name", expected)
	return a
}

func (a *AccountShowOutputAssert) HasMarketplaceConsumerBillingEntityName(expected string) *AccountShowOutputAssert {
	a.StringValueSet("marketplace_consumer_billing_entity_name", expected)
	return a
}

func (a *AccountShowOutputAssert) HasMarketplaceProviderBillingEntityName(expected string) *AccountShowOutputAssert {
	a.StringValueSet("marketplace_provider_billing_entity_name", expected)
	return a
}

func (a *AccountShowOutputAssert) HasOldAccountURL(expected string) *AccountShowOutputAssert {
	a.StringValueSet("old_account_url", expected)
	return a
}

func (a *AccountShowOutputAssert) HasIsOrgAdmin(expected bool) *AccountShowOutputAssert {
	a.BoolValueSet("is_org_admin", expected)
	return a
}

func (a *AccountShowOutputAssert) HasAccountOldUrlSavedOn(expected time.Time) *AccountShowOutputAssert {
	a.StringValueSet("account_old_url_saved_on", expected.String())
	return a
}

func (a *AccountShowOutputAssert) HasAccountOldUrlLastUsed(expected time.Time) *AccountShowOutputAssert {
	a.StringValueSet("account_old_url_last_used", expected.String())
	return a
}

func (a *AccountShowOutputAssert) HasOrganizationOldUrl(expected string) *AccountShowOutputAssert {
	a.StringValueSet("organization_old_url", expected)
	return a
}

func (a *AccountShowOutputAssert) HasOrganizationOldUrlSavedOn(expected time.Time) *AccountShowOutputAssert {
	a.StringValueSet("organization_old_url_saved_on", expected.String())
	return a
}

func (a *AccountShowOutputAssert) HasOrganizationOldUrlLastUsed(expected time.Time) *AccountShowOutputAssert {
	a.StringValueSet("organization_old_url_last_used", expected.String())
	return a
}

func (a *AccountShowOutputAssert) HasIsEventsAccount(expected bool) *AccountShowOutputAssert {
	a.BoolValueSet("is_events_account", expected)
	return a
}

func (a *AccountShowOutputAssert) HasIsOrganizationAccount(expected bool) *AccountShowOutputAssert {
	a.BoolValueSet("is_organization_account", expected)
	return a
}

func (a *AccountShowOutputAssert) HasDroppedOn(expected time.Time) *AccountShowOutputAssert {
	a.StringValueSet("dropped_on", expected.String())
	return a
}

func (a *AccountShowOutputAssert) HasScheduledDeletionTime(expected time.Time) *AccountShowOutputAssert {
	a.StringValueSet("scheduled_deletion_time", expected.String())
	return a
}

func (a *AccountShowOutputAssert) HasRestoredOn(expected time.Time) *AccountShowOutputAssert {
	a.StringValueSet("restored_on", expected.String())
	return a
}

func (a *AccountShowOutputAssert) HasMovedToOrganization(expected string) *AccountShowOutputAssert {
	a.StringValueSet("moved_to_organization", expected)
	return a
}

func (a *AccountShowOutputAssert) HasMovedOn(expected string) *AccountShowOutputAssert {
	a.StringValueSet("moved_on", expected)
	return a
}

func (a *AccountShowOutputAssert) HasOrganizationUrlExpirationOn(expected time.Time) *AccountShowOutputAssert {
	a.StringValueSet("organization_url_expiration_on", expected.String())
	return a
}

///////////////////////////////
// Attribute no value checks //
///////////////////////////////

func (a *AccountShowOutputAssert) HasNoOrganizationName() *AccountShowOutputAssert {
	a.ValueNotSet("organization_name")
	return a
}

func (a *AccountShowOutputAssert) HasNoAccountName() *AccountShowOutputAssert {
	a.ValueNotSet("account_name")
	return a
}

func (a *AccountShowOutputAssert) HasNoSnowflakeRegion() *AccountShowOutputAssert {
	a.ValueNotSet("snowflake_region")
	return a
}

func (a *AccountShowOutputAssert) HasNoRegionGroup() *AccountShowOutputAssert {
	a.ValueNotSet("region_group")
	return a
}

func (a *AccountShowOutputAssert) HasNoEdition() *AccountShowOutputAssert {
	a.ValueNotSet("edition")
	return a
}

func (a *AccountShowOutputAssert) HasNoAccountURL() *AccountShowOutputAssert {
	a.ValueNotSet("account_url")
	return a
}

func (a *AccountShowOutputAssert) HasNoCreatedOn() *AccountShowOutputAssert {
	a.ValueNotSet("created_on")
	return a
}

func (a *AccountShowOutputAssert) HasNoComment() *AccountShowOutputAssert {
	a.ValueNotSet("comment")
	return a
}

func (a *AccountShowOutputAssert) HasNoAccountLocator() *AccountShowOutputAssert {
	a.ValueNotSet("account_locator")
	return a
}

func (a *AccountShowOutputAssert) HasNoAccountLocatorUrl() *AccountShowOutputAssert {
	a.ValueNotSet("account_locator_url")
	return a
}

func (a *AccountShowOutputAssert) HasNoManagedAccounts() *AccountShowOutputAssert {
	a.ValueNotSet("managed_accounts")
	return a
}

func (a *AccountShowOutputAssert) HasNoConsumptionBillingEntityName() *AccountShowOutputAssert {
	a.ValueNotSet("consumption_billing_entity_name")
	return a
}

func (a *AccountShowOutputAssert) HasNoMarketplaceConsumerBillingEntityName() *AccountShowOutputAssert {
	a.ValueNotSet("marketplace_consumer_billing_entity_name")
	return a
}

func (a *AccountShowOutputAssert) HasNoMarketplaceProviderBillingEntityName() *AccountShowOutputAssert {
	a.ValueNotSet("marketplace_provider_billing_entity_name")
	return a
}

func (a *AccountShowOutputAssert) HasNoOldAccountURL() *AccountShowOutputAssert {
	a.ValueNotSet("old_account_url")
	return a
}

func (a *AccountShowOutputAssert) HasNoIsOrgAdmin() *AccountShowOutputAssert {
	a.ValueNotSet("is_org_admin")
	return a
}

func (a *AccountShowOutputAssert) HasNoAccountOldUrlSavedOn() *AccountShowOutputAssert {
	a.ValueNotSet("account_old_url_saved_on")
	return a
}

func (a *AccountShowOutputAssert) HasNoAccountOldUrlLastUsed() *AccountShowOutputAssert {
	a.ValueNotSet("account_old_url_last_used")
	return a
}

func (a *AccountShowOutputAssert) HasNoOrganizationOldUrl() *AccountShowOutputAssert {
	a.ValueNotSet("organization_old_url")
	return a
}

func (a *AccountShowOutputAssert) HasNoOrganizationOldUrlSavedOn() *AccountShowOutputAssert {
	a.ValueNotSet("organization_old_url_saved_on")
	return a
}

func (a *AccountShowOutputAssert) HasNoOrganizationOldUrlLastUsed() *AccountShowOutputAssert {
	a.ValueNotSet("organization_old_url_last_used")
	return a
}

func (a *AccountShowOutputAssert) HasNoIsEventsAccount() *AccountShowOutputAssert {
	a.ValueNotSet("is_events_account")
	return a
}

func (a *AccountShowOutputAssert) HasNoIsOrganizationAccount() *AccountShowOutputAssert {
	a.ValueNotSet("is_organization_account")
	return a
}

func (a *AccountShowOutputAssert) HasNoDroppedOn() *AccountShowOutputAssert {
	a.ValueNotSet("dropped_on")
	return a
}

func (a *AccountShowOutputAssert) HasNoScheduledDeletionTime() *AccountShowOutputAssert {
	a.ValueNotSet("scheduled_deletion_time")
	return a
}

func (a *AccountShowOutputAssert) HasNoRestoredOn() *AccountShowOutputAssert {
	a.ValueNotSet("restored_on")
	return a
}

func (a *AccountShowOutputAssert) HasNoMovedToOrganization() *AccountShowOutputAssert {
	a.ValueNotSet("moved_to_organization")
	return a
}

func (a *AccountShowOutputAssert) HasNoMovedOn() *AccountShowOutputAssert {
	a.ValueNotSet("moved_on")
	return a
}

func (a *AccountShowOutputAssert) HasNoOrganizationUrlExpirationOn() *AccountShowOutputAssert {
	a.ValueNotSet("organization_url_expiration_on")
	return a
}
