// Code generated by resource show output assertions generator (v0.1.0); DO NOT EDIT.

package resourceshowoutputassert

import (
	"testing"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

type CatalogIntegrationOpenCatalogDescribeOutputAssert struct {
	*assert.ResourceAssert
}

func CatalogIntegrationOpenCatalogDescribeOutput(t *testing.T, name string) *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	t.Helper()

	catalogIntegrationOpenCatalogAssert := CatalogIntegrationOpenCatalogDescribeOutputAssert{
		ResourceAssert: assert.NewResourceDescribeOutputAssert(name),
	}
	return &catalogIntegrationOpenCatalogAssert
}

func ImportedCatalogIntegrationOpenCatalogDescribeOutput(t *testing.T, id string) *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	t.Helper()

	catalogIntegrationOpenCatalogAssert := CatalogIntegrationOpenCatalogDescribeOutputAssert{
		ResourceAssert: assert.NewImportedResourceDescribeOutputAssert(id),
	}
	return &catalogIntegrationOpenCatalogAssert
}

////////////////////////////
// Attribute value checks //
////////////////////////////

func (c *CatalogIntegrationOpenCatalogDescribeOutputAssert) HasId(expected sdk.AccountObjectIdentifier) *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	c.StringValueSet("id", expected.Name())
	return c
}

func (c *CatalogIntegrationOpenCatalogDescribeOutputAssert) HasCatalogSource(expected sdk.CatalogIntegrationCatalogSourceType) *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	c.StringValueSet("catalog_source", string(expected))
	return c
}

func (c *CatalogIntegrationOpenCatalogDescribeOutputAssert) HasTableFormat(expected sdk.CatalogIntegrationTableFormat) *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	c.StringValueSet("table_format", string(expected))
	return c
}

func (c *CatalogIntegrationOpenCatalogDescribeOutputAssert) HasEnabled(expected bool) *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	c.BoolValueSet("enabled", expected)
	return c
}

func (c *CatalogIntegrationOpenCatalogDescribeOutputAssert) HasRefreshIntervalSeconds(expected int) *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	c.IntValueSet("refresh_interval_seconds", expected)
	return c
}

func (c *CatalogIntegrationOpenCatalogDescribeOutputAssert) HasComment(expected string) *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	c.StringValueSet("comment", expected)
	return c
}

func (c *CatalogIntegrationOpenCatalogDescribeOutputAssert) HasCatalogNamespace(expected string) *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	c.StringValueSet("catalog_namespace", expected)
	return c
}

///////////////////////////////
// Attribute no value checks //
///////////////////////////////

func (c *CatalogIntegrationOpenCatalogDescribeOutputAssert) HasNoId() *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	c.ValueNotSet("id")
	return c
}

func (c *CatalogIntegrationOpenCatalogDescribeOutputAssert) HasNoCatalogSource() *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	c.ValueNotSet("catalog_source")
	return c
}

func (c *CatalogIntegrationOpenCatalogDescribeOutputAssert) HasNoTableFormat() *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	c.ValueNotSet("table_format")
	return c
}

func (c *CatalogIntegrationOpenCatalogDescribeOutputAssert) HasNoEnabled() *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	c.ValueNotSet("enabled")
	return c
}

func (c *CatalogIntegrationOpenCatalogDescribeOutputAssert) HasNoRefreshIntervalSeconds() *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	c.ValueNotSet("refresh_interval_seconds")
	return c
}

func (c *CatalogIntegrationOpenCatalogDescribeOutputAssert) HasNoComment() *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	c.ValueNotSet("comment")
	return c
}

func (c *CatalogIntegrationOpenCatalogDescribeOutputAssert) HasNoCatalogNamespace() *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	c.ValueNotSet("catalog_namespace")
	return c
}

func (c *CatalogIntegrationOpenCatalogDescribeOutputAssert) HasNoRestConfig() *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	c.ValueNotSet("rest_config")
	return c
}

func (c *CatalogIntegrationOpenCatalogDescribeOutputAssert) HasNoRestAuthentication() *CatalogIntegrationOpenCatalogDescribeOutputAssert {
	c.ValueNotSet("rest_authentication")
	return c
}
