// Code generated by resource show output assertions generator (v0.1.0); DO NOT EDIT.

package resourceshowoutputassert

import (
	"testing"
	"time"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
)

type CatalogIntegrationShowOutputAssert struct {
	*assert.ResourceAssert
}

func CatalogIntegrationShowOutput(t *testing.T, name string) *CatalogIntegrationShowOutputAssert {
	t.Helper()

	catalogIntegrationAssert := CatalogIntegrationShowOutputAssert{
		ResourceAssert: assert.NewResourceAssert(name, "show_output"),
	}
	catalogIntegrationAssert.AddAssertion(assert.ValueSet("show_output.#", "1"))
	return &catalogIntegrationAssert
}

func ImportedCatalogIntegrationShowOutput(t *testing.T, id string) *CatalogIntegrationShowOutputAssert {
	t.Helper()

	catalogIntegrationAssert := CatalogIntegrationShowOutputAssert{
		ResourceAssert: assert.NewImportedResourceAssert(id, "show_output"),
	}
	catalogIntegrationAssert.AddAssertion(assert.ValueSet("show_output.#", "1"))
	return &catalogIntegrationAssert
}

////////////////////////////
// Attribute value checks //
////////////////////////////

func (c *CatalogIntegrationShowOutputAssert) HasName(expected string) *CatalogIntegrationShowOutputAssert {
	c.AddAssertion(assert.ResourceShowOutputValueSet("name", expected))
	return c
}

func (c *CatalogIntegrationShowOutputAssert) HasEnabled(expected bool) *CatalogIntegrationShowOutputAssert {
	c.AddAssertion(assert.ResourceShowOutputBoolValueSet("enabled", expected))
	return c
}

func (c *CatalogIntegrationShowOutputAssert) HasType(expected string) *CatalogIntegrationShowOutputAssert {
	c.AddAssertion(assert.ResourceShowOutputValueSet("type", expected))
	return c
}

func (c *CatalogIntegrationShowOutputAssert) HasCategory(expected string) *CatalogIntegrationShowOutputAssert {
	c.AddAssertion(assert.ResourceShowOutputValueSet("category", expected))
	return c
}

func (c *CatalogIntegrationShowOutputAssert) HasComment(expected string) *CatalogIntegrationShowOutputAssert {
	c.AddAssertion(assert.ResourceShowOutputValueSet("comment", expected))
	return c
}

func (c *CatalogIntegrationShowOutputAssert) HasCreatedOn(expected time.Time) *CatalogIntegrationShowOutputAssert {
	c.AddAssertion(assert.ResourceShowOutputValueSet("created_on", expected.String()))
	return c
}

///////////////////////////////
// Attribute no value checks //
///////////////////////////////

func (c *CatalogIntegrationShowOutputAssert) HasNoName() *CatalogIntegrationShowOutputAssert {
	c.AddAssertion(assert.ResourceShowOutputValueNotSet("name"))
	return c
}

func (c *CatalogIntegrationShowOutputAssert) HasNoEnabled() *CatalogIntegrationShowOutputAssert {
	c.AddAssertion(assert.ResourceShowOutputBoolValueNotSet("enabled"))
	return c
}

func (c *CatalogIntegrationShowOutputAssert) HasNoType() *CatalogIntegrationShowOutputAssert {
	c.AddAssertion(assert.ResourceShowOutputValueNotSet("type"))
	return c
}

func (c *CatalogIntegrationShowOutputAssert) HasNoCategory() *CatalogIntegrationShowOutputAssert {
	c.AddAssertion(assert.ResourceShowOutputValueNotSet("category"))
	return c
}

func (c *CatalogIntegrationShowOutputAssert) HasNoComment() *CatalogIntegrationShowOutputAssert {
	c.AddAssertion(assert.ResourceShowOutputValueNotSet("comment"))
	return c
}

func (c *CatalogIntegrationShowOutputAssert) HasNoCreatedOn() *CatalogIntegrationShowOutputAssert {
	c.AddAssertion(assert.ResourceShowOutputValueNotSet("created_on"))
	return c
}
