// Code generated by resource show output assertions generator (v0.1.0); DO NOT EDIT.

package resourceshowoutputassert

import (
	"testing"
	"time"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

type NotebookShowOutputAssert struct {
	*assert.ResourceAssert
}

func NotebookShowOutput(t *testing.T, name string) *NotebookShowOutputAssert {
	t.Helper()

	notebookAssert := NotebookShowOutputAssert{
		ResourceAssert: assert.NewResourceShowOutputAssert(name),
	}
	return &notebookAssert
}

func ImportedNotebookShowOutput(t *testing.T, id string) *NotebookShowOutputAssert {
	t.Helper()

	notebookAssert := NotebookShowOutputAssert{
		ResourceAssert: assert.NewImportedResourceShowOutputAssert(id),
	}
	return &notebookAssert
}

func NotebooksDatasourceShowOutput(t *testing.T, name string) *NotebookShowOutputAssert {
	t.Helper()

	return NotebooksDatasourceShowOutputOnIdx(t, name, 0)
}

func NotebooksDatasourceShowOutputOnIdx(t *testing.T, name string, idx int) *NotebookShowOutputAssert {
	t.Helper()

	notebookAssert := NotebookShowOutputAssert{
		ResourceAssert: assert.NewDatasourceShowOutputAssert(name, "notebooks", idx),
	}
	return &notebookAssert
}

////////////////////////////
// Attribute value checks //
////////////////////////////

func (n *NotebookShowOutputAssert) HasCreatedOn(expected time.Time) *NotebookShowOutputAssert {
	n.StringValueSet("created_on", expected.String())
	return n
}

func (n *NotebookShowOutputAssert) HasName(expected string) *NotebookShowOutputAssert {
	n.StringValueSet("name", expected)
	return n
}

func (n *NotebookShowOutputAssert) HasDatabaseName(expected string) *NotebookShowOutputAssert {
	n.StringValueSet("database_name", expected)
	return n
}

func (n *NotebookShowOutputAssert) HasSchemaName(expected string) *NotebookShowOutputAssert {
	n.StringValueSet("schema_name", expected)
	return n
}

func (n *NotebookShowOutputAssert) HasComment(expected string) *NotebookShowOutputAssert {
	n.StringValueSet("comment", expected)
	return n
}

func (n *NotebookShowOutputAssert) HasOwner(expected string) *NotebookShowOutputAssert {
	n.StringValueSet("owner", expected)
	return n
}

func (n *NotebookShowOutputAssert) HasQueryWarehouse(expected sdk.AccountObjectIdentifier) *NotebookShowOutputAssert {
	n.StringValueSet("query_warehouse", expected.Name())
	return n
}

func (n *NotebookShowOutputAssert) HasUrlId(expected string) *NotebookShowOutputAssert {
	n.StringValueSet("url_id", expected)
	return n
}

func (n *NotebookShowOutputAssert) HasOwnerRoleType(expected string) *NotebookShowOutputAssert {
	n.StringValueSet("owner_role_type", expected)
	return n
}

func (n *NotebookShowOutputAssert) HasCodeWarehouse(expected sdk.AccountObjectIdentifier) *NotebookShowOutputAssert {
	n.StringValueSet("code_warehouse", expected.Name())
	return n
}

///////////////////////////////
// Attribute no value checks //
///////////////////////////////

func (n *NotebookShowOutputAssert) HasNoCreatedOn() *NotebookShowOutputAssert {
	n.ValueNotSet("created_on")
	return n
}

func (n *NotebookShowOutputAssert) HasNoName() *NotebookShowOutputAssert {
	n.ValueNotSet("name")
	return n
}

func (n *NotebookShowOutputAssert) HasNoDatabaseName() *NotebookShowOutputAssert {
	n.ValueNotSet("database_name")
	return n
}

func (n *NotebookShowOutputAssert) HasNoSchemaName() *NotebookShowOutputAssert {
	n.ValueNotSet("schema_name")
	return n
}

func (n *NotebookShowOutputAssert) HasNoComment() *NotebookShowOutputAssert {
	n.ValueNotSet("comment")
	return n
}

func (n *NotebookShowOutputAssert) HasNoOwner() *NotebookShowOutputAssert {
	n.ValueNotSet("owner")
	return n
}

func (n *NotebookShowOutputAssert) HasNoQueryWarehouse() *NotebookShowOutputAssert {
	n.ValueNotSet("query_warehouse")
	return n
}

func (n *NotebookShowOutputAssert) HasNoUrlId() *NotebookShowOutputAssert {
	n.ValueNotSet("url_id")
	return n
}

func (n *NotebookShowOutputAssert) HasNoOwnerRoleType() *NotebookShowOutputAssert {
	n.ValueNotSet("owner_role_type")
	return n
}

func (n *NotebookShowOutputAssert) HasNoCodeWarehouse() *NotebookShowOutputAssert {
	n.ValueNotSet("code_warehouse")
	return n
}
