// Code generated by resource show output assertions generator (v0.1.0); DO NOT EDIT.

package resourceshowoutputassert

import (
	"testing"
	"time"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
)

type PasswordPolicyShowOutputAssert struct {
	*assert.ResourceAssert
}

func PasswordPolicyShowOutput(t *testing.T, name string) *PasswordPolicyShowOutputAssert {
	t.Helper()

	passwordPolicyAssert := PasswordPolicyShowOutputAssert{
		ResourceAssert: assert.NewResourceAssert(name, "show_output"),
	}
	passwordPolicyAssert.AddAssertion(assert.ValueSet("show_output.#", "1"))
	return &passwordPolicyAssert
}

func ImportedPasswordPolicyShowOutput(t *testing.T, id string) *PasswordPolicyShowOutputAssert {
	t.Helper()

	passwordPolicyAssert := PasswordPolicyShowOutputAssert{
		ResourceAssert: assert.NewImportedResourceAssert(id, "show_output"),
	}
	passwordPolicyAssert.AddAssertion(assert.ValueSet("show_output.#", "1"))
	return &passwordPolicyAssert
}

////////////////////////////
// Attribute value checks //
////////////////////////////

func (p *PasswordPolicyShowOutputAssert) HasCreatedOn(expected time.Time) *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueSet("created_on", expected.String()))
	return p
}

func (p *PasswordPolicyShowOutputAssert) HasName(expected string) *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueSet("name", expected))
	return p
}

func (p *PasswordPolicyShowOutputAssert) HasDatabaseName(expected string) *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueSet("database_name", expected))
	return p
}

func (p *PasswordPolicyShowOutputAssert) HasSchemaName(expected string) *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueSet("schema_name", expected))
	return p
}

func (p *PasswordPolicyShowOutputAssert) HasKind(expected string) *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueSet("kind", expected))
	return p
}

func (p *PasswordPolicyShowOutputAssert) HasOwner(expected string) *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueSet("owner", expected))
	return p
}

func (p *PasswordPolicyShowOutputAssert) HasComment(expected string) *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueSet("comment", expected))
	return p
}

func (p *PasswordPolicyShowOutputAssert) HasOwnerRoleType(expected string) *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueSet("owner_role_type", expected))
	return p
}

func (p *PasswordPolicyShowOutputAssert) HasOptions(expected string) *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueSet("options", expected))
	return p
}

///////////////////////////////
// Attribute no value checks //
///////////////////////////////

func (p *PasswordPolicyShowOutputAssert) HasNoCreatedOn() *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueNotSet("created_on"))
	return p
}

func (p *PasswordPolicyShowOutputAssert) HasNoName() *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueNotSet("name"))
	return p
}

func (p *PasswordPolicyShowOutputAssert) HasNoDatabaseName() *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueNotSet("database_name"))
	return p
}

func (p *PasswordPolicyShowOutputAssert) HasNoSchemaName() *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueNotSet("schema_name"))
	return p
}

func (p *PasswordPolicyShowOutputAssert) HasNoKind() *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueNotSet("kind"))
	return p
}

func (p *PasswordPolicyShowOutputAssert) HasNoOwner() *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueNotSet("owner"))
	return p
}

func (p *PasswordPolicyShowOutputAssert) HasNoComment() *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueNotSet("comment"))
	return p
}

func (p *PasswordPolicyShowOutputAssert) HasNoOwnerRoleType() *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueNotSet("owner_role_type"))
	return p
}

func (p *PasswordPolicyShowOutputAssert) HasNoOptions() *PasswordPolicyShowOutputAssert {
	p.AddAssertion(assert.ResourceShowOutputValueNotSet("options"))
	return p
}
