// Code generated by resource show output assertions generator (v0.1.0); DO NOT EDIT.

package resourceshowoutputassert

import (
	"testing"
	"time"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
)

type SchemaShowOutputAssert struct {
	*assert.ResourceAssert
}

func SchemaShowOutput(t *testing.T, name string) *SchemaShowOutputAssert {
	t.Helper()

	schemaAssert := SchemaShowOutputAssert{
		ResourceAssert: assert.NewResourceShowOutputAssert(name),
	}
	return &schemaAssert
}

func ImportedSchemaShowOutput(t *testing.T, id string) *SchemaShowOutputAssert {
	t.Helper()

	schemaAssert := SchemaShowOutputAssert{
		ResourceAssert: assert.NewImportedResourceShowOutputAssert(id),
	}
	return &schemaAssert
}

func SchemasDatasourceShowOutput(t *testing.T, name string) *SchemaShowOutputAssert {
	t.Helper()

	return SchemasDatasourceShowOutputOnIdx(t, name, 0)
}

func SchemasDatasourceShowOutputOnIdx(t *testing.T, name string, idx int) *SchemaShowOutputAssert {
	t.Helper()

	schemaAssert := SchemaShowOutputAssert{
		ResourceAssert: assert.NewDatasourceShowOutputAssert(name, "schemas", idx),
	}
	return &schemaAssert
}

////////////////////////////
// Attribute value checks //
////////////////////////////

func (s *SchemaShowOutputAssert) HasCreatedOn(expected time.Time) *SchemaShowOutputAssert {
	s.StringValueSet("created_on", expected.String())
	return s
}

func (s *SchemaShowOutputAssert) HasDroppedOn(expected time.Time) *SchemaShowOutputAssert {
	s.StringValueSet("dropped_on", expected.String())
	return s
}

func (s *SchemaShowOutputAssert) HasName(expected string) *SchemaShowOutputAssert {
	s.StringValueSet("name", expected)
	return s
}

func (s *SchemaShowOutputAssert) HasIsDefault(expected bool) *SchemaShowOutputAssert {
	s.BoolValueSet("is_default", expected)
	return s
}

func (s *SchemaShowOutputAssert) HasIsCurrent(expected bool) *SchemaShowOutputAssert {
	s.BoolValueSet("is_current", expected)
	return s
}

func (s *SchemaShowOutputAssert) HasDatabaseName(expected string) *SchemaShowOutputAssert {
	s.StringValueSet("database_name", expected)
	return s
}

func (s *SchemaShowOutputAssert) HasOwner(expected string) *SchemaShowOutputAssert {
	s.StringValueSet("owner", expected)
	return s
}

func (s *SchemaShowOutputAssert) HasComment(expected string) *SchemaShowOutputAssert {
	s.StringValueSet("comment", expected)
	return s
}

func (s *SchemaShowOutputAssert) HasOptions(expected string) *SchemaShowOutputAssert {
	s.StringValueSet("options", expected)
	return s
}

func (s *SchemaShowOutputAssert) HasRetentionTime(expected string) *SchemaShowOutputAssert {
	s.StringValueSet("retention_time", expected)
	return s
}

func (s *SchemaShowOutputAssert) HasOwnerRoleType(expected string) *SchemaShowOutputAssert {
	s.StringValueSet("owner_role_type", expected)
	return s
}

///////////////////////////////
// Attribute no value checks //
///////////////////////////////

func (s *SchemaShowOutputAssert) HasNoCreatedOn() *SchemaShowOutputAssert {
	s.ValueNotSet("created_on")
	return s
}

func (s *SchemaShowOutputAssert) HasNoDroppedOn() *SchemaShowOutputAssert {
	s.ValueNotSet("dropped_on")
	return s
}

func (s *SchemaShowOutputAssert) HasNoName() *SchemaShowOutputAssert {
	s.ValueNotSet("name")
	return s
}

func (s *SchemaShowOutputAssert) HasNoIsDefault() *SchemaShowOutputAssert {
	s.ValueNotSet("is_default")
	return s
}

func (s *SchemaShowOutputAssert) HasNoIsCurrent() *SchemaShowOutputAssert {
	s.ValueNotSet("is_current")
	return s
}

func (s *SchemaShowOutputAssert) HasNoDatabaseName() *SchemaShowOutputAssert {
	s.ValueNotSet("database_name")
	return s
}

func (s *SchemaShowOutputAssert) HasNoOwner() *SchemaShowOutputAssert {
	s.ValueNotSet("owner")
	return s
}

func (s *SchemaShowOutputAssert) HasNoComment() *SchemaShowOutputAssert {
	s.ValueNotSet("comment")
	return s
}

func (s *SchemaShowOutputAssert) HasNoOptions() *SchemaShowOutputAssert {
	s.ValueNotSet("options")
	return s
}

func (s *SchemaShowOutputAssert) HasNoRetentionTime() *SchemaShowOutputAssert {
	s.ValueNotSet("retention_time")
	return s
}

func (s *SchemaShowOutputAssert) HasNoOwnerRoleType() *SchemaShowOutputAssert {
	s.ValueNotSet("owner_role_type")
	return s
}
