// Code generated by resource show output assertions generator (v0.1.0); DO NOT EDIT.

package resourceshowoutputassert

import (
	"testing"
	"time"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

type StreamShowOutputAssert struct {
	*assert.ResourceAssert
}

func StreamShowOutput(t *testing.T, name string) *StreamShowOutputAssert {
	t.Helper()

	streamAssert := StreamShowOutputAssert{
		ResourceAssert: assert.NewResourceShowOutputAssert(name),
	}
	return &streamAssert
}

func ImportedStreamShowOutput(t *testing.T, id string) *StreamShowOutputAssert {
	t.Helper()

	streamAssert := StreamShowOutputAssert{
		ResourceAssert: assert.NewImportedResourceShowOutputAssert(id),
	}
	return &streamAssert
}

func StreamsDatasourceShowOutput(t *testing.T, name string) *StreamShowOutputAssert {
	t.Helper()

	return StreamsDatasourceShowOutputOnIdx(t, name, 0)
}

func StreamsDatasourceShowOutputOnIdx(t *testing.T, name string, idx int) *StreamShowOutputAssert {
	t.Helper()

	streamAssert := StreamShowOutputAssert{
		ResourceAssert: assert.NewDatasourceShowOutputAssert(name, "streams", idx),
	}
	return &streamAssert
}

////////////////////////////
// Attribute value checks //
////////////////////////////

func (s *StreamShowOutputAssert) HasCreatedOn(expected time.Time) *StreamShowOutputAssert {
	s.StringValueSet("created_on", expected.String())
	return s
}

func (s *StreamShowOutputAssert) HasName(expected string) *StreamShowOutputAssert {
	s.StringValueSet("name", expected)
	return s
}

func (s *StreamShowOutputAssert) HasDatabaseName(expected string) *StreamShowOutputAssert {
	s.StringValueSet("database_name", expected)
	return s
}

func (s *StreamShowOutputAssert) HasSchemaName(expected string) *StreamShowOutputAssert {
	s.StringValueSet("schema_name", expected)
	return s
}

func (s *StreamShowOutputAssert) HasOwner(expected string) *StreamShowOutputAssert {
	s.StringValueSet("owner", expected)
	return s
}

func (s *StreamShowOutputAssert) HasComment(expected string) *StreamShowOutputAssert {
	s.StringValueSet("comment", expected)
	return s
}

func (s *StreamShowOutputAssert) HasTableName(expected sdk.SchemaObjectIdentifier) *StreamShowOutputAssert {
	s.StringValueSet("table_name", expected.FullyQualifiedName())
	return s
}

func (s *StreamShowOutputAssert) HasSourceType(expected sdk.StreamSourceType) *StreamShowOutputAssert {
	s.StringValueSet("source_type", string(expected))
	return s
}

func (s *StreamShowOutputAssert) HasType(expected string) *StreamShowOutputAssert {
	s.StringValueSet("type", expected)
	return s
}

func (s *StreamShowOutputAssert) HasStale(expected bool) *StreamShowOutputAssert {
	s.BoolValueSet("stale", expected)
	return s
}

func (s *StreamShowOutputAssert) HasMode(expected sdk.StreamMode) *StreamShowOutputAssert {
	s.StringValueSet("mode", string(expected))
	return s
}

func (s *StreamShowOutputAssert) HasStaleAfter(expected time.Time) *StreamShowOutputAssert {
	s.StringValueSet("stale_after", expected.String())
	return s
}

func (s *StreamShowOutputAssert) HasInvalidReason(expected string) *StreamShowOutputAssert {
	s.StringValueSet("invalid_reason", expected)
	return s
}

func (s *StreamShowOutputAssert) HasOwnerRoleType(expected string) *StreamShowOutputAssert {
	s.StringValueSet("owner_role_type", expected)
	return s
}

///////////////////////////////
// Attribute no value checks //
///////////////////////////////

func (s *StreamShowOutputAssert) HasNoCreatedOn() *StreamShowOutputAssert {
	s.ValueNotSet("created_on")
	return s
}

func (s *StreamShowOutputAssert) HasNoName() *StreamShowOutputAssert {
	s.ValueNotSet("name")
	return s
}

func (s *StreamShowOutputAssert) HasNoDatabaseName() *StreamShowOutputAssert {
	s.ValueNotSet("database_name")
	return s
}

func (s *StreamShowOutputAssert) HasNoSchemaName() *StreamShowOutputAssert {
	s.ValueNotSet("schema_name")
	return s
}

func (s *StreamShowOutputAssert) HasNoOwner() *StreamShowOutputAssert {
	s.ValueNotSet("owner")
	return s
}

func (s *StreamShowOutputAssert) HasNoComment() *StreamShowOutputAssert {
	s.ValueNotSet("comment")
	return s
}

func (s *StreamShowOutputAssert) HasNoTableName() *StreamShowOutputAssert {
	s.ValueNotSet("table_name")
	return s
}

func (s *StreamShowOutputAssert) HasNoSourceType() *StreamShowOutputAssert {
	s.ValueNotSet("source_type")
	return s
}

func (s *StreamShowOutputAssert) HasNoBaseTables() *StreamShowOutputAssert {
	s.ValueSet("base_tables.#", "0")
	return s
}

func (s *StreamShowOutputAssert) HasNoType() *StreamShowOutputAssert {
	s.ValueNotSet("type")
	return s
}

func (s *StreamShowOutputAssert) HasNoStale() *StreamShowOutputAssert {
	s.ValueNotSet("stale")
	return s
}

func (s *StreamShowOutputAssert) HasNoMode() *StreamShowOutputAssert {
	s.ValueNotSet("mode")
	return s
}

func (s *StreamShowOutputAssert) HasNoStaleAfter() *StreamShowOutputAssert {
	s.ValueNotSet("stale_after")
	return s
}

func (s *StreamShowOutputAssert) HasNoInvalidReason() *StreamShowOutputAssert {
	s.ValueNotSet("invalid_reason")
	return s
}

func (s *StreamShowOutputAssert) HasNoOwnerRoleType() *StreamShowOutputAssert {
	s.ValueNotSet("owner_role_type")
	return s
}
