// Code generated by resource show output assertions generator (v0.1.0); DO NOT EDIT.

package resourceshowoutputassert

import (
	"testing"
	"time"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

type TagShowOutputAssert struct {
	*assert.ResourceAssert
}

func TagShowOutput(t *testing.T, name string) *TagShowOutputAssert {
	t.Helper()

	tagAssert := TagShowOutputAssert{
		ResourceAssert: assert.NewResourceShowOutputAssert(name),
	}
	return &tagAssert
}

func ImportedTagShowOutput(t *testing.T, id string) *TagShowOutputAssert {
	t.Helper()

	tagAssert := TagShowOutputAssert{
		ResourceAssert: assert.NewImportedResourceShowOutputAssert(id),
	}
	return &tagAssert
}

func TagsDatasourceShowOutput(t *testing.T, name string) *TagShowOutputAssert {
	t.Helper()

	return TagsDatasourceShowOutputOnIdx(t, name, 0)
}

func TagsDatasourceShowOutputOnIdx(t *testing.T, name string, idx int) *TagShowOutputAssert {
	t.Helper()

	tagAssert := TagShowOutputAssert{
		ResourceAssert: assert.NewDatasourceShowOutputAssert(name, "tags", idx),
	}
	return &tagAssert
}

////////////////////////////
// Attribute value checks //
////////////////////////////

func (t *TagShowOutputAssert) HasCreatedOn(expected time.Time) *TagShowOutputAssert {
	t.StringValueSet("created_on", expected.String())
	return t
}

func (t *TagShowOutputAssert) HasName(expected string) *TagShowOutputAssert {
	t.StringValueSet("name", expected)
	return t
}

func (t *TagShowOutputAssert) HasDatabaseName(expected string) *TagShowOutputAssert {
	t.StringValueSet("database_name", expected)
	return t
}

func (t *TagShowOutputAssert) HasSchemaName(expected string) *TagShowOutputAssert {
	t.StringValueSet("schema_name", expected)
	return t
}

func (t *TagShowOutputAssert) HasOwner(expected string) *TagShowOutputAssert {
	t.StringValueSet("owner", expected)
	return t
}

func (t *TagShowOutputAssert) HasComment(expected string) *TagShowOutputAssert {
	t.StringValueSet("comment", expected)
	return t
}

func (t *TagShowOutputAssert) HasOwnerRoleType(expected string) *TagShowOutputAssert {
	t.StringValueSet("owner_role_type", expected)
	return t
}

func (t *TagShowOutputAssert) HasPropagate(expected sdk.TagPropagation) *TagShowOutputAssert {
	t.StringValueSet("propagate", string(expected))
	return t
}

func (t *TagShowOutputAssert) HasOnConflict(expected string) *TagShowOutputAssert {
	t.StringValueSet("on_conflict", expected)
	return t
}

///////////////////////////////
// Attribute no value checks //
///////////////////////////////

func (t *TagShowOutputAssert) HasNoCreatedOn() *TagShowOutputAssert {
	t.ValueNotSet("created_on")
	return t
}

func (t *TagShowOutputAssert) HasNoName() *TagShowOutputAssert {
	t.ValueNotSet("name")
	return t
}

func (t *TagShowOutputAssert) HasNoDatabaseName() *TagShowOutputAssert {
	t.ValueNotSet("database_name")
	return t
}

func (t *TagShowOutputAssert) HasNoSchemaName() *TagShowOutputAssert {
	t.ValueNotSet("schema_name")
	return t
}

func (t *TagShowOutputAssert) HasNoOwner() *TagShowOutputAssert {
	t.ValueNotSet("owner")
	return t
}

func (t *TagShowOutputAssert) HasNoComment() *TagShowOutputAssert {
	t.ValueNotSet("comment")
	return t
}

func (t *TagShowOutputAssert) HasNoAllowedValues() *TagShowOutputAssert {
	t.ValueSet("allowed_values.#", "0")
	return t
}

func (t *TagShowOutputAssert) HasNoOwnerRoleType() *TagShowOutputAssert {
	t.ValueNotSet("owner_role_type")
	return t
}

func (t *TagShowOutputAssert) HasNoPropagate() *TagShowOutputAssert {
	t.ValueNotSet("propagate")
	return t
}

func (t *TagShowOutputAssert) HasNoOnConflict() *TagShowOutputAssert {
	t.ValueNotSet("on_conflict")
	return t
}
