// Code generated by data source model builder generator (v0.1.0); DO NOT EDIT.

package datasourcemodel

import (
	"encoding/json"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/config"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/datasources"
	tfconfig "github.com/hashicorp/terraform-plugin-testing/config"
)

type PasswordPoliciesModel struct {
	In               tfconfig.Variable `json:"in,omitempty"`
	Like             tfconfig.Variable `json:"like,omitempty"`
	Limit            tfconfig.Variable `json:"limit,omitempty"`
	PasswordPolicies tfconfig.Variable `json:"password_policies,omitempty"`
	WithDescribe     tfconfig.Variable `json:"with_describe,omitempty"`

	*config.DatasourceModelMeta
}

/////////////////////////////////////////////////
// Basic builders (resource name and required) //
/////////////////////////////////////////////////

func PasswordPolicies(
	datasourceName string,
) *PasswordPoliciesModel {
	p := &PasswordPoliciesModel{DatasourceModelMeta: config.DatasourceMeta(datasourceName, datasources.PasswordPolicies)}
	return p
}

func PasswordPoliciesWithDefaultMeta() *PasswordPoliciesModel {
	p := &PasswordPoliciesModel{DatasourceModelMeta: config.DatasourceDefaultMeta(datasources.PasswordPolicies)}
	return p
}

///////////////////////////////////////////////////////
// set proper json marshalling and handle depends on //
///////////////////////////////////////////////////////

func (p *PasswordPoliciesModel) MarshalJSON() ([]byte, error) {
	type Alias PasswordPoliciesModel
	return json.Marshal(&struct {
		*Alias
		DependsOn                 []string                      `json:"depends_on,omitempty"`
		SingleAttributeWorkaround config.ReplacementPlaceholder `json:"single_attribute_workaround,omitempty"`
	}{
		Alias:                     (*Alias)(p),
		DependsOn:                 p.DependsOn(),
		SingleAttributeWorkaround: config.SnowflakeProviderConfigSingleAttributeWorkaround,
	})
}

func (p *PasswordPoliciesModel) WithDependsOn(values ...string) *PasswordPoliciesModel {
	p.SetDependsOn(values...)
	return p
}

/////////////////////////////////
// below all the proper values //
/////////////////////////////////

// in attribute type is not yet supported, so WithIn can't be generated

func (p *PasswordPoliciesModel) WithLike(like string) *PasswordPoliciesModel {
	p.Like = tfconfig.StringVariable(like)
	return p
}

// limit attribute type is not yet supported, so WithLimit can't be generated

// password_policies attribute type is not yet supported, so WithPasswordPolicies can't be generated

func (p *PasswordPoliciesModel) WithWithDescribe(withDescribe bool) *PasswordPoliciesModel {
	p.WithDescribe = tfconfig.BoolVariable(withDescribe)
	return p
}

//////////////////////////////////////////
// below it's possible to set any value //
//////////////////////////////////////////

func (p *PasswordPoliciesModel) WithInValue(value tfconfig.Variable) *PasswordPoliciesModel {
	p.In = value
	return p
}

func (p *PasswordPoliciesModel) WithLikeValue(value tfconfig.Variable) *PasswordPoliciesModel {
	p.Like = value
	return p
}

func (p *PasswordPoliciesModel) WithLimitValue(value tfconfig.Variable) *PasswordPoliciesModel {
	p.Limit = value
	return p
}

func (p *PasswordPoliciesModel) WithPasswordPoliciesValue(value tfconfig.Variable) *PasswordPoliciesModel {
	p.PasswordPolicies = value
	return p
}

func (p *PasswordPoliciesModel) WithWithDescribeValue(value tfconfig.Variable) *PasswordPoliciesModel {
	p.WithDescribe = value
	return p
}
