// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

var (
	_ validatable = new(CreateAccountOptions)
	_ validatable = new(AlterAccountOptions)
	_ validatable = new(DropAccountOptions)
	_ validatable = new(UndropAccountOptions)
	_ validatable = new(ShowAccountOptions)
)

func (opts *CreateAccountOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, ErrInvalidObjectIdentifier)
	}
	if !anyValueSet(opts.AdminPassword, opts.AdminRsaPublicKey) {
		errs = append(errs, errAtLeastOneOf("CreateAccountOptions", "AdminPassword", "AdminRsaPublicKey"))
	}
	errs = append(errs, opts.additionalValidations())
	return JoinErrors(errs...)
}

func (opts *AlterAccountOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !exactlyOneValueSet(opts.Set, opts.Unset, opts.SetTag, opts.UnsetTag, opts.Drop, opts.RenameTo) {
		errs = append(errs, errExactlyOneOf("AlterAccountOptions", "Set", "Unset", "SetTag", "UnsetTag", "Drop", "RenameTo"))
	}
	if opts.RenameTo != nil && !ValidObjectIdentifier(opts.RenameTo) {
		errs = append(errs, ErrInvalidObjectIdentifier)
	}
	errs = append(errs, opts.additionalValidations())
	if valueSet(opts.Set) {
		if !exactlyOneValueSet(opts.Set.Parameters, opts.Set.LegacyParameters, opts.Set.ResourceMonitor, opts.Set.PackagesPolicy, opts.Set.PasswordPolicy, opts.Set.SessionPolicy, opts.Set.AuthenticationPolicy, opts.Set.FeaturePolicySet, opts.Set.OrgAdmin, opts.Set.ConsumptionBillingEntity) {
			errs = append(errs, errExactlyOneOf("AlterAccountOptions.Set", "Parameters", "LegacyParameters", "ResourceMonitor", "PackagesPolicy", "PasswordPolicy", "SessionPolicy", "AuthenticationPolicy", "FeaturePolicySet", "OrgAdmin", "ConsumptionBillingEntity"))
		}
		errs = append(errs, opts.Set.additionalValidations())
		if valueSet(opts.Set.LegacyParameters) {
			errs = append(errs, opts.Set.LegacyParameters.additionalValidations())
		}
	}
	if valueSet(opts.Unset) {
		if !exactlyOneValueSet(opts.Unset.Parameters, opts.Unset.LegacyParameters, opts.Unset.PackagesPolicy, opts.Unset.PasswordPolicy, opts.Unset.SessionPolicy, opts.Unset.AuthenticationPolicy, opts.Unset.ResourceMonitor, opts.Unset.FeaturePolicyUnset, opts.Unset.ConsumptionBillingEntity) {
			errs = append(errs, errExactlyOneOf("AlterAccountOptions.Unset", "Parameters", "LegacyParameters", "PackagesPolicy", "PasswordPolicy", "SessionPolicy", "AuthenticationPolicy", "ResourceMonitor", "FeaturePolicyUnset", "ConsumptionBillingEntity"))
		}
		errs = append(errs, opts.Unset.additionalValidations())
		if valueSet(opts.Unset.LegacyParameters) {
			if !anyValueSet(opts.Unset.LegacyParameters.AccountParameters, opts.Unset.LegacyParameters.SessionParameters, opts.Unset.LegacyParameters.ObjectParameters, opts.Unset.LegacyParameters.UserParameters) {
				errs = append(errs, errAtLeastOneOf("AlterAccountOptions.Unset.LegacyParameters", "AccountParameters", "SessionParameters", "ObjectParameters", "UserParameters"))
			}
		}
	}
	return JoinErrors(errs...)
}

func (opts *DropAccountOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, ErrInvalidObjectIdentifier)
	}
	return JoinErrors(errs...)
}

func (opts *UndropAccountOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, ErrInvalidObjectIdentifier)
	}
	return JoinErrors(errs...)
}

func (opts *ShowAccountOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	return JoinErrors(errs...)
}
