// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

func NewCreateAccountRequest(
	name AccountObjectIdentifier,
	adminName string,
	email string,
) *CreateAccountRequest {
	s := CreateAccountRequest{}
	s.name = name
	s.AdminName = adminName
	s.Email = email
	return &s
}

func (s *CreateAccountRequest) WithAdminPassword(adminPassword string) *CreateAccountRequest {
	s.AdminPassword = &adminPassword
	return s
}

func (s *CreateAccountRequest) WithAdminRsaPublicKey(adminRsaPublicKey string) *CreateAccountRequest {
	s.AdminRsaPublicKey = &adminRsaPublicKey
	return s
}

func (s *CreateAccountRequest) WithAdminUserType(adminUserType UserType) *CreateAccountRequest {
	s.AdminUserType = &adminUserType
	return s
}

func (s *CreateAccountRequest) WithFirstName(firstName string) *CreateAccountRequest {
	s.FirstName = &firstName
	return s
}

func (s *CreateAccountRequest) WithLastName(lastName string) *CreateAccountRequest {
	s.LastName = &lastName
	return s
}

func (s *CreateAccountRequest) WithMustChangePassword(mustChangePassword bool) *CreateAccountRequest {
	s.MustChangePassword = &mustChangePassword
	return s
}

func (s *CreateAccountRequest) WithEdition(edition AccountEdition) *CreateAccountRequest {
	s.Edition = edition
	return s
}

func (s *CreateAccountRequest) WithRegionGroup(regionGroup string) *CreateAccountRequest {
	s.RegionGroup = &regionGroup
	return s
}

func (s *CreateAccountRequest) WithRegion(region string) *CreateAccountRequest {
	s.Region = &region
	return s
}

func (s *CreateAccountRequest) WithComment(comment string) *CreateAccountRequest {
	s.Comment = &comment
	return s
}

func (s *CreateAccountRequest) WithConsumptionBillingEntity(consumptionBillingEntity string) *CreateAccountRequest {
	s.ConsumptionBillingEntity = &consumptionBillingEntity
	return s
}

func (s *CreateAccountRequest) WithPolaris(polaris bool) *CreateAccountRequest {
	s.Polaris = &polaris
	return s
}

func NewAlterAccountRequest() *AlterAccountRequest {
	s := AlterAccountRequest{}
	return &s
}

func (s *AlterAccountRequest) WithName(name AccountObjectIdentifier) *AlterAccountRequest {
	s.Name = &name
	return s
}

func (s *AlterAccountRequest) WithSet(set AccountSetRequest) *AlterAccountRequest {
	s.Set = &set
	return s
}

func (s *AlterAccountRequest) WithUnset(unset AccountUnsetRequest) *AlterAccountRequest {
	s.Unset = &unset
	return s
}

func (s *AlterAccountRequest) WithSetTag(setTag []TagAssociation) *AlterAccountRequest {
	s.SetTag = setTag
	return s
}

func (s *AlterAccountRequest) WithUnsetTag(unsetTag []ObjectIdentifier) *AlterAccountRequest {
	s.UnsetTag = unsetTag
	return s
}

func (s *AlterAccountRequest) WithRename(rename AccountRenameRequest) *AlterAccountRequest {
	s.Rename = &rename
	return s
}

func (s *AlterAccountRequest) WithDrop(drop AccountDropRequest) *AlterAccountRequest {
	s.Drop = &drop
	return s
}

func NewAccountSetRequest() *AccountSetRequest {
	s := AccountSetRequest{}
	return &s
}

func (s *AccountSetRequest) WithParameters(parameters AccountParameters) *AccountSetRequest {
	s.Parameters = &parameters
	return s
}

func (s *AccountSetRequest) WithLegacyParameters(legacyParameters AccountLevelParametersRequest) *AccountSetRequest {
	s.LegacyParameters = &legacyParameters
	return s
}

func (s *AccountSetRequest) WithResourceMonitor(resourceMonitor AccountObjectIdentifier) *AccountSetRequest {
	s.ResourceMonitor = &resourceMonitor
	return s
}

func (s *AccountSetRequest) WithPackagesPolicy(packagesPolicy SchemaObjectIdentifier) *AccountSetRequest {
	s.PackagesPolicy = &packagesPolicy
	return s
}

func (s *AccountSetRequest) WithPasswordPolicy(passwordPolicy SchemaObjectIdentifier) *AccountSetRequest {
	s.PasswordPolicy = &passwordPolicy
	return s
}

func (s *AccountSetRequest) WithSessionPolicy(sessionPolicy SchemaObjectIdentifier) *AccountSetRequest {
	s.SessionPolicy = &sessionPolicy
	return s
}

func (s *AccountSetRequest) WithAuthenticationPolicy(authenticationPolicy SchemaObjectIdentifier) *AccountSetRequest {
	s.AuthenticationPolicy = &authenticationPolicy
	return s
}

func (s *AccountSetRequest) WithFeaturePolicySet(featurePolicySet AccountFeaturePolicySetRequest) *AccountSetRequest {
	s.FeaturePolicySet = &featurePolicySet
	return s
}

func (s *AccountSetRequest) WithConsumptionBillingEntity(consumptionBillingEntity string) *AccountSetRequest {
	s.ConsumptionBillingEntity = &consumptionBillingEntity
	return s
}

func (s *AccountSetRequest) WithOrgAdmin(orgAdmin bool) *AccountSetRequest {
	s.OrgAdmin = &orgAdmin
	return s
}

func (s *AccountSetRequest) WithForce(force bool) *AccountSetRequest {
	s.Force = &force
	return s
}

func NewAccountLevelParametersRequest() *AccountLevelParametersRequest {
	s := AccountLevelParametersRequest{}
	return &s
}

func (s *AccountLevelParametersRequest) WithAccountParameters(accountParameters LegacyAccountParameters) *AccountLevelParametersRequest {
	s.AccountParameters = &accountParameters
	return s
}

func (s *AccountLevelParametersRequest) WithSessionParameters(sessionParameters SessionParameters) *AccountLevelParametersRequest {
	s.SessionParameters = &sessionParameters
	return s
}

func (s *AccountLevelParametersRequest) WithObjectParameters(objectParameters ObjectParameters) *AccountLevelParametersRequest {
	s.ObjectParameters = &objectParameters
	return s
}

func (s *AccountLevelParametersRequest) WithUserParameters(userParameters UserParameters) *AccountLevelParametersRequest {
	s.UserParameters = &userParameters
	return s
}

func NewAccountFeaturePolicySetRequest() *AccountFeaturePolicySetRequest {
	s := AccountFeaturePolicySetRequest{}
	return &s
}

func (s *AccountFeaturePolicySetRequest) WithFeaturePolicy(featurePolicy SchemaObjectIdentifier) *AccountFeaturePolicySetRequest {
	s.FeaturePolicy = &featurePolicy
	return s
}

func NewAccountUnsetRequest() *AccountUnsetRequest {
	s := AccountUnsetRequest{}
	return &s
}

func (s *AccountUnsetRequest) WithParameters(parameters AccountParametersUnset) *AccountUnsetRequest {
	s.Parameters = &parameters
	return s
}

func (s *AccountUnsetRequest) WithLegacyParameters(legacyParameters AccountLevelParametersUnsetRequest) *AccountUnsetRequest {
	s.LegacyParameters = &legacyParameters
	return s
}

func (s *AccountUnsetRequest) WithAuthenticationPolicy(authenticationPolicy bool) *AccountUnsetRequest {
	s.AuthenticationPolicy = &authenticationPolicy
	return s
}

func (s *AccountUnsetRequest) WithFeaturePolicyUnset(featurePolicyUnset AccountFeaturePolicyUnsetRequest) *AccountUnsetRequest {
	s.FeaturePolicyUnset = &featurePolicyUnset
	return s
}

func (s *AccountUnsetRequest) WithPackagesPolicy(packagesPolicy bool) *AccountUnsetRequest {
	s.PackagesPolicy = &packagesPolicy
	return s
}

func (s *AccountUnsetRequest) WithPasswordPolicy(passwordPolicy bool) *AccountUnsetRequest {
	s.PasswordPolicy = &passwordPolicy
	return s
}

func (s *AccountUnsetRequest) WithSessionPolicy(sessionPolicy bool) *AccountUnsetRequest {
	s.SessionPolicy = &sessionPolicy
	return s
}

func (s *AccountUnsetRequest) WithResourceMonitor(resourceMonitor bool) *AccountUnsetRequest {
	s.ResourceMonitor = &resourceMonitor
	return s
}

func (s *AccountUnsetRequest) WithConsumptionBillingEntity(consumptionBillingEntity bool) *AccountUnsetRequest {
	s.ConsumptionBillingEntity = &consumptionBillingEntity
	return s
}

func NewAccountLevelParametersUnsetRequest() *AccountLevelParametersUnsetRequest {
	s := AccountLevelParametersUnsetRequest{}
	return &s
}

func (s *AccountLevelParametersUnsetRequest) WithAccountParameters(accountParameters LegacyAccountParametersUnset) *AccountLevelParametersUnsetRequest {
	s.AccountParameters = &accountParameters
	return s
}

func (s *AccountLevelParametersUnsetRequest) WithSessionParameters(sessionParameters SessionParametersUnset) *AccountLevelParametersUnsetRequest {
	s.SessionParameters = &sessionParameters
	return s
}

func (s *AccountLevelParametersUnsetRequest) WithObjectParameters(objectParameters ObjectParametersUnset) *AccountLevelParametersUnsetRequest {
	s.ObjectParameters = &objectParameters
	return s
}

func (s *AccountLevelParametersUnsetRequest) WithUserParameters(userParameters UserParametersUnset) *AccountLevelParametersUnsetRequest {
	s.UserParameters = &userParameters
	return s
}

func NewAccountFeaturePolicyUnsetRequest() *AccountFeaturePolicyUnsetRequest {
	s := AccountFeaturePolicyUnsetRequest{}
	return &s
}

func (s *AccountFeaturePolicyUnsetRequest) WithFeaturePolicy(featurePolicy bool) *AccountFeaturePolicyUnsetRequest {
	s.FeaturePolicy = &featurePolicy
	return s
}

func NewAccountRenameRequest(
	newName AccountObjectIdentifier,
) *AccountRenameRequest {
	s := AccountRenameRequest{}
	s.NewName = newName
	return &s
}

func (s *AccountRenameRequest) WithSaveOldURL(saveOldURL bool) *AccountRenameRequest {
	s.SaveOldURL = &saveOldURL
	return s
}

func NewAccountDropRequest() *AccountDropRequest {
	s := AccountDropRequest{}
	return &s
}

func (s *AccountDropRequest) WithOldUrl(oldUrl bool) *AccountDropRequest {
	s.OldUrl = &oldUrl
	return s
}

func (s *AccountDropRequest) WithOldOrganizationUrl(oldOrganizationUrl bool) *AccountDropRequest {
	s.OldOrganizationUrl = &oldOrganizationUrl
	return s
}

func NewDropAccountRequest(
	name AccountObjectIdentifier,
) *DropAccountRequest {
	s := DropAccountRequest{}
	s.name = name
	return &s
}

func (s *DropAccountRequest) WithIfExists(ifExists bool) *DropAccountRequest {
	s.IfExists = &ifExists
	return s
}

func (s *DropAccountRequest) WithGracePeriodInDays(gracePeriodInDays int) *DropAccountRequest {
	s.GracePeriodInDays = &gracePeriodInDays
	return s
}

func NewUndropAccountRequest(
	name AccountObjectIdentifier,
) *UndropAccountRequest {
	s := UndropAccountRequest{}
	s.name = name
	return &s
}

func NewShowAccountRequest() *ShowAccountRequest {
	s := ShowAccountRequest{}
	return &s
}

func (s *ShowAccountRequest) WithHistory(history bool) *ShowAccountRequest {
	s.History = &history
	return s
}

func (s *ShowAccountRequest) WithLike(like Like) *ShowAccountRequest {
	s.Like = &like
	return s
}
