// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

var (
	_ optionsProvider[GetForEntityDataMetricFunctionReferenceOptions] = new(GetForEntityDataMetricFunctionReferenceRequest)
)

type GetForEntityDataMetricFunctionReferenceRequest struct {
	parameters *dataMetricFunctionReferenceParametersRequest
}

type dataMetricFunctionReferenceParametersRequest struct {
	arguments *dataMetricFunctionReferenceFunctionArgumentsRequest
}

type dataMetricFunctionReferenceFunctionArgumentsRequest struct {
	refEntityName   []ObjectIdentifier
	RefEntityDomain *DataMetricFunctionRefEntityDomainOption
}
