// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

import (
	"context"
	"errors"
	"strconv"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/internal/collections"
)

var (
	_ Databases                = (*databases)(nil)
	_ convertibleRow[Database] = new(databaseRow)
)

type databases struct {
	client *Client
}

func (v *databases) Create(ctx context.Context, request *CreateDatabaseRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *databases) Clone(ctx context.Context, request *CloneDatabaseRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *databases) CreateShared(ctx context.Context, request *CreateSharedDatabaseRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *databases) CreateSecondary(ctx context.Context, request *CreateSecondaryDatabaseRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *databases) CreateFromListing(ctx context.Context, request *CreateFromListingDatabaseRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *databases) CreateCatalogLinked(ctx context.Context, request *CreateCatalogLinkedDatabaseRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *databases) Alter(ctx context.Context, request *AlterDatabaseRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *databases) AlterReplication(ctx context.Context, request *AlterReplicationDatabaseRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *databases) AlterFailover(ctx context.Context, request *AlterFailoverDatabaseRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *databases) AlterCatalogLinked(ctx context.Context, request *AlterCatalogLinkedDatabaseRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *databases) Drop(ctx context.Context, request *DropDatabaseRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *databases) DropSafely(ctx context.Context, id AccountObjectIdentifier) error {
	return SafeDrop(v.client, func() error { return v.Drop(ctx, NewDropDatabaseRequest(id).WithIfExists(true)) }, ctx, id)
}

func (v *databases) Undrop(ctx context.Context, request *UndropDatabaseRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *databases) Show(ctx context.Context, request *ShowDatabaseRequest) ([]Database, error) {
	opts := request.toOpts()
	dbRows, err := validateAndQuery[databaseRow](v.client, ctx, opts)
	if err != nil {
		return nil, err
	}
	return convertRows[databaseRow, Database](dbRows)
}

func (v *databases) ShowByID(ctx context.Context, id AccountObjectIdentifier) (*Database, error) {
	request := NewShowDatabaseRequest().
		WithLike(Like{Pattern: String(id.Name())})
	databases, err := v.Show(ctx, request)
	if err != nil {
		return nil, err
	}
	return collections.FindFirst(databases, func(r Database) bool { return r.Name == id.Name() })
}

func (v *databases) ShowByIDSafely(ctx context.Context, id AccountObjectIdentifier) (*Database, error) {
	return SafeShowById(v.client, v.ShowByID, ctx, id)
}

func (r *CreateDatabaseRequest) toOpts() *CreateDatabaseOptions {
	opts := &CreateDatabaseOptions{
		OrReplace:                               r.OrReplace,
		Transient:                               r.Transient,
		IfNotExists:                             r.IfNotExists,
		name:                                    r.name,
		Catalog:                                 r.Catalog,
		DataRetentionTimeInDays:                 r.DataRetentionTimeInDays,
		DefaultDdlCollation:                     r.DefaultDdlCollation,
		DefaultNotebookComputePoolCpu:           r.DefaultNotebookComputePoolCpu,
		DefaultNotebookComputePoolGpu:           r.DefaultNotebookComputePoolGpu,
		EnableConsoleOutput:                     r.EnableConsoleOutput,
		ExternalVolume:                          r.ExternalVolume,
		LogEventLevel:                           r.LogEventLevel,
		LogLevel:                                r.LogLevel,
		MaxDataExtensionTimeInDays:              r.MaxDataExtensionTimeInDays,
		QuotedIdentifiersIgnoreCase:             r.QuotedIdentifiersIgnoreCase,
		ReplaceInvalidCharacters:                r.ReplaceInvalidCharacters,
		StorageSerializationPolicy:              r.StorageSerializationPolicy,
		SuspendTaskAfterNumFailures:             r.SuspendTaskAfterNumFailures,
		TaskAutoRetryAttempts:                   r.TaskAutoRetryAttempts,
		TraceLevel:                              r.TraceLevel,
		UserTaskManagedInitialWarehouseSize:     r.UserTaskManagedInitialWarehouseSize,
		UserTaskMinimumTriggerIntervalInSeconds: r.UserTaskMinimumTriggerIntervalInSeconds,
		UserTaskTimeoutMs:                       r.UserTaskTimeoutMs,
		Comment:                                 r.Comment,
		Tag:                                     r.Tag,
	}
	return opts
}

func (r *CloneDatabaseRequest) toOpts() *CloneDatabaseOptions {
	opts := &CloneDatabaseOptions{
		OrReplace:   r.OrReplace,
		Transient:   r.Transient,
		IfNotExists: r.IfNotExists,
		name:        r.name,
		Clone:       r.Clone,
	}
	return opts
}

func (r *CreateSharedDatabaseRequest) toOpts() *CreateSharedDatabaseOptions {
	opts := &CreateSharedDatabaseOptions{
		OrReplace:                               r.OrReplace,
		Transient:                               r.Transient,
		IfNotExists:                             r.IfNotExists,
		name:                                    r.name,
		FromShare:                               r.FromShare,
		Catalog:                                 r.Catalog,
		DefaultDdlCollation:                     r.DefaultDdlCollation,
		DefaultNotebookComputePoolCpu:           r.DefaultNotebookComputePoolCpu,
		DefaultNotebookComputePoolGpu:           r.DefaultNotebookComputePoolGpu,
		EnableConsoleOutput:                     r.EnableConsoleOutput,
		ExternalVolume:                          r.ExternalVolume,
		LogEventLevel:                           r.LogEventLevel,
		LogLevel:                                r.LogLevel,
		QuotedIdentifiersIgnoreCase:             r.QuotedIdentifiersIgnoreCase,
		ReplaceInvalidCharacters:                r.ReplaceInvalidCharacters,
		StorageSerializationPolicy:              r.StorageSerializationPolicy,
		SuspendTaskAfterNumFailures:             r.SuspendTaskAfterNumFailures,
		TaskAutoRetryAttempts:                   r.TaskAutoRetryAttempts,
		TraceLevel:                              r.TraceLevel,
		UserTaskManagedInitialWarehouseSize:     r.UserTaskManagedInitialWarehouseSize,
		UserTaskMinimumTriggerIntervalInSeconds: r.UserTaskMinimumTriggerIntervalInSeconds,
		UserTaskTimeoutMs:                       r.UserTaskTimeoutMs,
		Comment:                                 r.Comment,
		Tag:                                     r.Tag,
	}
	return opts
}

func (r *CreateSecondaryDatabaseRequest) toOpts() *CreateSecondaryDatabaseOptions {
	opts := &CreateSecondaryDatabaseOptions{
		OrReplace:                               r.OrReplace,
		Transient:                               r.Transient,
		IfNotExists:                             r.IfNotExists,
		name:                                    r.name,
		PrimaryDatabase:                         r.PrimaryDatabase,
		Catalog:                                 r.Catalog,
		DataRetentionTimeInDays:                 r.DataRetentionTimeInDays,
		DefaultDdlCollation:                     r.DefaultDdlCollation,
		DefaultNotebookComputePoolCpu:           r.DefaultNotebookComputePoolCpu,
		DefaultNotebookComputePoolGpu:           r.DefaultNotebookComputePoolGpu,
		EnableConsoleOutput:                     r.EnableConsoleOutput,
		ExternalVolume:                          r.ExternalVolume,
		LogEventLevel:                           r.LogEventLevel,
		LogLevel:                                r.LogLevel,
		MaxDataExtensionTimeInDays:              r.MaxDataExtensionTimeInDays,
		QuotedIdentifiersIgnoreCase:             r.QuotedIdentifiersIgnoreCase,
		ReplaceInvalidCharacters:                r.ReplaceInvalidCharacters,
		StorageSerializationPolicy:              r.StorageSerializationPolicy,
		SuspendTaskAfterNumFailures:             r.SuspendTaskAfterNumFailures,
		TaskAutoRetryAttempts:                   r.TaskAutoRetryAttempts,
		TraceLevel:                              r.TraceLevel,
		UserTaskManagedInitialWarehouseSize:     r.UserTaskManagedInitialWarehouseSize,
		UserTaskMinimumTriggerIntervalInSeconds: r.UserTaskMinimumTriggerIntervalInSeconds,
		UserTaskTimeoutMs:                       r.UserTaskTimeoutMs,
		Comment:                                 r.Comment,
	}
	return opts
}

func (r *CreateFromListingDatabaseRequest) toOpts() *CreateFromListingDatabaseOptions {
	opts := &CreateFromListingDatabaseOptions{
		name:        r.name,
		FromListing: r.FromListing,
	}
	return opts
}

func (r *CreateCatalogLinkedDatabaseRequest) toOpts() *CreateCatalogLinkedDatabaseOptions {
	opts := &CreateCatalogLinkedDatabaseOptions{
		name:                   r.name,
		ExternalVolume:         r.ExternalVolume,
		Comment:                r.Comment,
		Tag:                    r.Tag,
		CatalogCaseSensitivity: r.CatalogCaseSensitivity,
	}
	opts.LinkedCatalog = LinkedCatalog{
		Catalog:                   r.LinkedCatalog.Catalog,
		AllowedNamespaces:         r.LinkedCatalog.AllowedNamespaces,
		BlockedNamespaces:         r.LinkedCatalog.BlockedNamespaces,
		AllowedWriteOperations:    r.LinkedCatalog.AllowedWriteOperations,
		NamespaceMode:             r.LinkedCatalog.NamespaceMode,
		NamespaceFlattenDelimiter: r.LinkedCatalog.NamespaceFlattenDelimiter,
		SyncIntervalSeconds:       r.LinkedCatalog.SyncIntervalSeconds,
	}
	return opts
}

func (r *AlterDatabaseRequest) toOpts() *AlterDatabaseOptions {
	opts := &AlterDatabaseOptions{
		IfExists:  r.IfExists,
		name:      r.name,
		RenameTo:  r.RenameTo,
		SwapWith:  r.SwapWith,
		SetTags:   r.SetTags,
		UnsetTags: r.UnsetTags,
	}
	if r.Set != nil {
		opts.Set = &DatabaseSet{
			Catalog:                                 r.Set.Catalog,
			DataRetentionTimeInDays:                 r.Set.DataRetentionTimeInDays,
			DefaultDdlCollation:                     r.Set.DefaultDdlCollation,
			DefaultNotebookComputePoolCpu:           r.Set.DefaultNotebookComputePoolCpu,
			DefaultNotebookComputePoolGpu:           r.Set.DefaultNotebookComputePoolGpu,
			EnableConsoleOutput:                     r.Set.EnableConsoleOutput,
			ExternalVolume:                          r.Set.ExternalVolume,
			LogEventLevel:                           r.Set.LogEventLevel,
			LogLevel:                                r.Set.LogLevel,
			MaxDataExtensionTimeInDays:              r.Set.MaxDataExtensionTimeInDays,
			QuotedIdentifiersIgnoreCase:             r.Set.QuotedIdentifiersIgnoreCase,
			ReplaceInvalidCharacters:                r.Set.ReplaceInvalidCharacters,
			StorageSerializationPolicy:              r.Set.StorageSerializationPolicy,
			SuspendTaskAfterNumFailures:             r.Set.SuspendTaskAfterNumFailures,
			TaskAutoRetryAttempts:                   r.Set.TaskAutoRetryAttempts,
			TraceLevel:                              r.Set.TraceLevel,
			UserTaskManagedInitialWarehouseSize:     r.Set.UserTaskManagedInitialWarehouseSize,
			UserTaskMinimumTriggerIntervalInSeconds: r.Set.UserTaskMinimumTriggerIntervalInSeconds,
			UserTaskTimeoutMs:                       r.Set.UserTaskTimeoutMs,
			Comment:                                 r.Set.Comment,
		}
	}
	if r.Unset != nil {
		opts.Unset = &DatabaseUnset{
			Catalog:                                 r.Unset.Catalog,
			DataRetentionTimeInDays:                 r.Unset.DataRetentionTimeInDays,
			DefaultDdlCollation:                     r.Unset.DefaultDdlCollation,
			DefaultNotebookComputePoolCpu:           r.Unset.DefaultNotebookComputePoolCpu,
			DefaultNotebookComputePoolGpu:           r.Unset.DefaultNotebookComputePoolGpu,
			EnableConsoleOutput:                     r.Unset.EnableConsoleOutput,
			ExternalVolume:                          r.Unset.ExternalVolume,
			LogEventLevel:                           r.Unset.LogEventLevel,
			LogLevel:                                r.Unset.LogLevel,
			MaxDataExtensionTimeInDays:              r.Unset.MaxDataExtensionTimeInDays,
			QuotedIdentifiersIgnoreCase:             r.Unset.QuotedIdentifiersIgnoreCase,
			ReplaceInvalidCharacters:                r.Unset.ReplaceInvalidCharacters,
			StorageSerializationPolicy:              r.Unset.StorageSerializationPolicy,
			SuspendTaskAfterNumFailures:             r.Unset.SuspendTaskAfterNumFailures,
			TaskAutoRetryAttempts:                   r.Unset.TaskAutoRetryAttempts,
			TraceLevel:                              r.Unset.TraceLevel,
			UserTaskManagedInitialWarehouseSize:     r.Unset.UserTaskManagedInitialWarehouseSize,
			UserTaskMinimumTriggerIntervalInSeconds: r.Unset.UserTaskMinimumTriggerIntervalInSeconds,
			UserTaskTimeoutMs:                       r.Unset.UserTaskTimeoutMs,
			Comment:                                 r.Unset.Comment,
		}
	}
	return opts
}

func (r *AlterReplicationDatabaseRequest) toOpts() *AlterReplicationDatabaseOptions {
	opts := &AlterReplicationDatabaseOptions{
		name:    r.name,
		Refresh: r.Refresh,
	}
	if r.EnableReplication != nil {
		opts.EnableReplication = &EnableReplication{
			ToAccounts:         r.EnableReplication.ToAccounts,
			IgnoreEditionCheck: r.EnableReplication.IgnoreEditionCheck,
		}
	}
	if r.DisableReplication != nil {
		opts.DisableReplication = &DisableReplication{
			ToAccounts: r.DisableReplication.ToAccounts,
		}
	}
	return opts
}

func (r *AlterFailoverDatabaseRequest) toOpts() *AlterFailoverDatabaseOptions {
	opts := &AlterFailoverDatabaseOptions{
		name:    r.name,
		Primary: r.Primary,
	}
	if r.EnableFailover != nil {
		opts.EnableFailover = &EnableFailover{
			ToAccounts: r.EnableFailover.ToAccounts,
		}
	}
	if r.DisableFailover != nil {
		opts.DisableFailover = &DisableFailover{
			ToAccounts: r.DisableFailover.ToAccounts,
		}
	}
	return opts
}

func (r *AlterCatalogLinkedDatabaseRequest) toOpts() *AlterCatalogLinkedDatabaseOptions {
	opts := &AlterCatalogLinkedDatabaseOptions{
		IfExists:               r.IfExists,
		name:                   r.name,
		UnsetAllowedNamespaces: r.UnsetAllowedNamespaces,
		UnsetBlockedNamespaces: r.UnsetBlockedNamespaces,
	}
	if r.AddToAllowedNamespaces != nil {
		opts.AddToAllowedNamespaces = &AddToAllowedNamespaces{
			Namespaces: r.AddToAllowedNamespaces.Namespaces,
		}
	}
	if r.RemoveFromAllowedNamespaces != nil {
		opts.RemoveFromAllowedNamespaces = &RemoveFromAllowedNamespaces{
			Namespaces: r.RemoveFromAllowedNamespaces.Namespaces,
		}
	}
	if r.AddToBlockedNamespaces != nil {
		opts.AddToBlockedNamespaces = &AddToBlockedNamespaces{
			Namespaces: r.AddToBlockedNamespaces.Namespaces,
		}
	}
	if r.RemoveFromBlockedNamespaces != nil {
		opts.RemoveFromBlockedNamespaces = &RemoveFromBlockedNamespaces{
			Namespaces: r.RemoveFromBlockedNamespaces.Namespaces,
		}
	}
	if r.Set != nil {
		opts.Set = &CatalogLinkedDatabaseSet{
			SyncIntervalSeconds:    r.Set.SyncIntervalSeconds,
			AllowedWriteOperations: r.Set.AllowedWriteOperations,
		}
	}
	return opts
}

func (r *DropDatabaseRequest) toOpts() *DropDatabaseOptions {
	opts := &DropDatabaseOptions{
		IfExists: r.IfExists,
		name:     r.name,
		Cascade:  r.Cascade,
		Restrict: r.Restrict,
	}
	return opts
}

func (r *UndropDatabaseRequest) toOpts() *UndropDatabaseOptions {
	opts := &UndropDatabaseOptions{
		name: r.name,
	}
	return opts
}

func (r *ShowDatabaseRequest) toOpts() *ShowDatabaseOptions {
	opts := &ShowDatabaseOptions{
		Terse:      r.Terse,
		History:    r.History,
		Like:       r.Like,
		StartsWith: r.StartsWith,
		Limit:      r.Limit,
	}
	return opts
}

func (r databaseRow) convert() (*Database, error) {
	result := &Database{
		CreatedOn: r.CreatedOn,
		Name:      r.Name,
	}
	mapNullStringToRequiredBool(&result.IsDefault, r.IsDefault)
	mapNullStringToRequiredBool(&result.IsCurrent, r.IsCurrent)
	mapNullStringToNonNullableField(&result.Owner, r.Owner)
	mapNullStringToNonNullableField(&result.Comment, r.Comment)
	mapNullStringToNonNullableField(&result.Options, r.Options)
	mapNullStringToNonNullableField(&result.ResourceGroup, r.ResourceGroup)
	mapNullTimeToNonNullableField(&result.DroppedOn, r.DroppedOn)
	mapNullStringWithMapping(&result.Kind, r.Kind, ToDatabaseKind)
	mapNullStringToNonNullableField(&result.OwnerRoleType, r.OwnerRoleType)
	if err := r.additionalConvert(result); err != nil {
		return nil, err
	}
	return result, nil
}

func toDatabaseParametersDetails(params []*Parameter) (*DatabaseParametersDetails, error) {
	byKey := parametersByKey(params)
	var d DatabaseParametersDetails
	if err := errors.Join(
		fillTypedParameter(byKey["CATALOG"], ParseAccountObjectIdentifier, &d.Catalog),
		fillTypedParameter(byKey["DATA_RETENTION_TIME_IN_DAYS"], strconv.Atoi, &d.DataRetentionTimeInDays),
		fillTypedParameter(byKey["DEFAULT_DDL_COLLATION"], identityParse, &d.DefaultDdlCollation),
		fillTypedParameter(byKey["DEFAULT_NOTEBOOK_COMPUTE_POOL_CPU"], identityParse, &d.DefaultNotebookComputePoolCpu),
		fillTypedParameter(byKey["DEFAULT_NOTEBOOK_COMPUTE_POOL_GPU"], identityParse, &d.DefaultNotebookComputePoolGpu),
		fillTypedParameter(byKey["ENABLE_CONSOLE_OUTPUT"], strconv.ParseBool, &d.EnableConsoleOutput),
		fillTypedParameter(byKey["EXTERNAL_VOLUME"], ParseAccountObjectIdentifier, &d.ExternalVolume),
		fillTypedParameter(byKey["LOG_EVENT_LEVEL"], ToLogLevel, &d.LogEventLevel),
		fillTypedParameter(byKey["LOG_LEVEL"], ToLogLevel, &d.LogLevel),
		fillTypedParameter(byKey["MAX_DATA_EXTENSION_TIME_IN_DAYS"], strconv.Atoi, &d.MaxDataExtensionTimeInDays),
		fillTypedParameter(byKey["QUOTED_IDENTIFIERS_IGNORE_CASE"], strconv.ParseBool, &d.QuotedIdentifiersIgnoreCase),
		fillTypedParameter(byKey["REPLACE_INVALID_CHARACTERS"], strconv.ParseBool, &d.ReplaceInvalidCharacters),
		fillTypedParameter(byKey["STORAGE_SERIALIZATION_POLICY"], ToStorageSerializationPolicy, &d.StorageSerializationPolicy),
		fillTypedParameter(byKey["SUSPEND_TASK_AFTER_NUM_FAILURES"], strconv.Atoi, &d.SuspendTaskAfterNumFailures),
		fillTypedParameter(byKey["TASK_AUTO_RETRY_ATTEMPTS"], strconv.Atoi, &d.TaskAutoRetryAttempts),
		fillTypedParameter(byKey["TRACE_LEVEL"], ToTraceLevel, &d.TraceLevel),
		fillTypedParameter(byKey["USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE"], ToWarehouseSize, &d.UserTaskManagedInitialWarehouseSize),
		fillTypedParameter(byKey["USER_TASK_MINIMUM_TRIGGER_INTERVAL_IN_SECONDS"], strconv.Atoi, &d.UserTaskMinimumTriggerIntervalInSeconds),
		fillTypedParameter(byKey["USER_TASK_TIMEOUT_MS"], strconv.Atoi, &d.UserTaskTimeoutMs),
	); err != nil {
		return nil, err
	}
	return &d, nil
}

func (v *databases) ShowParametersDetails(ctx context.Context, id AccountObjectIdentifier) (*DatabaseParametersDetails, error) {
	params, err := v.ShowParameters(ctx, id)
	if err != nil {
		return nil, err
	}
	return toDatabaseParametersDetails(params)
}
