// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

var (
	_ validatable = new(CreateFailoverGroupOptions)
	_ validatable = new(CreateSecondaryReplicationGroupFailoverGroupOptions)
	_ validatable = new(AlterSourceFailoverGroupOptions)
	_ validatable = new(AlterTargetFailoverGroupOptions)
	_ validatable = new(DropFailoverGroupOptions)
	_ validatable = new(ShowFailoverGroupOptions)
	_ validatable = new(ShowFailoverGroupDatabasesFailoverGroupOptions)
	_ validatable = new(ShowFailoverGroupSharesFailoverGroupOptions)
)

func (opts *CreateFailoverGroupOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, errInvalidIdentifier("CreateFailoverGroupOptions", "name"))
	}
	return JoinErrors(errs...)
}

func (opts *CreateSecondaryReplicationGroupFailoverGroupOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, errInvalidIdentifier("CreateSecondaryReplicationGroupFailoverGroupOptions", "name"))
	}
	if !ValidObjectIdentifier(opts.PrimaryFailoverGroup) {
		errs = append(errs, errInvalidIdentifier("CreateSecondaryReplicationGroupFailoverGroupOptions", "PrimaryFailoverGroup"))
	}
	return JoinErrors(errs...)
}

func (opts *AlterSourceFailoverGroupOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, errInvalidIdentifier("AlterSourceFailoverGroupOptions", "name"))
	}
	if !exactlyOneValueSet(opts.RenameTo, opts.Set, opts.Unset, opts.Add, opts.Move, opts.Remove) {
		errs = append(errs, errExactlyOneOf("AlterSourceFailoverGroupOptions", "RenameTo", "Set", "Unset", "Add", "Move", "Remove"))
	}
	if valueSet(opts.Set) {
		errs = append(errs, opts.Set.additionalValidations())
	}
	if valueSet(opts.Unset) {
		if !anyValueSet(opts.Unset.ReplicationSchedule) {
			errs = append(errs, errAtLeastOneOf("AlterSourceFailoverGroupOptions.Unset", "ReplicationSchedule"))
		}
	}
	return JoinErrors(errs...)
}

func (opts *AlterTargetFailoverGroupOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, errInvalidIdentifier("AlterTargetFailoverGroupOptions", "name"))
	}
	if !exactlyOneValueSet(opts.Refresh, opts.Primary, opts.Suspend, opts.Resume) {
		errs = append(errs, errExactlyOneOf("AlterTargetFailoverGroupOptions", "Refresh", "Primary", "Suspend", "Resume"))
	}
	return JoinErrors(errs...)
}

func (opts *DropFailoverGroupOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, errInvalidIdentifier("DropFailoverGroupOptions", "name"))
	}
	return JoinErrors(errs...)
}

func (opts *ShowFailoverGroupOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	return JoinErrors(errs...)
}

func (opts *ShowFailoverGroupDatabasesFailoverGroupOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	return JoinErrors(errs...)
}

func (opts *ShowFailoverGroupSharesFailoverGroupOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	return JoinErrors(errs...)
}
