// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

func NewCreateFileFormatRequest(
	name SchemaObjectIdentifier,
	fileFormatType FileFormatType,
) *CreateFileFormatRequest {
	s := CreateFileFormatRequest{}
	s.name = name
	s.FileFormatType = fileFormatType
	return &s
}

func (s *CreateFileFormatRequest) WithOrReplace(orReplace bool) *CreateFileFormatRequest {
	s.OrReplace = &orReplace
	return s
}

func (s *CreateFileFormatRequest) WithIfNotExists(ifNotExists bool) *CreateFileFormatRequest {
	s.IfNotExists = &ifNotExists
	return s
}

func (s *CreateFileFormatRequest) WithFileFormatObjectOptions(fileFormatObjectOptions FileFormatObjectOptionsRequest) *CreateFileFormatRequest {
	s.FileFormatObjectOptions = fileFormatObjectOptions
	return s
}

func (s *CreateFileFormatRequest) WithComment(comment string) *CreateFileFormatRequest {
	s.Comment = &comment
	return s
}

func NewFileFormatObjectOptionsRequest() *FileFormatObjectOptionsRequest {
	s := FileFormatObjectOptionsRequest{}
	return &s
}

func (s *FileFormatObjectOptionsRequest) WithComment(comment string) *FileFormatObjectOptionsRequest {
	s.Comment = &comment
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvCompression(csvCompression CsvCompression) *FileFormatObjectOptionsRequest {
	s.CsvCompression = &csvCompression
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvRecordDelimiter(csvRecordDelimiter StageFileFormatStringOrNoneRequest) *FileFormatObjectOptionsRequest {
	s.CsvRecordDelimiter = &csvRecordDelimiter
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvFieldDelimiter(csvFieldDelimiter StageFileFormatStringOrNoneRequest) *FileFormatObjectOptionsRequest {
	s.CsvFieldDelimiter = &csvFieldDelimiter
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvMultiLine(csvMultiLine bool) *FileFormatObjectOptionsRequest {
	s.CsvMultiLine = &csvMultiLine
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvFileExtension(csvFileExtension string) *FileFormatObjectOptionsRequest {
	s.CsvFileExtension = &csvFileExtension
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvParseHeader(csvParseHeader bool) *FileFormatObjectOptionsRequest {
	s.CsvParseHeader = &csvParseHeader
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvSkipHeader(csvSkipHeader int) *FileFormatObjectOptionsRequest {
	s.CsvSkipHeader = &csvSkipHeader
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvSkipBlankLines(csvSkipBlankLines bool) *FileFormatObjectOptionsRequest {
	s.CsvSkipBlankLines = &csvSkipBlankLines
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvDateFormat(csvDateFormat StageFileFormatStringOrAutoRequest) *FileFormatObjectOptionsRequest {
	s.CsvDateFormat = &csvDateFormat
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvTimeFormat(csvTimeFormat StageFileFormatStringOrAutoRequest) *FileFormatObjectOptionsRequest {
	s.CsvTimeFormat = &csvTimeFormat
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvTimestampFormat(csvTimestampFormat StageFileFormatStringOrAutoRequest) *FileFormatObjectOptionsRequest {
	s.CsvTimestampFormat = &csvTimestampFormat
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvBinaryFormat(csvBinaryFormat BinaryFormat) *FileFormatObjectOptionsRequest {
	s.CsvBinaryFormat = &csvBinaryFormat
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvEscape(csvEscape StageFileFormatStringOrNoneRequest) *FileFormatObjectOptionsRequest {
	s.CsvEscape = &csvEscape
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvEscapeUnenclosedField(csvEscapeUnenclosedField StageFileFormatStringOrNoneRequest) *FileFormatObjectOptionsRequest {
	s.CsvEscapeUnenclosedField = &csvEscapeUnenclosedField
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvTrimSpace(csvTrimSpace bool) *FileFormatObjectOptionsRequest {
	s.CsvTrimSpace = &csvTrimSpace
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvFieldOptionallyEnclosedBy(csvFieldOptionallyEnclosedBy StageFileFormatStringOrNoneRequest) *FileFormatObjectOptionsRequest {
	s.CsvFieldOptionallyEnclosedBy = &csvFieldOptionallyEnclosedBy
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvNullIf(csvNullIf []NullString) *FileFormatObjectOptionsRequest {
	s.CsvNullIf = csvNullIf
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvErrorOnColumnCountMismatch(csvErrorOnColumnCountMismatch bool) *FileFormatObjectOptionsRequest {
	s.CsvErrorOnColumnCountMismatch = &csvErrorOnColumnCountMismatch
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvReplaceInvalidCharacters(csvReplaceInvalidCharacters bool) *FileFormatObjectOptionsRequest {
	s.CsvReplaceInvalidCharacters = &csvReplaceInvalidCharacters
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvEmptyFieldAsNull(csvEmptyFieldAsNull bool) *FileFormatObjectOptionsRequest {
	s.CsvEmptyFieldAsNull = &csvEmptyFieldAsNull
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvSkipByteOrderMark(csvSkipByteOrderMark bool) *FileFormatObjectOptionsRequest {
	s.CsvSkipByteOrderMark = &csvSkipByteOrderMark
	return s
}

func (s *FileFormatObjectOptionsRequest) WithCsvEncoding(csvEncoding CsvEncoding) *FileFormatObjectOptionsRequest {
	s.CsvEncoding = &csvEncoding
	return s
}

func (s *FileFormatObjectOptionsRequest) WithJsonCompression(jsonCompression JsonCompression) *FileFormatObjectOptionsRequest {
	s.JsonCompression = &jsonCompression
	return s
}

func (s *FileFormatObjectOptionsRequest) WithJsonDateFormat(jsonDateFormat StageFileFormatStringOrAutoRequest) *FileFormatObjectOptionsRequest {
	s.JsonDateFormat = &jsonDateFormat
	return s
}

func (s *FileFormatObjectOptionsRequest) WithJsonTimeFormat(jsonTimeFormat StageFileFormatStringOrAutoRequest) *FileFormatObjectOptionsRequest {
	s.JsonTimeFormat = &jsonTimeFormat
	return s
}

func (s *FileFormatObjectOptionsRequest) WithJsonTimestampFormat(jsonTimestampFormat StageFileFormatStringOrAutoRequest) *FileFormatObjectOptionsRequest {
	s.JsonTimestampFormat = &jsonTimestampFormat
	return s
}

func (s *FileFormatObjectOptionsRequest) WithJsonBinaryFormat(jsonBinaryFormat BinaryFormat) *FileFormatObjectOptionsRequest {
	s.JsonBinaryFormat = &jsonBinaryFormat
	return s
}

func (s *FileFormatObjectOptionsRequest) WithJsonTrimSpace(jsonTrimSpace bool) *FileFormatObjectOptionsRequest {
	s.JsonTrimSpace = &jsonTrimSpace
	return s
}

func (s *FileFormatObjectOptionsRequest) WithJsonMultiLine(jsonMultiLine bool) *FileFormatObjectOptionsRequest {
	s.JsonMultiLine = &jsonMultiLine
	return s
}

func (s *FileFormatObjectOptionsRequest) WithJsonNullIf(jsonNullIf []NullString) *FileFormatObjectOptionsRequest {
	s.JsonNullIf = jsonNullIf
	return s
}

func (s *FileFormatObjectOptionsRequest) WithJsonFileExtension(jsonFileExtension string) *FileFormatObjectOptionsRequest {
	s.JsonFileExtension = &jsonFileExtension
	return s
}

func (s *FileFormatObjectOptionsRequest) WithJsonEnableOctal(jsonEnableOctal bool) *FileFormatObjectOptionsRequest {
	s.JsonEnableOctal = &jsonEnableOctal
	return s
}

func (s *FileFormatObjectOptionsRequest) WithJsonAllowDuplicate(jsonAllowDuplicate bool) *FileFormatObjectOptionsRequest {
	s.JsonAllowDuplicate = &jsonAllowDuplicate
	return s
}

func (s *FileFormatObjectOptionsRequest) WithJsonStripOuterArray(jsonStripOuterArray bool) *FileFormatObjectOptionsRequest {
	s.JsonStripOuterArray = &jsonStripOuterArray
	return s
}

func (s *FileFormatObjectOptionsRequest) WithJsonStripNullValues(jsonStripNullValues bool) *FileFormatObjectOptionsRequest {
	s.JsonStripNullValues = &jsonStripNullValues
	return s
}

func (s *FileFormatObjectOptionsRequest) WithJsonReplaceInvalidCharacters(jsonReplaceInvalidCharacters bool) *FileFormatObjectOptionsRequest {
	s.JsonReplaceInvalidCharacters = &jsonReplaceInvalidCharacters
	return s
}

func (s *FileFormatObjectOptionsRequest) WithJsonIgnoreUtf8Errors(jsonIgnoreUtf8Errors bool) *FileFormatObjectOptionsRequest {
	s.JsonIgnoreUtf8Errors = &jsonIgnoreUtf8Errors
	return s
}

func (s *FileFormatObjectOptionsRequest) WithJsonSkipByteOrderMark(jsonSkipByteOrderMark bool) *FileFormatObjectOptionsRequest {
	s.JsonSkipByteOrderMark = &jsonSkipByteOrderMark
	return s
}

func (s *FileFormatObjectOptionsRequest) WithAvroCompression(avroCompression AvroCompression) *FileFormatObjectOptionsRequest {
	s.AvroCompression = &avroCompression
	return s
}

func (s *FileFormatObjectOptionsRequest) WithAvroTrimSpace(avroTrimSpace bool) *FileFormatObjectOptionsRequest {
	s.AvroTrimSpace = &avroTrimSpace
	return s
}

func (s *FileFormatObjectOptionsRequest) WithAvroReplaceInvalidCharacters(avroReplaceInvalidCharacters bool) *FileFormatObjectOptionsRequest {
	s.AvroReplaceInvalidCharacters = &avroReplaceInvalidCharacters
	return s
}

func (s *FileFormatObjectOptionsRequest) WithAvroNullIf(avroNullIf []NullString) *FileFormatObjectOptionsRequest {
	s.AvroNullIf = avroNullIf
	return s
}

func (s *FileFormatObjectOptionsRequest) WithOrcTrimSpace(orcTrimSpace bool) *FileFormatObjectOptionsRequest {
	s.OrcTrimSpace = &orcTrimSpace
	return s
}

func (s *FileFormatObjectOptionsRequest) WithOrcReplaceInvalidCharacters(orcReplaceInvalidCharacters bool) *FileFormatObjectOptionsRequest {
	s.OrcReplaceInvalidCharacters = &orcReplaceInvalidCharacters
	return s
}

func (s *FileFormatObjectOptionsRequest) WithOrcNullIf(orcNullIf []NullString) *FileFormatObjectOptionsRequest {
	s.OrcNullIf = orcNullIf
	return s
}

func (s *FileFormatObjectOptionsRequest) WithParquetCompression(parquetCompression ParquetCompression) *FileFormatObjectOptionsRequest {
	s.ParquetCompression = &parquetCompression
	return s
}

func (s *FileFormatObjectOptionsRequest) WithParquetSnappyCompression(parquetSnappyCompression bool) *FileFormatObjectOptionsRequest {
	s.ParquetSnappyCompression = &parquetSnappyCompression
	return s
}

func (s *FileFormatObjectOptionsRequest) WithParquetBinaryAsText(parquetBinaryAsText bool) *FileFormatObjectOptionsRequest {
	s.ParquetBinaryAsText = &parquetBinaryAsText
	return s
}

func (s *FileFormatObjectOptionsRequest) WithParquetUseLogicalType(parquetUseLogicalType bool) *FileFormatObjectOptionsRequest {
	s.ParquetUseLogicalType = &parquetUseLogicalType
	return s
}

func (s *FileFormatObjectOptionsRequest) WithParquetTrimSpace(parquetTrimSpace bool) *FileFormatObjectOptionsRequest {
	s.ParquetTrimSpace = &parquetTrimSpace
	return s
}

func (s *FileFormatObjectOptionsRequest) WithParquetUseVectorizedScanner(parquetUseVectorizedScanner bool) *FileFormatObjectOptionsRequest {
	s.ParquetUseVectorizedScanner = &parquetUseVectorizedScanner
	return s
}

func (s *FileFormatObjectOptionsRequest) WithParquetReplaceInvalidCharacters(parquetReplaceInvalidCharacters bool) *FileFormatObjectOptionsRequest {
	s.ParquetReplaceInvalidCharacters = &parquetReplaceInvalidCharacters
	return s
}

func (s *FileFormatObjectOptionsRequest) WithParquetNullIf(parquetNullIf []NullString) *FileFormatObjectOptionsRequest {
	s.ParquetNullIf = parquetNullIf
	return s
}

func (s *FileFormatObjectOptionsRequest) WithXmlCompression(xmlCompression XmlCompression) *FileFormatObjectOptionsRequest {
	s.XmlCompression = &xmlCompression
	return s
}

func (s *FileFormatObjectOptionsRequest) WithXmlIgnoreUtf8Errors(xmlIgnoreUtf8Errors bool) *FileFormatObjectOptionsRequest {
	s.XmlIgnoreUtf8Errors = &xmlIgnoreUtf8Errors
	return s
}

func (s *FileFormatObjectOptionsRequest) WithXmlPreserveSpace(xmlPreserveSpace bool) *FileFormatObjectOptionsRequest {
	s.XmlPreserveSpace = &xmlPreserveSpace
	return s
}

func (s *FileFormatObjectOptionsRequest) WithXmlStripOuterElement(xmlStripOuterElement bool) *FileFormatObjectOptionsRequest {
	s.XmlStripOuterElement = &xmlStripOuterElement
	return s
}

func (s *FileFormatObjectOptionsRequest) WithXmlDisableAutoConvert(xmlDisableAutoConvert bool) *FileFormatObjectOptionsRequest {
	s.XmlDisableAutoConvert = &xmlDisableAutoConvert
	return s
}

func (s *FileFormatObjectOptionsRequest) WithXmlReplaceInvalidCharacters(xmlReplaceInvalidCharacters bool) *FileFormatObjectOptionsRequest {
	s.XmlReplaceInvalidCharacters = &xmlReplaceInvalidCharacters
	return s
}

func (s *FileFormatObjectOptionsRequest) WithXmlSkipByteOrderMark(xmlSkipByteOrderMark bool) *FileFormatObjectOptionsRequest {
	s.XmlSkipByteOrderMark = &xmlSkipByteOrderMark
	return s
}

func NewStageFileFormatStringOrNoneRequest() *StageFileFormatStringOrNoneRequest {
	s := StageFileFormatStringOrNoneRequest{}
	return &s
}

func (s *StageFileFormatStringOrNoneRequest) WithValue(value string) *StageFileFormatStringOrNoneRequest {
	s.Value = &value
	return s
}

func (s *StageFileFormatStringOrNoneRequest) WithNone(none bool) *StageFileFormatStringOrNoneRequest {
	s.None = &none
	return s
}

func NewStageFileFormatStringOrAutoRequest() *StageFileFormatStringOrAutoRequest {
	s := StageFileFormatStringOrAutoRequest{}
	return &s
}

func (s *StageFileFormatStringOrAutoRequest) WithValue(value string) *StageFileFormatStringOrAutoRequest {
	s.Value = &value
	return s
}

func (s *StageFileFormatStringOrAutoRequest) WithAuto(auto bool) *StageFileFormatStringOrAutoRequest {
	s.Auto = &auto
	return s
}

func NewAlterFileFormatRequest(
	name SchemaObjectIdentifier,
) *AlterFileFormatRequest {
	s := AlterFileFormatRequest{}
	s.name = name
	return &s
}

func (s *AlterFileFormatRequest) WithIfExists(ifExists bool) *AlterFileFormatRequest {
	s.IfExists = &ifExists
	return s
}

func (s *AlterFileFormatRequest) WithRenameTo(renameTo SchemaObjectIdentifier) *AlterFileFormatRequest {
	s.RenameTo = &renameTo
	return s
}

func (s *AlterFileFormatRequest) WithSet(set FileFormatObjectOptionsRequest) *AlterFileFormatRequest {
	s.Set = &set
	return s
}

func NewDropFileFormatRequest(
	name SchemaObjectIdentifier,
) *DropFileFormatRequest {
	s := DropFileFormatRequest{}
	s.name = name
	return &s
}

func (s *DropFileFormatRequest) WithIfExists(ifExists bool) *DropFileFormatRequest {
	s.IfExists = &ifExists
	return s
}

func NewShowFileFormatRequest() *ShowFileFormatRequest {
	s := ShowFileFormatRequest{}
	return &s
}

func (s *ShowFileFormatRequest) WithLike(like Like) *ShowFileFormatRequest {
	s.Like = &like
	return s
}

func (s *ShowFileFormatRequest) WithIn(in In) *ShowFileFormatRequest {
	s.In = &in
	return s
}

func NewDescribeFileFormatRequest(
	name SchemaObjectIdentifier,
) *DescribeFileFormatRequest {
	s := DescribeFileFormatRequest{}
	s.name = name
	return &s
}

func NewDummyOperationFileFormatRequest() *DummyOperationFileFormatRequest {
	s := DummyOperationFileFormatRequest{}
	return &s
}

func (s *DummyOperationFileFormatRequest) WithFileFormat(fileFormat FileFormatOptionsRequest) *DummyOperationFileFormatRequest {
	s.FileFormat = &fileFormat
	return s
}

func NewFileFormatOptionsRequest() *FileFormatOptionsRequest {
	s := FileFormatOptionsRequest{}
	return &s
}

func (s *FileFormatOptionsRequest) WithCsvOptions(csvOptions FileFormatCsvOptionsRequest) *FileFormatOptionsRequest {
	s.CsvOptions = &csvOptions
	return s
}

func (s *FileFormatOptionsRequest) WithJsonOptions(jsonOptions FileFormatJsonOptionsRequest) *FileFormatOptionsRequest {
	s.JsonOptions = &jsonOptions
	return s
}

func (s *FileFormatOptionsRequest) WithAvroOptions(avroOptions FileFormatAvroOptionsRequest) *FileFormatOptionsRequest {
	s.AvroOptions = &avroOptions
	return s
}

func (s *FileFormatOptionsRequest) WithOrcOptions(orcOptions FileFormatOrcOptionsRequest) *FileFormatOptionsRequest {
	s.OrcOptions = &orcOptions
	return s
}

func (s *FileFormatOptionsRequest) WithParquetOptions(parquetOptions FileFormatParquetOptionsRequest) *FileFormatOptionsRequest {
	s.ParquetOptions = &parquetOptions
	return s
}

func (s *FileFormatOptionsRequest) WithXmlOptions(xmlOptions FileFormatXmlOptionsRequest) *FileFormatOptionsRequest {
	s.XmlOptions = &xmlOptions
	return s
}

func NewFileFormatCsvOptionsRequest() *FileFormatCsvOptionsRequest {
	s := FileFormatCsvOptionsRequest{}
	return &s
}

func (s *FileFormatCsvOptionsRequest) WithCompression(compression CsvCompression) *FileFormatCsvOptionsRequest {
	s.Compression = &compression
	return s
}

func (s *FileFormatCsvOptionsRequest) WithRecordDelimiter(recordDelimiter StageFileFormatStringOrNoneRequest) *FileFormatCsvOptionsRequest {
	s.RecordDelimiter = &recordDelimiter
	return s
}

func (s *FileFormatCsvOptionsRequest) WithFieldDelimiter(fieldDelimiter StageFileFormatStringOrNoneRequest) *FileFormatCsvOptionsRequest {
	s.FieldDelimiter = &fieldDelimiter
	return s
}

func (s *FileFormatCsvOptionsRequest) WithMultiLine(multiLine bool) *FileFormatCsvOptionsRequest {
	s.MultiLine = &multiLine
	return s
}

func (s *FileFormatCsvOptionsRequest) WithFileExtension(fileExtension string) *FileFormatCsvOptionsRequest {
	s.FileExtension = &fileExtension
	return s
}

func (s *FileFormatCsvOptionsRequest) WithParseHeader(parseHeader bool) *FileFormatCsvOptionsRequest {
	s.ParseHeader = &parseHeader
	return s
}

func (s *FileFormatCsvOptionsRequest) WithSkipHeader(skipHeader int) *FileFormatCsvOptionsRequest {
	s.SkipHeader = &skipHeader
	return s
}

func (s *FileFormatCsvOptionsRequest) WithSkipBlankLines(skipBlankLines bool) *FileFormatCsvOptionsRequest {
	s.SkipBlankLines = &skipBlankLines
	return s
}

func (s *FileFormatCsvOptionsRequest) WithDateFormat(dateFormat StageFileFormatStringOrAutoRequest) *FileFormatCsvOptionsRequest {
	s.DateFormat = &dateFormat
	return s
}

func (s *FileFormatCsvOptionsRequest) WithTimeFormat(timeFormat StageFileFormatStringOrAutoRequest) *FileFormatCsvOptionsRequest {
	s.TimeFormat = &timeFormat
	return s
}

func (s *FileFormatCsvOptionsRequest) WithTimestampFormat(timestampFormat StageFileFormatStringOrAutoRequest) *FileFormatCsvOptionsRequest {
	s.TimestampFormat = &timestampFormat
	return s
}

func (s *FileFormatCsvOptionsRequest) WithBinaryFormat(binaryFormat BinaryFormat) *FileFormatCsvOptionsRequest {
	s.BinaryFormat = &binaryFormat
	return s
}

func (s *FileFormatCsvOptionsRequest) WithEscape(escape StageFileFormatStringOrNoneRequest) *FileFormatCsvOptionsRequest {
	s.Escape = &escape
	return s
}

func (s *FileFormatCsvOptionsRequest) WithEscapeUnenclosedField(escapeUnenclosedField StageFileFormatStringOrNoneRequest) *FileFormatCsvOptionsRequest {
	s.EscapeUnenclosedField = &escapeUnenclosedField
	return s
}

func (s *FileFormatCsvOptionsRequest) WithTrimSpace(trimSpace bool) *FileFormatCsvOptionsRequest {
	s.TrimSpace = &trimSpace
	return s
}

func (s *FileFormatCsvOptionsRequest) WithFieldOptionallyEnclosedBy(fieldOptionallyEnclosedBy StageFileFormatStringOrNoneRequest) *FileFormatCsvOptionsRequest {
	s.FieldOptionallyEnclosedBy = &fieldOptionallyEnclosedBy
	return s
}

func (s *FileFormatCsvOptionsRequest) WithNullIf(nullIf []NullString) *FileFormatCsvOptionsRequest {
	s.NullIf = nullIf
	return s
}

func (s *FileFormatCsvOptionsRequest) WithErrorOnColumnCountMismatch(errorOnColumnCountMismatch bool) *FileFormatCsvOptionsRequest {
	s.ErrorOnColumnCountMismatch = &errorOnColumnCountMismatch
	return s
}

func (s *FileFormatCsvOptionsRequest) WithReplaceInvalidCharacters(replaceInvalidCharacters bool) *FileFormatCsvOptionsRequest {
	s.ReplaceInvalidCharacters = &replaceInvalidCharacters
	return s
}

func (s *FileFormatCsvOptionsRequest) WithEmptyFieldAsNull(emptyFieldAsNull bool) *FileFormatCsvOptionsRequest {
	s.EmptyFieldAsNull = &emptyFieldAsNull
	return s
}

func (s *FileFormatCsvOptionsRequest) WithSkipByteOrderMark(skipByteOrderMark bool) *FileFormatCsvOptionsRequest {
	s.SkipByteOrderMark = &skipByteOrderMark
	return s
}

func (s *FileFormatCsvOptionsRequest) WithEncoding(encoding CsvEncoding) *FileFormatCsvOptionsRequest {
	s.Encoding = &encoding
	return s
}

func NewFileFormatJsonOptionsRequest() *FileFormatJsonOptionsRequest {
	s := FileFormatJsonOptionsRequest{}
	return &s
}

func (s *FileFormatJsonOptionsRequest) WithCompression(compression JsonCompression) *FileFormatJsonOptionsRequest {
	s.Compression = &compression
	return s
}

func (s *FileFormatJsonOptionsRequest) WithDateFormat(dateFormat StageFileFormatStringOrAutoRequest) *FileFormatJsonOptionsRequest {
	s.DateFormat = &dateFormat
	return s
}

func (s *FileFormatJsonOptionsRequest) WithTimeFormat(timeFormat StageFileFormatStringOrAutoRequest) *FileFormatJsonOptionsRequest {
	s.TimeFormat = &timeFormat
	return s
}

func (s *FileFormatJsonOptionsRequest) WithTimestampFormat(timestampFormat StageFileFormatStringOrAutoRequest) *FileFormatJsonOptionsRequest {
	s.TimestampFormat = &timestampFormat
	return s
}

func (s *FileFormatJsonOptionsRequest) WithBinaryFormat(binaryFormat BinaryFormat) *FileFormatJsonOptionsRequest {
	s.BinaryFormat = &binaryFormat
	return s
}

func (s *FileFormatJsonOptionsRequest) WithTrimSpace(trimSpace bool) *FileFormatJsonOptionsRequest {
	s.TrimSpace = &trimSpace
	return s
}

func (s *FileFormatJsonOptionsRequest) WithMultiLine(multiLine bool) *FileFormatJsonOptionsRequest {
	s.MultiLine = &multiLine
	return s
}

func (s *FileFormatJsonOptionsRequest) WithNullIf(nullIf []NullString) *FileFormatJsonOptionsRequest {
	s.NullIf = nullIf
	return s
}

func (s *FileFormatJsonOptionsRequest) WithFileExtension(fileExtension string) *FileFormatJsonOptionsRequest {
	s.FileExtension = &fileExtension
	return s
}

func (s *FileFormatJsonOptionsRequest) WithEnableOctal(enableOctal bool) *FileFormatJsonOptionsRequest {
	s.EnableOctal = &enableOctal
	return s
}

func (s *FileFormatJsonOptionsRequest) WithAllowDuplicate(allowDuplicate bool) *FileFormatJsonOptionsRequest {
	s.AllowDuplicate = &allowDuplicate
	return s
}

func (s *FileFormatJsonOptionsRequest) WithStripOuterArray(stripOuterArray bool) *FileFormatJsonOptionsRequest {
	s.StripOuterArray = &stripOuterArray
	return s
}

func (s *FileFormatJsonOptionsRequest) WithStripNullValues(stripNullValues bool) *FileFormatJsonOptionsRequest {
	s.StripNullValues = &stripNullValues
	return s
}

func (s *FileFormatJsonOptionsRequest) WithReplaceInvalidCharacters(replaceInvalidCharacters bool) *FileFormatJsonOptionsRequest {
	s.ReplaceInvalidCharacters = &replaceInvalidCharacters
	return s
}

func (s *FileFormatJsonOptionsRequest) WithIgnoreUtf8Errors(ignoreUtf8Errors bool) *FileFormatJsonOptionsRequest {
	s.IgnoreUtf8Errors = &ignoreUtf8Errors
	return s
}

func (s *FileFormatJsonOptionsRequest) WithSkipByteOrderMark(skipByteOrderMark bool) *FileFormatJsonOptionsRequest {
	s.SkipByteOrderMark = &skipByteOrderMark
	return s
}

func NewFileFormatAvroOptionsRequest() *FileFormatAvroOptionsRequest {
	s := FileFormatAvroOptionsRequest{}
	return &s
}

func (s *FileFormatAvroOptionsRequest) WithCompression(compression AvroCompression) *FileFormatAvroOptionsRequest {
	s.Compression = &compression
	return s
}

func (s *FileFormatAvroOptionsRequest) WithTrimSpace(trimSpace bool) *FileFormatAvroOptionsRequest {
	s.TrimSpace = &trimSpace
	return s
}

func (s *FileFormatAvroOptionsRequest) WithReplaceInvalidCharacters(replaceInvalidCharacters bool) *FileFormatAvroOptionsRequest {
	s.ReplaceInvalidCharacters = &replaceInvalidCharacters
	return s
}

func (s *FileFormatAvroOptionsRequest) WithNullIf(nullIf []NullString) *FileFormatAvroOptionsRequest {
	s.NullIf = nullIf
	return s
}

func NewFileFormatOrcOptionsRequest() *FileFormatOrcOptionsRequest {
	s := FileFormatOrcOptionsRequest{}
	return &s
}

func (s *FileFormatOrcOptionsRequest) WithTrimSpace(trimSpace bool) *FileFormatOrcOptionsRequest {
	s.TrimSpace = &trimSpace
	return s
}

func (s *FileFormatOrcOptionsRequest) WithReplaceInvalidCharacters(replaceInvalidCharacters bool) *FileFormatOrcOptionsRequest {
	s.ReplaceInvalidCharacters = &replaceInvalidCharacters
	return s
}

func (s *FileFormatOrcOptionsRequest) WithNullIf(nullIf []NullString) *FileFormatOrcOptionsRequest {
	s.NullIf = nullIf
	return s
}

func NewFileFormatParquetOptionsRequest() *FileFormatParquetOptionsRequest {
	s := FileFormatParquetOptionsRequest{}
	return &s
}

func (s *FileFormatParquetOptionsRequest) WithCompression(compression ParquetCompression) *FileFormatParquetOptionsRequest {
	s.Compression = &compression
	return s
}

func (s *FileFormatParquetOptionsRequest) WithSnappyCompression(snappyCompression bool) *FileFormatParquetOptionsRequest {
	s.SnappyCompression = &snappyCompression
	return s
}

func (s *FileFormatParquetOptionsRequest) WithBinaryAsText(binaryAsText bool) *FileFormatParquetOptionsRequest {
	s.BinaryAsText = &binaryAsText
	return s
}

func (s *FileFormatParquetOptionsRequest) WithUseLogicalType(useLogicalType bool) *FileFormatParquetOptionsRequest {
	s.UseLogicalType = &useLogicalType
	return s
}

func (s *FileFormatParquetOptionsRequest) WithTrimSpace(trimSpace bool) *FileFormatParquetOptionsRequest {
	s.TrimSpace = &trimSpace
	return s
}

func (s *FileFormatParquetOptionsRequest) WithUseVectorizedScanner(useVectorizedScanner bool) *FileFormatParquetOptionsRequest {
	s.UseVectorizedScanner = &useVectorizedScanner
	return s
}

func (s *FileFormatParquetOptionsRequest) WithReplaceInvalidCharacters(replaceInvalidCharacters bool) *FileFormatParquetOptionsRequest {
	s.ReplaceInvalidCharacters = &replaceInvalidCharacters
	return s
}

func (s *FileFormatParquetOptionsRequest) WithNullIf(nullIf []NullString) *FileFormatParquetOptionsRequest {
	s.NullIf = nullIf
	return s
}

func NewFileFormatXmlOptionsRequest() *FileFormatXmlOptionsRequest {
	s := FileFormatXmlOptionsRequest{}
	return &s
}

func (s *FileFormatXmlOptionsRequest) WithCompression(compression XmlCompression) *FileFormatXmlOptionsRequest {
	s.Compression = &compression
	return s
}

func (s *FileFormatXmlOptionsRequest) WithIgnoreUtf8Errors(ignoreUtf8Errors bool) *FileFormatXmlOptionsRequest {
	s.IgnoreUtf8Errors = &ignoreUtf8Errors
	return s
}

func (s *FileFormatXmlOptionsRequest) WithPreserveSpace(preserveSpace bool) *FileFormatXmlOptionsRequest {
	s.PreserveSpace = &preserveSpace
	return s
}

func (s *FileFormatXmlOptionsRequest) WithStripOuterElement(stripOuterElement bool) *FileFormatXmlOptionsRequest {
	s.StripOuterElement = &stripOuterElement
	return s
}

func (s *FileFormatXmlOptionsRequest) WithDisableAutoConvert(disableAutoConvert bool) *FileFormatXmlOptionsRequest {
	s.DisableAutoConvert = &disableAutoConvert
	return s
}

func (s *FileFormatXmlOptionsRequest) WithReplaceInvalidCharacters(replaceInvalidCharacters bool) *FileFormatXmlOptionsRequest {
	s.ReplaceInvalidCharacters = &replaceInvalidCharacters
	return s
}

func (s *FileFormatXmlOptionsRequest) WithSkipByteOrderMark(skipByteOrderMark bool) *FileFormatXmlOptionsRequest {
	s.SkipByteOrderMark = &skipByteOrderMark
	return s
}
