// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

import "github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/datatypes"

var (
	_ optionsProvider[CreateIcebergTableOptions]                 = new(CreateIcebergTableRequest)
	_ optionsProvider[CreateFromIcebergFilesIcebergTableOptions] = new(CreateFromIcebergFilesIcebergTableRequest)
	_ optionsProvider[CreateFromDeltaLakeIcebergTableOptions]    = new(CreateFromDeltaLakeIcebergTableRequest)
	_ optionsProvider[CreateFromIcebergRestIcebergTableOptions]  = new(CreateFromIcebergRestIcebergTableRequest)
	_ optionsProvider[CreateFromAwsGlueIcebergTableOptions]      = new(CreateFromAwsGlueIcebergTableRequest)
	_ optionsProvider[AlterIcebergTableOptions]                  = new(AlterIcebergTableRequest)
	_ optionsProvider[DropIcebergTableOptions]                   = new(DropIcebergTableRequest)
	_ optionsProvider[ShowIcebergTableOptions]                   = new(ShowIcebergTableRequest)
	_ optionsProvider[DescribeIcebergTableOptions]               = new(DescribeIcebergTableRequest)
)

type CreateIcebergTableRequest struct {
	OrReplace                  *bool
	Transient                  *bool
	IfNotExists                *bool
	name                       SchemaObjectIdentifier                   // required
	ColumnsAndConstraints      IcebergTableColumnsAndConstraintsRequest // required
	PartitionBy                []IcebergTablePartitionExpressionRequest
	PathLayout                 *IcebergTablePathLayout
	ClusterBy                  []string
	ExternalVolume             *AccountObjectIdentifier
	Catalog                    *IcebergTableCatalog
	BaseLocation               *string
	TargetFileSize             *IcebergTableTargetFileSize
	CatalogSync                *string
	StorageSerializationPolicy *StorageSerializationPolicy
	DataRetentionTimeInDays    *int
	MaxDataExtensionTimeInDays *int
	ChangeTracking             *bool
	CopyGrants                 *bool
	ErrorLogging               *bool
	Comment                    *string
	IcebergVersion             *int
	EnableIcebergMergeOnRead   *bool
	RowAccessPolicy            *IcebergTableRowAccessPolicyRequest
	AggregationPolicy          *IcebergTableAggregationPolicyRequest
	Tag                        []TagAssociation
	EnableDataCompaction       *bool
	Contact                    []TableContact
}

type IcebergTableColumnsAndConstraintsRequest struct {
	Columns             []IcebergTableColumnRequest
	OutOfLineConstraint []TableOutOfLineConstraintRequest
}

type IcebergTableColumnRequest struct {
	Name             string             // required
	ColumnType       datatypes.DataType // required
	DefaultValue     *ColumnDefaultValue
	NotNull          *bool
	InlineConstraint *TableColumnInlineConstraintRequest
	MaskingPolicy    *TableColumnMaskingPolicyRequest
	ProjectionPolicy *TableColumnProjectionPolicyRequest
	Tag              []TagAssociation
	Comment          *string
}

type TableColumnInlineConstraintRequest struct {
	UniquePK *TableColumnInlineUniquePKRequest
	FK       *TableColumnInlineFKRequest
	CH       *TableColumnInlineCHRequest
}

type TableColumnInlineUniquePKRequest struct {
	Name               *string
	Unique             *bool
	PrimaryKey         *bool
	Enforced           *bool
	NotEnforced        *bool
	Deferrable         *bool
	NotDeferrable      *bool
	InitiallyDeferred  *bool
	InitiallyImmediate *bool
	Enable             *bool
	Disable            *bool
	Validate           *bool
	Novalidate         *bool
	Rely               *bool
	Norely             *bool
}

type TableColumnInlineFKRequest struct {
	Name               *string
	ForeignKey         *bool
	References         SchemaObjectIdentifier // required
	RefColumn          []Column
	Match              *MatchType
	On                 *ForeignKeyOnAction
	Enforced           *bool
	NotEnforced        *bool
	Deferrable         *bool
	NotDeferrable      *bool
	InitiallyDeferred  *bool
	InitiallyImmediate *bool
	Enable             *bool
	Disable            *bool
	Validate           *bool
	Novalidate         *bool
	Rely               *bool
	Norely             *bool
}

type TableColumnInlineCHRequest struct {
	Name             *string
	Expression       string // required
	EnableValidate   *bool
	EnableNovalidate *bool
}

type TableColumnMaskingPolicyRequest struct {
	MaskingPolicy SchemaObjectIdentifier // required
	Using         []Column
}

type TableColumnProjectionPolicyRequest struct {
	ProjectionPolicy SchemaObjectIdentifier // required
}

type TableOutOfLineConstraintRequest struct {
	UniquePK *TableOutOfLineUniquePKRequest
	FK       *TableOutOfLineFKRequest
	CH       *TableOutOfLineCHRequest
}

type TableOutOfLineUniquePKRequest struct {
	Name               *string
	Unique             *bool
	PrimaryKey         *bool
	Columns            []Column
	Enforced           *bool
	NotEnforced        *bool
	Deferrable         *bool
	NotDeferrable      *bool
	InitiallyDeferred  *bool
	InitiallyImmediate *bool
	Enable             *bool
	Disable            *bool
	Validate           *bool
	Novalidate         *bool
	Rely               *bool
	Norely             *bool
	Comment            *string
}

type TableOutOfLineFKRequest struct {
	Name               *string
	Columns            []Column
	References         SchemaObjectIdentifier // required
	RefColumns         []Column
	Match              *MatchType
	On                 *ForeignKeyOnAction
	Enforced           *bool
	NotEnforced        *bool
	Deferrable         *bool
	NotDeferrable      *bool
	InitiallyDeferred  *bool
	InitiallyImmediate *bool
	Enable             *bool
	Disable            *bool
	Validate           *bool
	Novalidate         *bool
	Rely               *bool
	Norely             *bool
	Comment            *string
}

type TableOutOfLineCHRequest struct {
	Name             *string
	Expression       string // required
	EnableValidate   *bool
	EnableNovalidate *bool
}

type IcebergTablePartitionExpressionRequest struct {
	Identity *string
	Bucket   *IcebergTablePartitionBucketRequest
	Truncate *IcebergTablePartitionTruncateRequest
	Year     *IcebergTablePartitionYearRequest
	Month    *IcebergTablePartitionMonthRequest
	Day      *IcebergTablePartitionDayRequest
	Hour     *IcebergTablePartitionHourRequest
}

type IcebergTablePartitionBucketRequest struct {
	Args IcebergTablePartitionBucketArgsRequest
}

type IcebergTablePartitionBucketArgsRequest struct {
	NumBuckets int    // required
	Column     string // required
}

type IcebergTablePartitionTruncateRequest struct {
	Args IcebergTablePartitionTruncateArgsRequest
}

type IcebergTablePartitionTruncateArgsRequest struct {
	Width  int    // required
	Column string // required
}

type IcebergTablePartitionYearRequest struct {
	Args IcebergTablePartitionTimeArgsRequest
}

type IcebergTablePartitionTimeArgsRequest struct {
	Column string // required
}

type IcebergTablePartitionMonthRequest struct {
	Args IcebergTablePartitionTimeArgsRequest
}

type IcebergTablePartitionDayRequest struct {
	Args IcebergTablePartitionTimeArgsRequest
}

type IcebergTablePartitionHourRequest struct {
	Args IcebergTablePartitionTimeArgsRequest
}

type IcebergTableRowAccessPolicyRequest struct {
	Name SchemaObjectIdentifier // required
	On   []Column               // required
}

type IcebergTableAggregationPolicyRequest struct {
	AggregationPolicy SchemaObjectIdentifier // required
}

type CreateFromIcebergFilesIcebergTableRequest struct {
	OrReplace                *bool
	IfNotExists              *bool
	name                     SchemaObjectIdentifier // required
	ExternalVolume           *AccountObjectIdentifier
	Catalog                  *AccountObjectIdentifier
	MetadataFilePath         string // required
	ReplaceInvalidCharacters *bool
	Comment                  *string
	Tag                      []TagAssociation
	Contact                  []TableContact
}

type CreateFromDeltaLakeIcebergTableRequest struct {
	OrReplace                *bool
	IfNotExists              *bool
	name                     SchemaObjectIdentifier // required
	ExternalVolume           *AccountObjectIdentifier
	Catalog                  *AccountObjectIdentifier
	BaseLocation             string // required
	ReplaceInvalidCharacters *bool
	AutoRefresh              *bool
	Comment                  *string
	Tag                      []TagAssociation
	Contact                  []TableContact
}

type CreateFromIcebergRestIcebergTableRequest struct {
	OrReplace                  *bool
	IfNotExists                *bool
	name                       SchemaObjectIdentifier // required
	ExternalVolume             *AccountObjectIdentifier
	Catalog                    *AccountObjectIdentifier
	CatalogTableName           string // required
	CatalogNamespace           *string
	PathLayout                 *IcebergTablePathLayout
	TargetFileSize             *IcebergTableTargetFileSize
	ReplaceInvalidCharacters   *bool
	AutoRefresh                *bool
	Comment                    *string
	StorageSerializationPolicy *StorageSerializationPolicy
	IcebergMergeOnReadBehavior *IcebergTableIcebergMergeOnReadBehavior
	EnableIcebergMergeOnRead   *bool
	Tag                        []TagAssociation
	Contact                    []TableContact
}

type CreateFromAwsGlueIcebergTableRequest struct {
	OrReplace                *bool
	IfNotExists              *bool
	name                     SchemaObjectIdentifier // required
	ExternalVolume           *AccountObjectIdentifier
	Catalog                  *AccountObjectIdentifier
	CatalogTableName         string // required
	CatalogNamespace         *string
	ReplaceInvalidCharacters *bool
	AutoRefresh              *bool
	Comment                  *string
	Tag                      []TagAssociation
	Contact                  []TableContact
}

type AlterIcebergTableRequest struct {
	IfExists                      *bool
	name                          SchemaObjectIdentifier // required
	AddColumnAction               *IcebergTableAddColumnActionRequest
	DropColumnAction              *TableDropColumnActionRequest
	RenameColumnAction            *TableRenameColumnActionRequest
	AlterColumnAction             []IcebergTableAlterColumnActionRequest
	SetMaskingPolicyOnColumn      *TableSetColumnMaskingPolicyRequest
	UnsetMaskingPolicyOnColumn    *TableUnsetColumnMaskingPolicyRequest
	SetProjectionPolicyOnColumn   *TableSetColumnProjectionPolicyRequest
	UnsetProjectionPolicyOnColumn *TableUnsetColumnProjectionPolicyRequest
	SetTagsOnColumn               *TableSetColumnTagsRequest
	UnsetTagsOnColumn             *TableUnsetColumnTagsRequest
	ClusteringAction              *IcebergTableClusteringActionRequest
	Set                           *IcebergTableSetPropertiesRequest
	Unset                         *IcebergTableUnsetPropertiesRequest
	SetTags                       []TagAssociation
	UnsetTags                     []ObjectIdentifier
	AddRowAccessPolicy            *ViewAddRowAccessPolicy
	DropRowAccessPolicy           *ViewDropRowAccessPolicy
	DropAndAddRowAccessPolicy     *ViewDropAndAddRowAccessPolicy
	DropAllRowAccessPolicies      *bool
	SetAggregationPolicy          *TableSetAggregationPolicyRequest
	UnsetAggregationPolicy        *TableUnsetAggregationPolicyRequest
	SetJoinPolicy                 *TableSetJoinPolicyRequest
	UnsetJoinPolicy               *TableUnsetJoinPolicyRequest
	SearchOptimizationAction      *TableSearchOptimizationActionRequest
}

type IcebergTableAddColumnActionRequest struct {
	IfNotExists      *bool
	Name             string             // required
	ColumnType       datatypes.DataType // required
	InlineConstraint *TableColumnInlineConstraintRequest
	DefaultValue     *ColumnDefaultValue
	MaskingPolicy    *TableColumnMaskingPolicyRequest
	ProjectionPolicy *TableColumnProjectionPolicyRequest
	Tag              []TagAssociation
}

type TableDropColumnActionRequest struct {
	IfExists *bool
	Columns  []Column // required
}

type TableRenameColumnActionRequest struct {
	OldName string // required
	NewName string
}

type IcebergTableAlterColumnActionRequest struct {
	ColumnName       string // required
	SetNotNull       *bool
	DropNotNull      *bool
	DataType         *datatypes.DataType
	Comment          *string
	UnsetComment     *bool
	SetWriteDefault  *string
	DropWriteDefault *bool
}

type TableSetColumnMaskingPolicyRequest struct {
	Name          string                 // required
	MaskingPolicy SchemaObjectIdentifier // required
	Using         []Column
	Force         *bool
}

type TableUnsetColumnMaskingPolicyRequest struct {
	Name string // required
}

type TableSetColumnProjectionPolicyRequest struct {
	Name             string                 // required
	ProjectionPolicy SchemaObjectIdentifier // required
	Force            *bool
}

type TableUnsetColumnProjectionPolicyRequest struct {
	Name string // required
}

type TableSetColumnTagsRequest struct {
	Name    string           // required
	SetTags []TagAssociation // required
}

type TableUnsetColumnTagsRequest struct {
	Name      string             // required
	UnsetTags []ObjectIdentifier // required
}

type IcebergTableClusteringActionRequest struct {
	ClusterBy            []string
	ChangeReclusterState *IcebergTableReclusterChangeStateRequest
	DropClusteringKey    *bool
}

type IcebergTableReclusterChangeStateRequest struct {
	State *ReclusterState
}

type IcebergTableSetPropertiesRequest struct {
	ReplaceInvalidCharacters   *bool
	CatalogSync                *string
	DataRetentionTimeInDays    *int
	MaxDataExtensionTimeInDays *int
	AutoRefresh                *bool
	TargetFileSize             *IcebergTableTargetFileSize
	Contact                    []TableContact
	LogEventLevel              *IcebergTableLogEventLevel
	ErrorLogging               *bool
	EnableDataCompaction       *bool
	EnableIcebergMergeOnRead   *bool
	Comment                    *string
}

type IcebergTableUnsetPropertiesRequest struct {
	ReplaceInvalidCharacters   *bool
	CatalogSync                *bool
	DataRetentionTimeInDays    *bool
	MaxDataExtensionTimeInDays *bool
	TargetFileSize             *bool
	LogEventLevel              *bool
	ErrorLogging               *bool
	EnableDataCompaction       *bool
	EnableIcebergMergeOnRead   *bool
	Comment                    *bool
}

type TableSetAggregationPolicyRequest struct {
	AggregationPolicy SchemaObjectIdentifier // required
	EntityKey         []Column
	Force             *bool
}

type TableUnsetAggregationPolicyRequest struct{}

type TableSetJoinPolicyRequest struct {
	JoinPolicy SchemaObjectIdentifier // required
	Force      *bool
}

type TableUnsetJoinPolicyRequest struct{}

type TableSearchOptimizationActionRequest struct {
	Add  *TableAddSearchOptimizationRequest
	Drop *TableDropSearchOptimizationRequest
}

type TableAddSearchOptimizationRequest struct {
	On []TableSearchMethodWithTargetRequest
}

type TableSearchMethodWithTargetRequest struct {
	Method TableSearchMethod // required
	Args   TableSearchMethodArgsRequest
}

type TableSearchMethodArgsRequest struct {
	Targets  []string
	Analyzer *string
}

type TableDropSearchOptimizationRequest struct {
	On []TableDropSearchOptimizationOnRequest
}

type TableDropSearchOptimizationOnRequest struct {
	SearchMethodWithTarget *TableSearchMethodWithTargetRequest
	ColumnName             *string
	ExpressionId           *string
}

type DropIcebergTableRequest struct {
	IfExists *bool
	name     SchemaObjectIdentifier // required
	Cascade  *bool
	Restrict *bool
}

type ShowIcebergTableRequest struct {
	Terse      *bool
	Like       *Like
	In         *In
	StartsWith *string
	Limit      *LimitFrom
}

type DescribeIcebergTableRequest struct {
	name         SchemaObjectIdentifier // required
	DescribeType *IcebergTableDescribeType
}
