// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

var (
	_ optionsProvider[CreateOpenflowConnectorOptions]   = new(CreateOpenflowConnectorRequest)
	_ optionsProvider[AlterOpenflowConnectorOptions]    = new(AlterOpenflowConnectorRequest)
	_ optionsProvider[DropOpenflowConnectorOptions]     = new(DropOpenflowConnectorRequest)
	_ optionsProvider[ShowOpenflowConnectorOptions]     = new(ShowOpenflowConnectorRequest)
	_ optionsProvider[DescribeOpenflowConnectorOptions] = new(DescribeOpenflowConnectorRequest)
)

type CreateOpenflowConnectorRequest struct {
	IfNotExists    *bool
	name           SchemaObjectIdentifier // required
	InRuntime      SchemaObjectIdentifier // required
	FromDefinition *string
	From           *Location
	DisplayName    *string
	Comment        *string
}

type AlterOpenflowConnectorRequest struct {
	name      SchemaObjectIdentifier // required
	Start     *bool
	Stop      *bool
	Terminate *bool
	Commit    *bool
	Abort     *bool
	Set       *OpenflowConnectorSetRequest
	Unset     *OpenflowConnectorUnsetRequest
}

type OpenflowConnectorSetRequest struct {
	DisplayName *string
	Comment     *string
}

type OpenflowConnectorUnsetRequest struct {
	DisplayName *bool
	Comment     *bool
}

type DropOpenflowConnectorRequest struct {
	IfExists *bool
	name     SchemaObjectIdentifier // required
}

type ShowOpenflowConnectorRequest struct {
	Like *Like
	In   *In
}

type DescribeOpenflowConnectorRequest struct {
	name SchemaObjectIdentifier // required
}
