// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

func NewCreatePipeRequest(
	name SchemaObjectIdentifier,
	copyStatement string,
) *CreatePipeRequest {
	s := CreatePipeRequest{}
	s.name = name
	s.copyStatement = copyStatement
	return &s
}

func (s *CreatePipeRequest) WithOrReplace(orReplace bool) *CreatePipeRequest {
	s.OrReplace = &orReplace
	return s
}

func (s *CreatePipeRequest) WithIfNotExists(ifNotExists bool) *CreatePipeRequest {
	s.IfNotExists = &ifNotExists
	return s
}

func (s *CreatePipeRequest) WithAutoIngest(autoIngest bool) *CreatePipeRequest {
	s.AutoIngest = &autoIngest
	return s
}

func (s *CreatePipeRequest) WithErrorIntegration(errorIntegration string) *CreatePipeRequest {
	s.ErrorIntegration = &errorIntegration
	return s
}

func (s *CreatePipeRequest) WithAwsSnsTopic(awsSnsTopic string) *CreatePipeRequest {
	s.AwsSnsTopic = &awsSnsTopic
	return s
}

func (s *CreatePipeRequest) WithIntegration(integration string) *CreatePipeRequest {
	s.Integration = &integration
	return s
}

func (s *CreatePipeRequest) WithComment(comment string) *CreatePipeRequest {
	s.Comment = &comment
	return s
}

func NewAlterPipeRequest(
	name SchemaObjectIdentifier,
) *AlterPipeRequest {
	s := AlterPipeRequest{}
	s.name = name
	return &s
}

func (s *AlterPipeRequest) WithIfExists(ifExists bool) *AlterPipeRequest {
	s.IfExists = &ifExists
	return s
}

func (s *AlterPipeRequest) WithSet(set PipeSetRequest) *AlterPipeRequest {
	s.Set = &set
	return s
}

func (s *AlterPipeRequest) WithUnset(unset PipeUnsetRequest) *AlterPipeRequest {
	s.Unset = &unset
	return s
}

func (s *AlterPipeRequest) WithSetTags(setTags []TagAssociation) *AlterPipeRequest {
	s.SetTags = setTags
	return s
}

func (s *AlterPipeRequest) WithUnsetTags(unsetTags []ObjectIdentifier) *AlterPipeRequest {
	s.UnsetTags = unsetTags
	return s
}

func (s *AlterPipeRequest) WithRefresh(refresh PipeRefreshRequest) *AlterPipeRequest {
	s.Refresh = &refresh
	return s
}

func NewPipeSetRequest() *PipeSetRequest {
	s := PipeSetRequest{}
	return &s
}

func (s *PipeSetRequest) WithErrorIntegration(errorIntegration string) *PipeSetRequest {
	s.ErrorIntegration = &errorIntegration
	return s
}

func (s *PipeSetRequest) WithPipeExecutionPaused(pipeExecutionPaused bool) *PipeSetRequest {
	s.PipeExecutionPaused = &pipeExecutionPaused
	return s
}

func (s *PipeSetRequest) WithComment(comment string) *PipeSetRequest {
	s.Comment = &comment
	return s
}

func NewPipeUnsetRequest() *PipeUnsetRequest {
	s := PipeUnsetRequest{}
	return &s
}

func (s *PipeUnsetRequest) WithErrorIntegration(errorIntegration bool) *PipeUnsetRequest {
	s.ErrorIntegration = &errorIntegration
	return s
}

func (s *PipeUnsetRequest) WithPipeExecutionPaused(pipeExecutionPaused bool) *PipeUnsetRequest {
	s.PipeExecutionPaused = &pipeExecutionPaused
	return s
}

func (s *PipeUnsetRequest) WithComment(comment bool) *PipeUnsetRequest {
	s.Comment = &comment
	return s
}

func NewPipeRefreshRequest() *PipeRefreshRequest {
	s := PipeRefreshRequest{}
	return &s
}

func (s *PipeRefreshRequest) WithPrefix(prefix string) *PipeRefreshRequest {
	s.Prefix = &prefix
	return s
}

func (s *PipeRefreshRequest) WithModifiedAfter(modifiedAfter string) *PipeRefreshRequest {
	s.ModifiedAfter = &modifiedAfter
	return s
}

func NewDropPipeRequest(
	name SchemaObjectIdentifier,
) *DropPipeRequest {
	s := DropPipeRequest{}
	s.name = name
	return &s
}

func (s *DropPipeRequest) WithIfExists(ifExists bool) *DropPipeRequest {
	s.IfExists = &ifExists
	return s
}

func NewShowPipeRequest() *ShowPipeRequest {
	s := ShowPipeRequest{}
	return &s
}

func (s *ShowPipeRequest) WithLike(like Like) *ShowPipeRequest {
	s.Like = &like
	return s
}

func (s *ShowPipeRequest) WithIn(in In) *ShowPipeRequest {
	s.In = &in
	return s
}

func NewDescribePipeRequest(
	name SchemaObjectIdentifier,
) *DescribePipeRequest {
	s := DescribePipeRequest{}
	s.name = name
	return &s
}
