// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

import "errors"

var (
	_ validatable = new(CreateSchemaOptions)
	_ validatable = new(AlterSchemaOptions)
	_ validatable = new(DropSchemaOptions)
	_ validatable = new(undropSchemaOptions)
	_ validatable = new(describeSchemaOptions)
	_ validatable = new(ShowSchemaOptions)
)

func (opts *CreateSchemaOptions) validate() error {
	if opts == nil {
		return errors.Join(ErrNilOptions)
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, ErrInvalidObjectIdentifier)
	}
	if valueSet(opts.Clone) {
		if err := opts.Clone.validate(); err != nil {
			errs = append(errs, err)
		}
	}
	if everyValueSet(opts.OrReplace, opts.IfNotExists) {
		errs = append(errs, errOneOf("CreateSchemaOptions", "IfNotExists", "OrReplace"))
	}
	if opts.ExternalVolume != nil && !ValidObjectIdentifier(opts.ExternalVolume) {
		errs = append(errs, errInvalidIdentifier("CreateSchemaOptions", "ExternalVolume"))
	}
	if opts.Catalog != nil && !ValidObjectIdentifier(opts.Catalog) {
		errs = append(errs, errInvalidIdentifier("CreateSchemaOptions", "Catalog"))
	}
	return errors.Join(errs...)
}

func (opts *AlterSchemaOptions) validate() error {
	if opts == nil {
		return errors.Join(ErrNilOptions)
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, ErrInvalidObjectIdentifier)
	}
	if opts.NewName != nil && !ValidObjectIdentifier(opts.NewName) {
		errs = append(errs, errInvalidIdentifier("AlterSchemaOptions", "NewName"))
	}
	if opts.SwapWith != nil && !ValidObjectIdentifier(opts.SwapWith) {
		errs = append(errs, errInvalidIdentifier("AlterSchemaOptions", "SwapWith"))
	}
	if !exactlyOneValueSet(opts.NewName, opts.SwapWith, opts.Set, opts.Unset, opts.SetTag, opts.UnsetTag, opts.EnableManagedAccess, opts.DisableManagedAccess) {
		errs = append(errs, errExactlyOneOf("AlterSchemaOptions", "NewName", "SwapWith", "Set", "Unset", "SetTag", "UnsetTag", "EnableManagedAccess", "DisableManagedAccess"))
	}
	if valueSet(opts.Set) {
		if err := opts.Set.validate(); err != nil {
			errs = append(errs, err)
		}
	}
	if valueSet(opts.Unset) {
		if err := opts.Unset.validate(); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

func (v *SchemaSet) validate() error {
	var errs []error
	if v.ExternalVolume != nil && !ValidObjectIdentifier(v.ExternalVolume) {
		errs = append(errs, errInvalidIdentifier("SchemaSet", "ExternalVolume"))
	}
	if v.Catalog != nil && !ValidObjectIdentifier(v.Catalog) {
		errs = append(errs, errInvalidIdentifier("SchemaSet", "Catalog"))
	}
	if !anyValueSet(
		v.DataRetentionTimeInDays,
		v.MaxDataExtensionTimeInDays,
		v.ExternalVolume,
		v.Catalog,
		v.ReplaceInvalidCharacters,
		v.DefaultDDLCollation,
		v.StorageSerializationPolicy,
		v.LogLevel,
		v.LogEventLevel,
		v.TraceLevel,
		v.SuspendTaskAfterNumFailures,
		v.TaskAutoRetryAttempts,
		v.UserTaskManagedInitialWarehouseSize,
		v.UserTaskTimeoutMs,
		v.UserTaskMinimumTriggerIntervalInSeconds,
		v.QuotedIdentifiersIgnoreCase,
		v.EnableConsoleOutput,
		v.PipeExecutionPaused,
		v.Comment,
	) {
		errs = append(errs, errAtLeastOneOf(
			"SchemaSet",
			"DataRetentionTimeInDays",
			"MaxDataExtensionTimeInDays",
			"ExternalVolume",
			"Catalog",
			"ReplaceInvalidCharacters",
			"DefaultDDLCollation",
			"StorageSerializationPolicy",
			"LogLevel",
			"LogEventLevel",
			"TraceLevel",
			"SuspendTaskAfterNumFailures",
			"TaskAutoRetryAttempts",
			"UserTaskManagedInitialWarehouseSize",
			"UserTaskTimeoutMs",
			"UserTaskMinimumTriggerIntervalInSeconds",
			"QuotedIdentifiersIgnoreCase",
			"EnableConsoleOutput",
			"PipeExecutionPaused",
			"Comment",
		))
	}
	return errors.Join(errs...)
}

func (v *SchemaUnset) validate() error {
	if !anyValueSet(
		v.DataRetentionTimeInDays,
		v.MaxDataExtensionTimeInDays,
		v.ExternalVolume,
		v.Catalog,
		v.ReplaceInvalidCharacters,
		v.DefaultDDLCollation,
		v.StorageSerializationPolicy,
		v.LogLevel,
		v.LogEventLevel,
		v.TraceLevel,
		v.SuspendTaskAfterNumFailures,
		v.TaskAutoRetryAttempts,
		v.UserTaskManagedInitialWarehouseSize,
		v.UserTaskTimeoutMs,
		v.UserTaskMinimumTriggerIntervalInSeconds,
		v.QuotedIdentifiersIgnoreCase,
		v.EnableConsoleOutput,
		v.PipeExecutionPaused,
		v.Comment,
	) {
		return errAtLeastOneOf(
			"SchemaUnset",
			"DataRetentionTimeInDays",
			"MaxDataExtensionTimeInDays",
			"ExternalVolume",
			"Catalog",
			"ReplaceInvalidCharacters",
			"DefaultDDLCollation",
			"StorageSerializationPolicy",
			"LogLevel",
			"LogEventLevel",
			"TraceLevel",
			"SuspendTaskAfterNumFailures",
			"TaskAutoRetryAttempts",
			"UserTaskManagedInitialWarehouseSize",
			"UserTaskTimeoutMs",
			"UserTaskMinimumTriggerIntervalInSeconds",
			"QuotedIdentifiersIgnoreCase",
			"EnableConsoleOutput",
			"PipeExecutionPaused",
			"Comment",
		)
	}
	return nil
}

func (opts *DropSchemaOptions) validate() error {
	if opts == nil {
		return errors.Join(ErrNilOptions)
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, ErrInvalidObjectIdentifier)
	}
	if everyValueSet(opts.Cascade, opts.Restrict) {
		errs = append(errs, errOneOf("DropSchemaOptions", "Cascade", "Restrict"))
	}
	return errors.Join(errs...)
}

func (opts *undropSchemaOptions) validate() error {
	if opts == nil {
		return errors.Join(ErrNilOptions)
	}
	if !ValidObjectIdentifier(opts.name) {
		return errors.Join(ErrInvalidObjectIdentifier)
	}
	return nil
}

func (opts *ShowSchemaOptions) validate() error {
	if opts == nil {
		return errors.Join(ErrNilOptions)
	}
	return nil
}

func (opts *describeSchemaOptions) validate() error {
	if opts == nil {
		return errors.Join(ErrNilOptions)
	}
	if !ValidObjectIdentifier(opts.name) {
		return errors.Join(ErrInvalidObjectIdentifier)
	}
	return nil
}
