// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

import (
	"testing"
)

func init() {
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[ApiAuthenticationSecurityIntegrationOauthClientAuthMethodOption]{"ApiAuthenticationSecurityIntegrationOauthClientAuthMethodOption", AllApiAuthenticationSecurityIntegrationOauthClientAuthMethodOptions, ToApiAuthenticationSecurityIntegrationOauthClientAuthMethodOption})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[ExternalOauthSecurityIntegrationTypeOption]{"ExternalOauthSecurityIntegrationTypeOption", AllExternalOauthSecurityIntegrationTypeOptions, ToExternalOauthSecurityIntegrationTypeOption})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[ExternalOauthSecurityIntegrationSnowflakeUserMappingAttributeOption]{"ExternalOauthSecurityIntegrationSnowflakeUserMappingAttributeOption", AllExternalOauthSecurityIntegrationSnowflakeUserMappingAttributeOptions, ToExternalOauthSecurityIntegrationSnowflakeUserMappingAttributeOption})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[ExternalOauthSecurityIntegrationAnyRoleModeOption]{"ExternalOauthSecurityIntegrationAnyRoleModeOption", AllExternalOauthSecurityIntegrationAnyRoleModeOptions, ToExternalOauthSecurityIntegrationAnyRoleModeOption})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[OauthSecurityIntegrationUseSecondaryRolesOption]{"OauthSecurityIntegrationUseSecondaryRolesOption", AllOauthSecurityIntegrationUseSecondaryRolesOptions, ToOauthSecurityIntegrationUseSecondaryRolesOption})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[OauthSecurityIntegrationClientTypeOption]{"OauthSecurityIntegrationClientTypeOption", AllOauthSecurityIntegrationClientTypeOptions, ToOauthSecurityIntegrationClientTypeOption})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[OauthSecurityIntegrationClientOption]{"OauthSecurityIntegrationClientOption", AllOauthSecurityIntegrationClientOptions, ToOauthSecurityIntegrationClientOption})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[Saml2SecurityIntegrationSaml2ProviderOption]{"Saml2SecurityIntegrationSaml2ProviderOption", AllSaml2SecurityIntegrationSaml2ProviderOptions, ToSaml2SecurityIntegrationSaml2ProviderOption})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[ScimSecurityIntegrationScimClientOption]{"ScimSecurityIntegrationScimClientOption", AllScimSecurityIntegrationScimClientOptions, ToScimSecurityIntegrationScimClientOption})
}

var securityIntegrationsTestIdAccountObjectIdentifier = randomAccountObjectIdentifier()

const (
	case_SecurityIntegrations_validation_CreateApiAuthenticationWithClientCredentialsFlow_name_ValidIdentifier                                     testCaseName = "validation_CreateApiAuthenticationWithClientCredentialsFlow_name_ValidIdentifier"
	case_SecurityIntegrations_validation_CreateApiAuthenticationWithClientCredentialsFlow_opts_ConflictingFields                                   testCaseName = "validation_CreateApiAuthenticationWithClientCredentialsFlow_opts_ConflictingFields"
	case_SecurityIntegrations_sql_CreateApiAuthenticationWithClientCredentialsFlow_basic                                                           testCaseName = "sql_CreateApiAuthenticationWithClientCredentialsFlow_basic"
	case_SecurityIntegrations_sql_CreateApiAuthenticationWithClientCredentialsFlow_all                                                             testCaseName = "sql_CreateApiAuthenticationWithClientCredentialsFlow_all"
	case_SecurityIntegrations_validation_CreateApiAuthenticationWithAuthorizationCodeGrantFlow_name_ValidIdentifier                                testCaseName = "validation_CreateApiAuthenticationWithAuthorizationCodeGrantFlow_name_ValidIdentifier"
	case_SecurityIntegrations_validation_CreateApiAuthenticationWithAuthorizationCodeGrantFlow_opts_ConflictingFields                              testCaseName = "validation_CreateApiAuthenticationWithAuthorizationCodeGrantFlow_opts_ConflictingFields"
	case_SecurityIntegrations_sql_CreateApiAuthenticationWithAuthorizationCodeGrantFlow_basic                                                      testCaseName = "sql_CreateApiAuthenticationWithAuthorizationCodeGrantFlow_basic"
	case_SecurityIntegrations_sql_CreateApiAuthenticationWithAuthorizationCodeGrantFlow_all                                                        testCaseName = "sql_CreateApiAuthenticationWithAuthorizationCodeGrantFlow_all"
	case_SecurityIntegrations_validation_CreateApiAuthenticationWithJwtBearerFlow_name_ValidIdentifier                                             testCaseName = "validation_CreateApiAuthenticationWithJwtBearerFlow_name_ValidIdentifier"
	case_SecurityIntegrations_validation_CreateApiAuthenticationWithJwtBearerFlow_opts_ConflictingFields                                           testCaseName = "validation_CreateApiAuthenticationWithJwtBearerFlow_opts_ConflictingFields"
	case_SecurityIntegrations_sql_CreateApiAuthenticationWithJwtBearerFlow_basic                                                                   testCaseName = "sql_CreateApiAuthenticationWithJwtBearerFlow_basic"
	case_SecurityIntegrations_sql_CreateApiAuthenticationWithJwtBearerFlow_all                                                                     testCaseName = "sql_CreateApiAuthenticationWithJwtBearerFlow_all"
	case_SecurityIntegrations_validation_CreateExternalOauth_opts_ConflictingFields_ExternalOauthBlockedRolesList_ExternalOauthAllowedRolesList    testCaseName = "validation_CreateExternalOauth_opts_ConflictingFields_ExternalOauthBlockedRolesList_ExternalOauthAllowedRolesList"
	case_SecurityIntegrations_validation_CreateExternalOauth_opts_ExactlyOneValueSet_NoneSet                                                       testCaseName = "validation_CreateExternalOauth_opts_ExactlyOneValueSet_NoneSet"
	case_SecurityIntegrations_validation_CreateExternalOauth_opts_ExactlyOneValueSet_MoreThanOneSet                                                testCaseName = "validation_CreateExternalOauth_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_SecurityIntegrations_validation_CreateExternalOauth_opts_ConflictingFields_ExternalOauthJwsKeysUrl_ExternalOauthRsaPublicKey2             testCaseName = "validation_CreateExternalOauth_opts_ConflictingFields_ExternalOauthJwsKeysUrl_ExternalOauthRsaPublicKey2"
	case_SecurityIntegrations_validation_CreateExternalOauth_name_ValidIdentifier                                                                  testCaseName = "validation_CreateExternalOauth_name_ValidIdentifier"
	case_SecurityIntegrations_validation_CreateExternalOauth_opts_ConflictingFields_OrReplace_IfNotExists                                          testCaseName = "validation_CreateExternalOauth_opts_ConflictingFields_OrReplace_IfNotExists"
	case_SecurityIntegrations_sql_CreateExternalOauth_basic                                                                                        testCaseName = "sql_CreateExternalOauth_basic"
	case_SecurityIntegrations_sql_CreateExternalOauth_all                                                                                          testCaseName = "sql_CreateExternalOauth_all"
	case_SecurityIntegrations_validation_CreateOauthForPartnerApplications_name_ValidIdentifier                                                    testCaseName = "validation_CreateOauthForPartnerApplications_name_ValidIdentifier"
	case_SecurityIntegrations_validation_CreateOauthForPartnerApplications_opts_ConflictingFields                                                  testCaseName = "validation_CreateOauthForPartnerApplications_opts_ConflictingFields"
	case_SecurityIntegrations_sql_CreateOauthForPartnerApplications_basic                                                                          testCaseName = "sql_CreateOauthForPartnerApplications_basic"
	case_SecurityIntegrations_sql_CreateOauthForPartnerApplications_all                                                                            testCaseName = "sql_CreateOauthForPartnerApplications_all"
	case_SecurityIntegrations_validation_CreateOauthForCustomClients_name_ValidIdentifier                                                          testCaseName = "validation_CreateOauthForCustomClients_name_ValidIdentifier"
	case_SecurityIntegrations_validation_CreateOauthForCustomClients_opts_ConflictingFields                                                        testCaseName = "validation_CreateOauthForCustomClients_opts_ConflictingFields"
	case_SecurityIntegrations_sql_CreateOauthForCustomClients_basic                                                                                testCaseName = "sql_CreateOauthForCustomClients_basic"
	case_SecurityIntegrations_sql_CreateOauthForCustomClients_all                                                                                  testCaseName = "sql_CreateOauthForCustomClients_all"
	case_SecurityIntegrations_validation_CreateSaml2_name_ValidIdentifier                                                                          testCaseName = "validation_CreateSaml2_name_ValidIdentifier"
	case_SecurityIntegrations_validation_CreateSaml2_opts_ConflictingFields                                                                        testCaseName = "validation_CreateSaml2_opts_ConflictingFields"
	case_SecurityIntegrations_sql_CreateSaml2_basic                                                                                                testCaseName = "sql_CreateSaml2_basic"
	case_SecurityIntegrations_sql_CreateSaml2_all                                                                                                  testCaseName = "sql_CreateSaml2_all"
	case_SecurityIntegrations_validation_CreateScim_name_ValidIdentifier                                                                           testCaseName = "validation_CreateScim_name_ValidIdentifier"
	case_SecurityIntegrations_validation_CreateScim_opts_ConflictingFields                                                                         testCaseName = "validation_CreateScim_opts_ConflictingFields"
	case_SecurityIntegrations_sql_CreateScim_basic                                                                                                 testCaseName = "sql_CreateScim_basic"
	case_SecurityIntegrations_sql_CreateScim_all                                                                                                   testCaseName = "sql_CreateScim_all"
	case_SecurityIntegrations_validation_AlterApiAuthenticationWithClientCredentialsFlow_name_ValidIdentifier                                      testCaseName = "validation_AlterApiAuthenticationWithClientCredentialsFlow_name_ValidIdentifier"
	case_SecurityIntegrations_validation_AlterApiAuthenticationWithClientCredentialsFlow_opts_ExactlyOneValueSet_NoneSet                           testCaseName = "validation_AlterApiAuthenticationWithClientCredentialsFlow_opts_ExactlyOneValueSet_NoneSet"
	case_SecurityIntegrations_validation_AlterApiAuthenticationWithClientCredentialsFlow_opts_ExactlyOneValueSet_MoreThanOneSet                    testCaseName = "validation_AlterApiAuthenticationWithClientCredentialsFlow_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_SecurityIntegrations_validation_AlterApiAuthenticationWithClientCredentialsFlow_opts_Set_AtLeastOneValueSet                               testCaseName = "validation_AlterApiAuthenticationWithClientCredentialsFlow_opts_Set_AtLeastOneValueSet"
	case_SecurityIntegrations_validation_AlterApiAuthenticationWithClientCredentialsFlow_opts_Unset_AtLeastOneValueSet                             testCaseName = "validation_AlterApiAuthenticationWithClientCredentialsFlow_opts_Unset_AtLeastOneValueSet"
	case_SecurityIntegrations_sql_AlterApiAuthenticationWithClientCredentialsFlow_Set                                                              testCaseName = "sql_AlterApiAuthenticationWithClientCredentialsFlow_Set"
	case_SecurityIntegrations_sql_AlterApiAuthenticationWithClientCredentialsFlow_Unset                                                            testCaseName = "sql_AlterApiAuthenticationWithClientCredentialsFlow_Unset"
	case_SecurityIntegrations_sql_AlterApiAuthenticationWithClientCredentialsFlow_SetTags                                                          testCaseName = "sql_AlterApiAuthenticationWithClientCredentialsFlow_SetTags"
	case_SecurityIntegrations_sql_AlterApiAuthenticationWithClientCredentialsFlow_UnsetTags                                                        testCaseName = "sql_AlterApiAuthenticationWithClientCredentialsFlow_UnsetTags"
	case_SecurityIntegrations_validation_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_name_ValidIdentifier                                 testCaseName = "validation_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_name_ValidIdentifier"
	case_SecurityIntegrations_validation_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_opts_ExactlyOneValueSet_NoneSet                      testCaseName = "validation_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_opts_ExactlyOneValueSet_NoneSet"
	case_SecurityIntegrations_validation_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_opts_ExactlyOneValueSet_MoreThanOneSet               testCaseName = "validation_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_SecurityIntegrations_validation_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_opts_Set_AtLeastOneValueSet                          testCaseName = "validation_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_opts_Set_AtLeastOneValueSet"
	case_SecurityIntegrations_validation_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_opts_Unset_AtLeastOneValueSet                        testCaseName = "validation_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_opts_Unset_AtLeastOneValueSet"
	case_SecurityIntegrations_sql_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_Set                                                         testCaseName = "sql_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_Set"
	case_SecurityIntegrations_sql_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_Unset                                                       testCaseName = "sql_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_Unset"
	case_SecurityIntegrations_sql_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_SetTags                                                     testCaseName = "sql_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_SetTags"
	case_SecurityIntegrations_sql_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_UnsetTags                                                   testCaseName = "sql_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_UnsetTags"
	case_SecurityIntegrations_validation_AlterApiAuthenticationWithJwtBearerFlow_name_ValidIdentifier                                              testCaseName = "validation_AlterApiAuthenticationWithJwtBearerFlow_name_ValidIdentifier"
	case_SecurityIntegrations_validation_AlterApiAuthenticationWithJwtBearerFlow_opts_ExactlyOneValueSet_NoneSet                                   testCaseName = "validation_AlterApiAuthenticationWithJwtBearerFlow_opts_ExactlyOneValueSet_NoneSet"
	case_SecurityIntegrations_validation_AlterApiAuthenticationWithJwtBearerFlow_opts_ExactlyOneValueSet_MoreThanOneSet                            testCaseName = "validation_AlterApiAuthenticationWithJwtBearerFlow_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_SecurityIntegrations_validation_AlterApiAuthenticationWithJwtBearerFlow_opts_Set_AtLeastOneValueSet                                       testCaseName = "validation_AlterApiAuthenticationWithJwtBearerFlow_opts_Set_AtLeastOneValueSet"
	case_SecurityIntegrations_validation_AlterApiAuthenticationWithJwtBearerFlow_opts_Unset_AtLeastOneValueSet                                     testCaseName = "validation_AlterApiAuthenticationWithJwtBearerFlow_opts_Unset_AtLeastOneValueSet"
	case_SecurityIntegrations_sql_AlterApiAuthenticationWithJwtBearerFlow_Set                                                                      testCaseName = "sql_AlterApiAuthenticationWithJwtBearerFlow_Set"
	case_SecurityIntegrations_sql_AlterApiAuthenticationWithJwtBearerFlow_Unset                                                                    testCaseName = "sql_AlterApiAuthenticationWithJwtBearerFlow_Unset"
	case_SecurityIntegrations_sql_AlterApiAuthenticationWithJwtBearerFlow_SetTags                                                                  testCaseName = "sql_AlterApiAuthenticationWithJwtBearerFlow_SetTags"
	case_SecurityIntegrations_sql_AlterApiAuthenticationWithJwtBearerFlow_UnsetTags                                                                testCaseName = "sql_AlterApiAuthenticationWithJwtBearerFlow_UnsetTags"
	case_SecurityIntegrations_validation_AlterExternalOauth_name_ValidIdentifier                                                                   testCaseName = "validation_AlterExternalOauth_name_ValidIdentifier"
	case_SecurityIntegrations_validation_AlterExternalOauth_opts_ExactlyOneValueSet_NoneSet                                                        testCaseName = "validation_AlterExternalOauth_opts_ExactlyOneValueSet_NoneSet"
	case_SecurityIntegrations_validation_AlterExternalOauth_opts_ExactlyOneValueSet_MoreThanOneSet                                                 testCaseName = "validation_AlterExternalOauth_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_SecurityIntegrations_validation_AlterExternalOauth_opts_Set_ConflictingFields_ExternalOauthBlockedRolesList_ExternalOauthAllowedRolesList testCaseName = "validation_AlterExternalOauth_opts_Set_ConflictingFields_ExternalOauthBlockedRolesList_ExternalOauthAllowedRolesList"
	case_SecurityIntegrations_validation_AlterExternalOauth_opts_Set_ConflictingFields_ExternalOauthJwsKeysUrl_ExternalOauthRsaPublicKey           testCaseName = "validation_AlterExternalOauth_opts_Set_ConflictingFields_ExternalOauthJwsKeysUrl_ExternalOauthRsaPublicKey"
	case_SecurityIntegrations_validation_AlterExternalOauth_opts_Set_ConflictingFields_ExternalOauthJwsKeysUrl_ExternalOauthRsaPublicKey2          testCaseName = "validation_AlterExternalOauth_opts_Set_ConflictingFields_ExternalOauthJwsKeysUrl_ExternalOauthRsaPublicKey2"
	case_SecurityIntegrations_validation_AlterExternalOauth_opts_Set_AtLeastOneValueSet                                                            testCaseName = "validation_AlterExternalOauth_opts_Set_AtLeastOneValueSet"
	case_SecurityIntegrations_validation_AlterExternalOauth_opts_Unset_AtLeastOneValueSet                                                          testCaseName = "validation_AlterExternalOauth_opts_Unset_AtLeastOneValueSet"
	case_SecurityIntegrations_sql_AlterExternalOauth_Set                                                                                           testCaseName = "sql_AlterExternalOauth_Set"
	case_SecurityIntegrations_sql_AlterExternalOauth_Unset                                                                                         testCaseName = "sql_AlterExternalOauth_Unset"
	case_SecurityIntegrations_sql_AlterExternalOauth_SetTags                                                                                       testCaseName = "sql_AlterExternalOauth_SetTags"
	case_SecurityIntegrations_sql_AlterExternalOauth_UnsetTags                                                                                     testCaseName = "sql_AlterExternalOauth_UnsetTags"
	case_SecurityIntegrations_validation_AlterOauthForPartnerApplications_name_ValidIdentifier                                                     testCaseName = "validation_AlterOauthForPartnerApplications_name_ValidIdentifier"
	case_SecurityIntegrations_validation_AlterOauthForPartnerApplications_opts_ExactlyOneValueSet_NoneSet                                          testCaseName = "validation_AlterOauthForPartnerApplications_opts_ExactlyOneValueSet_NoneSet"
	case_SecurityIntegrations_validation_AlterOauthForPartnerApplications_opts_ExactlyOneValueSet_MoreThanOneSet                                   testCaseName = "validation_AlterOauthForPartnerApplications_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_SecurityIntegrations_validation_AlterOauthForPartnerApplications_opts_Set_AtLeastOneValueSet                                              testCaseName = "validation_AlterOauthForPartnerApplications_opts_Set_AtLeastOneValueSet"
	case_SecurityIntegrations_validation_AlterOauthForPartnerApplications_opts_Unset_AtLeastOneValueSet                                            testCaseName = "validation_AlterOauthForPartnerApplications_opts_Unset_AtLeastOneValueSet"
	case_SecurityIntegrations_sql_AlterOauthForPartnerApplications_Set                                                                             testCaseName = "sql_AlterOauthForPartnerApplications_Set"
	case_SecurityIntegrations_sql_AlterOauthForPartnerApplications_Unset                                                                           testCaseName = "sql_AlterOauthForPartnerApplications_Unset"
	case_SecurityIntegrations_sql_AlterOauthForPartnerApplications_SetTags                                                                         testCaseName = "sql_AlterOauthForPartnerApplications_SetTags"
	case_SecurityIntegrations_sql_AlterOauthForPartnerApplications_UnsetTags                                                                       testCaseName = "sql_AlterOauthForPartnerApplications_UnsetTags"
	case_SecurityIntegrations_validation_AlterOauthForCustomClients_name_ValidIdentifier                                                           testCaseName = "validation_AlterOauthForCustomClients_name_ValidIdentifier"
	case_SecurityIntegrations_validation_AlterOauthForCustomClients_opts_ExactlyOneValueSet_NoneSet                                                testCaseName = "validation_AlterOauthForCustomClients_opts_ExactlyOneValueSet_NoneSet"
	case_SecurityIntegrations_validation_AlterOauthForCustomClients_opts_ExactlyOneValueSet_MoreThanOneSet                                         testCaseName = "validation_AlterOauthForCustomClients_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_SecurityIntegrations_validation_AlterOauthForCustomClients_opts_Set_AtLeastOneValueSet                                                    testCaseName = "validation_AlterOauthForCustomClients_opts_Set_AtLeastOneValueSet"
	case_SecurityIntegrations_validation_AlterOauthForCustomClients_opts_Unset_AtLeastOneValueSet                                                  testCaseName = "validation_AlterOauthForCustomClients_opts_Unset_AtLeastOneValueSet"
	case_SecurityIntegrations_sql_AlterOauthForCustomClients_Set                                                                                   testCaseName = "sql_AlterOauthForCustomClients_Set"
	case_SecurityIntegrations_sql_AlterOauthForCustomClients_Unset                                                                                 testCaseName = "sql_AlterOauthForCustomClients_Unset"
	case_SecurityIntegrations_sql_AlterOauthForCustomClients_SetTags                                                                               testCaseName = "sql_AlterOauthForCustomClients_SetTags"
	case_SecurityIntegrations_sql_AlterOauthForCustomClients_UnsetTags                                                                             testCaseName = "sql_AlterOauthForCustomClients_UnsetTags"
	case_SecurityIntegrations_validation_AlterSaml2_name_ValidIdentifier                                                                           testCaseName = "validation_AlterSaml2_name_ValidIdentifier"
	case_SecurityIntegrations_validation_AlterSaml2_opts_ExactlyOneValueSet_NoneSet                                                                testCaseName = "validation_AlterSaml2_opts_ExactlyOneValueSet_NoneSet"
	case_SecurityIntegrations_validation_AlterSaml2_opts_ExactlyOneValueSet_MoreThanOneSet                                                         testCaseName = "validation_AlterSaml2_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_SecurityIntegrations_validation_AlterSaml2_opts_Set_AtLeastOneValueSet                                                                    testCaseName = "validation_AlterSaml2_opts_Set_AtLeastOneValueSet"
	case_SecurityIntegrations_validation_AlterSaml2_opts_Unset_AtLeastOneValueSet                                                                  testCaseName = "validation_AlterSaml2_opts_Unset_AtLeastOneValueSet"
	case_SecurityIntegrations_sql_AlterSaml2_Set                                                                                                   testCaseName = "sql_AlterSaml2_Set"
	case_SecurityIntegrations_sql_AlterSaml2_Unset                                                                                                 testCaseName = "sql_AlterSaml2_Unset"
	case_SecurityIntegrations_sql_AlterSaml2_RefreshSaml2SnowflakePrivateKey                                                                       testCaseName = "sql_AlterSaml2_RefreshSaml2SnowflakePrivateKey"
	case_SecurityIntegrations_sql_AlterSaml2_SetTags                                                                                               testCaseName = "sql_AlterSaml2_SetTags"
	case_SecurityIntegrations_sql_AlterSaml2_UnsetTags                                                                                             testCaseName = "sql_AlterSaml2_UnsetTags"
	case_SecurityIntegrations_validation_AlterScim_name_ValidIdentifier                                                                            testCaseName = "validation_AlterScim_name_ValidIdentifier"
	case_SecurityIntegrations_validation_AlterScim_opts_ExactlyOneValueSet_NoneSet                                                                 testCaseName = "validation_AlterScim_opts_ExactlyOneValueSet_NoneSet"
	case_SecurityIntegrations_validation_AlterScim_opts_ExactlyOneValueSet_MoreThanOneSet                                                          testCaseName = "validation_AlterScim_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_SecurityIntegrations_validation_AlterScim_opts_Set_AtLeastOneValueSet                                                                     testCaseName = "validation_AlterScim_opts_Set_AtLeastOneValueSet"
	case_SecurityIntegrations_validation_AlterScim_opts_Unset_AtLeastOneValueSet                                                                   testCaseName = "validation_AlterScim_opts_Unset_AtLeastOneValueSet"
	case_SecurityIntegrations_sql_AlterScim_Set                                                                                                    testCaseName = "sql_AlterScim_Set"
	case_SecurityIntegrations_sql_AlterScim_Unset                                                                                                  testCaseName = "sql_AlterScim_Unset"
	case_SecurityIntegrations_sql_AlterScim_SetTags                                                                                                testCaseName = "sql_AlterScim_SetTags"
	case_SecurityIntegrations_sql_AlterScim_UnsetTags                                                                                              testCaseName = "sql_AlterScim_UnsetTags"
	case_SecurityIntegrations_validation_Drop_name_ValidIdentifier                                                                                 testCaseName = "validation_Drop_name_ValidIdentifier"
	case_SecurityIntegrations_sql_Drop_basic                                                                                                       testCaseName = "sql_Drop_basic"
	case_SecurityIntegrations_sql_Drop_all                                                                                                         testCaseName = "sql_Drop_all"
	case_SecurityIntegrations_validation_Describe_name_ValidIdentifier                                                                             testCaseName = "validation_Describe_name_ValidIdentifier"
	case_SecurityIntegrations_sql_Describe_basic                                                                                                   testCaseName = "sql_Describe_basic"
	case_SecurityIntegrations_sql_Show_basic                                                                                                       testCaseName = "sql_Show_basic"
	case_SecurityIntegrations_sql_Show_all                                                                                                         testCaseName = "sql_Show_all"
	case_SecurityIntegrations_sql_Show_Like                                                                                                        testCaseName = "sql_Show_Like"
)

type SecurityIntegrationsTestsContext struct {
	CreateApiAuthenticationWithClientCredentialsFlow      *sdkTestCtx[*CreateApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions]
	CreateApiAuthenticationWithAuthorizationCodeGrantFlow *sdkTestCtx[*CreateApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions]
	CreateApiAuthenticationWithJwtBearerFlow              *sdkTestCtx[*CreateApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions]
	CreateExternalOauth                                   *sdkTestCtx[*CreateExternalOauthSecurityIntegrationOptions]
	CreateOauthForPartnerApplications                     *sdkTestCtx[*CreateOauthForPartnerApplicationsSecurityIntegrationOptions]
	CreateOauthForCustomClients                           *sdkTestCtx[*CreateOauthForCustomClientsSecurityIntegrationOptions]
	CreateSaml2                                           *sdkTestCtx[*CreateSaml2SecurityIntegrationOptions]
	CreateScim                                            *sdkTestCtx[*CreateScimSecurityIntegrationOptions]
	AlterApiAuthenticationWithClientCredentialsFlow       *sdkTestCtx[*AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions]
	AlterApiAuthenticationWithAuthorizationCodeGrantFlow  *sdkTestCtx[*AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions]
	AlterApiAuthenticationWithJwtBearerFlow               *sdkTestCtx[*AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions]
	AlterExternalOauth                                    *sdkTestCtx[*AlterExternalOauthSecurityIntegrationOptions]
	AlterOauthForPartnerApplications                      *sdkTestCtx[*AlterOauthForPartnerApplicationsSecurityIntegrationOptions]
	AlterOauthForCustomClients                            *sdkTestCtx[*AlterOauthForCustomClientsSecurityIntegrationOptions]
	AlterSaml2                                            *sdkTestCtx[*AlterSaml2SecurityIntegrationOptions]
	AlterScim                                             *sdkTestCtx[*AlterScimSecurityIntegrationOptions]
	Drop                                                  *sdkTestCtx[*DropSecurityIntegrationOptions]
	Describe                                              *sdkTestCtx[*DescribeSecurityIntegrationOptions]
	Show                                                  *sdkTestCtx[*ShowSecurityIntegrationOptions]
}

var securityIntegrationsTests = SecurityIntegrationsTestsContext{
	CreateApiAuthenticationWithClientCredentialsFlow: newSdkTestCtx[*CreateApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions](
		"SecurityIntegrations", "CreateApiAuthenticationWithClientCredentialsFlow",
	).
		withDefaultOpts(func() *CreateApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions {
			return &CreateApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateApiAuthenticationWithClientCredentialsFlow_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*CreateApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateApiAuthenticationWithClientCredentialsFlow_opts_ConflictingFields,
				ExpectedErr: errOneOf("CreateApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions]{
				Name:           case_SecurityIntegrations_sql_CreateApiAuthenticationWithClientCredentialsFlow_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_CreateApiAuthenticationWithClientCredentialsFlow_all,
			},
		),
	CreateApiAuthenticationWithAuthorizationCodeGrantFlow: newSdkTestCtx[*CreateApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions](
		"SecurityIntegrations", "CreateApiAuthenticationWithAuthorizationCodeGrantFlow",
	).
		withDefaultOpts(func() *CreateApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions {
			return &CreateApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateApiAuthenticationWithAuthorizationCodeGrantFlow_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*CreateApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateApiAuthenticationWithAuthorizationCodeGrantFlow_opts_ConflictingFields,
				ExpectedErr: errOneOf("CreateApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions]{
				Name:           case_SecurityIntegrations_sql_CreateApiAuthenticationWithAuthorizationCodeGrantFlow_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_CreateApiAuthenticationWithAuthorizationCodeGrantFlow_all,
			},
		),
	CreateApiAuthenticationWithJwtBearerFlow: newSdkTestCtx[*CreateApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions](
		"SecurityIntegrations", "CreateApiAuthenticationWithJwtBearerFlow",
	).
		withDefaultOpts(func() *CreateApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions {
			return &CreateApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateApiAuthenticationWithJwtBearerFlow_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*CreateApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateApiAuthenticationWithJwtBearerFlow_opts_ConflictingFields,
				ExpectedErr: errOneOf("CreateApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions]{
				Name:           case_SecurityIntegrations_sql_CreateApiAuthenticationWithJwtBearerFlow_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_CreateApiAuthenticationWithJwtBearerFlow_all,
			},
		),
	CreateExternalOauth: newSdkTestCtx[*CreateExternalOauthSecurityIntegrationOptions](
		"SecurityIntegrations", "CreateExternalOauth",
	).
		withDefaultOpts(func() *CreateExternalOauthSecurityIntegrationOptions {
			return &CreateExternalOauthSecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateExternalOauthSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateExternalOauth_opts_ConflictingFields_ExternalOauthBlockedRolesList_ExternalOauthAllowedRolesList,
				ExpectedErr: errOneOf("CreateExternalOauthSecurityIntegrationOptions", "ExternalOauthBlockedRolesList", "ExternalOauthAllowedRolesList"),
				DefaultModify: func(opts *CreateExternalOauthSecurityIntegrationOptions) {
					opts.ExternalOauthBlockedRolesList = &BlockedRolesList{}
					opts.ExternalOauthAllowedRolesList = &AllowedRolesList{}
				},
			},
			validationCase[*CreateExternalOauthSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateExternalOauth_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("CreateExternalOauthSecurityIntegrationOptions", "ExternalOauthJwsKeysUrl", "ExternalOauthRsaPublicKey"),
				DefaultModify: func(opts *CreateExternalOauthSecurityIntegrationOptions) {
					opts.ExternalOauthJwsKeysUrl = nil
					opts.ExternalOauthRsaPublicKey = nil
				},
			},
			validationCase[*CreateExternalOauthSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateExternalOauth_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("CreateExternalOauthSecurityIntegrationOptions", "ExternalOauthJwsKeysUrl", "ExternalOauthRsaPublicKey"),
			},
			validationCase[*CreateExternalOauthSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateExternalOauth_opts_ConflictingFields_ExternalOauthJwsKeysUrl_ExternalOauthRsaPublicKey2,
				ExpectedErr: errOneOf("CreateExternalOauthSecurityIntegrationOptions", "ExternalOauthJwsKeysUrl", "ExternalOauthRsaPublicKey2"),
			},
			validationCase[*CreateExternalOauthSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateExternalOauth_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateExternalOauthSecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*CreateExternalOauthSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateExternalOauth_opts_ConflictingFields_OrReplace_IfNotExists,
				ExpectedErr: errOneOf("CreateExternalOauthSecurityIntegrationOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateExternalOauthSecurityIntegrationOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateExternalOauthSecurityIntegrationOptions]{
				Name:           case_SecurityIntegrations_sql_CreateExternalOauth_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateExternalOauthSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_CreateExternalOauth_all,
			},
		),
	CreateOauthForPartnerApplications: newSdkTestCtx[*CreateOauthForPartnerApplicationsSecurityIntegrationOptions](
		"SecurityIntegrations", "CreateOauthForPartnerApplications",
	).
		withDefaultOpts(func() *CreateOauthForPartnerApplicationsSecurityIntegrationOptions {
			return &CreateOauthForPartnerApplicationsSecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateOauthForPartnerApplicationsSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateOauthForPartnerApplications_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateOauthForPartnerApplicationsSecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*CreateOauthForPartnerApplicationsSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateOauthForPartnerApplications_opts_ConflictingFields,
				ExpectedErr: errOneOf("CreateOauthForPartnerApplicationsSecurityIntegrationOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateOauthForPartnerApplicationsSecurityIntegrationOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateOauthForPartnerApplicationsSecurityIntegrationOptions]{
				Name:           case_SecurityIntegrations_sql_CreateOauthForPartnerApplications_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateOauthForPartnerApplicationsSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_CreateOauthForPartnerApplications_all,
			},
		),
	CreateOauthForCustomClients: newSdkTestCtx[*CreateOauthForCustomClientsSecurityIntegrationOptions](
		"SecurityIntegrations", "CreateOauthForCustomClients",
	).
		withDefaultOpts(func() *CreateOauthForCustomClientsSecurityIntegrationOptions {
			return &CreateOauthForCustomClientsSecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateOauthForCustomClientsSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateOauthForCustomClients_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateOauthForCustomClientsSecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*CreateOauthForCustomClientsSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateOauthForCustomClients_opts_ConflictingFields,
				ExpectedErr: errOneOf("CreateOauthForCustomClientsSecurityIntegrationOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateOauthForCustomClientsSecurityIntegrationOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateOauthForCustomClientsSecurityIntegrationOptions]{
				Name:           case_SecurityIntegrations_sql_CreateOauthForCustomClients_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateOauthForCustomClientsSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_CreateOauthForCustomClients_all,
			},
		),
	CreateSaml2: newSdkTestCtx[*CreateSaml2SecurityIntegrationOptions](
		"SecurityIntegrations", "CreateSaml2",
	).
		withDefaultOpts(func() *CreateSaml2SecurityIntegrationOptions {
			return &CreateSaml2SecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateSaml2SecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateSaml2_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateSaml2SecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*CreateSaml2SecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateSaml2_opts_ConflictingFields,
				ExpectedErr: errOneOf("CreateSaml2SecurityIntegrationOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateSaml2SecurityIntegrationOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateSaml2SecurityIntegrationOptions]{
				Name:           case_SecurityIntegrations_sql_CreateSaml2_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateSaml2SecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_CreateSaml2_all,
			},
		),
	CreateScim: newSdkTestCtx[*CreateScimSecurityIntegrationOptions](
		"SecurityIntegrations", "CreateScim",
	).
		withDefaultOpts(func() *CreateScimSecurityIntegrationOptions {
			return &CreateScimSecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateScimSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateScim_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateScimSecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*CreateScimSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_CreateScim_opts_ConflictingFields,
				ExpectedErr: errOneOf("CreateScimSecurityIntegrationOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateScimSecurityIntegrationOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateScimSecurityIntegrationOptions]{
				Name:           case_SecurityIntegrations_sql_CreateScim_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateScimSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_CreateScim_all,
			},
		),
	AlterApiAuthenticationWithClientCredentialsFlow: newSdkTestCtx[*AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions](
		"SecurityIntegrations", "AlterApiAuthenticationWithClientCredentialsFlow",
	).
		withDefaultOpts(func() *AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions {
			return &AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterApiAuthenticationWithClientCredentialsFlow_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterApiAuthenticationWithClientCredentialsFlow_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions", "Set", "Unset", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions) {
					opts.Set = nil
					opts.Unset = nil
					opts.SetTags = nil
					opts.UnsetTags = nil
				},
			},
			validationCase[*AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterApiAuthenticationWithClientCredentialsFlow_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions", "Set", "Unset", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions) {
					opts.Set = &ApiAuthenticationWithClientCredentialsFlowIntegrationSet{}
					opts.Unset = &ApiAuthenticationWithClientCredentialsFlowIntegrationUnset{}
				},
			},
			validationCase[*AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterApiAuthenticationWithClientCredentialsFlow_opts_Set_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions.Set", "Enabled", "OauthTokenEndpoint", "OauthClientAuthMethod", "OauthClientId", "OauthClientSecret", "OauthGrantClientCredentials", "OauthAccessTokenValidity", "OauthRefreshTokenValidity", "OauthAllowedScopes", "Comment"),
				DefaultModify: func(opts *AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions) {
					opts.Set = &ApiAuthenticationWithClientCredentialsFlowIntegrationSet{}
					opts.Set.Enabled = nil
					opts.Set.OauthTokenEndpoint = nil
					opts.Set.OauthClientAuthMethod = nil
					opts.Set.OauthClientId = nil
					opts.Set.OauthClientSecret = nil
					opts.Set.OauthGrantClientCredentials = nil
					opts.Set.OauthAccessTokenValidity = nil
					opts.Set.OauthRefreshTokenValidity = nil
					opts.Set.OauthAllowedScopes = nil
					opts.Set.Comment = nil
				},
			},
			validationCase[*AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterApiAuthenticationWithClientCredentialsFlow_opts_Unset_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions.Unset", "Enabled", "Comment"),
				DefaultModify: func(opts *AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions) {
					opts.Unset = &ApiAuthenticationWithClientCredentialsFlowIntegrationUnset{}
					opts.Unset.Enabled = nil
					opts.Unset.Comment = nil
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterApiAuthenticationWithClientCredentialsFlow_Set,
			},
			sqlCase[*AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterApiAuthenticationWithClientCredentialsFlow_Unset,
			},
			sqlCase[*AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterApiAuthenticationWithClientCredentialsFlow_SetTags,
			},
			sqlCase[*AlterApiAuthenticationWithClientCredentialsFlowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterApiAuthenticationWithClientCredentialsFlow_UnsetTags,
			},
		),
	AlterApiAuthenticationWithAuthorizationCodeGrantFlow: newSdkTestCtx[*AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions](
		"SecurityIntegrations", "AlterApiAuthenticationWithAuthorizationCodeGrantFlow",
	).
		withDefaultOpts(func() *AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions {
			return &AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions", "Set", "Unset", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions) {
					opts.Set = nil
					opts.Unset = nil
					opts.SetTags = nil
					opts.UnsetTags = nil
				},
			},
			validationCase[*AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions", "Set", "Unset", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions) {
					opts.Set = &ApiAuthenticationWithAuthorizationCodeGrantFlowIntegrationSet{}
					opts.Unset = &ApiAuthenticationWithAuthorizationCodeGrantFlowIntegrationUnset{}
				},
			},
			validationCase[*AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_opts_Set_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions.Set", "Enabled", "OauthAuthorizationEndpoint", "OauthTokenEndpoint", "OauthClientAuthMethod", "OauthClientId", "OauthClientSecret", "OauthGrantAuthorizationCode", "OauthAccessTokenValidity", "OauthRefreshTokenValidity", "OauthAllowedScopes", "Comment"),
				DefaultModify: func(opts *AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions) {
					opts.Set = &ApiAuthenticationWithAuthorizationCodeGrantFlowIntegrationSet{}
					opts.Set.Enabled = nil
					opts.Set.OauthAuthorizationEndpoint = nil
					opts.Set.OauthTokenEndpoint = nil
					opts.Set.OauthClientAuthMethod = nil
					opts.Set.OauthClientId = nil
					opts.Set.OauthClientSecret = nil
					opts.Set.OauthGrantAuthorizationCode = nil
					opts.Set.OauthAccessTokenValidity = nil
					opts.Set.OauthRefreshTokenValidity = nil
					opts.Set.OauthAllowedScopes = nil
					opts.Set.Comment = nil
				},
			},
			validationCase[*AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_opts_Unset_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions.Unset", "Enabled", "Comment"),
				DefaultModify: func(opts *AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions) {
					opts.Unset = &ApiAuthenticationWithAuthorizationCodeGrantFlowIntegrationUnset{}
					opts.Unset.Enabled = nil
					opts.Unset.Comment = nil
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_Set,
			},
			sqlCase[*AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_Unset,
			},
			sqlCase[*AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_SetTags,
			},
			sqlCase[*AlterApiAuthenticationWithAuthorizationCodeGrantFlowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterApiAuthenticationWithAuthorizationCodeGrantFlow_UnsetTags,
			},
		),
	AlterApiAuthenticationWithJwtBearerFlow: newSdkTestCtx[*AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions](
		"SecurityIntegrations", "AlterApiAuthenticationWithJwtBearerFlow",
	).
		withDefaultOpts(func() *AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions {
			return &AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterApiAuthenticationWithJwtBearerFlow_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterApiAuthenticationWithJwtBearerFlow_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions", "Set", "Unset", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions) {
					opts.Set = nil
					opts.Unset = nil
					opts.SetTags = nil
					opts.UnsetTags = nil
				},
			},
			validationCase[*AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterApiAuthenticationWithJwtBearerFlow_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions", "Set", "Unset", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions) {
					opts.Set = &ApiAuthenticationWithJwtBearerFlowIntegrationSet{}
					opts.Unset = &ApiAuthenticationWithJwtBearerFlowIntegrationUnset{}
				},
			},
			validationCase[*AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterApiAuthenticationWithJwtBearerFlow_opts_Set_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions.Set", "Enabled", "OauthAuthorizationEndpoint", "OauthTokenEndpoint", "OauthClientAuthMethod", "OauthClientId", "OauthClientSecret", "OauthGrantJwtBearer", "OauthAccessTokenValidity", "OauthRefreshTokenValidity", "Comment"),
				DefaultModify: func(opts *AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions) {
					opts.Set = &ApiAuthenticationWithJwtBearerFlowIntegrationSet{}
					opts.Set.Enabled = nil
					opts.Set.OauthAuthorizationEndpoint = nil
					opts.Set.OauthTokenEndpoint = nil
					opts.Set.OauthClientAuthMethod = nil
					opts.Set.OauthClientId = nil
					opts.Set.OauthClientSecret = nil
					opts.Set.OauthGrantJwtBearer = nil
					opts.Set.OauthAccessTokenValidity = nil
					opts.Set.OauthRefreshTokenValidity = nil
					opts.Set.Comment = nil
				},
			},
			validationCase[*AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterApiAuthenticationWithJwtBearerFlow_opts_Unset_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions.Unset", "Enabled", "Comment"),
				DefaultModify: func(opts *AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions) {
					opts.Unset = &ApiAuthenticationWithJwtBearerFlowIntegrationUnset{}
					opts.Unset.Enabled = nil
					opts.Unset.Comment = nil
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterApiAuthenticationWithJwtBearerFlow_Set,
			},
			sqlCase[*AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterApiAuthenticationWithJwtBearerFlow_Unset,
			},
			sqlCase[*AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterApiAuthenticationWithJwtBearerFlow_SetTags,
			},
			sqlCase[*AlterApiAuthenticationWithJwtBearerFlowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterApiAuthenticationWithJwtBearerFlow_UnsetTags,
			},
		),
	AlterExternalOauth: newSdkTestCtx[*AlterExternalOauthSecurityIntegrationOptions](
		"SecurityIntegrations", "AlterExternalOauth",
	).
		withDefaultOpts(func() *AlterExternalOauthSecurityIntegrationOptions {
			return &AlterExternalOauthSecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterExternalOauthSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterExternalOauth_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterExternalOauthSecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*AlterExternalOauthSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterExternalOauth_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterExternalOauthSecurityIntegrationOptions", "Set", "Unset", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterExternalOauthSecurityIntegrationOptions) {
					opts.Set = nil
					opts.Unset = nil
					opts.SetTags = nil
					opts.UnsetTags = nil
				},
			},
			validationCase[*AlterExternalOauthSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterExternalOauth_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterExternalOauthSecurityIntegrationOptions", "Set", "Unset", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterExternalOauthSecurityIntegrationOptions) {
					opts.Set = &ExternalOauthIntegrationSet{}
					opts.Unset = &ExternalOauthIntegrationUnset{}
				},
			},
			validationCase[*AlterExternalOauthSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterExternalOauth_opts_Set_ConflictingFields_ExternalOauthBlockedRolesList_ExternalOauthAllowedRolesList,
				ExpectedErr: errOneOf("AlterExternalOauthSecurityIntegrationOptions.Set", "ExternalOauthBlockedRolesList", "ExternalOauthAllowedRolesList"),
				DefaultModify: func(opts *AlterExternalOauthSecurityIntegrationOptions) {
					opts.Set = &ExternalOauthIntegrationSet{}
					opts.Set.ExternalOauthBlockedRolesList = &BlockedRolesList{}
					opts.Set.ExternalOauthAllowedRolesList = &AllowedRolesList{}
				},
			},
			validationCase[*AlterExternalOauthSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterExternalOauth_opts_Set_ConflictingFields_ExternalOauthJwsKeysUrl_ExternalOauthRsaPublicKey,
				ExpectedErr: errOneOf("AlterExternalOauthSecurityIntegrationOptions.Set", "ExternalOauthJwsKeysUrl", "ExternalOauthRsaPublicKey"),
			},
			validationCase[*AlterExternalOauthSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterExternalOauth_opts_Set_ConflictingFields_ExternalOauthJwsKeysUrl_ExternalOauthRsaPublicKey2,
				ExpectedErr: errOneOf("AlterExternalOauthSecurityIntegrationOptions.Set", "ExternalOauthJwsKeysUrl", "ExternalOauthRsaPublicKey2"),
			},
			validationCase[*AlterExternalOauthSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterExternalOauth_opts_Set_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterExternalOauthSecurityIntegrationOptions.Set", "Enabled", "ExternalOauthType", "ExternalOauthIssuer", "ExternalOauthTokenUserMappingClaim", "ExternalOauthSnowflakeUserMappingAttribute", "ExternalOauthJwsKeysUrl", "ExternalOauthBlockedRolesList", "ExternalOauthAllowedRolesList", "ExternalOauthRsaPublicKey", "ExternalOauthRsaPublicKey2", "ExternalOauthAudienceList", "ExternalOauthAnyRoleMode", "ExternalOauthScopeDelimiter", "ExternalOauthScopeMappingAttribute", "Comment"),
				DefaultModify: func(opts *AlterExternalOauthSecurityIntegrationOptions) {
					opts.Set = &ExternalOauthIntegrationSet{}
					opts.Set.Enabled = nil
					opts.Set.ExternalOauthType = nil
					opts.Set.ExternalOauthIssuer = nil
					opts.Set.ExternalOauthTokenUserMappingClaim = nil
					opts.Set.ExternalOauthSnowflakeUserMappingAttribute = nil
					opts.Set.ExternalOauthJwsKeysUrl = nil
					opts.Set.ExternalOauthBlockedRolesList = nil
					opts.Set.ExternalOauthAllowedRolesList = nil
					opts.Set.ExternalOauthRsaPublicKey = nil
					opts.Set.ExternalOauthRsaPublicKey2 = nil
					opts.Set.ExternalOauthAudienceList = nil
					opts.Set.ExternalOauthAnyRoleMode = nil
					opts.Set.ExternalOauthScopeDelimiter = nil
					opts.Set.ExternalOauthScopeMappingAttribute = nil
					opts.Set.Comment = nil
				},
			},
			validationCase[*AlterExternalOauthSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterExternalOauth_opts_Unset_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterExternalOauthSecurityIntegrationOptions.Unset", "Enabled", "ExternalOauthAudienceList"),
				DefaultModify: func(opts *AlterExternalOauthSecurityIntegrationOptions) {
					opts.Unset = &ExternalOauthIntegrationUnset{}
					opts.Unset.Enabled = nil
					opts.Unset.ExternalOauthAudienceList = nil
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterExternalOauthSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterExternalOauth_Set,
			},
			sqlCase[*AlterExternalOauthSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterExternalOauth_Unset,
			},
			sqlCase[*AlterExternalOauthSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterExternalOauth_SetTags,
			},
			sqlCase[*AlterExternalOauthSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterExternalOauth_UnsetTags,
			},
		),
	AlterOauthForPartnerApplications: newSdkTestCtx[*AlterOauthForPartnerApplicationsSecurityIntegrationOptions](
		"SecurityIntegrations", "AlterOauthForPartnerApplications",
	).
		withDefaultOpts(func() *AlterOauthForPartnerApplicationsSecurityIntegrationOptions {
			return &AlterOauthForPartnerApplicationsSecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterOauthForPartnerApplicationsSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterOauthForPartnerApplications_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterOauthForPartnerApplicationsSecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*AlterOauthForPartnerApplicationsSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterOauthForPartnerApplications_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterOauthForPartnerApplicationsSecurityIntegrationOptions", "Set", "Unset", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterOauthForPartnerApplicationsSecurityIntegrationOptions) {
					opts.Set = nil
					opts.Unset = nil
					opts.SetTags = nil
					opts.UnsetTags = nil
				},
			},
			validationCase[*AlterOauthForPartnerApplicationsSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterOauthForPartnerApplications_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterOauthForPartnerApplicationsSecurityIntegrationOptions", "Set", "Unset", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterOauthForPartnerApplicationsSecurityIntegrationOptions) {
					opts.Set = &OauthForPartnerApplicationsIntegrationSet{}
					opts.Unset = &OauthForPartnerApplicationsIntegrationUnset{}
				},
			},
			validationCase[*AlterOauthForPartnerApplicationsSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterOauthForPartnerApplications_opts_Set_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterOauthForPartnerApplicationsSecurityIntegrationOptions.Set", "Enabled", "OauthIssueRefreshTokens", "OauthRedirectUri", "OauthRefreshTokenValidity", "OauthUseSecondaryRoles", "AllowedRolesList", "BlockedRolesList", "Comment"),
				DefaultModify: func(opts *AlterOauthForPartnerApplicationsSecurityIntegrationOptions) {
					opts.Set = &OauthForPartnerApplicationsIntegrationSet{}
					opts.Set.Enabled = nil
					opts.Set.OauthIssueRefreshTokens = nil
					opts.Set.OauthRedirectUri = nil
					opts.Set.OauthRefreshTokenValidity = nil
					opts.Set.OauthUseSecondaryRoles = nil
					opts.Set.AllowedRolesList = nil
					opts.Set.BlockedRolesList = nil
					opts.Set.Comment = nil
				},
			},
			validationCase[*AlterOauthForPartnerApplicationsSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterOauthForPartnerApplications_opts_Unset_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterOauthForPartnerApplicationsSecurityIntegrationOptions.Unset", "Enabled", "OauthUseSecondaryRoles"),
				DefaultModify: func(opts *AlterOauthForPartnerApplicationsSecurityIntegrationOptions) {
					opts.Unset = &OauthForPartnerApplicationsIntegrationUnset{}
					opts.Unset.Enabled = nil
					opts.Unset.OauthUseSecondaryRoles = nil
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterOauthForPartnerApplicationsSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterOauthForPartnerApplications_Set,
			},
			sqlCase[*AlterOauthForPartnerApplicationsSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterOauthForPartnerApplications_Unset,
			},
			sqlCase[*AlterOauthForPartnerApplicationsSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterOauthForPartnerApplications_SetTags,
			},
			sqlCase[*AlterOauthForPartnerApplicationsSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterOauthForPartnerApplications_UnsetTags,
			},
		),
	AlterOauthForCustomClients: newSdkTestCtx[*AlterOauthForCustomClientsSecurityIntegrationOptions](
		"SecurityIntegrations", "AlterOauthForCustomClients",
	).
		withDefaultOpts(func() *AlterOauthForCustomClientsSecurityIntegrationOptions {
			return &AlterOauthForCustomClientsSecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterOauthForCustomClientsSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterOauthForCustomClients_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterOauthForCustomClientsSecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*AlterOauthForCustomClientsSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterOauthForCustomClients_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterOauthForCustomClientsSecurityIntegrationOptions", "Set", "Unset", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterOauthForCustomClientsSecurityIntegrationOptions) {
					opts.Set = nil
					opts.Unset = nil
					opts.SetTags = nil
					opts.UnsetTags = nil
				},
			},
			validationCase[*AlterOauthForCustomClientsSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterOauthForCustomClients_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterOauthForCustomClientsSecurityIntegrationOptions", "Set", "Unset", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterOauthForCustomClientsSecurityIntegrationOptions) {
					opts.Set = &OauthForCustomClientsIntegrationSet{}
					opts.Unset = &OauthForCustomClientsIntegrationUnset{}
				},
			},
			validationCase[*AlterOauthForCustomClientsSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterOauthForCustomClients_opts_Set_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterOauthForCustomClientsSecurityIntegrationOptions.Set", "Enabled", "OauthRedirectUri", "OauthAllowNonTlsRedirectUri", "OauthEnforcePkce", "PreAuthorizedRolesList", "AllowedRolesList", "BlockedRolesList", "OauthIssueRefreshTokens", "OauthRefreshTokenValidity", "OauthUseSecondaryRoles", "NetworkPolicy", "OauthClientRsaPublicKey", "OauthClientRsaPublicKey2", "Comment"),
				DefaultModify: func(opts *AlterOauthForCustomClientsSecurityIntegrationOptions) {
					opts.Set = &OauthForCustomClientsIntegrationSet{}
					opts.Set.Enabled = nil
					opts.Set.OauthRedirectUri = nil
					opts.Set.OauthAllowNonTlsRedirectUri = nil
					opts.Set.OauthEnforcePkce = nil
					opts.Set.PreAuthorizedRolesList = nil
					opts.Set.AllowedRolesList = nil
					opts.Set.BlockedRolesList = nil
					opts.Set.OauthIssueRefreshTokens = nil
					opts.Set.OauthRefreshTokenValidity = nil
					opts.Set.OauthUseSecondaryRoles = nil
					opts.Set.NetworkPolicy = nil
					opts.Set.OauthClientRsaPublicKey = nil
					opts.Set.OauthClientRsaPublicKey2 = nil
					opts.Set.Comment = nil
				},
			},
			validationCase[*AlterOauthForCustomClientsSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterOauthForCustomClients_opts_Unset_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterOauthForCustomClientsSecurityIntegrationOptions.Unset", "Enabled", "NetworkPolicy", "OauthUseSecondaryRoles", "OauthClientRsaPublicKey", "OauthClientRsaPublicKey2"),
				DefaultModify: func(opts *AlterOauthForCustomClientsSecurityIntegrationOptions) {
					opts.Unset = &OauthForCustomClientsIntegrationUnset{}
					opts.Unset.Enabled = nil
					opts.Unset.NetworkPolicy = nil
					opts.Unset.OauthUseSecondaryRoles = nil
					opts.Unset.OauthClientRsaPublicKey = nil
					opts.Unset.OauthClientRsaPublicKey2 = nil
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterOauthForCustomClientsSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterOauthForCustomClients_Set,
			},
			sqlCase[*AlterOauthForCustomClientsSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterOauthForCustomClients_Unset,
			},
			sqlCase[*AlterOauthForCustomClientsSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterOauthForCustomClients_SetTags,
			},
			sqlCase[*AlterOauthForCustomClientsSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterOauthForCustomClients_UnsetTags,
			},
		),
	AlterSaml2: newSdkTestCtx[*AlterSaml2SecurityIntegrationOptions](
		"SecurityIntegrations", "AlterSaml2",
	).
		withDefaultOpts(func() *AlterSaml2SecurityIntegrationOptions {
			return &AlterSaml2SecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterSaml2SecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterSaml2_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterSaml2SecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*AlterSaml2SecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterSaml2_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterSaml2SecurityIntegrationOptions", "Set", "Unset", "RefreshSaml2SnowflakePrivateKey", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterSaml2SecurityIntegrationOptions) {
					opts.Set = nil
					opts.Unset = nil
					opts.RefreshSaml2SnowflakePrivateKey = nil
					opts.SetTags = nil
					opts.UnsetTags = nil
				},
			},
			validationCase[*AlterSaml2SecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterSaml2_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterSaml2SecurityIntegrationOptions", "Set", "Unset", "RefreshSaml2SnowflakePrivateKey", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterSaml2SecurityIntegrationOptions) {
					opts.Set = &Saml2IntegrationSet{}
					opts.Unset = &Saml2IntegrationUnset{}
				},
			},
			validationCase[*AlterSaml2SecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterSaml2_opts_Set_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterSaml2SecurityIntegrationOptions.Set", "Enabled", "Saml2Issuer", "Saml2SsoUrl", "Saml2Provider", "Saml2X509Cert", "AllowedUserDomains", "AllowedEmailPatterns", "Saml2SpInitiatedLoginPageLabel", "Saml2EnableSpInitiated", "Saml2SnowflakeX509Cert", "Saml2SignRequest", "Saml2RequestedNameidFormat", "Saml2PostLogoutRedirectUrl", "Saml2ForceAuthn", "Saml2SnowflakeIssuerUrl", "Saml2SnowflakeAcsUrl", "Comment"),
				DefaultModify: func(opts *AlterSaml2SecurityIntegrationOptions) {
					opts.Set = &Saml2IntegrationSet{}
					opts.Set.Enabled = nil
					opts.Set.Saml2Issuer = nil
					opts.Set.Saml2SsoUrl = nil
					opts.Set.Saml2Provider = nil
					opts.Set.Saml2X509Cert = nil
					opts.Set.AllowedUserDomains = nil
					opts.Set.AllowedEmailPatterns = nil
					opts.Set.Saml2SpInitiatedLoginPageLabel = nil
					opts.Set.Saml2EnableSpInitiated = nil
					opts.Set.Saml2SnowflakeX509Cert = nil
					opts.Set.Saml2SignRequest = nil
					opts.Set.Saml2RequestedNameidFormat = nil
					opts.Set.Saml2PostLogoutRedirectUrl = nil
					opts.Set.Saml2ForceAuthn = nil
					opts.Set.Saml2SnowflakeIssuerUrl = nil
					opts.Set.Saml2SnowflakeAcsUrl = nil
					opts.Set.Comment = nil
				},
			},
			validationCase[*AlterSaml2SecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterSaml2_opts_Unset_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterSaml2SecurityIntegrationOptions.Unset", "Saml2ForceAuthn", "Saml2RequestedNameidFormat", "Saml2PostLogoutRedirectUrl", "Comment"),
				DefaultModify: func(opts *AlterSaml2SecurityIntegrationOptions) {
					opts.Unset = &Saml2IntegrationUnset{}
					opts.Unset.Saml2ForceAuthn = nil
					opts.Unset.Saml2RequestedNameidFormat = nil
					opts.Unset.Saml2PostLogoutRedirectUrl = nil
					opts.Unset.Comment = nil
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterSaml2SecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterSaml2_Set,
			},
			sqlCase[*AlterSaml2SecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterSaml2_Unset,
			},
			sqlCase[*AlterSaml2SecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterSaml2_RefreshSaml2SnowflakePrivateKey,
			},
			sqlCase[*AlterSaml2SecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterSaml2_SetTags,
			},
			sqlCase[*AlterSaml2SecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterSaml2_UnsetTags,
			},
		),
	AlterScim: newSdkTestCtx[*AlterScimSecurityIntegrationOptions](
		"SecurityIntegrations", "AlterScim",
	).
		withDefaultOpts(func() *AlterScimSecurityIntegrationOptions {
			return &AlterScimSecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterScimSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterScim_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterScimSecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*AlterScimSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterScim_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterScimSecurityIntegrationOptions", "Set", "Unset", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterScimSecurityIntegrationOptions) {
					opts.Set = nil
					opts.Unset = nil
					opts.SetTags = nil
					opts.UnsetTags = nil
				},
			},
			validationCase[*AlterScimSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterScim_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterScimSecurityIntegrationOptions", "Set", "Unset", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterScimSecurityIntegrationOptions) {
					opts.Set = &ScimIntegrationSet{}
					opts.Unset = &ScimIntegrationUnset{}
				},
			},
			validationCase[*AlterScimSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterScim_opts_Set_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterScimSecurityIntegrationOptions.Set", "Enabled", "NetworkPolicy", "SyncPassword", "Comment"),
				DefaultModify: func(opts *AlterScimSecurityIntegrationOptions) {
					opts.Set = &ScimIntegrationSet{}
					opts.Set.Enabled = nil
					opts.Set.NetworkPolicy = nil
					opts.Set.SyncPassword = nil
					opts.Set.Comment = nil
				},
			},
			validationCase[*AlterScimSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_AlterScim_opts_Unset_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterScimSecurityIntegrationOptions.Unset", "Enabled", "NetworkPolicy", "SyncPassword"),
				DefaultModify: func(opts *AlterScimSecurityIntegrationOptions) {
					opts.Unset = &ScimIntegrationUnset{}
					opts.Unset.Enabled = nil
					opts.Unset.NetworkPolicy = nil
					opts.Unset.SyncPassword = nil
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterScimSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterScim_Set,
			},
			sqlCase[*AlterScimSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterScim_Unset,
			},
			sqlCase[*AlterScimSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterScim_SetTags,
			},
			sqlCase[*AlterScimSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_AlterScim_UnsetTags,
			},
		),
	Drop: newSdkTestCtx[*DropSecurityIntegrationOptions](
		"SecurityIntegrations", "Drop",
	).
		withDefaultOpts(func() *DropSecurityIntegrationOptions {
			return &DropSecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*DropSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_Drop_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *DropSecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
		).
		withSqlCases(
			sqlCase[*DropSecurityIntegrationOptions]{
				Name:           case_SecurityIntegrations_sql_Drop_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*DropSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_Drop_all,
			},
		),
	Describe: newSdkTestCtx[*DescribeSecurityIntegrationOptions](
		"SecurityIntegrations", "Describe",
	).
		withDefaultOpts(func() *DescribeSecurityIntegrationOptions {
			return &DescribeSecurityIntegrationOptions{
				name: securityIntegrationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*DescribeSecurityIntegrationOptions]{
				Name:        case_SecurityIntegrations_validation_Describe_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *DescribeSecurityIntegrationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
		).
		withSqlCases(
			sqlCase[*DescribeSecurityIntegrationOptions]{
				Name:           case_SecurityIntegrations_sql_Describe_basic,
				NoModifyNeeded: true,
			},
		),
	Show: newSdkTestCtx[*ShowSecurityIntegrationOptions](
		"SecurityIntegrations", "Show",
	).
		withDefaultOpts(func() *ShowSecurityIntegrationOptions {
			return &ShowSecurityIntegrationOptions{}
		}).
		withValidationCases().
		withSqlCases(
			sqlCase[*ShowSecurityIntegrationOptions]{
				Name:           case_SecurityIntegrations_sql_Show_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*ShowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_Show_all,
			},
			sqlCase[*ShowSecurityIntegrationOptions]{
				Name: case_SecurityIntegrations_sql_Show_Like,
			},
		),
}

func TestSecurityIntegrations_CreateApiAuthenticationWithClientCredentialsFlow(t *testing.T) {
	securityIntegrationsTests.CreateApiAuthenticationWithClientCredentialsFlow.RunValidationCases(t)
	securityIntegrationsTests.CreateApiAuthenticationWithClientCredentialsFlow.RunSqlCases(t)
}

func TestSecurityIntegrations_CreateApiAuthenticationWithAuthorizationCodeGrantFlow(t *testing.T) {
	securityIntegrationsTests.CreateApiAuthenticationWithAuthorizationCodeGrantFlow.RunValidationCases(t)
	securityIntegrationsTests.CreateApiAuthenticationWithAuthorizationCodeGrantFlow.RunSqlCases(t)
}

func TestSecurityIntegrations_CreateApiAuthenticationWithJwtBearerFlow(t *testing.T) {
	securityIntegrationsTests.CreateApiAuthenticationWithJwtBearerFlow.RunValidationCases(t)
	securityIntegrationsTests.CreateApiAuthenticationWithJwtBearerFlow.RunSqlCases(t)
}

func TestSecurityIntegrations_CreateExternalOauth(t *testing.T) {
	securityIntegrationsTests.CreateExternalOauth.RunValidationCases(t)
	securityIntegrationsTests.CreateExternalOauth.RunSqlCases(t)
}

func TestSecurityIntegrations_CreateOauthForPartnerApplications(t *testing.T) {
	securityIntegrationsTests.CreateOauthForPartnerApplications.RunValidationCases(t)
	securityIntegrationsTests.CreateOauthForPartnerApplications.RunSqlCases(t)
}

func TestSecurityIntegrations_CreateOauthForCustomClients(t *testing.T) {
	securityIntegrationsTests.CreateOauthForCustomClients.RunValidationCases(t)
	securityIntegrationsTests.CreateOauthForCustomClients.RunSqlCases(t)
}

func TestSecurityIntegrations_CreateSaml2(t *testing.T) {
	securityIntegrationsTests.CreateSaml2.RunValidationCases(t)
	securityIntegrationsTests.CreateSaml2.RunSqlCases(t)
}

func TestSecurityIntegrations_CreateScim(t *testing.T) {
	securityIntegrationsTests.CreateScim.RunValidationCases(t)
	securityIntegrationsTests.CreateScim.RunSqlCases(t)
}

func TestSecurityIntegrations_AlterApiAuthenticationWithClientCredentialsFlow(t *testing.T) {
	securityIntegrationsTests.AlterApiAuthenticationWithClientCredentialsFlow.RunValidationCases(t)
	securityIntegrationsTests.AlterApiAuthenticationWithClientCredentialsFlow.RunSqlCases(t)
}

func TestSecurityIntegrations_AlterApiAuthenticationWithAuthorizationCodeGrantFlow(t *testing.T) {
	securityIntegrationsTests.AlterApiAuthenticationWithAuthorizationCodeGrantFlow.RunValidationCases(t)
	securityIntegrationsTests.AlterApiAuthenticationWithAuthorizationCodeGrantFlow.RunSqlCases(t)
}

func TestSecurityIntegrations_AlterApiAuthenticationWithJwtBearerFlow(t *testing.T) {
	securityIntegrationsTests.AlterApiAuthenticationWithJwtBearerFlow.RunValidationCases(t)
	securityIntegrationsTests.AlterApiAuthenticationWithJwtBearerFlow.RunSqlCases(t)
}

func TestSecurityIntegrations_AlterExternalOauth(t *testing.T) {
	securityIntegrationsTests.AlterExternalOauth.RunValidationCases(t)
	securityIntegrationsTests.AlterExternalOauth.RunSqlCases(t)
}

func TestSecurityIntegrations_AlterOauthForPartnerApplications(t *testing.T) {
	securityIntegrationsTests.AlterOauthForPartnerApplications.RunValidationCases(t)
	securityIntegrationsTests.AlterOauthForPartnerApplications.RunSqlCases(t)
}

func TestSecurityIntegrations_AlterOauthForCustomClients(t *testing.T) {
	securityIntegrationsTests.AlterOauthForCustomClients.RunValidationCases(t)
	securityIntegrationsTests.AlterOauthForCustomClients.RunSqlCases(t)
}

func TestSecurityIntegrations_AlterSaml2(t *testing.T) {
	securityIntegrationsTests.AlterSaml2.RunValidationCases(t)
	securityIntegrationsTests.AlterSaml2.RunSqlCases(t)
}

func TestSecurityIntegrations_AlterScim(t *testing.T) {
	securityIntegrationsTests.AlterScim.RunValidationCases(t)
	securityIntegrationsTests.AlterScim.RunSqlCases(t)
}

func TestSecurityIntegrations_Drop(t *testing.T) {
	securityIntegrationsTests.Drop.RunValidationCases(t)
	securityIntegrationsTests.Drop.RunSqlCases(t)
}

func TestSecurityIntegrations_Describe(t *testing.T) {
	securityIntegrationsTests.Describe.RunValidationCases(t)
	securityIntegrationsTests.Describe.RunSqlCases(t)
}

func TestSecurityIntegrations_Show(t *testing.T) {
	securityIntegrationsTests.Show.RunValidationCases(t)
	securityIntegrationsTests.Show.RunSqlCases(t)
}
