// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

import (
	"context"
)

type Sessions interface {
	Alter(ctx context.Context, request *AlterSessionRequest) error
	UseWarehouse(ctx context.Context, request *UseWarehouseSessionRequest) error
	UseDatabase(ctx context.Context, request *UseDatabaseSessionRequest) error
	UseSchema(ctx context.Context, request *UseSchemaSessionRequest) error
	UseRole(ctx context.Context, request *UseRoleSessionRequest) error
	UseSecondaryRoles(ctx context.Context, request *UseSecondaryRolesSessionRequest) error
	ShowParameters(ctx context.Context, opts *ShowParametersOptions) ([]*Parameter, error)
}

// AlterSessionOptions is based on https://docs.snowflake.com/en/sql-reference/sql/alter-session.
type AlterSessionOptions struct {
	alter   bool          `ddl:"static" sql:"ALTER"`
	session bool          `ddl:"static" sql:"SESSION"`
	Set     *SessionSet   `ddl:"keyword" sql:"SET"`
	Unset   *SessionUnset `ddl:"keyword" sql:"UNSET"`
}

type SessionSet struct {
	SessionParameters *SessionParameters `ddl:"list"`
}

type SessionUnset struct {
	SessionParametersUnset *SessionParametersUnset `ddl:"list"`
}

// UseWarehouseSessionOptions is based on https://docs.snowflake.com/en/sql-reference/sql/use-warehouse.
type UseWarehouseSessionOptions struct {
	useWarehouse bool                    `ddl:"static" sql:"USE WAREHOUSE"`
	name         AccountObjectIdentifier `ddl:"identifier"`
}

// UseDatabaseSessionOptions is based on https://docs.snowflake.com/en/sql-reference/sql/use-database.
type UseDatabaseSessionOptions struct {
	useDatabase bool                    `ddl:"static" sql:"USE DATABASE"`
	name        AccountObjectIdentifier `ddl:"identifier"`
}

// UseSchemaSessionOptions is based on https://docs.snowflake.com/en/sql-reference/sql/use-schema.
type UseSchemaSessionOptions struct {
	useSchema bool                     `ddl:"static" sql:"USE SCHEMA"`
	name      DatabaseObjectIdentifier `ddl:"identifier"`
}

// UseRoleSessionOptions is based on https://docs.snowflake.com/en/sql-reference/sql/use-role.
type UseRoleSessionOptions struct {
	useRole bool                    `ddl:"static" sql:"USE ROLE"`
	name    AccountObjectIdentifier `ddl:"identifier"`
}

// UseSecondaryRolesSessionOptions is based on https://docs.snowflake.com/en/sql-reference/sql/use-secondary-roles.
type UseSecondaryRolesSessionOptions struct {
	useSecondaryRoles bool                `ddl:"static" sql:"USE SECONDARY ROLES"`
	Option            SecondaryRoleOption `ddl:"keyword"`
}
