// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

var (
	_ optionsProvider[CreateSnowflakeIntelligenceOptions]     = new(CreateSnowflakeIntelligenceRequest)
	_ optionsProvider[AlterSnowflakeIntelligenceOptions]      = new(AlterSnowflakeIntelligenceRequest)
	_ optionsProvider[DropSnowflakeIntelligenceOptions]       = new(DropSnowflakeIntelligenceRequest)
	_ optionsProvider[ShowSnowflakeIntelligenceOptions]       = new(ShowSnowflakeIntelligenceRequest)
	_ optionsProvider[DescribeSnowflakeIntelligenceOptions]   = new(DescribeSnowflakeIntelligenceRequest)
	_ optionsProvider[ShowAgentsSnowflakeIntelligenceOptions] = new(ShowAgentsSnowflakeIntelligenceRequest)
)

type CreateSnowflakeIntelligenceRequest struct {
	OrReplace   *bool
	IfNotExists *bool
	name        AccountObjectIdentifier // required
}

type AlterSnowflakeIntelligenceRequest struct {
	IfExists  *bool
	name      AccountObjectIdentifier // required
	AddAgent  *SchemaObjectIdentifier
	DropAgent *SchemaObjectIdentifier
}

type DropSnowflakeIntelligenceRequest struct {
	IfExists *bool
	name     AccountObjectIdentifier // required
}

type ShowSnowflakeIntelligenceRequest struct{}

type DescribeSnowflakeIntelligenceRequest struct {
	name AccountObjectIdentifier // required
}

type ShowAgentsSnowflakeIntelligenceRequest struct {
	name AccountObjectIdentifier // required
}
