// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

import (
	"testing"
)

func init() {
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[StorageLifecyclePolicyArchiveTier]{"StorageLifecyclePolicyArchiveTier", AllStorageLifecyclePolicyArchiveTiers, ToStorageLifecyclePolicyArchiveTier})
}

func TestStorageLifecyclePolicies_Create(t *testing.T) {
	id := randomSchemaObjectIdentifier()
	// Minimal valid CreateStorageLifecyclePolicyOptions
	defaultOpts := func() *CreateStorageLifecyclePolicyOptions {
		return &CreateStorageLifecyclePolicyOptions{
			// adjusted manually
			name: id,
			args: []CreateStorageLifecyclePolicyArgs{{
				Name:     "n",
				DataType: dataTypeVarchar,
			}},
			body: "true",
		}
	}

	t.Run("validation: nil options", func(t *testing.T) {
		opts := (*CreateStorageLifecyclePolicyOptions)(nil)
		assertOptsInvalidJoinedErrors(t, opts, ErrNilOptions)
	})

	t.Run("validation: valid identifier for [opts.name]", func(t *testing.T) {
		opts := defaultOpts()
		opts.name = emptySchemaObjectIdentifier
		assertOptsInvalidJoinedErrors(t, opts, ErrInvalidObjectIdentifier)
	})

	t.Run("validation: [opts.args] should be set", func(t *testing.T) {
		opts := defaultOpts()
		opts.args = []CreateStorageLifecyclePolicyArgs{}
		assertOptsInvalidJoinedErrors(t, opts, errNotSet("CreateStorageLifecyclePolicyOptions", "args"))
	})

	t.Run("validation: [opts.body] should be set", func(t *testing.T) {
		opts := defaultOpts()
		opts.body = ""
		assertOptsInvalidJoinedErrors(t, opts, errNotSet("CreateStorageLifecyclePolicyOptions", "body"))
	})

	t.Run("validation: conflicting fields for [opts.OrReplace opts.IfNotExists]", func(t *testing.T) {
		opts := defaultOpts()
		opts.OrReplace = new(true)
		opts.IfNotExists = new(true)
		assertOptsInvalidJoinedErrors(t, opts, errOneOf("CreateStorageLifecyclePolicyOptions", "OrReplace", "IfNotExists"))
	})

	t.Run("basic", func(t *testing.T) {
		opts := defaultOpts()
		assertOptsValidAndSQLEquals(t, opts, `CREATE STORAGE LIFECYCLE POLICY %s AS ("n" VARCHAR(16777216)) RETURNS BOOLEAN -> true`, id.FullyQualifiedName())
	})

	t.Run("two parameters", func(t *testing.T) {
		opts := defaultOpts()
		opts.args = []CreateStorageLifecyclePolicyArgs{{
			Name:     "n1",
			DataType: dataTypeVarchar,
		}, {
			Name:     "n2",
			DataType: dataTypeVarchar,
		}}
		assertOptsValidAndSQLEquals(t, opts, `CREATE STORAGE LIFECYCLE POLICY %s AS ("n1" VARCHAR(16777216), "n2" VARCHAR(16777216)) RETURNS BOOLEAN -> true`, id.FullyQualifiedName())
	})

	t.Run("all options", func(t *testing.T) {
		opts := defaultOpts()
		opts.OrReplace = new(true)
		opts.ArchiveTier = new(StorageLifecyclePolicyArchiveTierCold)
		opts.ArchiveForDays = new(365)
		opts.Comment = new("some comment")
		opts.Tag = []TagAssociation{
			{
				Name:  NewAccountObjectIdentifier("tag1"),
				Value: "value1",
			},
			{
				Name:  NewAccountObjectIdentifier("tag2"),
				Value: "value2",
			},
		}
		assertOptsValidAndSQLEquals(t, opts, `CREATE OR REPLACE STORAGE LIFECYCLE POLICY %s AS ("n" VARCHAR(16777216)) RETURNS BOOLEAN -> true ARCHIVE_TIER = COLD ARCHIVE_FOR_DAYS = 365 COMMENT = 'some comment' TAG ("tag1" = 'value1', "tag2" = 'value2')`, id.FullyQualifiedName())
	})
}

func TestStorageLifecyclePolicies_Alter(t *testing.T) {
	id := randomSchemaObjectIdentifier()
	// Minimal valid AlterStorageLifecyclePolicyOptions
	defaultOpts := func() *AlterStorageLifecyclePolicyOptions {
		return &AlterStorageLifecyclePolicyOptions{
			name: id,
		}
	}

	t.Run("validation: nil options", func(t *testing.T) {
		opts := (*AlterStorageLifecyclePolicyOptions)(nil)
		assertOptsInvalidJoinedErrors(t, opts, ErrNilOptions)
	})

	t.Run("validation: valid identifier for [opts.name]", func(t *testing.T) {
		opts := defaultOpts()
		opts.name = emptySchemaObjectIdentifier
		assertOptsInvalidJoinedErrors(t, opts, ErrInvalidObjectIdentifier)
	})

	t.Run("validation: exactly one field from [opts.RenameTo opts.SetBody opts.Set opts.SetTags opts.Unset opts.UnsetTags] should be present", func(t *testing.T) {
		opts := defaultOpts()
		assertOptsInvalidJoinedErrors(t, opts, errExactlyOneOf("AlterStorageLifecyclePolicyOptions", "RenameTo", "SetBody", "Set", "SetTags", "Unset", "UnsetTags"))
	})

	t.Run("validation: exactly one field from [opts.RenameTo opts.SetBody opts.Set opts.SetTags opts.Unset opts.UnsetTags] should be present - more present", func(t *testing.T) {
		opts := defaultOpts()
		opts.Set = &StorageLifecyclePolicySet{
			Comment: new("some comment"),
		}
		opts.Unset = &StorageLifecyclePolicyUnset{
			Comment: new(true),
		}
		assertOptsInvalidJoinedErrors(t, opts, errExactlyOneOf("AlterStorageLifecyclePolicyOptions", "RenameTo", "SetBody", "Set", "SetTags", "Unset", "UnsetTags"))
	})

	t.Run("validation: at least one of the fields [opts.Set.ArchiveTier opts.Set.ArchiveForDays opts.Set.Comment] should be set", func(t *testing.T) {
		opts := defaultOpts()
		opts.Set = &StorageLifecyclePolicySet{}
		assertOptsInvalidJoinedErrors(t, opts, errAtLeastOneOf("AlterStorageLifecyclePolicyOptions.Set", "ArchiveTier", "ArchiveForDays", "Comment"))
	})

	t.Run("validation: at least one of the fields [opts.Unset.ArchiveForDays opts.Unset.Comment] should be set", func(t *testing.T) {
		opts := defaultOpts()
		opts.Unset = &StorageLifecyclePolicyUnset{}
		assertOptsInvalidJoinedErrors(t, opts, errAtLeastOneOf("AlterStorageLifecyclePolicyOptions.Unset", "ArchiveForDays", "Comment"))
	})

	// all variants added manually
	t.Run("rename", func(t *testing.T) {
		opts := defaultOpts()
		newId := randomSchemaObjectIdentifier()
		opts.RenameTo = &newId
		assertOptsValidAndSQLEquals(t, opts, "ALTER STORAGE LIFECYCLE POLICY %s RENAME TO %s", id.FullyQualifiedName(), newId.FullyQualifiedName())
	})

	t.Run("set body", func(t *testing.T) {
		opts := defaultOpts()
		opts.SetBody = new("true")
		assertOptsValidAndSQLEquals(t, opts, "ALTER STORAGE LIFECYCLE POLICY %s SET BODY -> true", id.FullyQualifiedName())
	})

	t.Run("set", func(t *testing.T) {
		opts := defaultOpts()
		opts.Set = &StorageLifecyclePolicySet{
			ArchiveTier:    new(StorageLifecyclePolicyArchiveTierCool),
			ArchiveForDays: new(120),
			Comment:        new("some comment"),
		}
		assertOptsValidAndSQLEquals(t, opts, "ALTER STORAGE LIFECYCLE POLICY %s SET ARCHIVE_TIER = COOL ARCHIVE_FOR_DAYS = 120 COMMENT = 'some comment'", id.FullyQualifiedName())
	})

	t.Run("set tags", func(t *testing.T) {
		opts := defaultOpts()
		opts.SetTags = []TagAssociation{
			{
				Name:  NewAccountObjectIdentifier("tag1"),
				Value: "value1",
			},
			{
				Name:  NewAccountObjectIdentifier("tag2"),
				Value: "value2",
			},
		}
		assertOptsValidAndSQLEquals(t, opts, `ALTER STORAGE LIFECYCLE POLICY %s SET TAG "tag1" = 'value1', "tag2" = 'value2'`, id.FullyQualifiedName())
	})

	t.Run("unset", func(t *testing.T) {
		opts := defaultOpts()
		opts.Unset = &StorageLifecyclePolicyUnset{
			ArchiveForDays: new(true),
			Comment:        new(true),
		}
		assertOptsValidAndSQLEquals(t, opts, "ALTER STORAGE LIFECYCLE POLICY %s UNSET ARCHIVE_FOR_DAYS, COMMENT", id.FullyQualifiedName())
	})

	t.Run("unset tags", func(t *testing.T) {
		opts := defaultOpts()
		opts.UnsetTags = []ObjectIdentifier{
			NewAccountObjectIdentifier("tag1"),
			NewAccountObjectIdentifier("tag2"),
		}
		assertOptsValidAndSQLEquals(t, opts, `ALTER STORAGE LIFECYCLE POLICY %s UNSET TAG "tag1", "tag2"`, id.FullyQualifiedName())
	})
}

func TestStorageLifecyclePolicies_Drop(t *testing.T) {
	id := randomSchemaObjectIdentifier()
	// Minimal valid DropStorageLifecyclePolicyOptions
	defaultOpts := func() *DropStorageLifecyclePolicyOptions {
		return &DropStorageLifecyclePolicyOptions{
			name: id,
		}
	}

	t.Run("validation: nil options", func(t *testing.T) {
		opts := (*DropStorageLifecyclePolicyOptions)(nil)
		assertOptsInvalidJoinedErrors(t, opts, ErrNilOptions)
	})

	t.Run("validation: valid identifier for [opts.name]", func(t *testing.T) {
		opts := defaultOpts()
		opts.name = emptySchemaObjectIdentifier
		assertOptsInvalidJoinedErrors(t, opts, ErrInvalidObjectIdentifier)
	})

	t.Run("basic", func(t *testing.T) {
		opts := defaultOpts()
		assertOptsValidAndSQLEquals(t, opts, "DROP STORAGE LIFECYCLE POLICY %s", id.FullyQualifiedName())
	})

	t.Run("all options", func(t *testing.T) {
		opts := defaultOpts()
		opts.IfExists = new(true)
		assertOptsValidAndSQLEquals(t, opts, "DROP STORAGE LIFECYCLE POLICY IF EXISTS %s", id.FullyQualifiedName())
	})
}

func TestStorageLifecyclePolicies_Show(t *testing.T) {
	// Minimal valid ShowStorageLifecyclePolicyOptions
	defaultOpts := func() *ShowStorageLifecyclePolicyOptions {
		return &ShowStorageLifecyclePolicyOptions{}
	}

	t.Run("validation: nil options", func(t *testing.T) {
		opts := (*ShowStorageLifecyclePolicyOptions)(nil)
		assertOptsInvalidJoinedErrors(t, opts, ErrNilOptions)
	})

	t.Run("basic", func(t *testing.T) {
		opts := defaultOpts()
		assertOptsValidAndSQLEquals(t, opts, "SHOW STORAGE LIFECYCLE POLICIES")
	})

	t.Run("all options", func(t *testing.T) {
		opts := defaultOpts()
		opts.Like = &Like{
			Pattern: String("like-pattern"),
		}
		opts.In = &ExtendedIn{
			In: In{
				Account: new(true),
			},
		}
		assertOptsValidAndSQLEquals(t, opts, "SHOW STORAGE LIFECYCLE POLICIES LIKE 'like-pattern' IN ACCOUNT")
	})
}

func TestStorageLifecyclePolicies_Describe(t *testing.T) {
	id := randomSchemaObjectIdentifier()
	// Minimal valid DescribeStorageLifecyclePolicyOptions
	defaultOpts := func() *DescribeStorageLifecyclePolicyOptions {
		return &DescribeStorageLifecyclePolicyOptions{
			name: id,
		}
	}

	t.Run("validation: nil options", func(t *testing.T) {
		opts := (*DescribeStorageLifecyclePolicyOptions)(nil)
		assertOptsInvalidJoinedErrors(t, opts, ErrNilOptions)
	})

	t.Run("validation: valid identifier for [opts.name]", func(t *testing.T) {
		opts := defaultOpts()
		opts.name = emptySchemaObjectIdentifier
		assertOptsInvalidJoinedErrors(t, opts, ErrInvalidObjectIdentifier)
	})

	t.Run("basic", func(t *testing.T) {
		opts := defaultOpts()
		assertOptsValidAndSQLEquals(t, opts, "DESCRIBE STORAGE LIFECYCLE POLICY %s", id.FullyQualifiedName())
	})

	// all options removed manually
}
