// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

import "github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/datatypes"

var (
	_ optionsProvider[CreateStorageLifecyclePolicyOptions]   = new(CreateStorageLifecyclePolicyRequest)
	_ optionsProvider[AlterStorageLifecyclePolicyOptions]    = new(AlterStorageLifecyclePolicyRequest)
	_ optionsProvider[DropStorageLifecyclePolicyOptions]     = new(DropStorageLifecyclePolicyRequest)
	_ optionsProvider[ShowStorageLifecyclePolicyOptions]     = new(ShowStorageLifecyclePolicyRequest)
	_ optionsProvider[DescribeStorageLifecyclePolicyOptions] = new(DescribeStorageLifecyclePolicyRequest)
)

type CreateStorageLifecyclePolicyRequest struct {
	OrReplace      *bool
	IfNotExists    *bool
	name           SchemaObjectIdentifier                    // required
	args           []CreateStorageLifecyclePolicyArgsRequest // required
	body           string                                    // required
	ArchiveTier    *StorageLifecyclePolicyArchiveTier
	ArchiveForDays *int
	Comment        *string
	Tag            []TagAssociation
}

type CreateStorageLifecyclePolicyArgsRequest struct {
	Name     string             // required
	DataType datatypes.DataType // required
}

type AlterStorageLifecyclePolicyRequest struct {
	name      SchemaObjectIdentifier // required
	RenameTo  *SchemaObjectIdentifier
	SetBody   *string
	Set       *StorageLifecyclePolicySetRequest
	SetTags   []TagAssociation
	Unset     *StorageLifecyclePolicyUnsetRequest
	UnsetTags []ObjectIdentifier
}

type StorageLifecyclePolicySetRequest struct {
	ArchiveTier    *StorageLifecyclePolicyArchiveTier
	ArchiveForDays *int
	Comment        *string
}

type StorageLifecyclePolicyUnsetRequest struct {
	ArchiveForDays *bool
	Comment        *bool
}

type DropStorageLifecyclePolicyRequest struct {
	IfExists *bool
	name     SchemaObjectIdentifier // required
}

type ShowStorageLifecyclePolicyRequest struct {
	Like *Like
	In   *ExtendedIn
}

type DescribeStorageLifecyclePolicyRequest struct {
	name SchemaObjectIdentifier // required
}
