// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

import (
	"context"
	"database/sql"
	"time"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/datatypes"
)

type StorageLifecyclePolicies interface {
	Create(ctx context.Context, request *CreateStorageLifecyclePolicyRequest) error
	Alter(ctx context.Context, request *AlterStorageLifecyclePolicyRequest) error
	Drop(ctx context.Context, request *DropStorageLifecyclePolicyRequest) error
	DropSafely(ctx context.Context, id SchemaObjectIdentifier) error
	Show(ctx context.Context, request *ShowStorageLifecyclePolicyRequest) ([]StorageLifecyclePolicy, error)
	ShowByID(ctx context.Context, id SchemaObjectIdentifier) (*StorageLifecyclePolicy, error)
	ShowByIDSafely(ctx context.Context, id SchemaObjectIdentifier) (*StorageLifecyclePolicy, error)
	Describe(ctx context.Context, id SchemaObjectIdentifier) (*StorageLifecyclePolicyDetails, error)
}

// CreateStorageLifecyclePolicyOptions is based on https://docs.snowflake.com/en/sql-reference/sql/create-storage-lifecycle-policy.
type CreateStorageLifecyclePolicyOptions struct {
	create                 bool                               `ddl:"static" sql:"CREATE"`
	OrReplace              *bool                              `ddl:"keyword" sql:"OR REPLACE"`
	storageLifecyclePolicy bool                               `ddl:"static" sql:"STORAGE LIFECYCLE POLICY"`
	IfNotExists            *bool                              `ddl:"keyword" sql:"IF NOT EXISTS"`
	name                   SchemaObjectIdentifier             `ddl:"identifier"`
	args                   []CreateStorageLifecyclePolicyArgs `ddl:"parameter,parentheses,no_equals" sql:"AS"`
	returnsBoolean         bool                               `ddl:"static" sql:"RETURNS BOOLEAN"`
	body                   string                             `ddl:"parameter,no_quotes,no_equals" sql:"->"`
	ArchiveTier            *StorageLifecyclePolicyArchiveTier `ddl:"parameter" sql:"ARCHIVE_TIER"`
	ArchiveForDays         *int                               `ddl:"parameter" sql:"ARCHIVE_FOR_DAYS"`
	Comment                *string                            `ddl:"parameter,single_quotes" sql:"COMMENT"`
	Tag                    []TagAssociation                   `ddl:"keyword,parentheses" sql:"TAG"`
}

type CreateStorageLifecyclePolicyArgs struct {
	Name     string             `ddl:"keyword,double_quotes"`
	DataType datatypes.DataType `ddl:"parameter,no_equals"`
}

// AlterStorageLifecyclePolicyOptions is based on https://docs.snowflake.com/en/sql-reference/sql/alter-storage-lifecycle-policy.
type AlterStorageLifecyclePolicyOptions struct {
	alter                  bool                         `ddl:"static" sql:"ALTER"`
	storageLifecyclePolicy bool                         `ddl:"static" sql:"STORAGE LIFECYCLE POLICY"`
	name                   SchemaObjectIdentifier       `ddl:"identifier"`
	RenameTo               *SchemaObjectIdentifier      `ddl:"identifier" sql:"RENAME TO"`
	SetBody                *string                      `ddl:"parameter,no_quotes,no_equals" sql:"SET BODY ->"`
	Set                    *StorageLifecyclePolicySet   `ddl:"keyword" sql:"SET"`
	SetTags                []TagAssociation             `ddl:"keyword" sql:"SET TAG"`
	Unset                  *StorageLifecyclePolicyUnset `ddl:"list,no_parentheses" sql:"UNSET"`
	UnsetTags              []ObjectIdentifier           `ddl:"keyword" sql:"UNSET TAG"`
}

type StorageLifecyclePolicySet struct {
	ArchiveTier    *StorageLifecyclePolicyArchiveTier `ddl:"parameter" sql:"ARCHIVE_TIER"`
	ArchiveForDays *int                               `ddl:"parameter" sql:"ARCHIVE_FOR_DAYS"`
	Comment        *string                            `ddl:"parameter,single_quotes" sql:"COMMENT"`
}

type StorageLifecyclePolicyUnset struct {
	ArchiveForDays *bool `ddl:"keyword" sql:"ARCHIVE_FOR_DAYS"`
	Comment        *bool `ddl:"keyword" sql:"COMMENT"`
}

// DropStorageLifecyclePolicyOptions is based on https://docs.snowflake.com/en/sql-reference/sql/drop-storage-lifecycle-policy.
type DropStorageLifecyclePolicyOptions struct {
	drop                   bool                   `ddl:"static" sql:"DROP"`
	storageLifecyclePolicy bool                   `ddl:"static" sql:"STORAGE LIFECYCLE POLICY"`
	IfExists               *bool                  `ddl:"keyword" sql:"IF EXISTS"`
	name                   SchemaObjectIdentifier `ddl:"identifier"`
}

// ShowStorageLifecyclePolicyOptions is based on https://docs.snowflake.com/en/sql-reference/sql/show-storage-lifecycle-policies.
type ShowStorageLifecyclePolicyOptions struct {
	show                     bool  `ddl:"static" sql:"SHOW"`
	storageLifecyclePolicies bool  `ddl:"static" sql:"STORAGE LIFECYCLE POLICIES"`
	Like                     *Like `ddl:"keyword" sql:"LIKE"`
	In                       *In   `ddl:"keyword" sql:"IN"`
}

type storageLifecyclePolicyDBRow struct {
	CreatedOn     time.Time `db:"created_on"`
	Name          string    `db:"name"`
	DatabaseName  string    `db:"database_name"`
	SchemaName    string    `db:"schema_name"`
	Kind          string    `db:"kind"`
	Owner         string    `db:"owner"`
	Comment       string    `db:"comment"`
	OwnerRoleType string    `db:"owner_role_type"`
	Options       string    `db:"options"`
}

type StorageLifecyclePolicy struct {
	CreatedOn     time.Time
	Name          string
	DatabaseName  string
	SchemaName    string
	Kind          string
	Owner         string
	Comment       string
	OwnerRoleType string
	Options       string
}

func (v *StorageLifecyclePolicy) ID() SchemaObjectIdentifier {
	return NewSchemaObjectIdentifier(v.DatabaseName, v.SchemaName, v.Name)
}

func (v *StorageLifecyclePolicy) ObjectType() ObjectType {
	return ObjectTypeStorageLifecyclePolicy
}

// DescribeStorageLifecyclePolicyOptions is based on https://docs.snowflake.com/en/sql-reference/sql/desc-storage-lifecycle-policy.
type DescribeStorageLifecyclePolicyOptions struct {
	describe               bool                   `ddl:"static" sql:"DESCRIBE"`
	storageLifecyclePolicy bool                   `ddl:"static" sql:"STORAGE LIFECYCLE POLICY"`
	name                   SchemaObjectIdentifier `ddl:"identifier"`
}

type describeStorageLifecyclePolicyDBRow struct {
	Name           string        `db:"name"`
	Signature      string        `db:"signature"`
	ReturnType     string        `db:"return_type"`
	Body           string        `db:"body"`
	ArchiveForDays sql.NullInt64 `db:"archive_for_days"`
	ArchiveTier    string        `db:"archive_tier"`
}

type StorageLifecyclePolicyDetails struct {
	Name           string
	DatabaseName   string
	SchemaName     string
	Signature      []TableColumnSignature
	ReturnType     datatypes.DataType
	Body           string
	ArchiveForDays *int
	ArchiveTier    string
}
