// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

func NewDescribeSearchOptimizationTableRequest(
	name SchemaObjectIdentifier,
) *DescribeSearchOptimizationTableRequest {
	s := DescribeSearchOptimizationTableRequest{}
	s.name = name
	return &s
}

func NewShowConstraintsTableRequest(
	database AccountObjectIdentifier,
	tableSchema string,
	tableName string,
) *ShowConstraintsTableRequest {
	s := ShowConstraintsTableRequest{}
	s.Database = database
	s.TableSchema = tableSchema
	s.TableName = tableName
	return &s
}
