// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

import "fmt"

var (
	_ validatable = new(CreateTableOptions)
	_ validatable = new(CreateAsSelectTableOptions)
	_ validatable = new(CreateUsingTemplateTableOptions)
	_ validatable = new(CreateLikeTableOptions)
	_ validatable = new(CreateCloneTableOptions)
	_ validatable = new(AlterTableOptions)
	_ validatable = new(DropTableOptions)
	_ validatable = new(ShowTableOptions)
	_ validatable = new(DescribeColumnsTableOptions)
	_ validatable = new(DescribeStageTableOptions)
	_ validatable = new(DescribeSearchOptimizationTableOptions)
	_ validatable = new(SelectTableConstraintsTableOptions)
	_ validatable = new(SelectCheckConstraintsTableOptions)
)

func (opts *CreateTableOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, errInvalidIdentifier("CreateTableOptions", "name"))
	}
	errs = append(errs, opts.additionalValidations())
	if valueSet(opts.ColumnsAndConstraints) {
		if valueSet(opts.ColumnsAndConstraints.Columns) {
			for columnIdx, column := range opts.ColumnsAndConstraints.Columns {
				if valueSet(column.DefaultValue) {
					if !exactlyOneValueSet(column.DefaultValue.Expression, column.DefaultValue.Identity) {
						errs = append(errs, errExactlyOneOf(fmt.Sprintf("CreateTableOptions.ColumnsAndConstraints.Columns[%d].DefaultValue", columnIdx), "Expression", "Identity"))
					}
					if valueSet(column.DefaultValue.Identity) {
						if everyValueSet(column.DefaultValue.Identity.Order, column.DefaultValue.Identity.Noorder) {
							errs = append(errs, errOneOf(fmt.Sprintf("CreateTableOptions.ColumnsAndConstraints.Columns[%d].DefaultValue.Identity", columnIdx), "Order", "Noorder"))
						}
					}
				}
				if valueSet(column.MaskingPolicy) {
					if !ValidObjectIdentifier(column.MaskingPolicy.Name) {
						errs = append(errs, errInvalidIdentifier(fmt.Sprintf("CreateTableOptions.ColumnsAndConstraints.Columns[%d].MaskingPolicy", columnIdx), "Name"))
					}
				}
				if valueSet(column.Tag) {
					for tagIdx, tag := range column.Tag {
						if !ValidObjectIdentifier(tag.Name) {
							errs = append(errs, errInvalidIdentifier(fmt.Sprintf("CreateTableOptions.ColumnsAndConstraints.Columns[%d].Tag[%d]", columnIdx, tagIdx), "Name"))
						}
					}
				}
			}
		}
		if valueSet(opts.ColumnsAndConstraints.OutOfLineConstraint) {
			for outOfLineConstraintIdx, outOfLineConstraint := range opts.ColumnsAndConstraints.OutOfLineConstraint {
				if !valueSet(outOfLineConstraint.Columns) {
					errs = append(errs, errNotSet(fmt.Sprintf("CreateTableOptions.ColumnsAndConstraints.OutOfLineConstraint[%d]", outOfLineConstraintIdx), "Columns"))
				}
				if everyValueSet(outOfLineConstraint.Enforced, outOfLineConstraint.NotEnforced) {
					errs = append(errs, errOneOf(fmt.Sprintf("CreateTableOptions.ColumnsAndConstraints.OutOfLineConstraint[%d]", outOfLineConstraintIdx), "Enforced", "NotEnforced"))
				}
				if everyValueSet(outOfLineConstraint.Deferrable, outOfLineConstraint.NotDeferrable) {
					errs = append(errs, errOneOf(fmt.Sprintf("CreateTableOptions.ColumnsAndConstraints.OutOfLineConstraint[%d]", outOfLineConstraintIdx), "Deferrable", "NotDeferrable"))
				}
				if everyValueSet(outOfLineConstraint.InitiallyDeferred, outOfLineConstraint.InitiallyImmediate) {
					errs = append(errs, errOneOf(fmt.Sprintf("CreateTableOptions.ColumnsAndConstraints.OutOfLineConstraint[%d]", outOfLineConstraintIdx), "InitiallyDeferred", "InitiallyImmediate"))
				}
				if everyValueSet(outOfLineConstraint.Enable, outOfLineConstraint.Disable) {
					errs = append(errs, errOneOf(fmt.Sprintf("CreateTableOptions.ColumnsAndConstraints.OutOfLineConstraint[%d]", outOfLineConstraintIdx), "Enable", "Disable"))
				}
				if everyValueSet(outOfLineConstraint.Validate, outOfLineConstraint.Novalidate) {
					errs = append(errs, errOneOf(fmt.Sprintf("CreateTableOptions.ColumnsAndConstraints.OutOfLineConstraint[%d]", outOfLineConstraintIdx), "Validate", "Novalidate"))
				}
				if everyValueSet(outOfLineConstraint.Rely, outOfLineConstraint.Norely) {
					errs = append(errs, errOneOf(fmt.Sprintf("CreateTableOptions.ColumnsAndConstraints.OutOfLineConstraint[%d]", outOfLineConstraintIdx), "Rely", "Norely"))
				}
			}
		}
	}
	if valueSet(opts.StageFileFormat) {
		if !exactlyOneValueSet(opts.StageFileFormat.FormatName, opts.StageFileFormat.FileFormatType) {
			errs = append(errs, errExactlyOneOf("CreateTableOptions.StageFileFormat", "FormatName", "FileFormatType"))
		}
	}
	if valueSet(opts.Tag) {
		for tagIdx, tag := range opts.Tag {
			if !ValidObjectIdentifier(tag.Name) {
				errs = append(errs, errInvalidIdentifier(fmt.Sprintf("CreateTableOptions.Tag[%d]", tagIdx), "Name"))
			}
		}
	}
	return JoinErrors(errs...)
}

func (opts *CreateAsSelectTableOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, errInvalidIdentifier("CreateAsSelectTableOptions", "name"))
	}
	if !valueSet(opts.Columns) {
		errs = append(errs, errNotSet("CreateAsSelectTableOptions", "Columns"))
	}
	if !valueSet(opts.Query) {
		errs = append(errs, errNotSet("CreateAsSelectTableOptions", "Query"))
	}
	return JoinErrors(errs...)
}

func (opts *CreateUsingTemplateTableOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, errInvalidIdentifier("CreateUsingTemplateTableOptions", "name"))
	}
	return JoinErrors(errs...)
}

func (opts *CreateLikeTableOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, errInvalidIdentifier("CreateLikeTableOptions", "name"))
	}
	if !ValidObjectIdentifier(opts.SourceTable) {
		errs = append(errs, errInvalidIdentifier("CreateLikeTableOptions", "SourceTable"))
	}
	return JoinErrors(errs...)
}

func (opts *CreateCloneTableOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, errInvalidIdentifier("CreateCloneTableOptions", "name"))
	}
	if !ValidObjectIdentifier(opts.SourceTable) {
		errs = append(errs, errInvalidIdentifier("CreateCloneTableOptions", "SourceTable"))
	}
	return JoinErrors(errs...)
}

func (opts *AlterTableOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, errInvalidIdentifier("AlterTableOptions", "name"))
	}
	if opts.RenameTo != nil && !ValidObjectIdentifier(opts.RenameTo) {
		errs = append(errs, errInvalidIdentifier("AlterTableOptions", "RenameTo"))
	}
	if opts.SwapWith != nil && !ValidObjectIdentifier(opts.SwapWith) {
		errs = append(errs, errInvalidIdentifier("AlterTableOptions", "SwapWith"))
	}
	if !exactlyOneValueSet(opts.RenameTo, opts.SwapWith, opts.ClusteringAction, opts.ColumnAction, opts.ConstraintAction, opts.ExternalTableAction, opts.SearchOptimizationAction, opts.Set, opts.SetTags, opts.UnsetTags, opts.Unset, opts.AddRowAccessPolicy, opts.DropRowAccessPolicy, opts.DropAndAddRowAccessPolicy, opts.DropAllRowAccessPolicies, opts.AddStorageLifecyclePolicy, opts.DropStorageLifecyclePolicy) {
		errs = append(errs, errExactlyOneOf("AlterTableOptions", "RenameTo", "SwapWith", "ClusteringAction", "ColumnAction", "ConstraintAction", "ExternalTableAction", "SearchOptimizationAction", "Set", "SetTags", "UnsetTags", "Unset", "AddRowAccessPolicy", "DropRowAccessPolicy", "DropAndAddRowAccessPolicy", "DropAllRowAccessPolicies", "AddStorageLifecyclePolicy", "DropStorageLifecyclePolicy"))
	}
	errs = append(errs, opts.additionalValidations())
	if valueSet(opts.ClusteringAction) {
		if !exactlyOneValueSet(opts.ClusteringAction.ClusterBy, opts.ClusteringAction.Recluster, opts.ClusteringAction.ChangeReclusterState, opts.ClusteringAction.DropClusteringKey) {
			errs = append(errs, errExactlyOneOf("AlterTableOptions.ClusteringAction", "ClusterBy", "Recluster", "ChangeReclusterState", "DropClusteringKey"))
		}
	}
	if valueSet(opts.ColumnAction) {
		if !exactlyOneValueSet(opts.ColumnAction.Add, opts.ColumnAction.Rename, opts.ColumnAction.Alter, opts.ColumnAction.SetMaskingPolicy, opts.ColumnAction.UnsetMaskingPolicy, opts.ColumnAction.SetTags, opts.ColumnAction.UnsetTags, opts.ColumnAction.DropColumns) {
			errs = append(errs, errExactlyOneOf("AlterTableOptions.ColumnAction", "Add", "Rename", "Alter", "SetMaskingPolicy", "UnsetMaskingPolicy", "SetTags", "UnsetTags", "DropColumns"))
		}
		if valueSet(opts.ColumnAction.Add) {
			if valueSet(opts.ColumnAction.Add.DefaultValue) {
				if !exactlyOneValueSet(opts.ColumnAction.Add.DefaultValue.Expression, opts.ColumnAction.Add.DefaultValue.Identity) {
					errs = append(errs, errExactlyOneOf("AlterTableOptions.ColumnAction.Add.DefaultValue", "Expression", "Identity"))
				}
				if valueSet(opts.ColumnAction.Add.DefaultValue.Identity) {
					if everyValueSet(opts.ColumnAction.Add.DefaultValue.Identity.Order, opts.ColumnAction.Add.DefaultValue.Identity.Noorder) {
						errs = append(errs, errOneOf("AlterTableOptions.ColumnAction.Add.DefaultValue.Identity", "Order", "Noorder"))
					}
				}
			}
			if valueSet(opts.ColumnAction.Add.MaskingPolicy) {
				if !ValidObjectIdentifier(opts.ColumnAction.Add.MaskingPolicy.Name) {
					errs = append(errs, errInvalidIdentifier("AlterTableOptions.ColumnAction.Add.MaskingPolicy", "Name"))
				}
			}
			if valueSet(opts.ColumnAction.Add.Tag) {
				for tagIdx, tag := range opts.ColumnAction.Add.Tag {
					if !ValidObjectIdentifier(tag.Name) {
						errs = append(errs, errInvalidIdentifier(fmt.Sprintf("AlterTableOptions.ColumnAction.Add.Tag[%d]", tagIdx), "Name"))
					}
				}
			}
		}
		if valueSet(opts.ColumnAction.Alter) {
			for alterIdx, alter := range opts.ColumnAction.Alter {
				if !exactlyOneValueSet(alter.DropDefault, alter.SetDefault, alter.NotNullConstraint, alter.DataType, alter.Comment, alter.UnsetComment) {
					errs = append(errs, errExactlyOneOf(fmt.Sprintf("AlterTableOptions.ColumnAction.Alter[%d]", alterIdx), "DropDefault", "SetDefault", "NotNullConstraint", "DataType", "Comment", "UnsetComment"))
				}
			}
		}
		if valueSet(opts.ColumnAction.SetTags) {
			if valueSet(opts.ColumnAction.SetTags.SetTags) {
				for setTagIdx, setTag := range opts.ColumnAction.SetTags.SetTags {
					if !ValidObjectIdentifier(setTag.Name) {
						errs = append(errs, errInvalidIdentifier(fmt.Sprintf("AlterTableOptions.ColumnAction.SetTags.SetTags[%d]", setTagIdx), "Name"))
					}
				}
			}
		}
	}
	if valueSet(opts.ConstraintAction) {
		if !exactlyOneValueSet(opts.ConstraintAction.Add, opts.ConstraintAction.Rename, opts.ConstraintAction.Alter, opts.ConstraintAction.Drop) {
			errs = append(errs, errExactlyOneOf("AlterTableOptions.ConstraintAction", "Add", "Rename", "Alter", "Drop"))
		}
		if valueSet(opts.ConstraintAction.Add) {
			if !valueSet(opts.ConstraintAction.Add.Columns) {
				errs = append(errs, errNotSet("AlterTableOptions.ConstraintAction.Add", "Columns"))
			}
			if everyValueSet(opts.ConstraintAction.Add.Enforced, opts.ConstraintAction.Add.NotEnforced) {
				errs = append(errs, errOneOf("AlterTableOptions.ConstraintAction.Add", "Enforced", "NotEnforced"))
			}
			if everyValueSet(opts.ConstraintAction.Add.Deferrable, opts.ConstraintAction.Add.NotDeferrable) {
				errs = append(errs, errOneOf("AlterTableOptions.ConstraintAction.Add", "Deferrable", "NotDeferrable"))
			}
			if everyValueSet(opts.ConstraintAction.Add.InitiallyDeferred, opts.ConstraintAction.Add.InitiallyImmediate) {
				errs = append(errs, errOneOf("AlterTableOptions.ConstraintAction.Add", "InitiallyDeferred", "InitiallyImmediate"))
			}
			if everyValueSet(opts.ConstraintAction.Add.Enable, opts.ConstraintAction.Add.Disable) {
				errs = append(errs, errOneOf("AlterTableOptions.ConstraintAction.Add", "Enable", "Disable"))
			}
			if everyValueSet(opts.ConstraintAction.Add.Validate, opts.ConstraintAction.Add.Novalidate) {
				errs = append(errs, errOneOf("AlterTableOptions.ConstraintAction.Add", "Validate", "Novalidate"))
			}
			if everyValueSet(opts.ConstraintAction.Add.Rely, opts.ConstraintAction.Add.Norely) {
				errs = append(errs, errOneOf("AlterTableOptions.ConstraintAction.Add", "Rely", "Norely"))
			}
		}
		if valueSet(opts.ConstraintAction.Alter) {
			if !exactlyOneValueSet(opts.ConstraintAction.Alter.ConstraintName, opts.ConstraintAction.Alter.PrimaryKey, opts.ConstraintAction.Alter.Unique, opts.ConstraintAction.Alter.ForeignKey) {
				errs = append(errs, errExactlyOneOf("AlterTableOptions.ConstraintAction.Alter", "ConstraintName", "PrimaryKey", "Unique", "ForeignKey"))
			}
		}
		if valueSet(opts.ConstraintAction.Drop) {
			if !exactlyOneValueSet(opts.ConstraintAction.Drop.ConstraintName, opts.ConstraintAction.Drop.PrimaryKey, opts.ConstraintAction.Drop.Unique, opts.ConstraintAction.Drop.ForeignKey) {
				errs = append(errs, errExactlyOneOf("AlterTableOptions.ConstraintAction.Drop", "ConstraintName", "PrimaryKey", "Unique", "ForeignKey"))
			}
		}
	}
	if valueSet(opts.ExternalTableAction) {
		if !exactlyOneValueSet(opts.ExternalTableAction.Add, opts.ExternalTableAction.Rename, opts.ExternalTableAction.Drop) {
			errs = append(errs, errExactlyOneOf("AlterTableOptions.ExternalTableAction", "Add", "Rename", "Drop"))
		}
		if valueSet(opts.ExternalTableAction.Drop) {
			if !valueSet(opts.ExternalTableAction.Drop.Names) {
				errs = append(errs, errNotSet("AlterTableOptions.ExternalTableAction.Drop", "Names"))
			}
		}
	}
	if valueSet(opts.SearchOptimizationAction) {
		if !exactlyOneValueSet(opts.SearchOptimizationAction.Add, opts.SearchOptimizationAction.Drop) {
			errs = append(errs, errExactlyOneOf("AlterTableOptions.SearchOptimizationAction", "Add", "Drop"))
		}
		if valueSet(opts.SearchOptimizationAction.Drop) {
			if valueSet(opts.SearchOptimizationAction.Drop.On) {
				for onIdx, on := range opts.SearchOptimizationAction.Drop.On {
					if !exactlyOneValueSet(on.SearchMethodWithTarget, on.ColumnName, on.ExpressionId) {
						errs = append(errs, errExactlyOneOf(fmt.Sprintf("AlterTableOptions.SearchOptimizationAction.Drop.On[%d]", onIdx), "SearchMethodWithTarget", "ColumnName", "ExpressionId"))
					}
				}
			}
		}
	}
	if valueSet(opts.Set) {
		if valueSet(opts.Set.StageFileFormat) {
			if !exactlyOneValueSet(opts.Set.StageFileFormat.FormatName, opts.Set.StageFileFormat.FileFormatType) {
				errs = append(errs, errExactlyOneOf("AlterTableOptions.Set.StageFileFormat", "FormatName", "FileFormatType"))
			}
		}
	}
	if valueSet(opts.SetTags) {
		for setTagIdx, setTag := range opts.SetTags {
			if !ValidObjectIdentifier(setTag.Name) {
				errs = append(errs, errInvalidIdentifier(fmt.Sprintf("AlterTableOptions.SetTags[%d]", setTagIdx), "Name"))
			}
		}
	}
	if valueSet(opts.AddStorageLifecyclePolicy) {
		if !ValidObjectIdentifier(opts.AddStorageLifecyclePolicy.StorageLifecyclePolicy) {
			errs = append(errs, errInvalidIdentifier("AlterTableOptions.AddStorageLifecyclePolicy", "StorageLifecyclePolicy"))
		}
		if !valueSet(opts.AddStorageLifecyclePolicy.On) {
			errs = append(errs, errNotSet("AlterTableOptions.AddStorageLifecyclePolicy", "On"))
		}
	}
	return JoinErrors(errs...)
}

func (opts *DropTableOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, errInvalidIdentifier("DropTableOptions", "name"))
	}
	if everyValueSet(opts.Cascade, opts.Restrict) {
		errs = append(errs, errOneOf("DropTableOptions", "Cascade", "Restrict"))
	}
	return JoinErrors(errs...)
}

func (opts *ShowTableOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	errs = append(errs, opts.additionalValidations())
	return JoinErrors(errs...)
}

func (opts *DescribeColumnsTableOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, errInvalidIdentifier("DescribeColumnsTableOptions", "name"))
	}
	return JoinErrors(errs...)
}

func (opts *DescribeStageTableOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, errInvalidIdentifier("DescribeStageTableOptions", "name"))
	}
	return JoinErrors(errs...)
}

func (opts *DescribeSearchOptimizationTableOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.name) {
		errs = append(errs, errInvalidIdentifier("DescribeSearchOptimizationTableOptions", "name"))
	}
	return JoinErrors(errs...)
}

func (opts *SelectTableConstraintsTableOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.Database) {
		errs = append(errs, errInvalidIdentifier("SelectTableConstraintsTableOptions", "Database"))
	}
	return JoinErrors(errs...)
}

func (opts *SelectCheckConstraintsTableOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	if !ValidObjectIdentifier(opts.Database) {
		errs = append(errs, errInvalidIdentifier("SelectCheckConstraintsTableOptions", "Database"))
	}
	return JoinErrors(errs...)
}
