// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

func NewGetForEntityTagReferenceRequest(
	parameters *tagReferenceParametersRequest,
) *GetForEntityTagReferenceRequest {
	s := GetForEntityTagReferenceRequest{}
	s.parameters = parameters
	return &s
}

func NewtagReferenceParametersRequest(
	arguments *tagReferenceFunctionArgumentsRequest,
) *tagReferenceParametersRequest {
	s := tagReferenceParametersRequest{}
	s.arguments = arguments
	return &s
}

func NewtagReferenceFunctionArgumentsRequest(
	objectName *string,
	objectDomain *TagReferenceObjectDomain,
) *tagReferenceFunctionArgumentsRequest {
	s := tagReferenceFunctionArgumentsRequest{}
	s.ObjectName = objectName
	s.ObjectDomain = objectDomain
	return &s
}
