// Code generated by dto builder generator; DO NOT EDIT.

package sdk

import ()

func NewSetTagRequest(
	objectType ObjectType,
	objectName ObjectIdentifier,
) *SetTagRequest {
	s := SetTagRequest{}
	s.objectType = objectType
	s.objectName = objectName
	return &s
}

func (s *SetTagRequest) WithSetTags(SetTags []TagAssociation) *SetTagRequest {
	s.SetTags = SetTags
	return s
}

func NewUnsetTagRequest(
	objectType ObjectType,
	objectName ObjectIdentifier,
) *UnsetTagRequest {
	s := UnsetTagRequest{}
	s.objectType = objectType
	s.objectName = objectName
	return &s
}

func (s *UnsetTagRequest) WithIfExists(IfExists bool) *UnsetTagRequest {
	s.IfExists = &IfExists
	return s
}

func (s *UnsetTagRequest) WithUnsetTags(UnsetTags []ObjectIdentifier) *UnsetTagRequest {
	s.UnsetTags = UnsetTags
	return s
}

func NewSetTagOnCurrentAccountRequest() *SetTagOnCurrentAccountRequest {
	return &SetTagOnCurrentAccountRequest{}
}

func (s *SetTagOnCurrentAccountRequest) WithSetTags(SetTags []TagAssociation) *SetTagOnCurrentAccountRequest {
	s.SetTags = SetTags
	return s
}

func NewUnsetTagOnCurrentAccountRequest() *UnsetTagOnCurrentAccountRequest {
	return &UnsetTagOnCurrentAccountRequest{}
}

func (s *UnsetTagOnCurrentAccountRequest) WithUnsetTags(UnsetTags []ObjectIdentifier) *UnsetTagOnCurrentAccountRequest {
	s.UnsetTags = UnsetTags
	return s
}

func NewTagPropagateRequest(
	propagationMethod TagPropagation,
) *TagPropagateRequest {
	s := TagPropagateRequest{}
	s.propagationMethod = propagationMethod
	return &s
}

func (s *TagPropagateRequest) WithOnConflict(onConflict TagOnConflict) *TagPropagateRequest {
	s.onConflict = &onConflict
	return s
}

func NewCreateTagRequest(
	name SchemaObjectIdentifier,
) *CreateTagRequest {
	s := CreateTagRequest{}
	s.name = name
	return &s
}

func (s *CreateTagRequest) WithOrReplace(orReplace bool) *CreateTagRequest {
	s.orReplace = &orReplace
	return s
}

func (s *CreateTagRequest) WithIfNotExists(ifNotExists bool) *CreateTagRequest {
	s.ifNotExists = &ifNotExists
	return s
}

func (s *CreateTagRequest) WithComment(comment string) *CreateTagRequest {
	s.comment = &comment
	return s
}

func (s *CreateTagRequest) WithAllowedValues(allowedValues []string) *CreateTagRequest {
	s.allowedValues = allowedValues
	return s
}

func (s *CreateTagRequest) WithPropagate(propagate TagPropagateRequest) *CreateTagRequest {
	s.propagate = &propagate
	return s
}

func NewAlterTagRequest(
	name SchemaObjectIdentifier,
) *AlterTagRequest {
	s := AlterTagRequest{}
	s.name = name
	return &s
}

func (s *AlterTagRequest) WithIfExists(ifExists bool) *AlterTagRequest {
	s.ifExists = &ifExists
	return s
}

func (s *AlterTagRequest) WithAdd(add []string) *AlterTagRequest {
	s.add = add
	return s
}

func (s *AlterTagRequest) WithDrop(drop []string) *AlterTagRequest {
	s.drop = drop
	return s
}

func (s *AlterTagRequest) WithSet(set TagSetRequest) *AlterTagRequest {
	s.set = &set
	return s
}

func (s *AlterTagRequest) WithUnset(unset TagUnsetRequest) *AlterTagRequest {
	s.unset = &unset
	return s
}

func (s *AlterTagRequest) WithRename(rename SchemaObjectIdentifier) *AlterTagRequest {
	s.rename = &rename
	return s
}

func NewTagSetRequest() *TagSetRequest {
	return &TagSetRequest{}
}

func (s *TagSetRequest) WithMaskingPolicies(maskingPolicies []SchemaObjectIdentifier) *TagSetRequest {
	s.maskingPolicies = maskingPolicies
	return s
}

func (s *TagSetRequest) WithForce(force bool) *TagSetRequest {
	s.force = &force
	return s
}

func (s *TagSetRequest) WithAllowedValues(allowedValues []string) *TagSetRequest {
	s.allowedValues = allowedValues
	return s
}

func (s *TagSetRequest) WithPropagate(propagate TagPropagateRequest) *TagSetRequest {
	s.propagate = &propagate
	return s
}

func (s *TagSetRequest) WithComment(comment string) *TagSetRequest {
	s.comment = &comment
	return s
}

func NewTagUnsetRequest() *TagUnsetRequest {
	return &TagUnsetRequest{}
}

func (s *TagUnsetRequest) WithMaskingPolicies(maskingPolicies []SchemaObjectIdentifier) *TagUnsetRequest {
	s.maskingPolicies = maskingPolicies
	return s
}

func (s *TagUnsetRequest) WithAllowedValues(allowedValues bool) *TagUnsetRequest {
	s.allowedValues = &allowedValues
	return s
}

func (s *TagUnsetRequest) WithPropagate(propagate bool) *TagUnsetRequest {
	s.propagate = &propagate
	return s
}

func (s *TagUnsetRequest) WithOnConflict(onConflict bool) *TagUnsetRequest {
	s.onConflict = &onConflict
	return s
}

func (s *TagUnsetRequest) WithComment(comment bool) *TagUnsetRequest {
	s.comment = &comment
	return s
}

func NewShowTagRequest() *ShowTagRequest {
	return &ShowTagRequest{}
}

func (s *ShowTagRequest) WithLike(Like Like) *ShowTagRequest {
	s.Like = &Like
	return s
}

func (s *ShowTagRequest) WithIn(In ExtendedIn) *ShowTagRequest {
	s.In = &In
	return s
}

func NewDropTagRequest(
	name SchemaObjectIdentifier,
) *DropTagRequest {
	s := DropTagRequest{}
	s.name = name
	return &s
}

func (s *DropTagRequest) WithIfExists(ifExists bool) *DropTagRequest {
	s.ifExists = ifExists
	return s
}

func NewUndropTagRequest(
	name SchemaObjectIdentifier,
) *UndropTagRequest {
	s := UndropTagRequest{}
	s.name = name
	return &s
}
