// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

var (
	_ optionsProvider[CreateTaskOptions]        = new(CreateTaskRequest)
	_ optionsProvider[CreateOrAlterTaskOptions] = new(CreateOrAlterTaskRequest)
	_ optionsProvider[CloneTaskOptions]         = new(CloneTaskRequest)
	_ optionsProvider[AlterTaskOptions]         = new(AlterTaskRequest)
	_ optionsProvider[DropTaskOptions]          = new(DropTaskRequest)
	_ optionsProvider[ShowTaskOptions]          = new(ShowTaskRequest)
	_ optionsProvider[DescribeTaskOptions]      = new(DescribeTaskRequest)
	_ optionsProvider[ExecuteTaskOptions]       = new(ExecuteTaskRequest)
)

type CreateTaskRequest struct {
	OrReplace   *bool
	IfNotExists *bool
	name        SchemaObjectIdentifier // required
	// adjusted manually
	Warehouse                               *CreateTaskWarehouseRequest
	Schedule                                *string
	Config                                  *string
	AllowOverlappingExecution               *bool
	SessionParameters                       *SessionParameters
	UserTaskTimeoutMs                       *int
	SuspendTaskAfterNumFailures             *int
	ErrorIntegration                        *AccountObjectIdentifier
	Comment                                 *string
	Finalize                                *SchemaObjectIdentifier
	TaskAutoRetryAttempts                   *int
	Tag                                     []TagAssociation
	UserTaskMinimumTriggerIntervalInSeconds *int
	After                                   []SchemaObjectIdentifier
	When                                    *string
	sql                                     string // required
}

// added manually
func (r *CreateTaskRequest) GetName() SchemaObjectIdentifier {
	return r.name
}

// added manually
type CreateTaskWarehouseRequest struct {
	Warehouse                           *AccountObjectIdentifier
	UserTaskManagedInitialWarehouseSize *WarehouseSize
}

type CreateOrAlterTaskRequest struct {
	name SchemaObjectIdentifier // required
	// adjusted manually
	Warehouse                   *CreateTaskWarehouseRequest
	Schedule                    *string
	Config                      *string
	AllowOverlappingExecution   *bool
	UserTaskTimeoutMs           *int
	SessionParameters           *SessionParameters
	SuspendTaskAfterNumFailures *int
	ErrorIntegration            *AccountObjectIdentifier
	Comment                     *string
	Finalize                    *SchemaObjectIdentifier
	TaskAutoRetryAttempts       *int
	After                       []SchemaObjectIdentifier
	When                        *string
	sql                         string // required
}

// added manually
func (r *CreateOrAlterTaskRequest) GetName() SchemaObjectIdentifier {
	return r.name
}

type CloneTaskRequest struct {
	OrReplace  *bool
	name       SchemaObjectIdentifier // required
	sourceTask SchemaObjectIdentifier // required
	CopyGrants *bool
}

type AlterTaskRequest struct {
	IfExists      *bool
	name          SchemaObjectIdentifier // required
	Resume        *bool
	Suspend       *bool
	RemoveAfter   []SchemaObjectIdentifier
	AddAfter      []SchemaObjectIdentifier
	Set           *TaskSetRequest
	Unset         *TaskUnsetRequest
	SetTags       []TagAssociation
	UnsetTags     []ObjectIdentifier
	SetFinalize   *SchemaObjectIdentifier
	UnsetFinalize *bool
	ModifyAs      *string
	ModifyWhen    *string
	RemoveWhen    *bool
}

// added manually
func (r *AlterTaskRequest) GetName() SchemaObjectIdentifier {
	return r.name
}

type TaskSetRequest struct {
	Warehouse                               *AccountObjectIdentifier
	UserTaskManagedInitialWarehouseSize     *WarehouseSize
	Schedule                                *string
	Config                                  *string
	AllowOverlappingExecution               *bool
	UserTaskTimeoutMs                       *int
	SuspendTaskAfterNumFailures             *int
	ErrorIntegration                        *AccountObjectIdentifier
	Comment                                 *string
	SessionParameters                       *SessionParameters
	TaskAutoRetryAttempts                   *int
	UserTaskMinimumTriggerIntervalInSeconds *int
}

type TaskUnsetRequest struct {
	Warehouse                               *bool
	UserTaskManagedInitialWarehouseSize     *bool
	Schedule                                *bool
	Config                                  *bool
	AllowOverlappingExecution               *bool
	UserTaskTimeoutMs                       *bool
	SuspendTaskAfterNumFailures             *bool
	ErrorIntegration                        *bool
	Comment                                 *bool
	TaskAutoRetryAttempts                   *bool
	UserTaskMinimumTriggerIntervalInSeconds *bool
	SessionParametersUnset                  *SessionParametersUnset
}

type DropTaskRequest struct {
	IfExists *bool
	name     SchemaObjectIdentifier // required
}

type ShowTaskRequest struct {
	Terse      *bool
	Like       *Like
	In         *ExtendedIn
	StartsWith *string
	RootOnly   *bool
	Limit      *LimitFrom
}

type DescribeTaskRequest struct {
	name SchemaObjectIdentifier // required
}

type ExecuteTaskRequest struct {
	name      SchemaObjectIdentifier // required
	RetryLast *bool
}
