// Code generated by resource model builder generator (v0.1.0); DO NOT EDIT.

package model

import (
	"encoding/json"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/config"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/resources"
	tfconfig "github.com/hashicorp/terraform-plugin-testing/config"
)

type ApiIntegrationGitRepositoryOauth2Model struct {
	Name                       tfconfig.Variable `json:"name,omitempty"`
	ApiAllowedPrefixes         tfconfig.Variable `json:"api_allowed_prefixes,omitempty"`
	ApiBlockedPrefixes         tfconfig.Variable `json:"api_blocked_prefixes,omitempty"`
	Comment                    tfconfig.Variable `json:"comment,omitempty"`
	Enabled                    tfconfig.Variable `json:"enabled,omitempty"`
	FullyQualifiedName         tfconfig.Variable `json:"fully_qualified_name,omitempty"`
	OauthAccessTokenValidity   tfconfig.Variable `json:"oauth_access_token_validity,omitempty"`
	OauthAllowedScopes         tfconfig.Variable `json:"oauth_allowed_scopes,omitempty"`
	OauthAuthorizationEndpoint tfconfig.Variable `json:"oauth_authorization_endpoint,omitempty"`
	OauthClientId              tfconfig.Variable `json:"oauth_client_id,omitempty"`
	OauthClientSecret          tfconfig.Variable `json:"oauth_client_secret,omitempty"`
	OauthRefreshTokenValidity  tfconfig.Variable `json:"oauth_refresh_token_validity,omitempty"`
	OauthTokenEndpoint         tfconfig.Variable `json:"oauth_token_endpoint,omitempty"`
	OauthUsername              tfconfig.Variable `json:"oauth_username,omitempty"`

	DynamicBlock *config.DynamicBlock `json:"dynamic,omitempty"`

	*config.ResourceModelMeta
}

/////////////////////////////////////////////////
// Basic builders (resource name and required) //
/////////////////////////////////////////////////

func ApiIntegrationGitRepositoryOauth2(
	resourceName string,
	name string,
	apiAllowedPrefixes []string,
	enabled bool,
	oauthAuthorizationEndpoint string,
	oauthClientId string,
	oauthClientSecret string,
	oauthTokenEndpoint string,
) *ApiIntegrationGitRepositoryOauth2Model {
	a := &ApiIntegrationGitRepositoryOauth2Model{ResourceModelMeta: config.Meta(resourceName, resources.ApiIntegrationGitRepositoryOauth2)}
	a.WithName(name)
	a.WithApiAllowedPrefixes(apiAllowedPrefixes)
	a.WithEnabled(enabled)
	a.WithOauthAuthorizationEndpoint(oauthAuthorizationEndpoint)
	a.WithOauthClientId(oauthClientId)
	a.WithOauthClientSecret(oauthClientSecret)
	a.WithOauthTokenEndpoint(oauthTokenEndpoint)
	return a
}

func ApiIntegrationGitRepositoryOauth2WithDefaultMeta(
	name string,
	apiAllowedPrefixes []string,
	enabled bool,
	oauthAuthorizationEndpoint string,
	oauthClientId string,
	oauthClientSecret string,
	oauthTokenEndpoint string,
) *ApiIntegrationGitRepositoryOauth2Model {
	a := &ApiIntegrationGitRepositoryOauth2Model{ResourceModelMeta: config.DefaultMeta(resources.ApiIntegrationGitRepositoryOauth2)}
	a.WithName(name)
	a.WithApiAllowedPrefixes(apiAllowedPrefixes)
	a.WithEnabled(enabled)
	a.WithOauthAuthorizationEndpoint(oauthAuthorizationEndpoint)
	a.WithOauthClientId(oauthClientId)
	a.WithOauthClientSecret(oauthClientSecret)
	a.WithOauthTokenEndpoint(oauthTokenEndpoint)
	return a
}

///////////////////////////////////////////////////////////////////////
// set proper json marshalling, handle depends on and dynamic blocks //
///////////////////////////////////////////////////////////////////////

func (a *ApiIntegrationGitRepositoryOauth2Model) MarshalJSON() ([]byte, error) {
	type Alias ApiIntegrationGitRepositoryOauth2Model
	return json.Marshal(&struct {
		*Alias
		DependsOn []string         `json:"depends_on,omitempty"`
		Timeouts  *config.Timeouts `json:"timeouts,omitempty"`
	}{
		Alias:     (*Alias)(a),
		DependsOn: a.DependsOn(),
		Timeouts:  a.Timeouts(),
	})
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithDependsOn(values ...string) *ApiIntegrationGitRepositoryOauth2Model {
	a.SetDependsOn(values...)
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithDynamicBlock(dynamicBlock *config.DynamicBlock) *ApiIntegrationGitRepositoryOauth2Model {
	a.DynamicBlock = dynamicBlock
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithTimeout(timeout config.Timeouts) *ApiIntegrationGitRepositoryOauth2Model {
	a.SetTimeout(timeout)
	return a
}

/////////////////////////////////
// below all the proper values //
/////////////////////////////////

func (a *ApiIntegrationGitRepositoryOauth2Model) WithName(name string) *ApiIntegrationGitRepositoryOauth2Model {
	a.Name = tfconfig.StringVariable(name)
	return a
}

// api_allowed_prefixes attribute type is not yet supported, so WithApiAllowedPrefixes can't be generated

// api_blocked_prefixes attribute type is not yet supported, so WithApiBlockedPrefixes can't be generated

func (a *ApiIntegrationGitRepositoryOauth2Model) WithComment(comment string) *ApiIntegrationGitRepositoryOauth2Model {
	a.Comment = tfconfig.StringVariable(comment)
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithEnabled(enabled bool) *ApiIntegrationGitRepositoryOauth2Model {
	a.Enabled = tfconfig.BoolVariable(enabled)
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithFullyQualifiedName(fullyQualifiedName string) *ApiIntegrationGitRepositoryOauth2Model {
	a.FullyQualifiedName = tfconfig.StringVariable(fullyQualifiedName)
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithOauthAccessTokenValidity(oauthAccessTokenValidity int) *ApiIntegrationGitRepositoryOauth2Model {
	a.OauthAccessTokenValidity = tfconfig.IntegerVariable(oauthAccessTokenValidity)
	return a
}

// oauth_allowed_scopes attribute type is not yet supported, so WithOauthAllowedScopes can't be generated

func (a *ApiIntegrationGitRepositoryOauth2Model) WithOauthAuthorizationEndpoint(oauthAuthorizationEndpoint string) *ApiIntegrationGitRepositoryOauth2Model {
	a.OauthAuthorizationEndpoint = tfconfig.StringVariable(oauthAuthorizationEndpoint)
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithOauthClientId(oauthClientId string) *ApiIntegrationGitRepositoryOauth2Model {
	a.OauthClientId = tfconfig.StringVariable(oauthClientId)
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithOauthClientSecret(oauthClientSecret string) *ApiIntegrationGitRepositoryOauth2Model {
	a.OauthClientSecret = tfconfig.StringVariable(oauthClientSecret)
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithOauthRefreshTokenValidity(oauthRefreshTokenValidity int) *ApiIntegrationGitRepositoryOauth2Model {
	a.OauthRefreshTokenValidity = tfconfig.IntegerVariable(oauthRefreshTokenValidity)
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithOauthTokenEndpoint(oauthTokenEndpoint string) *ApiIntegrationGitRepositoryOauth2Model {
	a.OauthTokenEndpoint = tfconfig.StringVariable(oauthTokenEndpoint)
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithOauthUsername(oauthUsername string) *ApiIntegrationGitRepositoryOauth2Model {
	a.OauthUsername = tfconfig.StringVariable(oauthUsername)
	return a
}

//////////////////////////////////////////
// below it's possible to set any value //
//////////////////////////////////////////

func (a *ApiIntegrationGitRepositoryOauth2Model) WithNameValue(value tfconfig.Variable) *ApiIntegrationGitRepositoryOauth2Model {
	a.Name = value
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithApiAllowedPrefixesValue(value tfconfig.Variable) *ApiIntegrationGitRepositoryOauth2Model {
	a.ApiAllowedPrefixes = value
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithApiBlockedPrefixesValue(value tfconfig.Variable) *ApiIntegrationGitRepositoryOauth2Model {
	a.ApiBlockedPrefixes = value
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithCommentValue(value tfconfig.Variable) *ApiIntegrationGitRepositoryOauth2Model {
	a.Comment = value
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithEnabledValue(value tfconfig.Variable) *ApiIntegrationGitRepositoryOauth2Model {
	a.Enabled = value
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithFullyQualifiedNameValue(value tfconfig.Variable) *ApiIntegrationGitRepositoryOauth2Model {
	a.FullyQualifiedName = value
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithOauthAccessTokenValidityValue(value tfconfig.Variable) *ApiIntegrationGitRepositoryOauth2Model {
	a.OauthAccessTokenValidity = value
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithOauthAllowedScopesValue(value tfconfig.Variable) *ApiIntegrationGitRepositoryOauth2Model {
	a.OauthAllowedScopes = value
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithOauthAuthorizationEndpointValue(value tfconfig.Variable) *ApiIntegrationGitRepositoryOauth2Model {
	a.OauthAuthorizationEndpoint = value
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithOauthClientIdValue(value tfconfig.Variable) *ApiIntegrationGitRepositoryOauth2Model {
	a.OauthClientId = value
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithOauthClientSecretValue(value tfconfig.Variable) *ApiIntegrationGitRepositoryOauth2Model {
	a.OauthClientSecret = value
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithOauthRefreshTokenValidityValue(value tfconfig.Variable) *ApiIntegrationGitRepositoryOauth2Model {
	a.OauthRefreshTokenValidity = value
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithOauthTokenEndpointValue(value tfconfig.Variable) *ApiIntegrationGitRepositoryOauth2Model {
	a.OauthTokenEndpoint = value
	return a
}

func (a *ApiIntegrationGitRepositoryOauth2Model) WithOauthUsernameValue(value tfconfig.Variable) *ApiIntegrationGitRepositoryOauth2Model {
	a.OauthUsername = value
	return a
}
