// Code generated by resource model builder generator (v0.1.0); DO NOT EDIT.

package model

import (
	"encoding/json"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/config"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/resources"
	tfconfig "github.com/hashicorp/terraform-plugin-testing/config"
)

type ExternalS3CompatibleStageModel struct {
	Database           tfconfig.Variable `json:"database,omitempty"`
	Schema             tfconfig.Variable `json:"schema,omitempty"`
	Name               tfconfig.Variable `json:"name,omitempty"`
	Cloud              tfconfig.Variable `json:"cloud,omitempty"`
	Comment            tfconfig.Variable `json:"comment,omitempty"`
	Credentials        tfconfig.Variable `json:"credentials,omitempty"`
	Directory          tfconfig.Variable `json:"directory,omitempty"`
	Endpoint           tfconfig.Variable `json:"endpoint,omitempty"`
	FileFormat         tfconfig.Variable `json:"file_format,omitempty"`
	FullyQualifiedName tfconfig.Variable `json:"fully_qualified_name,omitempty"`
	StageType          tfconfig.Variable `json:"stage_type,omitempty"`
	Url                tfconfig.Variable `json:"url,omitempty"`

	DynamicBlock *config.DynamicBlock `json:"dynamic,omitempty"`

	*config.ResourceModelMeta
}

/////////////////////////////////////////////////
// Basic builders (resource name and required) //
/////////////////////////////////////////////////

func ExternalS3CompatibleStage(
	resourceName string,
	database string,
	schema string,
	name string,
	endpoint string,
	url string,
) *ExternalS3CompatibleStageModel {
	e := &ExternalS3CompatibleStageModel{ResourceModelMeta: config.Meta(resourceName, resources.ExternalS3CompatibleStage)}
	e.WithDatabase(database)
	e.WithSchema(schema)
	e.WithName(name)
	e.WithEndpoint(endpoint)
	e.WithUrl(url)
	return e
}

func ExternalS3CompatibleStageWithDefaultMeta(
	database string,
	schema string,
	name string,
	endpoint string,
	url string,
) *ExternalS3CompatibleStageModel {
	e := &ExternalS3CompatibleStageModel{ResourceModelMeta: config.DefaultMeta(resources.ExternalS3CompatibleStage)}
	e.WithDatabase(database)
	e.WithSchema(schema)
	e.WithName(name)
	e.WithEndpoint(endpoint)
	e.WithUrl(url)
	return e
}

///////////////////////////////////////////////////////////////////////
// set proper json marshalling, handle depends on and dynamic blocks //
///////////////////////////////////////////////////////////////////////

func (e *ExternalS3CompatibleStageModel) MarshalJSON() ([]byte, error) {
	type Alias ExternalS3CompatibleStageModel
	return json.Marshal(&struct {
		*Alias
		DependsOn []string `json:"depends_on,omitempty"`
	}{
		Alias:     (*Alias)(e),
		DependsOn: e.DependsOn(),
	})
}

func (e *ExternalS3CompatibleStageModel) WithDependsOn(values ...string) *ExternalS3CompatibleStageModel {
	e.SetDependsOn(values...)
	return e
}

func (e *ExternalS3CompatibleStageModel) WithDynamicBlock(dynamicBlock *config.DynamicBlock) *ExternalS3CompatibleStageModel {
	e.DynamicBlock = dynamicBlock
	return e
}

/////////////////////////////////
// below all the proper values //
/////////////////////////////////

func (e *ExternalS3CompatibleStageModel) WithDatabase(database string) *ExternalS3CompatibleStageModel {
	e.Database = tfconfig.StringVariable(database)
	return e
}

func (e *ExternalS3CompatibleStageModel) WithSchema(schema string) *ExternalS3CompatibleStageModel {
	e.Schema = tfconfig.StringVariable(schema)
	return e
}

func (e *ExternalS3CompatibleStageModel) WithName(name string) *ExternalS3CompatibleStageModel {
	e.Name = tfconfig.StringVariable(name)
	return e
}

func (e *ExternalS3CompatibleStageModel) WithCloud(cloud string) *ExternalS3CompatibleStageModel {
	e.Cloud = tfconfig.StringVariable(cloud)
	return e
}

func (e *ExternalS3CompatibleStageModel) WithComment(comment string) *ExternalS3CompatibleStageModel {
	e.Comment = tfconfig.StringVariable(comment)
	return e
}

// credentials attribute type is not yet supported, so WithCredentials can't be generated

// directory attribute type is not yet supported, so WithDirectory can't be generated

func (e *ExternalS3CompatibleStageModel) WithEndpoint(endpoint string) *ExternalS3CompatibleStageModel {
	e.Endpoint = tfconfig.StringVariable(endpoint)
	return e
}

// file_format attribute type is not yet supported, so WithFileFormat can't be generated

func (e *ExternalS3CompatibleStageModel) WithFullyQualifiedName(fullyQualifiedName string) *ExternalS3CompatibleStageModel {
	e.FullyQualifiedName = tfconfig.StringVariable(fullyQualifiedName)
	return e
}

func (e *ExternalS3CompatibleStageModel) WithStageType(stageType string) *ExternalS3CompatibleStageModel {
	e.StageType = tfconfig.StringVariable(stageType)
	return e
}

func (e *ExternalS3CompatibleStageModel) WithUrl(url string) *ExternalS3CompatibleStageModel {
	e.Url = tfconfig.StringVariable(url)
	return e
}

//////////////////////////////////////////
// below it's possible to set any value //
//////////////////////////////////////////

func (e *ExternalS3CompatibleStageModel) WithDatabaseValue(value tfconfig.Variable) *ExternalS3CompatibleStageModel {
	e.Database = value
	return e
}

func (e *ExternalS3CompatibleStageModel) WithSchemaValue(value tfconfig.Variable) *ExternalS3CompatibleStageModel {
	e.Schema = value
	return e
}

func (e *ExternalS3CompatibleStageModel) WithNameValue(value tfconfig.Variable) *ExternalS3CompatibleStageModel {
	e.Name = value
	return e
}

func (e *ExternalS3CompatibleStageModel) WithCloudValue(value tfconfig.Variable) *ExternalS3CompatibleStageModel {
	e.Cloud = value
	return e
}

func (e *ExternalS3CompatibleStageModel) WithCommentValue(value tfconfig.Variable) *ExternalS3CompatibleStageModel {
	e.Comment = value
	return e
}

func (e *ExternalS3CompatibleStageModel) WithCredentialsValue(value tfconfig.Variable) *ExternalS3CompatibleStageModel {
	e.Credentials = value
	return e
}

func (e *ExternalS3CompatibleStageModel) WithDirectoryValue(value tfconfig.Variable) *ExternalS3CompatibleStageModel {
	e.Directory = value
	return e
}

func (e *ExternalS3CompatibleStageModel) WithEndpointValue(value tfconfig.Variable) *ExternalS3CompatibleStageModel {
	e.Endpoint = value
	return e
}

func (e *ExternalS3CompatibleStageModel) WithFileFormatValue(value tfconfig.Variable) *ExternalS3CompatibleStageModel {
	e.FileFormat = value
	return e
}

func (e *ExternalS3CompatibleStageModel) WithFullyQualifiedNameValue(value tfconfig.Variable) *ExternalS3CompatibleStageModel {
	e.FullyQualifiedName = value
	return e
}

func (e *ExternalS3CompatibleStageModel) WithStageTypeValue(value tfconfig.Variable) *ExternalS3CompatibleStageModel {
	e.StageType = value
	return e
}

func (e *ExternalS3CompatibleStageModel) WithUrlValue(value tfconfig.Variable) *ExternalS3CompatibleStageModel {
	e.Url = value
	return e
}
