// Code generated by resource model builder generator (v0.1.0); DO NOT EDIT.

package model

import (
	"encoding/json"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/config"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/resources"
	tfconfig "github.com/hashicorp/terraform-plugin-testing/config"
)

type FileFormatXmlModel struct {
	Database                 tfconfig.Variable `json:"database,omitempty"`
	Schema                   tfconfig.Variable `json:"schema,omitempty"`
	Name                     tfconfig.Variable `json:"name,omitempty"`
	Comment                  tfconfig.Variable `json:"comment,omitempty"`
	Compression              tfconfig.Variable `json:"compression,omitempty"`
	DisableAutoConvert       tfconfig.Variable `json:"disable_auto_convert,omitempty"`
	DisableSnowflakeData     tfconfig.Variable `json:"disable_snowflake_data,omitempty"`
	FullyQualifiedName       tfconfig.Variable `json:"fully_qualified_name,omitempty"`
	IgnoreUtf8Errors         tfconfig.Variable `json:"ignore_utf8_errors,omitempty"`
	PreserveSpace            tfconfig.Variable `json:"preserve_space,omitempty"`
	ReplaceInvalidCharacters tfconfig.Variable `json:"replace_invalid_characters,omitempty"`
	SkipByteOrderMark        tfconfig.Variable `json:"skip_byte_order_mark,omitempty"`
	StripOuterElement        tfconfig.Variable `json:"strip_outer_element,omitempty"`
	Type_                    tfconfig.Variable `json:"type,omitempty"`

	DynamicBlock *config.DynamicBlock `json:"dynamic,omitempty"`

	*config.ResourceModelMeta
}

/////////////////////////////////////////////////
// Basic builders (resource name and required) //
/////////////////////////////////////////////////

func FileFormatXml(
	resourceName string,
	database string,
	schema string,
	name string,
) *FileFormatXmlModel {
	f := &FileFormatXmlModel{ResourceModelMeta: config.Meta(resourceName, resources.FileFormatXml)}
	f.WithDatabase(database)
	f.WithSchema(schema)
	f.WithName(name)
	return f
}

func FileFormatXmlWithDefaultMeta(
	database string,
	schema string,
	name string,
) *FileFormatXmlModel {
	f := &FileFormatXmlModel{ResourceModelMeta: config.DefaultMeta(resources.FileFormatXml)}
	f.WithDatabase(database)
	f.WithSchema(schema)
	f.WithName(name)
	return f
}

///////////////////////////////////////////////////////////////////////
// set proper json marshalling, handle depends on and dynamic blocks //
///////////////////////////////////////////////////////////////////////

func (f *FileFormatXmlModel) MarshalJSON() ([]byte, error) {
	type Alias FileFormatXmlModel
	return json.Marshal(&struct {
		*Alias
		DependsOn []string         `json:"depends_on,omitempty"`
		Timeouts  *config.Timeouts `json:"timeouts,omitempty"`
	}{
		Alias:     (*Alias)(f),
		DependsOn: f.DependsOn(),
		Timeouts:  f.Timeouts(),
	})
}

func (f *FileFormatXmlModel) WithDependsOn(values ...string) *FileFormatXmlModel {
	f.SetDependsOn(values...)
	return f
}

func (f *FileFormatXmlModel) WithDynamicBlock(dynamicBlock *config.DynamicBlock) *FileFormatXmlModel {
	f.DynamicBlock = dynamicBlock
	return f
}

func (f *FileFormatXmlModel) WithTimeout(timeout config.Timeouts) *FileFormatXmlModel {
	f.SetTimeout(timeout)
	return f
}

/////////////////////////////////
// below all the proper values //
/////////////////////////////////

func (f *FileFormatXmlModel) WithDatabase(database string) *FileFormatXmlModel {
	f.Database = tfconfig.StringVariable(database)
	return f
}

func (f *FileFormatXmlModel) WithSchema(schema string) *FileFormatXmlModel {
	f.Schema = tfconfig.StringVariable(schema)
	return f
}

func (f *FileFormatXmlModel) WithName(name string) *FileFormatXmlModel {
	f.Name = tfconfig.StringVariable(name)
	return f
}

func (f *FileFormatXmlModel) WithComment(comment string) *FileFormatXmlModel {
	f.Comment = tfconfig.StringVariable(comment)
	return f
}

func (f *FileFormatXmlModel) WithCompression(compression string) *FileFormatXmlModel {
	f.Compression = tfconfig.StringVariable(compression)
	return f
}

func (f *FileFormatXmlModel) WithDisableAutoConvert(disableAutoConvert string) *FileFormatXmlModel {
	f.DisableAutoConvert = tfconfig.StringVariable(disableAutoConvert)
	return f
}

func (f *FileFormatXmlModel) WithDisableSnowflakeData(disableSnowflakeData string) *FileFormatXmlModel {
	f.DisableSnowflakeData = tfconfig.StringVariable(disableSnowflakeData)
	return f
}

func (f *FileFormatXmlModel) WithFullyQualifiedName(fullyQualifiedName string) *FileFormatXmlModel {
	f.FullyQualifiedName = tfconfig.StringVariable(fullyQualifiedName)
	return f
}

func (f *FileFormatXmlModel) WithIgnoreUtf8Errors(ignoreUtf8Errors string) *FileFormatXmlModel {
	f.IgnoreUtf8Errors = tfconfig.StringVariable(ignoreUtf8Errors)
	return f
}

func (f *FileFormatXmlModel) WithPreserveSpace(preserveSpace string) *FileFormatXmlModel {
	f.PreserveSpace = tfconfig.StringVariable(preserveSpace)
	return f
}

func (f *FileFormatXmlModel) WithReplaceInvalidCharacters(replaceInvalidCharacters string) *FileFormatXmlModel {
	f.ReplaceInvalidCharacters = tfconfig.StringVariable(replaceInvalidCharacters)
	return f
}

func (f *FileFormatXmlModel) WithSkipByteOrderMark(skipByteOrderMark string) *FileFormatXmlModel {
	f.SkipByteOrderMark = tfconfig.StringVariable(skipByteOrderMark)
	return f
}

func (f *FileFormatXmlModel) WithStripOuterElement(stripOuterElement string) *FileFormatXmlModel {
	f.StripOuterElement = tfconfig.StringVariable(stripOuterElement)
	return f
}

func (f *FileFormatXmlModel) WithType(type_ string) *FileFormatXmlModel {
	f.Type_ = tfconfig.StringVariable(type_)
	return f
}

//////////////////////////////////////////
// below it's possible to set any value //
//////////////////////////////////////////

func (f *FileFormatXmlModel) WithDatabaseValue(value tfconfig.Variable) *FileFormatXmlModel {
	f.Database = value
	return f
}

func (f *FileFormatXmlModel) WithSchemaValue(value tfconfig.Variable) *FileFormatXmlModel {
	f.Schema = value
	return f
}

func (f *FileFormatXmlModel) WithNameValue(value tfconfig.Variable) *FileFormatXmlModel {
	f.Name = value
	return f
}

func (f *FileFormatXmlModel) WithCommentValue(value tfconfig.Variable) *FileFormatXmlModel {
	f.Comment = value
	return f
}

func (f *FileFormatXmlModel) WithCompressionValue(value tfconfig.Variable) *FileFormatXmlModel {
	f.Compression = value
	return f
}

func (f *FileFormatXmlModel) WithDisableAutoConvertValue(value tfconfig.Variable) *FileFormatXmlModel {
	f.DisableAutoConvert = value
	return f
}

func (f *FileFormatXmlModel) WithDisableSnowflakeDataValue(value tfconfig.Variable) *FileFormatXmlModel {
	f.DisableSnowflakeData = value
	return f
}

func (f *FileFormatXmlModel) WithFullyQualifiedNameValue(value tfconfig.Variable) *FileFormatXmlModel {
	f.FullyQualifiedName = value
	return f
}

func (f *FileFormatXmlModel) WithIgnoreUtf8ErrorsValue(value tfconfig.Variable) *FileFormatXmlModel {
	f.IgnoreUtf8Errors = value
	return f
}

func (f *FileFormatXmlModel) WithPreserveSpaceValue(value tfconfig.Variable) *FileFormatXmlModel {
	f.PreserveSpace = value
	return f
}

func (f *FileFormatXmlModel) WithReplaceInvalidCharactersValue(value tfconfig.Variable) *FileFormatXmlModel {
	f.ReplaceInvalidCharacters = value
	return f
}

func (f *FileFormatXmlModel) WithSkipByteOrderMarkValue(value tfconfig.Variable) *FileFormatXmlModel {
	f.SkipByteOrderMark = value
	return f
}

func (f *FileFormatXmlModel) WithStripOuterElementValue(value tfconfig.Variable) *FileFormatXmlModel {
	f.StripOuterElement = value
	return f
}

func (f *FileFormatXmlModel) WithTypeValue(value tfconfig.Variable) *FileFormatXmlModel {
	f.Type_ = value
	return f
}
