// Code generated by resource model builder generator (v0.1.0); DO NOT EDIT.

package model

import (
	"encoding/json"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/config"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/resources"
	tfconfig "github.com/hashicorp/terraform-plugin-testing/config"
)

type FileFormatAvroModel struct {
	Database                 tfconfig.Variable `json:"database,omitempty"`
	Schema                   tfconfig.Variable `json:"schema,omitempty"`
	Name                     tfconfig.Variable `json:"name,omitempty"`
	Comment                  tfconfig.Variable `json:"comment,omitempty"`
	Compression              tfconfig.Variable `json:"compression,omitempty"`
	FullyQualifiedName       tfconfig.Variable `json:"fully_qualified_name,omitempty"`
	NullIf                   tfconfig.Variable `json:"null_if,omitempty"`
	ReplaceInvalidCharacters tfconfig.Variable `json:"replace_invalid_characters,omitempty"`
	TrimSpace                tfconfig.Variable `json:"trim_space,omitempty"`
	Type_                    tfconfig.Variable `json:"type,omitempty"`

	DynamicBlock *config.DynamicBlock `json:"dynamic,omitempty"`

	*config.ResourceModelMeta
}

/////////////////////////////////////////////////
// Basic builders (resource name and required) //
/////////////////////////////////////////////////

func FileFormatAvro(
	resourceName string,
	database string,
	schema string,
	name string,
) *FileFormatAvroModel {
	f := &FileFormatAvroModel{ResourceModelMeta: config.Meta(resourceName, resources.FileFormatAvro)}
	f.WithDatabase(database)
	f.WithSchema(schema)
	f.WithName(name)
	return f
}

func FileFormatAvroWithDefaultMeta(
	database string,
	schema string,
	name string,
) *FileFormatAvroModel {
	f := &FileFormatAvroModel{ResourceModelMeta: config.DefaultMeta(resources.FileFormatAvro)}
	f.WithDatabase(database)
	f.WithSchema(schema)
	f.WithName(name)
	return f
}

///////////////////////////////////////////////////////////////////////
// set proper json marshalling, handle depends on and dynamic blocks //
///////////////////////////////////////////////////////////////////////

func (f *FileFormatAvroModel) MarshalJSON() ([]byte, error) {
	type Alias FileFormatAvroModel
	return json.Marshal(&struct {
		*Alias
		DependsOn []string         `json:"depends_on,omitempty"`
		Timeouts  *config.Timeouts `json:"timeouts,omitempty"`
	}{
		Alias:     (*Alias)(f),
		DependsOn: f.DependsOn(),
		Timeouts:  f.Timeouts(),
	})
}

func (f *FileFormatAvroModel) WithDependsOn(values ...string) *FileFormatAvroModel {
	f.SetDependsOn(values...)
	return f
}

func (f *FileFormatAvroModel) WithDynamicBlock(dynamicBlock *config.DynamicBlock) *FileFormatAvroModel {
	f.DynamicBlock = dynamicBlock
	return f
}

func (f *FileFormatAvroModel) WithTimeout(timeout config.Timeouts) *FileFormatAvroModel {
	f.SetTimeout(timeout)
	return f
}

/////////////////////////////////
// below all the proper values //
/////////////////////////////////

func (f *FileFormatAvroModel) WithDatabase(database string) *FileFormatAvroModel {
	f.Database = tfconfig.StringVariable(database)
	return f
}

func (f *FileFormatAvroModel) WithSchema(schema string) *FileFormatAvroModel {
	f.Schema = tfconfig.StringVariable(schema)
	return f
}

func (f *FileFormatAvroModel) WithName(name string) *FileFormatAvroModel {
	f.Name = tfconfig.StringVariable(name)
	return f
}

func (f *FileFormatAvroModel) WithComment(comment string) *FileFormatAvroModel {
	f.Comment = tfconfig.StringVariable(comment)
	return f
}

func (f *FileFormatAvroModel) WithCompression(compression string) *FileFormatAvroModel {
	f.Compression = tfconfig.StringVariable(compression)
	return f
}

func (f *FileFormatAvroModel) WithFullyQualifiedName(fullyQualifiedName string) *FileFormatAvroModel {
	f.FullyQualifiedName = tfconfig.StringVariable(fullyQualifiedName)
	return f
}

// null_if attribute type is not yet supported, so WithNullIf can't be generated

func (f *FileFormatAvroModel) WithReplaceInvalidCharacters(replaceInvalidCharacters string) *FileFormatAvroModel {
	f.ReplaceInvalidCharacters = tfconfig.StringVariable(replaceInvalidCharacters)
	return f
}

func (f *FileFormatAvroModel) WithTrimSpace(trimSpace string) *FileFormatAvroModel {
	f.TrimSpace = tfconfig.StringVariable(trimSpace)
	return f
}

func (f *FileFormatAvroModel) WithType(type_ string) *FileFormatAvroModel {
	f.Type_ = tfconfig.StringVariable(type_)
	return f
}

//////////////////////////////////////////
// below it's possible to set any value //
//////////////////////////////////////////

func (f *FileFormatAvroModel) WithDatabaseValue(value tfconfig.Variable) *FileFormatAvroModel {
	f.Database = value
	return f
}

func (f *FileFormatAvroModel) WithSchemaValue(value tfconfig.Variable) *FileFormatAvroModel {
	f.Schema = value
	return f
}

func (f *FileFormatAvroModel) WithNameValue(value tfconfig.Variable) *FileFormatAvroModel {
	f.Name = value
	return f
}

func (f *FileFormatAvroModel) WithCommentValue(value tfconfig.Variable) *FileFormatAvroModel {
	f.Comment = value
	return f
}

func (f *FileFormatAvroModel) WithCompressionValue(value tfconfig.Variable) *FileFormatAvroModel {
	f.Compression = value
	return f
}

func (f *FileFormatAvroModel) WithFullyQualifiedNameValue(value tfconfig.Variable) *FileFormatAvroModel {
	f.FullyQualifiedName = value
	return f
}

func (f *FileFormatAvroModel) WithNullIfValue(value tfconfig.Variable) *FileFormatAvroModel {
	f.NullIf = value
	return f
}

func (f *FileFormatAvroModel) WithReplaceInvalidCharactersValue(value tfconfig.Variable) *FileFormatAvroModel {
	f.ReplaceInvalidCharacters = value
	return f
}

func (f *FileFormatAvroModel) WithTrimSpaceValue(value tfconfig.Variable) *FileFormatAvroModel {
	f.TrimSpace = value
	return f
}

func (f *FileFormatAvroModel) WithTypeValue(value tfconfig.Variable) *FileFormatAvroModel {
	f.Type_ = value
	return f
}
