// Code generated by resource model builder generator (v0.1.0); DO NOT EDIT.

package model

import (
	"encoding/json"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/config"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/resources"
	tfconfig "github.com/hashicorp/terraform-plugin-testing/config"
)

type IcebergTableFromAwsGlueModel struct {
	Database                 tfconfig.Variable `json:"database,omitempty"`
	Schema                   tfconfig.Variable `json:"schema,omitempty"`
	Name                     tfconfig.Variable `json:"name,omitempty"`
	AutoRefresh              tfconfig.Variable `json:"auto_refresh,omitempty"`
	Catalog                  tfconfig.Variable `json:"catalog,omitempty"`
	CatalogNamespace         tfconfig.Variable `json:"catalog_namespace,omitempty"`
	CatalogTableName         tfconfig.Variable `json:"catalog_table_name,omitempty"`
	Comment                  tfconfig.Variable `json:"comment,omitempty"`
	ExternalVolume           tfconfig.Variable `json:"external_volume,omitempty"`
	FullyQualifiedName       tfconfig.Variable `json:"fully_qualified_name,omitempty"`
	ReplaceInvalidCharacters tfconfig.Variable `json:"replace_invalid_characters,omitempty"`

	DynamicBlock *config.DynamicBlock `json:"dynamic,omitempty"`

	*config.ResourceModelMeta
}

/////////////////////////////////////////////////
// Basic builders (resource name and required) //
/////////////////////////////////////////////////

func IcebergTableFromAwsGlue(
	resourceName string,
	database string,
	schema string,
	name string,
	catalogTableName string,
) *IcebergTableFromAwsGlueModel {
	i := &IcebergTableFromAwsGlueModel{ResourceModelMeta: config.Meta(resourceName, resources.IcebergTableFromAwsGlue)}
	i.WithDatabase(database)
	i.WithSchema(schema)
	i.WithName(name)
	i.WithCatalogTableName(catalogTableName)
	return i
}

func IcebergTableFromAwsGlueWithDefaultMeta(
	database string,
	schema string,
	name string,
	catalogTableName string,
) *IcebergTableFromAwsGlueModel {
	i := &IcebergTableFromAwsGlueModel{ResourceModelMeta: config.DefaultMeta(resources.IcebergTableFromAwsGlue)}
	i.WithDatabase(database)
	i.WithSchema(schema)
	i.WithName(name)
	i.WithCatalogTableName(catalogTableName)
	return i
}

///////////////////////////////////////////////////////////////////////
// set proper json marshalling, handle depends on and dynamic blocks //
///////////////////////////////////////////////////////////////////////

func (i *IcebergTableFromAwsGlueModel) MarshalJSON() ([]byte, error) {
	type Alias IcebergTableFromAwsGlueModel
	return json.Marshal(&struct {
		*Alias
		DependsOn []string         `json:"depends_on,omitempty"`
		Timeouts  *config.Timeouts `json:"timeouts,omitempty"`
	}{
		Alias:     (*Alias)(i),
		DependsOn: i.DependsOn(),
		Timeouts:  i.Timeouts(),
	})
}

func (i *IcebergTableFromAwsGlueModel) WithDependsOn(values ...string) *IcebergTableFromAwsGlueModel {
	i.SetDependsOn(values...)
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithDynamicBlock(dynamicBlock *config.DynamicBlock) *IcebergTableFromAwsGlueModel {
	i.DynamicBlock = dynamicBlock
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithTimeout(timeout config.Timeouts) *IcebergTableFromAwsGlueModel {
	i.SetTimeout(timeout)
	return i
}

/////////////////////////////////
// below all the proper values //
/////////////////////////////////

func (i *IcebergTableFromAwsGlueModel) WithDatabase(database string) *IcebergTableFromAwsGlueModel {
	i.Database = tfconfig.StringVariable(database)
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithSchema(schema string) *IcebergTableFromAwsGlueModel {
	i.Schema = tfconfig.StringVariable(schema)
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithName(name string) *IcebergTableFromAwsGlueModel {
	i.Name = tfconfig.StringVariable(name)
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithAutoRefresh(autoRefresh string) *IcebergTableFromAwsGlueModel {
	i.AutoRefresh = tfconfig.StringVariable(autoRefresh)
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithCatalog(catalog string) *IcebergTableFromAwsGlueModel {
	i.Catalog = tfconfig.StringVariable(catalog)
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithCatalogNamespace(catalogNamespace string) *IcebergTableFromAwsGlueModel {
	i.CatalogNamespace = tfconfig.StringVariable(catalogNamespace)
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithCatalogTableName(catalogTableName string) *IcebergTableFromAwsGlueModel {
	i.CatalogTableName = tfconfig.StringVariable(catalogTableName)
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithComment(comment string) *IcebergTableFromAwsGlueModel {
	i.Comment = tfconfig.StringVariable(comment)
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithExternalVolume(externalVolume string) *IcebergTableFromAwsGlueModel {
	i.ExternalVolume = tfconfig.StringVariable(externalVolume)
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithFullyQualifiedName(fullyQualifiedName string) *IcebergTableFromAwsGlueModel {
	i.FullyQualifiedName = tfconfig.StringVariable(fullyQualifiedName)
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithReplaceInvalidCharacters(replaceInvalidCharacters bool) *IcebergTableFromAwsGlueModel {
	i.ReplaceInvalidCharacters = tfconfig.BoolVariable(replaceInvalidCharacters)
	return i
}

//////////////////////////////////////////
// below it's possible to set any value //
//////////////////////////////////////////

func (i *IcebergTableFromAwsGlueModel) WithDatabaseValue(value tfconfig.Variable) *IcebergTableFromAwsGlueModel {
	i.Database = value
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithSchemaValue(value tfconfig.Variable) *IcebergTableFromAwsGlueModel {
	i.Schema = value
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithNameValue(value tfconfig.Variable) *IcebergTableFromAwsGlueModel {
	i.Name = value
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithAutoRefreshValue(value tfconfig.Variable) *IcebergTableFromAwsGlueModel {
	i.AutoRefresh = value
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithCatalogValue(value tfconfig.Variable) *IcebergTableFromAwsGlueModel {
	i.Catalog = value
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithCatalogNamespaceValue(value tfconfig.Variable) *IcebergTableFromAwsGlueModel {
	i.CatalogNamespace = value
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithCatalogTableNameValue(value tfconfig.Variable) *IcebergTableFromAwsGlueModel {
	i.CatalogTableName = value
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithCommentValue(value tfconfig.Variable) *IcebergTableFromAwsGlueModel {
	i.Comment = value
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithExternalVolumeValue(value tfconfig.Variable) *IcebergTableFromAwsGlueModel {
	i.ExternalVolume = value
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithFullyQualifiedNameValue(value tfconfig.Variable) *IcebergTableFromAwsGlueModel {
	i.FullyQualifiedName = value
	return i
}

func (i *IcebergTableFromAwsGlueModel) WithReplaceInvalidCharactersValue(value tfconfig.Variable) *IcebergTableFromAwsGlueModel {
	i.ReplaceInvalidCharacters = value
	return i
}
