// Code generated by resource model builder generator (v0.1.0); DO NOT EDIT.

package model

import (
	"encoding/json"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/config"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/resources"
	tfconfig "github.com/hashicorp/terraform-plugin-testing/config"
)

type PostgresForkModel struct {
	Name               tfconfig.Variable `json:"name,omitempty"`
	At                 tfconfig.Variable `json:"at,omitempty"`
	Before             tfconfig.Variable `json:"before,omitempty"`
	Comment            tfconfig.Variable `json:"comment,omitempty"`
	ComputeFamily      tfconfig.Variable `json:"compute_family,omitempty"`
	ForkFrom           tfconfig.Variable `json:"fork_from,omitempty"`
	FullyQualifiedName tfconfig.Variable `json:"fully_qualified_name,omitempty"`
	HighAvailability   tfconfig.Variable `json:"high_availability,omitempty"`
	PostgresSettings   tfconfig.Variable `json:"postgres_settings,omitempty"`
	StorageSizeGb      tfconfig.Variable `json:"storage_size_gb,omitempty"`

	DynamicBlock *config.DynamicBlock `json:"dynamic,omitempty"`

	*config.ResourceModelMeta
}

/////////////////////////////////////////////////
// Basic builders (resource name and required) //
/////////////////////////////////////////////////

func PostgresFork(
	resourceName string,
	name string,
	forkFrom string,
) *PostgresForkModel {
	p := &PostgresForkModel{ResourceModelMeta: config.Meta(resourceName, resources.PostgresFork)}
	p.WithName(name)
	p.WithForkFrom(forkFrom)
	return p
}

func PostgresForkWithDefaultMeta(
	name string,
	forkFrom string,
) *PostgresForkModel {
	p := &PostgresForkModel{ResourceModelMeta: config.DefaultMeta(resources.PostgresFork)}
	p.WithName(name)
	p.WithForkFrom(forkFrom)
	return p
}

///////////////////////////////////////////////////////////////////////
// set proper json marshalling, handle depends on and dynamic blocks //
///////////////////////////////////////////////////////////////////////

func (p *PostgresForkModel) MarshalJSON() ([]byte, error) {
	type Alias PostgresForkModel
	return json.Marshal(&struct {
		*Alias
		DependsOn []string `json:"depends_on,omitempty"`
	}{
		Alias:     (*Alias)(p),
		DependsOn: p.DependsOn(),
	})
}

func (p *PostgresForkModel) WithDependsOn(values ...string) *PostgresForkModel {
	p.SetDependsOn(values...)
	return p
}

func (p *PostgresForkModel) WithDynamicBlock(dynamicBlock *config.DynamicBlock) *PostgresForkModel {
	p.DynamicBlock = dynamicBlock
	return p
}

/////////////////////////////////
// below all the proper values //
/////////////////////////////////

func (p *PostgresForkModel) WithName(name string) *PostgresForkModel {
	p.Name = tfconfig.StringVariable(name)
	return p
}

// at attribute type is not yet supported, so WithAt can't be generated

// before attribute type is not yet supported, so WithBefore can't be generated

func (p *PostgresForkModel) WithComment(comment string) *PostgresForkModel {
	p.Comment = tfconfig.StringVariable(comment)
	return p
}

func (p *PostgresForkModel) WithComputeFamily(computeFamily string) *PostgresForkModel {
	p.ComputeFamily = tfconfig.StringVariable(computeFamily)
	return p
}

func (p *PostgresForkModel) WithForkFrom(forkFrom string) *PostgresForkModel {
	p.ForkFrom = tfconfig.StringVariable(forkFrom)
	return p
}

func (p *PostgresForkModel) WithFullyQualifiedName(fullyQualifiedName string) *PostgresForkModel {
	p.FullyQualifiedName = tfconfig.StringVariable(fullyQualifiedName)
	return p
}

func (p *PostgresForkModel) WithHighAvailability(highAvailability bool) *PostgresForkModel {
	p.HighAvailability = tfconfig.BoolVariable(highAvailability)
	return p
}

func (p *PostgresForkModel) WithPostgresSettings(postgresSettings string) *PostgresForkModel {
	p.PostgresSettings = tfconfig.StringVariable(postgresSettings)
	return p
}

func (p *PostgresForkModel) WithStorageSizeGb(storageSizeGb int) *PostgresForkModel {
	p.StorageSizeGb = tfconfig.IntegerVariable(storageSizeGb)
	return p
}

//////////////////////////////////////////
// below it's possible to set any value //
//////////////////////////////////////////

func (p *PostgresForkModel) WithNameValue(value tfconfig.Variable) *PostgresForkModel {
	p.Name = value
	return p
}

func (p *PostgresForkModel) WithAtValue(value tfconfig.Variable) *PostgresForkModel {
	p.At = value
	return p
}

func (p *PostgresForkModel) WithBeforeValue(value tfconfig.Variable) *PostgresForkModel {
	p.Before = value
	return p
}

func (p *PostgresForkModel) WithCommentValue(value tfconfig.Variable) *PostgresForkModel {
	p.Comment = value
	return p
}

func (p *PostgresForkModel) WithComputeFamilyValue(value tfconfig.Variable) *PostgresForkModel {
	p.ComputeFamily = value
	return p
}

func (p *PostgresForkModel) WithForkFromValue(value tfconfig.Variable) *PostgresForkModel {
	p.ForkFrom = value
	return p
}

func (p *PostgresForkModel) WithFullyQualifiedNameValue(value tfconfig.Variable) *PostgresForkModel {
	p.FullyQualifiedName = value
	return p
}

func (p *PostgresForkModel) WithHighAvailabilityValue(value tfconfig.Variable) *PostgresForkModel {
	p.HighAvailability = value
	return p
}

func (p *PostgresForkModel) WithPostgresSettingsValue(value tfconfig.Variable) *PostgresForkModel {
	p.PostgresSettings = value
	return p
}

func (p *PostgresForkModel) WithStorageSizeGbValue(value tfconfig.Variable) *PostgresForkModel {
	p.StorageSizeGb = value
	return p
}
