// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package example

var _ validatable = new(CreateCustomInterfaceMethodExampleOptions)

func (opts *CreateCustomInterfaceMethodExampleOptions) validate() error {
	if opts == nil {
		return ErrNilOptions
	}
	var errs []error
	return JoinErrors(errs...)
}
