// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package example

import (
	"context"
)

var _ CustomInterfaceMethodExamples = (*customInterfaceMethodExamples)(nil)

type customInterfaceMethodExamples struct {
	client *Client
}

func (v *customInterfaceMethodExamples) Create(ctx context.Context, request *CreateCustomInterfaceMethodExampleRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (r *CreateCustomInterfaceMethodExampleRequest) toOpts() *CreateCustomInterfaceMethodExampleOptions {
	opts := &CreateCustomInterfaceMethodExampleOptions{
		name: r.name,
	}
	return opts
}
