// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package example

import (
	"context"
)

type DropSafelyForceExamples interface {
	Drop(ctx context.Context, request *DropDropSafelyForceExampleRequest) error
	DropSafely(ctx context.Context, id AccountObjectIdentifier) error
}

// DropDropSafelyForceExampleOptions is based on https://example.com.
type DropDropSafelyForceExampleOptions struct {
	drop     bool                    `ddl:"static" sql:"DROP"`
	whatever bool                    `ddl:"static" sql:"WHATEVER"`
	IfExists *bool                   `ddl:"keyword" sql:"IF EXISTS"`
	Force    *bool                   `ddl:"keyword" sql:"FORCE"`
	name     AccountObjectIdentifier `ddl:"identifier"`
}
