// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package example

var _ optionsProvider[DropDropSafelyForceExampleOptions] = new(DropDropSafelyForceExampleRequest)

type DropDropSafelyForceExampleRequest struct {
	IfExists *bool
	Force    *bool
	name     AccountObjectIdentifier // required
}
