// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package example

import (
	"context"
)

type SliceValidationExamples interface {
	Create(ctx context.Context, request *CreateSliceValidationExampleRequest) error
}

// CreateSliceValidationExampleOptions is based on https://example.com.
type CreateSliceValidationExampleOptions struct {
	create                 bool                    `ddl:"static" sql:"CREATE"`
	sliceValidationExample bool                    `ddl:"static" sql:"SLICE VALIDATION EXAMPLE"`
	name                   AccountObjectIdentifier `ddl:"identifier"`
	DualChecks             []DualCheckItem         `ddl:"keyword" sql:"DUAL_CHECKS"`
	PlainItems             []PlainItem             `ddl:"keyword" sql:"PLAIN_ITEMS"`
	CheckedItems           []CheckedItem           `ddl:"keyword" sql:"CHECKED_ITEMS"`
	Items                  []NestedListItem        `ddl:"keyword" sql:"ITEMS"`
}

type DualCheckItem struct {
	A *string `ddl:"keyword"`
	B *string `ddl:"keyword"`
	C *string `ddl:"keyword"`
}

type PlainItem struct {
	Nested *NestedNoOwn `ddl:"keyword"`
}

type NestedNoOwn struct {
	X *string `ddl:"keyword"`
	Y *string `ddl:"keyword"`
}

type CheckedItem struct {
	Left   *string        `ddl:"keyword"`
	Right  *string        `ddl:"keyword"`
	Nested *NestedWithOwn `ddl:"keyword"`
}

type NestedWithOwn struct {
	P *string `ddl:"keyword"`
	Q *string `ddl:"keyword"`
}

type NestedListItem struct {
	SubItems []SubItem `ddl:"keyword" sql:"SUB_ITEMS"`
}

type SubItem struct {
	Name  *string `ddl:"keyword"`
	Alias *string `ddl:"keyword"`
}
