// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package example

func NewCreateToOptsOptionalExampleRequest(
	name DatabaseObjectIdentifier,
) *CreateToOptsOptionalExampleRequest {
	s := CreateToOptsOptionalExampleRequest{}
	s.name = name
	return &s
}

func (s *CreateToOptsOptionalExampleRequest) WithIfExists(ifExists bool) *CreateToOptsOptionalExampleRequest {
	s.IfExists = &ifExists
	return s
}

func NewAlterToOptsOptionalExampleRequest(
	name DatabaseObjectIdentifier,
	requiredField RequiredFieldRequest,
) *AlterToOptsOptionalExampleRequest {
	s := AlterToOptsOptionalExampleRequest{}
	s.name = name
	s.RequiredField = requiredField
	return &s
}

func (s *AlterToOptsOptionalExampleRequest) WithIfExists(ifExists bool) *AlterToOptsOptionalExampleRequest {
	s.IfExists = &ifExists
	return s
}

func (s *AlterToOptsOptionalExampleRequest) WithOptionalField(optionalField OptionalFieldRequest) *AlterToOptsOptionalExampleRequest {
	s.OptionalField = &optionalField
	return s
}

func NewOptionalFieldRequest() *OptionalFieldRequest {
	s := OptionalFieldRequest{}
	return &s
}

func (s *OptionalFieldRequest) WithSomeList(someList []DatabaseObjectIdentifier) *OptionalFieldRequest {
	s.SomeList = someList
	return s
}

func NewRequiredFieldRequest(
	someRequiredList []DatabaseObjectIdentifier,
) *RequiredFieldRequest {
	s := RequiredFieldRequest{}
	s.SomeRequiredList = someRequiredList
	return &s
}
