// Code generated by resource parameter assertions generator (v0.1.0); DO NOT EDIT.

package resourceparametersassert

import (
	"testing"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

type FunctionResourceParametersAssert struct {
	*assert.ResourceAssert
}

func FunctionResourceParameters(t *testing.T, name string) *FunctionResourceParametersAssert {
	t.Helper()

	resourceParameterAssert := FunctionResourceParametersAssert{
		ResourceAssert: assert.NewResourceParametersAssert(name),
	}
	return &resourceParameterAssert
}

func ImportedFunctionResourceParameters(t *testing.T, id string) *FunctionResourceParametersAssert {
	t.Helper()

	resourceParameterAssert := FunctionResourceParametersAssert{
		ResourceAssert: assert.NewImportedResourceParametersAssert(id),
	}
	return &resourceParameterAssert
}

////////////////////////////
// Parameter value checks //
////////////////////////////

func (f *FunctionResourceParametersAssert) HasEnableConsoleOutput(expected bool) *FunctionResourceParametersAssert {
	f.ParameterBoolValueSet(string(sdk.FunctionParameterEnableConsoleOutput), expected)
	return f
}

func (f *FunctionResourceParametersAssert) HasLogLevel(expected sdk.LogLevel) *FunctionResourceParametersAssert {
	f.ParameterValueSet(string(sdk.FunctionParameterLogLevel), string(expected))
	return f
}

func (f *FunctionResourceParametersAssert) HasLogEventLevel(expected sdk.LogLevel) *FunctionResourceParametersAssert {
	f.ParameterValueSet(string(sdk.FunctionParameterLogEventLevel), string(expected))
	return f
}

func (f *FunctionResourceParametersAssert) HasMetricLevel(expected sdk.MetricLevel) *FunctionResourceParametersAssert {
	f.ParameterValueSet(string(sdk.FunctionParameterMetricLevel), string(expected))
	return f
}

func (f *FunctionResourceParametersAssert) HasTraceLevel(expected sdk.TraceLevel) *FunctionResourceParametersAssert {
	f.ParameterValueSet(string(sdk.FunctionParameterTraceLevel), string(expected))
	return f
}

////////////////////////////
// Parameter level checks //
////////////////////////////

func (f *FunctionResourceParametersAssert) HasEnableConsoleOutputLevel(expected sdk.ParameterType) *FunctionResourceParametersAssert {
	f.ParameterLevelSet(string(sdk.FunctionParameterEnableConsoleOutput), expected)
	return f
}

func (f *FunctionResourceParametersAssert) HasLogLevelLevel(expected sdk.ParameterType) *FunctionResourceParametersAssert {
	f.ParameterLevelSet(string(sdk.FunctionParameterLogLevel), expected)
	return f
}

func (f *FunctionResourceParametersAssert) HasLogEventLevelLevel(expected sdk.ParameterType) *FunctionResourceParametersAssert {
	f.ParameterLevelSet(string(sdk.FunctionParameterLogEventLevel), expected)
	return f
}

func (f *FunctionResourceParametersAssert) HasMetricLevelLevel(expected sdk.ParameterType) *FunctionResourceParametersAssert {
	f.ParameterLevelSet(string(sdk.FunctionParameterMetricLevel), expected)
	return f
}

func (f *FunctionResourceParametersAssert) HasTraceLevelLevel(expected sdk.ParameterType) *FunctionResourceParametersAssert {
	f.ParameterLevelSet(string(sdk.FunctionParameterTraceLevel), expected)
	return f
}
