// Code generated by resource assertions generator (v0.1.0); DO NOT EDIT.

package resourceassert

import (
	"testing"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
)

type IcebergTableFromFilesResourceAssert struct {
	*assert.ResourceAssert
}

func IcebergTableFromFilesResource(t *testing.T, name string) *IcebergTableFromFilesResourceAssert {
	t.Helper()

	return &IcebergTableFromFilesResourceAssert{
		ResourceAssert: assert.NewResourceAssert(name, "resource"),
	}
}

func ImportedIcebergTableFromFilesResource(t *testing.T, id string) *IcebergTableFromFilesResourceAssert {
	t.Helper()

	return &IcebergTableFromFilesResourceAssert{
		ResourceAssert: assert.NewImportedResourceAssert(id, "imported resource"),
	}
}

//////////////////////////////////
// Attribute typed value checks //
//////////////////////////////////

func (i *IcebergTableFromFilesResourceAssert) HasDatabase(expected string) *IcebergTableFromFilesResourceAssert {
	i.StringValueSet("database", expected)
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasSchema(expected string) *IcebergTableFromFilesResourceAssert {
	i.StringValueSet("schema", expected)
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasName(expected string) *IcebergTableFromFilesResourceAssert {
	i.StringValueSet("name", expected)
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasCatalog(expected string) *IcebergTableFromFilesResourceAssert {
	i.StringValueSet("catalog", expected)
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasComment(expected string) *IcebergTableFromFilesResourceAssert {
	i.StringValueSet("comment", expected)
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasExternalVolume(expected string) *IcebergTableFromFilesResourceAssert {
	i.StringValueSet("external_volume", expected)
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasFullyQualifiedName(expected string) *IcebergTableFromFilesResourceAssert {
	i.StringValueSet("fully_qualified_name", expected)
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasMetadataFilePath(expected string) *IcebergTableFromFilesResourceAssert {
	i.StringValueSet("metadata_file_path", expected)
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasReplaceInvalidCharacters(expected bool) *IcebergTableFromFilesResourceAssert {
	i.BoolValueSet("replace_invalid_characters", expected)
	return i
}

///////////////////////////////////
// Attribute value string checks //
///////////////////////////////////

func (i *IcebergTableFromFilesResourceAssert) HasDatabaseString(expected string) *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueSet("database", expected))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasSchemaString(expected string) *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueSet("schema", expected))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasNameString(expected string) *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueSet("name", expected))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasCatalogString(expected string) *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueSet("catalog", expected))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasCommentString(expected string) *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueSet("comment", expected))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasExternalVolumeString(expected string) *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueSet("external_volume", expected))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasFullyQualifiedNameString(expected string) *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueSet("fully_qualified_name", expected))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasMetadataFilePathString(expected string) *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueSet("metadata_file_path", expected))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasReplaceInvalidCharactersString(expected string) *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueSet("replace_invalid_characters", expected))
	return i
}

///////////////////////////////
// Attribute no value checks //
///////////////////////////////

func (i *IcebergTableFromFilesResourceAssert) HasNoDatabase() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueNotSet("database"))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasNoSchema() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueNotSet("schema"))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasNoName() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueNotSet("name"))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasNoCatalog() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueNotSet("catalog"))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasNoComment() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueNotSet("comment"))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasNoExternalVolume() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueNotSet("external_volume"))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasNoFullyQualifiedName() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueNotSet("fully_qualified_name"))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasNoMetadataFilePath() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueNotSet("metadata_file_path"))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasNoReplaceInvalidCharacters() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueNotSet("replace_invalid_characters"))
	return i
}

////////////////////////////
// Attribute empty checks //
////////////////////////////

func (i *IcebergTableFromFilesResourceAssert) HasCatalogEmpty() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueSet("catalog", ""))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasCommentEmpty() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueSet("comment", ""))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasExternalVolumeEmpty() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueSet("external_volume", ""))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasFullyQualifiedNameEmpty() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueSet("fully_qualified_name", ""))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasReplaceInvalidCharactersEmpty() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValueSet("replace_invalid_characters", ""))
	return i
}

///////////////////////////////
// Attribute presence checks //
///////////////////////////////

func (i *IcebergTableFromFilesResourceAssert) HasDatabaseNotEmpty() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValuePresent("database"))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasSchemaNotEmpty() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValuePresent("schema"))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasNameNotEmpty() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValuePresent("name"))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasCatalogNotEmpty() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValuePresent("catalog"))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasCommentNotEmpty() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValuePresent("comment"))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasExternalVolumeNotEmpty() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValuePresent("external_volume"))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasFullyQualifiedNameNotEmpty() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValuePresent("fully_qualified_name"))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasMetadataFilePathNotEmpty() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValuePresent("metadata_file_path"))
	return i
}

func (i *IcebergTableFromFilesResourceAssert) HasReplaceInvalidCharactersNotEmpty() *IcebergTableFromFilesResourceAssert {
	i.AddAssertion(assert.ValuePresent("replace_invalid_characters"))
	return i
}
