// Code generated by resource assertions generator (v0.1.0); DO NOT EDIT.

package resourceassert

import (
	"testing"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
)

type ManagedAccountResourceAssert struct {
	*assert.ResourceAssert
}

func ManagedAccountResource(t *testing.T, name string) *ManagedAccountResourceAssert {
	t.Helper()

	return &ManagedAccountResourceAssert{
		ResourceAssert: assert.NewResourceAssertTmp(name),
	}
}

func ImportedManagedAccountResource(t *testing.T, id string) *ManagedAccountResourceAssert {
	t.Helper()

	return &ManagedAccountResourceAssert{
		ResourceAssert: assert.NewImportedResourceAssertTmp(id),
	}
}

//////////////////////////////////
// Attribute typed value checks //
//////////////////////////////////

func (m *ManagedAccountResourceAssert) HasName(expected string) *ManagedAccountResourceAssert {
	m.StringValueSet("name", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasAdminName(expected string) *ManagedAccountResourceAssert {
	m.StringValueSet("admin_name", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasAdminPassword(expected string) *ManagedAccountResourceAssert {
	m.StringValueSet("admin_password", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasCloud(expected string) *ManagedAccountResourceAssert {
	m.StringValueSet("cloud", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasComment(expected string) *ManagedAccountResourceAssert {
	m.StringValueSet("comment", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasCreatedOn(expected string) *ManagedAccountResourceAssert {
	m.StringValueSet("created_on", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasFullyQualifiedName(expected string) *ManagedAccountResourceAssert {
	m.StringValueSet("fully_qualified_name", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasLocator(expected string) *ManagedAccountResourceAssert {
	m.StringValueSet("locator", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasRegion(expected string) *ManagedAccountResourceAssert {
	m.StringValueSet("region", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasType(expected string) *ManagedAccountResourceAssert {
	m.StringValueSet("type", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasUrl(expected string) *ManagedAccountResourceAssert {
	m.StringValueSet("url", expected)
	return m
}

///////////////////////////////////
// Attribute value string checks //
///////////////////////////////////

func (m *ManagedAccountResourceAssert) HasNameString(expected string) *ManagedAccountResourceAssert {
	m.ValueSet("name", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasAdminNameString(expected string) *ManagedAccountResourceAssert {
	m.ValueSet("admin_name", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasAdminPasswordString(expected string) *ManagedAccountResourceAssert {
	m.ValueSet("admin_password", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasCloudString(expected string) *ManagedAccountResourceAssert {
	m.ValueSet("cloud", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasCommentString(expected string) *ManagedAccountResourceAssert {
	m.ValueSet("comment", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasCreatedOnString(expected string) *ManagedAccountResourceAssert {
	m.ValueSet("created_on", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasFullyQualifiedNameString(expected string) *ManagedAccountResourceAssert {
	m.ValueSet("fully_qualified_name", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasLocatorString(expected string) *ManagedAccountResourceAssert {
	m.ValueSet("locator", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasRegionString(expected string) *ManagedAccountResourceAssert {
	m.ValueSet("region", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasTypeString(expected string) *ManagedAccountResourceAssert {
	m.ValueSet("type", expected)
	return m
}

func (m *ManagedAccountResourceAssert) HasUrlString(expected string) *ManagedAccountResourceAssert {
	m.ValueSet("url", expected)
	return m
}

///////////////////////////////
// Attribute no value checks //
///////////////////////////////

func (m *ManagedAccountResourceAssert) HasNoName() *ManagedAccountResourceAssert {
	m.ValueNotSet("name")
	return m
}

func (m *ManagedAccountResourceAssert) HasNoAdminName() *ManagedAccountResourceAssert {
	m.ValueNotSet("admin_name")
	return m
}

func (m *ManagedAccountResourceAssert) HasNoAdminPassword() *ManagedAccountResourceAssert {
	m.ValueNotSet("admin_password")
	return m
}

func (m *ManagedAccountResourceAssert) HasNoCloud() *ManagedAccountResourceAssert {
	m.ValueNotSet("cloud")
	return m
}

func (m *ManagedAccountResourceAssert) HasNoComment() *ManagedAccountResourceAssert {
	m.ValueNotSet("comment")
	return m
}

func (m *ManagedAccountResourceAssert) HasNoCreatedOn() *ManagedAccountResourceAssert {
	m.ValueNotSet("created_on")
	return m
}

func (m *ManagedAccountResourceAssert) HasNoFullyQualifiedName() *ManagedAccountResourceAssert {
	m.ValueNotSet("fully_qualified_name")
	return m
}

func (m *ManagedAccountResourceAssert) HasNoLocator() *ManagedAccountResourceAssert {
	m.ValueNotSet("locator")
	return m
}

func (m *ManagedAccountResourceAssert) HasNoRegion() *ManagedAccountResourceAssert {
	m.ValueNotSet("region")
	return m
}

func (m *ManagedAccountResourceAssert) HasNoType() *ManagedAccountResourceAssert {
	m.ValueNotSet("type")
	return m
}

func (m *ManagedAccountResourceAssert) HasNoUrl() *ManagedAccountResourceAssert {
	m.ValueNotSet("url")
	return m
}

////////////////////////////
// Attribute empty checks //
////////////////////////////

func (m *ManagedAccountResourceAssert) HasCloudEmpty() *ManagedAccountResourceAssert {
	m.ValueSet("cloud", "")
	return m
}

func (m *ManagedAccountResourceAssert) HasCommentEmpty() *ManagedAccountResourceAssert {
	m.ValueSet("comment", "")
	return m
}

func (m *ManagedAccountResourceAssert) HasCreatedOnEmpty() *ManagedAccountResourceAssert {
	m.ValueSet("created_on", "")
	return m
}

func (m *ManagedAccountResourceAssert) HasFullyQualifiedNameEmpty() *ManagedAccountResourceAssert {
	m.ValueSet("fully_qualified_name", "")
	return m
}

func (m *ManagedAccountResourceAssert) HasLocatorEmpty() *ManagedAccountResourceAssert {
	m.ValueSet("locator", "")
	return m
}

func (m *ManagedAccountResourceAssert) HasRegionEmpty() *ManagedAccountResourceAssert {
	m.ValueSet("region", "")
	return m
}

func (m *ManagedAccountResourceAssert) HasTypeEmpty() *ManagedAccountResourceAssert {
	m.ValueSet("type", "")
	return m
}

func (m *ManagedAccountResourceAssert) HasUrlEmpty() *ManagedAccountResourceAssert {
	m.ValueSet("url", "")
	return m
}

///////////////////////////////
// Attribute presence checks //
///////////////////////////////

func (m *ManagedAccountResourceAssert) HasNameNotEmpty() *ManagedAccountResourceAssert {
	m.ValuePresent("name")
	return m
}

func (m *ManagedAccountResourceAssert) HasAdminNameNotEmpty() *ManagedAccountResourceAssert {
	m.ValuePresent("admin_name")
	return m
}

func (m *ManagedAccountResourceAssert) HasAdminPasswordNotEmpty() *ManagedAccountResourceAssert {
	m.ValuePresent("admin_password")
	return m
}

func (m *ManagedAccountResourceAssert) HasCloudNotEmpty() *ManagedAccountResourceAssert {
	m.ValuePresent("cloud")
	return m
}

func (m *ManagedAccountResourceAssert) HasCommentNotEmpty() *ManagedAccountResourceAssert {
	m.ValuePresent("comment")
	return m
}

func (m *ManagedAccountResourceAssert) HasCreatedOnNotEmpty() *ManagedAccountResourceAssert {
	m.ValuePresent("created_on")
	return m
}

func (m *ManagedAccountResourceAssert) HasFullyQualifiedNameNotEmpty() *ManagedAccountResourceAssert {
	m.ValuePresent("fully_qualified_name")
	return m
}

func (m *ManagedAccountResourceAssert) HasLocatorNotEmpty() *ManagedAccountResourceAssert {
	m.ValuePresent("locator")
	return m
}

func (m *ManagedAccountResourceAssert) HasRegionNotEmpty() *ManagedAccountResourceAssert {
	m.ValuePresent("region")
	return m
}

func (m *ManagedAccountResourceAssert) HasTypeNotEmpty() *ManagedAccountResourceAssert {
	m.ValuePresent("type")
	return m
}

func (m *ManagedAccountResourceAssert) HasUrlNotEmpty() *ManagedAccountResourceAssert {
	m.ValuePresent("url")
	return m
}
