// Code generated by resource assertions generator (v0.1.0); DO NOT EDIT.

package resourceassert

import (
	"testing"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
)

type PipeResourceAssert struct {
	*assert.ResourceAssert
}

func PipeResource(t *testing.T, name string) *PipeResourceAssert {
	t.Helper()

	return &PipeResourceAssert{
		ResourceAssert: assert.NewResourceAssertTmp(name),
	}
}

func ImportedPipeResource(t *testing.T, id string) *PipeResourceAssert {
	t.Helper()

	return &PipeResourceAssert{
		ResourceAssert: assert.NewImportedResourceAssertTmp(id),
	}
}

//////////////////////////////////
// Attribute typed value checks //
//////////////////////////////////

func (p *PipeResourceAssert) HasDatabase(expected string) *PipeResourceAssert {
	p.StringValueSet("database", expected)
	return p
}

func (p *PipeResourceAssert) HasSchema(expected string) *PipeResourceAssert {
	p.StringValueSet("schema", expected)
	return p
}

func (p *PipeResourceAssert) HasName(expected string) *PipeResourceAssert {
	p.StringValueSet("name", expected)
	return p
}

func (p *PipeResourceAssert) HasAutoIngest(expected bool) *PipeResourceAssert {
	p.BoolValueSet("auto_ingest", expected)
	return p
}

func (p *PipeResourceAssert) HasAwsSnsTopicArn(expected string) *PipeResourceAssert {
	p.StringValueSet("aws_sns_topic_arn", expected)
	return p
}

func (p *PipeResourceAssert) HasComment(expected string) *PipeResourceAssert {
	p.StringValueSet("comment", expected)
	return p
}

func (p *PipeResourceAssert) HasCopyStatement(expected string) *PipeResourceAssert {
	p.StringValueSet("copy_statement", expected)
	return p
}

func (p *PipeResourceAssert) HasErrorIntegration(expected string) *PipeResourceAssert {
	p.StringValueSet("error_integration", expected)
	return p
}

func (p *PipeResourceAssert) HasFullyQualifiedName(expected string) *PipeResourceAssert {
	p.StringValueSet("fully_qualified_name", expected)
	return p
}

func (p *PipeResourceAssert) HasIntegration(expected string) *PipeResourceAssert {
	p.StringValueSet("integration", expected)
	return p
}

func (p *PipeResourceAssert) HasNotificationChannel(expected string) *PipeResourceAssert {
	p.StringValueSet("notification_channel", expected)
	return p
}

func (p *PipeResourceAssert) HasOwner(expected string) *PipeResourceAssert {
	p.StringValueSet("owner", expected)
	return p
}

///////////////////////////////////
// Attribute value string checks //
///////////////////////////////////

func (p *PipeResourceAssert) HasDatabaseString(expected string) *PipeResourceAssert {
	p.ValueSet("database", expected)
	return p
}

func (p *PipeResourceAssert) HasSchemaString(expected string) *PipeResourceAssert {
	p.ValueSet("schema", expected)
	return p
}

func (p *PipeResourceAssert) HasNameString(expected string) *PipeResourceAssert {
	p.ValueSet("name", expected)
	return p
}

func (p *PipeResourceAssert) HasAutoIngestString(expected string) *PipeResourceAssert {
	p.ValueSet("auto_ingest", expected)
	return p
}

func (p *PipeResourceAssert) HasAwsSnsTopicArnString(expected string) *PipeResourceAssert {
	p.ValueSet("aws_sns_topic_arn", expected)
	return p
}

func (p *PipeResourceAssert) HasCommentString(expected string) *PipeResourceAssert {
	p.ValueSet("comment", expected)
	return p
}

func (p *PipeResourceAssert) HasCopyStatementString(expected string) *PipeResourceAssert {
	p.ValueSet("copy_statement", expected)
	return p
}

func (p *PipeResourceAssert) HasErrorIntegrationString(expected string) *PipeResourceAssert {
	p.ValueSet("error_integration", expected)
	return p
}

func (p *PipeResourceAssert) HasFullyQualifiedNameString(expected string) *PipeResourceAssert {
	p.ValueSet("fully_qualified_name", expected)
	return p
}

func (p *PipeResourceAssert) HasIntegrationString(expected string) *PipeResourceAssert {
	p.ValueSet("integration", expected)
	return p
}

func (p *PipeResourceAssert) HasNotificationChannelString(expected string) *PipeResourceAssert {
	p.ValueSet("notification_channel", expected)
	return p
}

func (p *PipeResourceAssert) HasOwnerString(expected string) *PipeResourceAssert {
	p.ValueSet("owner", expected)
	return p
}

///////////////////////////////
// Attribute no value checks //
///////////////////////////////

func (p *PipeResourceAssert) HasNoDatabase() *PipeResourceAssert {
	p.ValueNotSet("database")
	return p
}

func (p *PipeResourceAssert) HasNoSchema() *PipeResourceAssert {
	p.ValueNotSet("schema")
	return p
}

func (p *PipeResourceAssert) HasNoName() *PipeResourceAssert {
	p.ValueNotSet("name")
	return p
}

func (p *PipeResourceAssert) HasNoAutoIngest() *PipeResourceAssert {
	p.ValueNotSet("auto_ingest")
	return p
}

func (p *PipeResourceAssert) HasNoAwsSnsTopicArn() *PipeResourceAssert {
	p.ValueNotSet("aws_sns_topic_arn")
	return p
}

func (p *PipeResourceAssert) HasNoComment() *PipeResourceAssert {
	p.ValueNotSet("comment")
	return p
}

func (p *PipeResourceAssert) HasNoCopyStatement() *PipeResourceAssert {
	p.ValueNotSet("copy_statement")
	return p
}

func (p *PipeResourceAssert) HasNoErrorIntegration() *PipeResourceAssert {
	p.ValueNotSet("error_integration")
	return p
}

func (p *PipeResourceAssert) HasNoFullyQualifiedName() *PipeResourceAssert {
	p.ValueNotSet("fully_qualified_name")
	return p
}

func (p *PipeResourceAssert) HasNoIntegration() *PipeResourceAssert {
	p.ValueNotSet("integration")
	return p
}

func (p *PipeResourceAssert) HasNoNotificationChannel() *PipeResourceAssert {
	p.ValueNotSet("notification_channel")
	return p
}

func (p *PipeResourceAssert) HasNoOwner() *PipeResourceAssert {
	p.ValueNotSet("owner")
	return p
}

////////////////////////////
// Attribute empty checks //
////////////////////////////

func (p *PipeResourceAssert) HasAutoIngestEmpty() *PipeResourceAssert {
	p.ValueSet("auto_ingest", "")
	return p
}

func (p *PipeResourceAssert) HasAwsSnsTopicArnEmpty() *PipeResourceAssert {
	p.ValueSet("aws_sns_topic_arn", "")
	return p
}

func (p *PipeResourceAssert) HasCommentEmpty() *PipeResourceAssert {
	p.ValueSet("comment", "")
	return p
}

func (p *PipeResourceAssert) HasErrorIntegrationEmpty() *PipeResourceAssert {
	p.ValueSet("error_integration", "")
	return p
}

func (p *PipeResourceAssert) HasFullyQualifiedNameEmpty() *PipeResourceAssert {
	p.ValueSet("fully_qualified_name", "")
	return p
}

func (p *PipeResourceAssert) HasIntegrationEmpty() *PipeResourceAssert {
	p.ValueSet("integration", "")
	return p
}

func (p *PipeResourceAssert) HasNotificationChannelEmpty() *PipeResourceAssert {
	p.ValueSet("notification_channel", "")
	return p
}

func (p *PipeResourceAssert) HasOwnerEmpty() *PipeResourceAssert {
	p.ValueSet("owner", "")
	return p
}

///////////////////////////////
// Attribute presence checks //
///////////////////////////////

func (p *PipeResourceAssert) HasDatabaseNotEmpty() *PipeResourceAssert {
	p.ValuePresent("database")
	return p
}

func (p *PipeResourceAssert) HasSchemaNotEmpty() *PipeResourceAssert {
	p.ValuePresent("schema")
	return p
}

func (p *PipeResourceAssert) HasNameNotEmpty() *PipeResourceAssert {
	p.ValuePresent("name")
	return p
}

func (p *PipeResourceAssert) HasAutoIngestNotEmpty() *PipeResourceAssert {
	p.ValuePresent("auto_ingest")
	return p
}

func (p *PipeResourceAssert) HasAwsSnsTopicArnNotEmpty() *PipeResourceAssert {
	p.ValuePresent("aws_sns_topic_arn")
	return p
}

func (p *PipeResourceAssert) HasCommentNotEmpty() *PipeResourceAssert {
	p.ValuePresent("comment")
	return p
}

func (p *PipeResourceAssert) HasCopyStatementNotEmpty() *PipeResourceAssert {
	p.ValuePresent("copy_statement")
	return p
}

func (p *PipeResourceAssert) HasErrorIntegrationNotEmpty() *PipeResourceAssert {
	p.ValuePresent("error_integration")
	return p
}

func (p *PipeResourceAssert) HasFullyQualifiedNameNotEmpty() *PipeResourceAssert {
	p.ValuePresent("fully_qualified_name")
	return p
}

func (p *PipeResourceAssert) HasIntegrationNotEmpty() *PipeResourceAssert {
	p.ValuePresent("integration")
	return p
}

func (p *PipeResourceAssert) HasNotificationChannelNotEmpty() *PipeResourceAssert {
	p.ValuePresent("notification_channel")
	return p
}

func (p *PipeResourceAssert) HasOwnerNotEmpty() *PipeResourceAssert {
	p.ValuePresent("owner")
	return p
}
