//go:build sdk_generation

package defs

import (
	"fmt"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/generator/gen"
)

func init() {
	gen.AllSdkObjectDefinitions = append(
		gen.AllSdkObjectDefinitions,
		accountsDef,
		alertsDef,
		apiIntegrationsDef,
		applicationPackagesDef,
		applicationRolesDef,
		applicationsDef,
		authenticationPoliciesDef,
		backupPoliciesDef,
		budgetsDef,
		catalogIntegrationsDef,
		computePoolsDef,
		connectionsDef,
		contextFunctionsDef,
		cortexAgentsDef,
		cortexSearchServicesDef,
		databaseRolesDef,
		databasesDef,
		dynamicTablesDef,
		dataMetricFunctionReferencesDef,
		eventTablesDef,
		externalTablesDef,
		externalAccessIntegrationsDef,
		externalFunctionsDef,
		externalVolumesDef,
		failoverGroupsDef,
		fileFormatsDef,
		functionsDef,
		gitRepositoriesDef,
		grantsDef,
		hybridTablesDef,
		icebergTablesDef,
		imageRepositoriesDef,
		listingsDef,
		managedAccountsDef,
		maskingPoliciesDef,
		materializedViewsDef,
		mcpServersDef,
		networkPoliciesDef,
		networkRulesDef,
		notebooksDef,
		notificationIntegrationsDef,
		openflowConnectorDefinitionsDef,
		openflowConnectorsDef,
		openflowDeploymentsDef,
		openflowRuntimesDef,
		organizationAccountsDef,
		passwordPoliciesDef,
		pipesDef,
		policyReferencesDef,
		postgresInstancesDef,
		proceduresDef,
		replicationFunctionsDef,
		resourceMonitorsDef,
		rolesDef,
		rowAccessPoliciesDef,
		secretsDef,
		schemasDef,
		securityIntegrationsDef,
		sessionsDef,
		sharesDef,
		semanticViewsDef,
		sequencesDef,
		servicesDef,
		sessionPoliciesDef,
		stagesDef,
		storageIntegrationsDef,
		storageLifecyclePoliciesDef,
		streamlitsDef,
		streamsDef,
		systemFunctionsDef,
		tablesDef,
		tagReferencesDef,
		tagsDef,
		tasksDef,
		userProgrammaticAccessTokensDef,
		usersDef,
		viewsDef,
		warehousesDef,
	)
	fmt.Println("SDK object definitions:")
	for _, def := range gen.AllSdkObjectDefinitions {
		fmt.Printf(" - %s\n", def.Name)
	}
}
