name: Documentation And Code Formatting

on:
  push:
    branches:
      - main
      - dev
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  docs-and-fmt:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        id: setup_terraform
        with:
          terraform_version: 1.7.4
          terraform_wrapper: false

      - name: Install dependencies
        run: make dev-setup

      - name: Check documentation and code formatting
        run: make pre-push-check
