name: Unit tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:

permissions:
  contents: read

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: false

      - name: Run unit tests
        run: make test-unit
        env:
          TEST_SF_TF_TEST_TYPE: "unit"
