name: Unit tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:

permissions:
  contents: read

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: false

      - name: Run unit tests
        # pipefail needs to be set to ensure that the exit code of make test command is captured even when piped (otherwise it would take the exit code of make save-test-results)
        run: set -o pipefail && make test-unit | make save-test-results
        env:
          TEST_SF_TF_TEST_TYPE: "unit"
